### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#10]
Eww should provide support for Wayland. For this, mainly the window positioning and stacking behaviour needs to be abstracted away and reimplemented for wayland.
This should be pretty simple to implement by making use of [gtk-layer-shell-rs](https://github.com/subgraph/gtk-layer-shell-rs).

## Acceptance criteria
- Eww widgets are correctly positioned and stacked when run on wayland

**Comment by elkowar** [comment]
@buffet please PR kthx :3

**Comment by buffet** [comment]
@elkowar Sadly, that's impossible, as I can't type on Wayland. You'd have to help me setup XMobad first. :/

**Comment by elkowar** [comment]
@buffet deal, I'll help you get into XMokay, and you'll implement wayland support at 2WPM! Pog!

**Comment by elkowar** [comment]
This is blocked by https://github.com/buffet/rice/issues/3

**Comment by 6gk** [comment]
wayland more like wbadland woah i just smartphowned y'all

**Comment by elkowar** [comment]
Hey, @buffet.
https://github.com/buffet/rice/issues/3 has been closed for a while now, are there any updates on this?

**Comment by 6gk** [comment]
wait, why did you add the macos label?

**Comment by elkowar** [comment]
6gk because apparently, my brain is slightly disphunctional

**Comment by 6gk** [comment]
a bit more than slightly.

need i remind you that you added uwuspeak to plover-fancytext?

**Comment by 0reoKing** [comment]
Stop shit posting guys.

**Comment by 0reoKing** [comment]
Stop shit posting

**Comment by 6gk** [comment]
@0reoKing Stop ~~shit~~ posting guys.

**Comment by 0reoKing** [comment]
Are there any plans to port this to gtk3

**Comment by 6gk** [comment]
bruh stop shitposting

**Comment by elkowar** [comment]
For now, this can be closed, given that gtk4 completely removes the ability to render on arbitrary surfaces - making it impossible to use layer-shell in gtk4, and thus making this impossible.


**NOTE** that this does not mean eww is not functional under wayland: Widget windows can still be opened normally. The issue is that without support for layer-shell, it's impossible to have them act as anything other than normal application windows, which will usually get titlebars and such, and are not possible to position at a fixed place on screen. Thus, positioning the widgets via the eww configuration on wayland is, and probably won't be possible, but you should still be able to achieve the same thing by positioning the window from the compositor side - assuming that your compositor provides API to do so.

If GTK doesn't get their shit together, I'll probably implement some kind of integration into a few common wayland compositors, depending on how viable that turns out to be - I really don't wanna be part of the reason wayland isn't viable. But for now,.. Thank GNOME/GTK for wayland eww to be impossible.

Here are some links related to the issue:
- https://discourse.ubuntu.com/t/wayland-protocols-for-special-purpose-surfaces/15330
- https://gitlab.gnome.org/GNOME/gtk/-/issues/2132
Specifically thank GNOME for implementing their own protocol (worse) instead of implementing the standard Layershell protocol, and thank GTK for assuming GNOME to be the only platform that matters.

**Comment by 6gk** [comment]
@elkowar stop shitposting

**Comment by elkowar** [comment]
As the gtk4 branch has been killed of (as a result of instability and other issues in gtk4) this can be reopened - proper wayland support may be a thing soon!

**Comment by Th3Whit3Wolf** [comment]
Just curious would it be possible to use [Smithay](https://github.com/Smithay/client-toolkit) to get eww running on wayland?

**Comment by snakedye** [comment]
With GTK4 no because they provide a way to make surfaces anything other than windows.

[Eww](https://github.com/elkowar/eww/pull/125) also already runs on Wayland.

**Comment by undefinedDarkness** [comment]
will that ever get merged ?

**Comment by elkowar** [comment]
Yes, don't worry. I've just been busy with other things recently

**Comment by 6gk** [comment]
I wonder what.  👀

>

**Comment by elkowar** [comment]
Implemented in #125
