### ISSUE TITLE
[BUG] Build fails

### ISSUE THREAD

**Issue by fuzebox1** [elkowar/eww#100]
## Describe the bug

I'm using the arch aur package. The pkgbuild appears to be set up correctly according to the eww docs.

Edit: Fixed by installing rustup instead.

```
   Compiling eww v0.1.0 (/home/fuze/.cache/paru/clone/eww-git/src/eww)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:1
```

## Reproducing the issue
Tried twice.

## Expected behaviour
Expected it would compile...

**Comment by elkowar** [comment]
I am not the maintainer of the AUR package.
If there are issues with any non-official eww package please raise those issues with the respective package maintainers instead, as i have no control nor responsibility for these packages.
