### ISSUE TITLE
[BUG] 68GB logfile 

### ISSUE THREAD

**Issue by leg7** [elkowar/eww#1000]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I just found a 68 gigabyte logfile in my .local/cache. What the fuck.
I think this happened because my WM sometimes crashes when my laptop is docked and wakes up from sleep. I guess eww can't draw the window because the compositor is dead and just logs it like crazy.

here's the tail of the log
[log.txt](https://github.com/owenrumney/eww-bar/files/13651698/log.txt)

### Expected behaviour

Don't log 68 fricking gigabytes!

**Comment by alekulyn** [comment]
I'm getting similar behavior and near similar logs on my machine. My logfile was growing at a rate of around 2MB/sec
