### ISSUE TITLE
Having issues compiling eww

### ISSUE THREAD

**Issue by Besufikad17** [elkowar/eww#1002]
Hey there guys, I followed the installation instruction provided in the documentation but I am having this error `error: could not find system library 'gdk-3.0' required by the 'gdk-sys' crate`. I have checked if `libgdk` is installed or not like this:

![image](https://github.com/elkowar/eww/assets/64811433/7bb5ec4e-1d59-4946-943f-506ea17e3928)

but I am still getting the same error. Am I missing something? Thanks in advance.

OS: `OpenSUSE Tumbleweed`

**Comment by sbradnick** [comment]
I would suggest installing rustup and using nightly from there. I recall trying to get eww to build in OBS and it never worked. Much easier to do it this way and copy over the resulting binary. I'm disappointed to not have it installed via zypper, but it is what it is :wink:

**Comment by elkowar** [comment]
Well, you are missing the gdk3 library -- check if you have gtk-devel libraries or something you're missing

**Comment by Besufikad17** [comment]
> I would suggest installing rustup and using nightly from there. I recall trying to get eww to build in OBS and it never worked. Much easier to do it this way and copy over the resulting binary. I'm disappointed to not have it installed via zypper, but it is what it is 😉

How do I use nightly?

**Comment by sbradnick** [comment]
Install rustup package and run `rustup toolchain install nightly`; maybe verify with `rustup toolchain list` and ensure something like "nightly-x86_64-unknown-linux-gnu" is `(default)`

NOTE: I'm no where near a rust dev in any way or claim to know all the ins-and-outs of setting it up, just sharing my experience in getting it to build in Tumbleweed :smile: Also check out -> https://rust-lang.github.io/rustup/concepts/channels.html
