### ISSUE TITLE
[BUG] How can i know the window i want to open

### ISSUE THREAD

**Issue by JoestarJorry** [elkowar/eww#1006]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I try to run the eww but i find that i don't konw the window name

**Comment by Jozhin-s-Bazhin** [comment]
The name of your window should be in your eww.yuck file behind defwindow. The config is usually located in ~/.config/eww/eww.yuck.
```
(
    defwindow bar [mon]
              ^^^ here
    :monitor mon
    :geometry
    (
        geometry
        :anchor "top center"
        :x "0"
        :y "0"
        :width "100%"
    )
    :stacking "fg"
    :exclusive "true"
    :focusable "false"
    :class "bar"
    :namespace "eww_bar"
    (bar_container :mon mon)
)
```

**Comment by newor0599** [comment]
running `eww windwos` will all window, a * means its open

**Comment by CannedStrawberries** [comment]
I have realized since posting this that there is an underlying issue with my EWW install. Cargo claims to have build it successfully, and I have all the dependency packages installed, but my system doesn't seem to believe that EWW exists 
![image](https://github.com/user-attachments/assets/1d7b1a90-1a01-4147-9687-551a954c25a5)
