### ISSUE TITLE
[BUG] Extra item in scroll widget

### ISSUE THREAD

**Issue by newor0599** [elkowar/eww#1011]
### Checklist before submitting an issue

- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)
- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)

### Description of the bug

It seems like there is an extra item in the scroll widget, making me unable to vexpand or valign properly
![image](https://github.com/elkowar/eww/assets/114163256/e4241e8a-11cd-4fef-ac6d-0eccb181eb96)

### Reproducing the issue

Making a scroll widget with a box in it can easily reproduce this issue

### Additional context

![image](https://github.com/elkowar/eww/assets/114163256/7ab87641-6362-432d-81ff-85cfda086e9e)
I was unable to make the scrol widget to vexpand
The red box indicate the item with a class .frame

**Comment by bhaumik-tripathi** [comment]
hey @newor0599, how did you fix this issue?

**Comment by newor0599** [comment]
Try applying vexpand on your scroll widget

**Comment by bhaumik-tripathi** [comment]
thanks but it didn't effect the issue I am having.

**Comment by newor0599** [comment]
I have moved on to other gtk widget wrapper, [ignis](https://github.com/linkfrg/ignis) is what I'm using now
