### ISSUE TITLE
How to use combo-box-text widget

### ISSUE THREAD

**Issue by qxb3** [elkowar/eww#1012]
This maybe a dumb question but how can i use this widget? `combo-box-text`? What is `vec`? There is none anywhere in the docs that explain it. Thanks.

**Comment by newor0599** [comment]
![image](https://github.com/elkowar/eww/assets/114163256/a52fc342-8754-4763-b64a-d269e6d61cf7)
According to EWW's own documentation, it is a widget that allow user to select between several item.
vec is the item that should be displayed in the combo box text

**Comment by qxb3** [comment]
yeah that is where i'm confused, what is `vec`?

**Comment by newor0599** [comment]
the content inside the combo text

**Comment by qxb3** [comment]
i know its the content of the widget but how do u do it? do u have any examples?

**Comment by newor0599** [comment]
Since EWW is written in rust, `vec` might be a way to store a list of data

**Comment by newor0599** [comment]
Ok i figured it out ! :D
`vec` can be written like this
`:items "[Option1, Option2, Option3]"`

**Comment by qxb3** [comment]
thank you!

**Comment by victorz** [comment]
I think this should be re-opened. There's no way to figure this out just by reading the documentation. I found it out on my own just experimenting and assuming stuff from experience of being a developer myself. This is buggy/poor documentation.
