### ISSUE TITLE
Not able to build due to an apparent missing system library, which does exist

### ISSUE THREAD

**Issue by Softheartofstone** [elkowar/eww#1015]
doing `cargo build --release --no-default-features --features=wayland` 
gives out 
`   Compiling gtk-layer-shell-sys v0.6.0
The following warnings were emitted during compilation:

warning: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "gtk-layer-shell-0" "gtk-layer-shell-0 >= 0.1"` did not exit successfully: exit status: 1

error: failed to run custom build command for `gtk-layer-shell-sys v0.6.0`

Caused by:
  process didn't exit successfully: `/home/manaveshwar/eww/target/release/build/gtk-layer-shell-sys-1489b1f9a6541738/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GTK_LAYER_SHELL_0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "gtk-layer-shell-0" "gtk-layer-shell-0 >= 0.1"` did not exit successfully: exit status: 1
  error: could not find system library 'gtk-layer-shell-0' required by the 'gtk-layer-shell-sys' crate

  --- stderr
  Package gtk-layer-shell-0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gtk-layer-shell-0', required by 'virtual:world', not found
  Package 'gtk-layer-shell-0', required by 'virtual:world', not found`

the output of `ldconfig -p | grep gtk-layer` is `libgtk-layer-shell.so.0 (libc6,x86-64) => /lib64/libgtk-layer-shell.so.0`

I looked up the following to fix the issue 

https://github.com/subgraph/gtk-layer-shell-rs/issues/1
https://askubuntu.com/questions/210210/pkg-config-path-environment-variable

i also reinstalled pkg-config, sorry if this is a stupid question i am new to this.

i am running a fedora 39 system with wayland as my WM

**Comment by polyfloyd** [comment]
Do you have the `-dev` package installed? `sudo apt install libgtk-layer-shell-dev`
