### ISSUE TITLE
getting error when trying to install eww on fedora 39

### ISSUE THREAD

**Issue by Gorillyas** [elkowar/eww#1026]
i have been following all the steps to install eww on the eww wiki and i encountered this issue while trying to install it for wayland, is there any way to fix this problem?

This is the error i get:

warning: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "gtk-layer-shell-0" "gtk-layer-shell-0 >= 0.1"` did not exit successfully: exit status: 1

error: failed to run custom build command for `gtk-layer-shell-sys v0.6.0`

Caused by:
  process didn't exit successfully: `/home/gorillyas/eww/target/release/build/gtk-layer-shell-sys-1489b1f9a6541738/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GTK_LAYER_SHELL_0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "gtk-layer-shell-0" "gtk-layer-shell-0 >= 0.1"` did not exit successfully: exit status: 1
  error: could not find system library 'gtk-layer-shell-0' required by the 'gtk-layer-shell-sys' crate

  --- stderr
  Package gtk-layer-shell-0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gtk-layer-shell-0', required by 'virtual:world', not found
  Package 'gtk-layer-shell-0', required by 'virtual:world', not found

warning: build failed, waiting for other jobs to finish...

**Comment by vaparetia** [comment]
You need the "devel" variation of the package. It's called ```gtk-layer-shell-devel```.
