### ISSUE TITLE
Facing lowercase issue while creating EWW widget

### ISSUE THREAD

**Issue by MrVivekRajan** [elkowar/eww#1035]
I am trying to create a day widget using Eww. I even successfully made it but the issue is that in output only the first letter of the day is in uppercase and rest other letters are in lowercase. I want all the letters to be in uppercase. I have shared the code which i used and also attached the image of the output. 

Code:-
(defwidget day []
    (box :class "day" :orientation "horizontal" :space-evenly "false" 
        (label :class "day_label" :text { formattime(EWW_TIME, "%A")})
    )

Output Image:-
![240224_19h00m07s_screenshot](https://github.com/elkowar/eww/assets/85994908/aa72e7b1-8f51-414c-8f4f-39d526ce7bf1)

**Comment by Rayzeq** [comment]
You can't get this in uppercase using `formattime`.
If you don't mind polling you can do:
```
(defpoll day
  :interval "60s"
  :initial ""
  "date +'%A' | tr '[a-z]' '[A-Z]'"
)

(defwidget day []
  (box
    :class "day"
    :orientation "horizontal"
    :space-evenly "false"
    (label :class "day_label" :text day)
  )
)
```

**Comment by MrVivekRajan** [comment]
> You can't get this in uppercase using `formattime`. If you don't mind polling you can do:
> 
> ```
> (defpoll day
>   :interval "60s"
>   :initial ""
>   "date +'%A' | tr '[a-z]' '[A-Z]'"
> )
> 
> (defwidget day []
>   (box
>     :class "day"
>     :orientation "horizontal"
>     :space-evenly "false"
>     (label :class "day_label" :text day)
>   )
> )
> ```

Thank you so much brother. I successfully fixed the lowercase issue. Also got to learn something new about eww configuration.
