### ISSUE TITLE
[BUG] jq broken in 5.0.0

### ISSUE THREAD

**Issue by kthu** [elkowar/eww#1039]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

After upgrading to eww 5.0.0 all my jq expressions are broken. It seems they always return the full document regardless of the filter. 

Here is a simple example:
```
❯ eww --version
eww 0.5.0 387d344690903949121040f8a892f946e323c472
❯ bat ~/.config/eww/eww.yuck
   1   (defvar ws {jq("[7,8,9]", ".[0]")})
   2   
❯ eww reload
❯ eww get ws
[7,8,9]
❯ eww get ws | jaq ".[0]"
7
```

**Comment by w-lfchen** [comment]
For an easy bisect it would be nice to know which version/commit you were previously on, would you mind adding that?

**Comment by kthu** [comment]
Yeah, sorry about the bad bug report. 

I'm not sure exactly which version I was on before upgrading since it was built from git, but it was 0.4.0 something.

I've now tested various revisions, and 4385782be4152517d432c3a1e356b95695617325 is the culprit. e6817f221bb18d0604ff44ec13671d793469a90c works fine.

**Comment by cmargiotta** [comment]
Version in nix unstable has the same bug

**Comment by w-lfchen** [comment]
> Version in nix unstable has the same bug

This is due to nixpkgs currently using the v0.5.0 tag, as can be seen [here](https://github.com/NixOS/nixpkgs/blob/b6401f808a81578655d4745760379cd621cf97b9/pkgs/applications/window-managers/eww/default.nix#L19C1-L19C25).

**Comment by cmargiotta** [comment]
> > Version in nix unstable has the same bug
> 
> This is due to nixpkgs currently using the v0.5.0 tag, as can be seen [here](https://github.com/NixOS/nixpkgs/blob/b6401f808a81578655d4745760379cd621cf97b9/pkgs/applications/window-managers/eww/default.nix#L19C1-L19C25).

Sorry if I'm missing something, isn't v0.5.0 the latest release?

**Comment by w-lfchen** [comment]
@cmargiotta it is.
@cmargiotta @kthu I'd appreciate it if you could test my pr branch and see whether that fixes jq for you.

**Comment by kthu** [comment]
Yes, that fixed it! :+1:

**Comment by cmargiotta** [comment]
Yes, it works correctly now! Thank you so much!
