### ISSUE TITLE
linear-gradient() error

### ISSUE THREAD

**Issue by H-FTM** [elkowar/eww#1048]
Hello i have some widgets using the linear-gradient scss attribute it was working until i updated my system, now i got a gtk3 error : linear-gradient is deprecated

**Comment by w-lfchen** [comment]
Could you provide some more details such as a minimal config and a guide for reproducing the error?
This would help a lot in trying to fix it.

**Comment by H-FTM** [comment]
yeah, it's in the scss file i have a linear-gradient(white, black) and it doesnt appear because of the error

**Comment by w-lfchen** [comment]
Using the following config:
eww.scss:
```scss
.test {
    background: linear-gradient(white, black);
}
```
eww.yuck:
```
(defwindow test
  :monitor 0
  :geometry (geometry
    :width "100px"
    :height "100px"
    :anchor "center"
  )
  (box :class "test"))
```
and then running `eww open --toggle test` on the latest commit, I am unable to reproduce your issue. There is also nothing in the log file.

**Comment by H-FTM** [comment]
oh my bad 


Caused by:
    <data>:1:53Missing closing bracket at end of linear gradient
^C

i just dont know how to fix this because i dont have any missing bracket

**Comment by w-lfchen** [comment]
I can't help you without seeing your config because I am unable to verify whether you are right in your assumption about your code without said code.
If you provide the relevant lines here, I can have a look at it. Without it, there's not much I, or anyone for that matter, can do to help you.

**Comment by H-FTM** [comment]
Tsym for your help, i just fixed it.
