### ISSUE TITLE
[FEATURE] tailwindcss support?

### ISSUE THREAD

**Issue by iiian** [elkowar/eww#1057]
### Description of the requested feature

Hey @elkowar. Long time eww-fan, first time caller. Any idea if `tailwindcss` works out of the box with `eww`? If not, does integrating support sound like a good first-time-contributor ticket, and something you'd want in the project?

**Comment by elkowar** [comment]
I don't think that's gonna work well, as gtk CSS _does_ differ from regular css quite a bit :/

**Comment by iiian** [comment]
Ah, no worries then.
