### ISSUE TITLE
[DOCS] Include types of attributes in widget documentation

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#106]
The documentation generator for widget documentation should include the type of the property, such that it's more obvious which values can be used there. A short explaination of the fact that all of them have to be in quotes should be added to the top of the widget documentation.

**Comment by elkowar** [comment]
@gilmirmo has taken on this issue. Poggers!

**Comment by gilmirmo** [comment]
yes I'll do it

**Comment by elkowar** [comment]
He'll, in fact, not do it 😄

**Comment by undefinedDarkness** [comment]
Ill do it :sweat_smile:

**Comment by undefinedDarkness** [comment]
This should be done now by #148

**Comment by elkowar** [comment]
Yes, fixed in #148 ! Thanks!
