### ISSUE TITLE
[FIX] Compilation errors

### ISSUE THREAD

**Issue by one2onepiece** [elkowar/eww#1062]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Not compiled on 04/04/2024. Build failed when compiling `dbusmenu-glib v0.1.0`. Previous releases compiled normally on the same system setup (arch). I tried to fix it myself, but without success. This library is ugly in my opinion.

### Reproducing the issue

```sh
git clone https://github.com/elkowar/eww.git
cd eww
cargo update
cargo build --release --no-default-features --features=wayland
```

### Expected behaviour

Compiled executable.

**Comment by Rayzeq** [comment]
Did you do a `cargo update` ? `dbusmenu-glib` have an issue which make it not compile with newer version of the glib.
Also, please post the error message to help debugging.
PS: it's an ugly lib because it's fully auto-generated by [gir](https://github.com/gtk-rs/gir), which means that the lib itself isn't meant to be modified, fixes should be done in gir.

**Comment by one2onepiece** [comment]
You caught me, sir. `cargo update` was like a reflex, you do it automatically. Now everything is in order, I checked the much-needed tray, it works. Thanks! Issue is closed.
```sh
rm -rf ~/.cargo/registry/*
git clone https://github.com/elkowar/eww.git
cd eww
### do-not-do-that --> cargo update
cargo build --release --no-default-features --features=wayland
```

**Comment by one2onepiece** [comment]
Can we rename this issue to some like "[BUG] Compilation Error" for others (i'm not a Github-pro)?
PS. Everything is getting too complicated... I am grateful to those who hold on. Sometimes it's easier to start from scratch than to dig into the problem.

**Comment by f1sle** [comment]
I faced the same issue on fresh arch setup and after I installed three packages it worked fine:

1. libdbusmenu-glib
2. libdbusmenu-gtk3
3. gtk-layer-shell
