### ISSUE TITLE
Could not find `ObjectExt` in `glib`

### ISSUE THREAD

**Issue by Runa-pufferfish** [elkowar/eww#1063]
Apologies for the lack of format or technical knowledge, but running the command <pre>$ cargo build --release --no-default-features --features=wayland
</pre> on my Debian 12 system returns: 

<pre><span style="color:#26A269"><b> Compiling</b></span> dbusmenu-glib v0.1.0
<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/client.rs:203:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>203</b></span> <span style="color:#2A7BDE"><b>|</b></span>         glib::ObjectExt::property(self.as_ref(), &quot;dbus-name&quot;)
    <span style="color:#2A7BDE"><b>| </b></span>              <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>203</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::property(self.as_ref(), &quot;dbus-name&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>203</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::property(self.as_ref(), &quot;dbus-name&quot;)
<span style="color:#2A7BDE"><b>203</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::property(self.as_ref(), &quot;dbus-name&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/client.rs:207:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>207</b></span> <span style="color:#2A7BDE"><b>|</b></span>         glib::ObjectExt::property(self.as_ref(), &quot;dbus-object&quot;)
    <span style="color:#2A7BDE"><b>| </b></span>              <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>207</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::property(self.as_ref(), &quot;dbus-object&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>207</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::property(self.as_ref(), &quot;dbus-object&quot;)
<span style="color:#2A7BDE"><b>207</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::property(self.as_ref(), &quot;dbus-object&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/client.rs:211:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>211</b></span> <span style="color:#2A7BDE"><b>|</b></span>         glib::ObjectExt::property(self.as_ref(), &quot;group-events&quot;)
    <span style="color:#2A7BDE"><b>| </b></span>              <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>211</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::property(self.as_ref(), &quot;group-events&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>211</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::property(self.as_ref(), &quot;group-events&quot;)
<span style="color:#2A7BDE"><b>211</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::property(self.as_ref(), &quot;group-events&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/client.rs:215:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>215</b></span> <span style="color:#2A7BDE"><b>|</b></span> <span style="color:#2A7BDE"><b>...</b></span>   glib::ObjectExt::set_property(self.as_ref(),&quot;group-events&quot;, group<span style="color:#2A7BDE"><b>...</b></span>
    <span style="color:#2A7BDE"><b>| </b></span>            <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>215</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::set_property(self.as_ref(),&quot;group-events&quot;, group_events)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>215</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::set_property(self.as_ref(),&quot;group-events&quot;, group_events)
<span style="color:#2A7BDE"><b>215</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::set_property(self.as_ref(),&quot;group-events&quot;, group_events)
    <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
  <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/menuitem_proxy.rs:69:15
   <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>69</b></span> <span style="color:#2A7BDE"><b>|</b></span>         glib::ObjectExt::property(self.as_ref(), &quot;menu-item&quot;)
   <span style="color:#2A7BDE"><b>| </b></span>              <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
   <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
   <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>69</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::property(self.as_ref(), &quot;menu-item&quot;)
   <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
   <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>  <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
   <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
   <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>69</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::property(self.as_ref(), &quot;menu-item&quot;)
<span style="color:#2A7BDE"><b>69</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::property(self.as_ref(), &quot;menu-item&quot;)
   <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/server.rs:190:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>190</b></span> <span style="color:#2A7BDE"><b>|</b></span>         glib::ObjectExt::property(self.as_ref(), &quot;dbus-object&quot;)
    <span style="color:#2A7BDE"><b>| </b></span>              <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>190</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::property(self.as_ref(), &quot;dbus-object&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>190</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::property(self.as_ref(), &quot;dbus-object&quot;)
<span style="color:#2A7BDE"><b>190</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::property(self.as_ref(), &quot;dbus-object&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/server.rs:194:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>194</b></span> <span style="color:#2A7BDE"><b>|</b></span>         glib::ObjectExt::property(self.as_ref(), &quot;root-node&quot;)
    <span style="color:#2A7BDE"><b>| </b></span>              <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>194</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::property(self.as_ref(), &quot;root-node&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>194</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::property(self.as_ref(), &quot;root-node&quot;)
<span style="color:#2A7BDE"><b>194</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::property(self.as_ref(), &quot;root-node&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/server.rs:198:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>198</b></span> <span style="color:#2A7BDE"><b>|</b></span> <span style="color:#2A7BDE"><b>...</b></span>   glib::ObjectExt::set_property(self.as_ref(),&quot;root-node&quot;, root_node)
    <span style="color:#2A7BDE"><b>| </b></span>            <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>198</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::set_property(self.as_ref(),&quot;root-node&quot;, root_node)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>198</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::set_property(self.as_ref(),&quot;root-node&quot;, root_node)
<span style="color:#2A7BDE"><b>198</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::set_property(self.as_ref(),&quot;root-node&quot;, root_node)
    <span style="color:#2A7BDE"><b>|</b></span>

<span style="color:#F66151"><b>error[E0433]</b></span><b>: failed to resolve: could not find `ObjectExt` in `glib`</b>
   <span style="color:#2A7BDE"><b>--&gt; </b></span>/home/runa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/server.rs:202:15
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>202</b></span> <span style="color:#2A7BDE"><b>|</b></span>         glib::ObjectExt::property(self.as_ref(), &quot;version&quot;)
    <span style="color:#2A7BDE"><b>| </b></span>              <span style="color:#F66151"><b>^^^^^^^^^</b></span> <span style="color:#F66151"><b>could not find `ObjectExt` in `glib`</b></span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: a struct with a similar name exists
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>202</b></span> <span style="color:#2A7BDE"><b>| </b></span>        glib::<span style="color:#33D17A">Object</span>::property(self.as_ref(), &quot;version&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>               <span style="color:#33D17A">~~~~~~</span>
<span style="color:#33C7DE"><b>help</b></span>: consider importing this trait
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>6</b></span>   <span style="color:#33D17A">+ use glib::prelude::ObjectExt;</span>
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#33C7DE"><b>help</b></span>: if you import `ObjectExt`, refer to it directly
    <span style="color:#2A7BDE"><b>|</b></span>
<span style="color:#2A7BDE"><b>202</b></span> <span style="color:#F66151">- </span>        <span style="color:#F66151">glib::</span>ObjectExt::property(self.as_ref(), &quot;version&quot;)
<span style="color:#2A7BDE"><b>202</b></span> <span style="color:#33D17A">+ </span>        ObjectExt::property(self.as_ref(), &quot;version&quot;)
    <span style="color:#2A7BDE"><b>|</b></span>

<b>For more information about this error, try `rustc --explain E0433`.</b>
<span style="color:#C01C28"><b>error</b></span><b>:</b> could not compile `dbusmenu-glib` (lib) due to 9 previous errors

Just prior to this I downloaded the missing dbusmenu dev file using <pre><span style="color:#12488B"><b>/eww</b></span>$ sudo apt install libdbusmenu-gtk3-dev
</pre>, which resulted in the following error.

**Comment by Rayzeq** [comment]
This is this same issue as this one #1062, please see the fix in it.
