### ISSUE TITLE
eww crates.io name

### ISSUE THREAD

**Issue by LU15W1R7H** [elkowar/eww#1076]
Hi! I'm the owner of the crate name "eww" on crates.io, see [here](https://crates.io/crates/eww).
I'm no longer developing my crate and it's pretty much obsolete.

I wanted to ask if you are interested in taking ownership of this name and publishing your eww on crates.io.
If so let me know!

**Comment by elkowar** [comment]
Uhh, that would be really cool, yea!

**Comment by LU15W1R7H** [comment]
Okay, all I need is your crates.io username (might be your GitHub name, if you sign in using it).
Let me know and I'll transfer ownership to you.

**Comment by elkowar** [comment]
It is just ElKowar, yea! Thanks a ton

**Comment by LU15W1R7H** [comment]
Okay, the invite is out!

**Comment by elkowar** [comment]
Thanks a lot! I'll publish eww there soon!
