### ISSUE TITLE
[FEATURE] Resolve all paths relative to the eww config

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#108]
## Description of the requested feature
Eww has many places where Paths may be used such as image paths, commands in attributes like `onClick` and most importantly paths in script-vars. All of these should be resolved relatively to the eww configuration directory.

For this the following needs to be done:
- [ ] Script-vars get executed in the eww config directory (running pwd yields the config path)
- [ ] `onClick` and other script attributes get executed in the config directory
- [ ] path resolution of any widget attributes representing paths is relative to the config directory
- [ ] *if possible* resolution of paths in `url`s in scss is relative to the eww config directory. This may be fully satisfied by a fix for #103.

## Proposed configuration syntax
No changes required

**Comment by legendofmiracles** [comment]
Doesn't this https://github.com/elkowar/eww/pull/110 fix that?

**Comment by undefinedDarkness** [comment]
Should be, ill run some tests at some point

**Comment by undefinedDarkness** [comment]
Ran my rudimetry tests, and yes #110 does fix all of that :smile:

**Comment by elkowar** [comment]
Sick! Then we can close this! Thanks!
