### ISSUE TITLE
[BUG] Cargo.lock version is incorrect in latest release

### ISSUE THREAD

**Issue by NwE0kmCE** [elkowar/eww#1088]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

In the latest release of eww (v0.6.0), the eww package version specified in `Cargo.lock` is 0.5.0, but should be 0.6.0 (if i'm not mistaken). 

### Reproducing the issue

Download the latest source from https://github.com/elkowar/eww/archive/refs/tags/v0.6.0.tar.gz and unpack with  `tar -xvf eww-0.6.0.tar.gz`

### Expected behaviour

Cargo.lock should show the package `eww` as being version 0.6.0

**Comment by w-lfchen** [comment]
This has been addressed in https://github.com/elkowar/eww/commit/8397744f403c87ab39523b4bf9e0216ad444f1bb.
