### ISSUE TITLE
lto build

### ISSUE THREAD

**Issue by CaptainBloodz** [elkowar/eww#1089]
### Description of the requested feature

lto is a obvious binary characteristic which works fine here on gentoo

### Proposed configuration syntax

By adding:
-Clto=fat
Cembed-bitcode=yes
-Zdylib-lto

**Comment by elkowar** [comment]
Given that there is currently no "official" package of eww anywhere, I'm unsure what exactly you're asking for here. Wouldn't enabling LTO and stuff like that optimally be a thing that the package declares, rather than the project itself?

**Comment by CaptainBloodz** [comment]
Despite gentoo package has options (X , debug, wayland),  they could only be there to only constraint execution environment, not the binary generation itself.

No problem pushing at packaging level.
