### ISSUE TITLE
[FEATURE] allow partially exclusive

### ISSUE THREAD

**Issue by jlo62** [elkowar/eww#1090]
### Description of the requested feature

Allow to make only part of the widget exclusive. This would make it possible to widgets that expand vertical to the rest of the bar.
Or in other words, drop down widgets for bars.

### Proposed configuration syntax

dunno

### Additional context

Sorry this is the stuppidest image but the only one I found:\
![image](https://github.com/elkowar/eww/assets/122014753/239d4c74-2504-4249-ba29-c2f91aa29b55)

**Comment by elkowar** [comment]
I don't think that that's really possible to do within one window. What you'd need to do is to configure a separate window for the dropdown, and make your button in the bar just `eww open that-window` at some speicifc coordinates
