### ISSUE TITLE
Support for reading environment variables in config files

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#11]
Eww should support reading environment variables anywhere, to make it easier to refer to paths and other variables.
The syntax for this should simply be `some text $ENV_VAR <button>whatever</button>`.

As this should probably only be done once, it would be possible to introduce a simple env-var expansion step into the *parser*, where we simply replace all env-var mentions with the respective values before even running it through the XML parser.

While this feels somewhat hacky, any other implementations would require doing env-var expansion in multiple, less "hidden" places, thus making the code less nice to read.

## Acceptance criteria
- the eww.xml file as well as the eww.scss file allow users to use `$VAR_NAME` syntax to refer to environment variables, which will be expanded directly after the respective file is read

**Comment by elkowar** [comment]
Just for you, @exorcist-git :P

**Comment by exorcist-git** [comment]
jesus... thanks a bunch

**Comment by buffet** [comment]
Doing this before the XML parser means that the stuff needs to be escaped or checked for validity (and there I'd argue that it shouldn't be done before the XML parsing).

**Comment by elkowar** [comment]
@buffet not really. if the user want's to load in XML from an env var, why should he not be able to? if the env-var expands to invalid xml, there will just be a parse-error. i think that's perfect.
