### ISSUE TITLE
[FEATURE] precompiled binaries

### ISSUE THREAD

**Issue by aalouaoui** [elkowar/eww#112]
## Description of the requested feature
A lot of people have low end computers, and compiling programs on those takes a long time. For example compiling eww on my computer takes around 20min, So is it possible to provide compiled binaries from time to time?

**Comment by legendofmiracles** [comment]
Once eww releases, i'm sure that will happen.

**Comment by undefinedDarkness** [comment]
20min isnt that bad... but yeah once there is an actual release that might happen

**Comment by Axarva** [comment]
If you really need one, my dotfiles repo has the latest binary of the master branch [here](https://github.com/Axarva/dotfiles-2.0/blob/main/bin/eww).

**Comment by aalouaoui** [comment]
Thank, I will use them for now.
