### ISSUE TITLE
[BUG] Window arguments not working?

### ISSUE THREAD

**Issue by pagedMov** [elkowar/eww#1133]
### Description of the bug

I try to create a window that takes arguments, like "(defwindow bar [arg1 arg2])" but keep getting this error:
error: Wrong type of expression
  ┌─ test.yuck:1:19
  │
1 │ (defwindow my_bar [arg1 ?arg2]
  │                   ──────────── Expected a `List` here
  │
  → Expected: List
         Got: Array

I copy+pasted the window arguments example directly from the documentation and it's still throwing this error. I don't think it's my environment either because I just moved from NixOS to Arch and it was behaving like this in NixOS as well. I'm on 0.6.0-1, which is apparently the latest version, are the docs up to date?

### Reproducing the issue

(defwindow my_bar [arg1 ?arg2]
          :geometry (geometry
                       :x      "0%"
                       :y      "6px"
                       :width  "100%"
                       :height { arg1 == "small" ? "30px" : "40px" }
                       :anchor "top center")
          :stacking   "bg"
          :windowtype "dock"
          :reserve    (struts :distance "50px" :side "top")
    (my_widget :arg2 arg2))

This is the window arguments example ripped straight out of the documentation. It's the only code in my eww.yuck config. Attempting to start the eww daemon throws an error saying it got an Array when it wanted a List.

**Comment by ovalkonia** [comment]
I was not able to reproduce the issue, it works just fine for me. Can you provide some more context?

**Comment by elkowar** [comment]
Make sure you're using eww 0.6.0
