### ISSUE TITLE
[FEATURE] Allow setting window's screen option to be a variable

### ISSUE THREAD

**Issue by Barbarossa93** [elkowar/eww#114]
# Description of the requested feature
It would be nice to allow the screen option for windows to accept a variable e.g. `screen="{{monitor}}"`. For my particular use case, I'm actually using eww as a notification frontend with [tiramisu](https://github.com/Sweets/tiramisu) since I find dunst's theming options subpar. I want to be able to see the notification window on the monitor I'm currently focused on so that I don't miss the notification. Regardless, even if I was using eww as intended, it makes sense to pop up the eww window(s) on the monitor that is currently focused for whatever information I'm interested in. It's annoying to open eww and realize you hard set it for the far left monitor when you're currently focused on your far right monitor (assuming you're using a three or more monitor setup).

**Comment by elkowar** [comment]
I now added support for `--monitor` when opening a widget, thus you can now override the value set in the configuration when opening the window. this isn't quite the same as having it in the config, but it is consistent with the other overrides provided by the CLI api. Thus, I'd say this can be closed

**Comment by GideonWolfe** [comment]
Hello, I found this issue and implemented the feature into my `polybar` like so:

```ini
[module/eww-left]
type = custom/script
click-left = eww open --monitor 1 sidebar
click-right = eww close sidebar
exec = "/home/gideon/.config/polybar/scripts/eww-button.sh"
format-foreground = ${colors.color5}
tail = true
interval = 90
```
When I was initially implementing this last night, running `eww open --monitor 1 sidebar` would open my window on my left most monitor.

I turn my monitors off (don't logout, hibernate, or shutdown the system) and I go to bed. Wake up this morning, and the same `eww open --monitor 1 sidebar` opens the window on my middle screen. How can I keep this consistent?

**Comment by undefinedDarkness** [comment]
shutdown like a sane person :p
but I really have no idea

**Comment by GideonWolfe** [comment]
Hah I'll keep an eye on it and see if I notice a pattern. After restarting `polybar` + `eww` after messing about it works "normally" now. On that note, is there any sort of `eww toggle` control? I can't figure out how to tell `polybar` whether to run `eww open` or `eww close` to toggle a window on or off.

**Comment by legendofmiracles** [comment]
Not *yet*.
But you could easily make a small shellscript.

**Comment by GideonWolfe** [comment]
I actually already found a solution.

`eww close <window> || eww open <window>`

**Comment by GideonWolfe** [comment]
All credit goes [here](https://github.com/rayes0/dotfiles)
