### ISSUE TITLE
[BUG] Couldn’t recognize the image file format

### ISSUE THREAD

**Issue by fabolous005** [elkowar/eww#1151]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I have a script running that listens to playerctl to download current `mpris:artUrl`, but when i try to display that image with the `image` widget i get above error.
The image is fine for other applications (kitty icat, Gimp).

### Reproducing the issue

[Test mpris Art](https://i.scdn.co/image/ab67616d0000b27392d21aef6c0d288cc4c05973)
```lisp
(image
    :path "path to image"
    :width 118
    :height 118
```

### Expected behaviour

Display the image.

### Additional context

Some debug info:
```
$ file pictures/mpris_art.jpg 
pictures/mpris_art.jpg: JPEG image data, JFIF standard 1.01,
resolution (DPCM), density 236x236, segment length 16,
baseline, precision 8, 640x640, components 3
```

**Comment by ovalkonia** [comment]
That's something wrong on your side. Check if you have `libjpeg` installed.

**Comment by fabolous005** [comment]
You are right, of course i had libjpeg installed, but the `jpeg` useflag is not enabled by default for gdk-pixbuf, enabling it fixed it for me...
