### ISSUE TITLE
[BUG] Screen enumeration is inconsistent with my Wayland compositor

### ISSUE THREAD

**Issue by ewancg** [elkowar/eww#1153]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I have created a simple widget.
```lisp
(defwidget power-menu-buttons []
  (box :class "button-container"
       :orientation "vertical"
       :halign "left"
       :spacing 4
    (button :onclick "systemctl suspend" "Suspend")
    (button :onclick "systemctl poweroff" "Shut down")
    (button :onclick "systemctl reboot" "Reboot")
))

(defwindow power-menu [screen]
           :id "power-menu"
           :monitor screen
           :geometry (geometry :x "3px"
                               :y "3px"
                               :width "15%"
                               :height "10%"
                               :anchor "top left")
           :stacking "overlay"
           :exclusive false
           :focusable false
           :wm-ignore false
           (power-menu-buttons)
)
```
I want to be able to pass the screen that the widget is shown on as a parameter so that I may show it on any of my monitors.

I have 2 monitors, and I'm currently passing the ID of whichever one Hyprland reports as the active monitor to the widget's window. The full invocation looks like this.
```bash
eww active-windows | grep "power-menu"
if [ $? -eq 0 ]; then 
    eww close power-menu 
else
    scr=$(hyprctl activewindow | grep monitor | head -n 1 | awk '{print $2}')
    eww open power-menu --screen $scr
    notify-send $scr
fi
```

The widget is consistently shown on *the other* monitor.

In my case I could just use the process of elimination to get the correct monitor, but for 3 or more there's no way to do it reliably and (as far as I can tell) eww provides no way to query screen information.

### Expected behaviour

I expect the widget to be shown on the screen that Hyprland reports as active.

**Comment by w-lfchen** [comment]
i ran into a similar issue, and i'm really not sure whether this is hyprland's or eww's fault.
the issue i was facing was the fact that hyprland's monitor ids are inconsistent and sometimes even changed on my 2 monitor setup, this might be similar for you, so i'd recommend maybe logging for a bit which of your monitors gets assigned which id.
my fix for launching 2 bars, one on each monitor, consists of a very ugly hack in which i basically look for the order in which hyprland reports the monitors iirc.

a different approach you might want to look into could be getting the monitor's model from `hyprctl monitors` and then passing that via the `--screen` flag.

#1086 might be of interest to you as well.

**Comment by ewancg** [comment]
There's almost certainly a better way to do this, but the following should at least work for any googlers with the same issue. 
```bash
monitor_id=$(hyprctl activewindow | grep monitor | head -n 1 | awk '{print $2}')
hyprctl monitors | grep -A10 "ID $(monitor_id)" | grep 'model:' | awk '{print $2}'
```

My script now looks like this.
```bash
#!/usr/bin/env bash
# eww-toggle-window
# $1 = window name, $2 = monitor id (or none for current)

function get_monitor {    
    if [ ! -z $1 ]; then
        printf "$1"
    else
        hyprctl monitors | grep -A10 "ID $(hyprctl activewindow | grep monitor | head -n 1 | awk '{print $2}')" | grep 'model:' | awk '{print $2}'
    fi        
}

eww active-windows | grep "$1"
if [ $? -eq 0 ]; then 
    eww close "$1"
else
    eww open "$1" --screen="$(get_monitor $2)"
fi
```

**Comment by w-lfchen** [comment]
if you now have a solution that works i'd suggest closing this issue, there is already a pr trying to make display adapters work

**Comment by ovalkonia** [comment]
@ewancg Won't something like `hyprctl -j monitors | jq -r 'first(.[] | select(.focused)) | .model'` work?

**Comment by ewancg** [comment]
@ovalkonia Yes it would! Thanks

**Comment by w-lfchen** [comment]
510b824e7545a7c98e050522a7bc93d884c53432 made it to master, this might be of interest to you
