### ISSUE TITLE
[BUG] master fails to build on rust-1.80.1

### ISSUE THREAD

**Issue by CaptainBloodz** [elkowar/eww#1156]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Using locally build rust-1.80.1
[gui-apps:eww-9999:20240814-220722.log.gz](https://github.com/user-attachments/files/16619557/gui-apps.eww-9999.20240814-220722.log.gz)
Currently testing from binary package.

**Comment by CaptainBloodz** [comment]
Same issue with rust-1.80.1 binary package:
[gui-apps:eww-9999:20240814-224051.log.gz](https://github.com/user-attachments/files/16619632/gui-apps.eww-9999.20240814-224051.log.gz)

**Comment by w-lfchen** [comment]
will be closed by #1144
see #1141 as well

**Comment by CaptainBloodz** [comment]
+1

**Comment by w-lfchen** [comment]
> +1

sorry, i don't understand what means.
does the issue persist?
it should be fixed on master now

**Comment by CaptainBloodz** [comment]
Fixed, indeed.
Sorry
Thks

**Comment by w-lfchen** [comment]
don't worry about it ^^
