### ISSUE TITLE
[BUILD FAIL]  Cannot build on Fedora 40

### ISSUE THREAD

**Issue by D4yvid** [elkowar/eww#1157]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm trying to compile eww in Fedora 40, but no success. I used the eww documentation and saw all the packages needed to compile it, i searched all of them in the fedora repos (the `-devel` and normal ones, as the `-devel` packages are the development ones), and even after installing all of these:
- cairo
- cairo-devel
- freetype-devel
- gdk-pixbuf2
- gdk-pixbuf2-devel
- gdk-pixbuf2-pixbuf2-devel
- glib2
- glib2-devel
- glibc
- gtk-layer-shell
- gtk-layer-shell-devel
- gtk3
- gtk3-devel
- libdbusmenu
- libdbusmenu-devel
- libdbusmenu-gtk3
- libdbusmenu-gtk3-devel
- libgcc
- libpng
- libpng-devel
- libwayland-client
- libwayland-cursor
- libwayland-egl
- libxkbcommon-*
- pango
- pango-devel
- pkgconfig

*NOTE*: The `libwayland*` packages do not have a `-devel` variant, at least on my system

<details>
  <summary>When i build, i get this error:</summary>
  <pre>
[day@pearl eww]$ cargo build --release --no-default-features --features=x11
   Compiling gdk-sys v0.17.0
   Compiling chrono-tz v0.8.3
   Compiling strum_macros v0.26.1
   Compiling cached_proc_macro v0.19.1
   Compiling libm v0.2.8
   Compiling jaq-std v1.2.1
   Compiling memoffset v0.6.5
   Compiling atk v0.17.1
error: failed to run custom build command for `gdk-sys v0.17.0`

Caused by:
  process didn't exit successfully: `/tmp/eww/target/release/build/gdk-sys-e08f87dceca6e53f/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GDK_3.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "gdk-3.0" "gdk-3.0 >= 3.22"` did not exit successfully: exit status: 1
  error: could not find system library 'gdk-3.0' required by the 'gdk-sys' crate

  --- stderr
  Package wayland-client was not found in the pkg-config search path.
  Perhaps you should add the directory containing `wayland-client.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'wayland-client', required by 'gdk-3.0', not found
  Package 'xkbcommon', required by 'gdk-3.0', not found
  Package 'wayland-cursor', required by 'gdk-3.0', not found
  Package 'wayland-egl', required by 'gdk-3.0', not found

warning: build failed, waiting for other jobs to finish...
  </pre>
</details>

**Comment by ovalkonia** [comment]
You won't happen to use homebrew, will you?
