### ISSUE TITLE
[BUG] Build failing

### ISSUE THREAD

**Issue by sowdowdow** [elkowar/eww#1186]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags dbusmenu-gtk3-0.4 dbusmenu-gtk3-0.4 >= 16

  The system library `dbusmenu-gtk3-0.4` required by crate `dbusmenu-gtk3-sys` was not found.
  The file `dbusmenu-gtk3-0.4.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `dbusmenu-gtk3-0.4.pc`.

### Reproducing the issue

On Ubuntu 24.04, GNOME Shell 46.0

Follow the installation [tutorial](https://elkowar.github.io/eww/) up to here :

`cargo build --release --no-default-features --features x11`

**Comment by w-lfchen** [comment]
could this be related to #1125?

**Comment by sowdowdow** [comment]
> is the package `libdbusmenu-gtk3` (that should be the name for ubuntu if i'm not mistaken) installed?

I guess it is : 
```
➜  ~ apt list | grep libdbusmenu-gtk3

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libdbusmenu-gtk3-4/noble,now 18.10.20180917~bzr492+repack1-3.1ubuntu5 amd64  [installé, automatique]
libdbusmenu-gtk3-dev/noble 18.10.20180917~bzr492+repack1-3.1ubuntu5 amd64
```
