### ISSUE TITLE
Support Multi-file configuration

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#12]
Eww should support an `<includes>`  block that allows users to include XML from other files.

This block should be placed at the same level as `<definitions>`, `<variables>` and `<windows>`, and have the following shape:
```xml
<includes>
  <file path="./something.xml"/>
  <file path="./somethingelse.xml"/>
</includes>
```

every one of these files should follow the same structure as the main `eww.xml` file, and may themselves contain other includes. 

At parse time, all the includes should first be parsed into their own `EwwConfig` instance, which should then be merged into one combined `EwwConfig`.

For error messages to stay helpful, the text position of each `WidgetUse` should be expanded into a new struct which also stores the path to the file it was read from. This should then be included in the `Display` implementation of said struct. 

In a later version of this, a namespacing system should be introduced, but that is not part of this issue.

**Acceptance Criteria**
- The EwwConfig parser is expanded to allow for a new block: `<includes>`, which contains a list of files to include.
- Included files are parsed as EwwConfigs and then merged together
- Error messages that show line-numbers correctly contain the path to the file the error originated in
- File paths are correctly resolved relative to the current file
- Tests are written to show that the implementation of merging `EwwConfig`s is correct

**Comment by elkowar** [comment]
@druskus20, this may be something for you. Should not be too hard to implement. If you want, we could go over the implementation together ;D

**Comment by druskus20** [comment]
Sure, I can do this. Will let you know if I need some help.

**Comment by elkowar** [comment]
perfect, i'll assign this issue to you ;D
