### ISSUE TITLE
[FEATURE] Starting eww with a different config path without restarting it.

### ISSUE THREAD

**Issue by Swexti** [elkowar/eww#120]
## Description of the requested feature
Basically i want to use the -c flag without restarting eww

## Proposed configuration syntax
idk

# Additional context
no

**Comment by undefinedDarkness** [comment]
Just make it a one liner or bash function or smth? You'd hvae to run eww reload anyway

**Comment by elkowar** [comment]
this has two possible implementations:
- make it possible to run multiple eww daemons. That should definitely be done regardless of the other option, and would pretty much only require the eww daemon socket file to be specific to the provided config file - running another one when another config file is selected.
- make a daemonless mode that immediately opens a single window and nothing more. This would be a bit harder to implement, but also provide a lot of value both for debugging, development and widget-development.

Nr. 1 I'll definitely implement, Nr. 2 maybe in the future

**Comment by elkowar** [comment]
it is now possible to run different configurations simultaneously, running multiple daemons is now possible by passing different --config flags to the daemon and other commands. Thus this can be closed!
