### ISSUE TITLE
[BUG] Button Colors do not work

### ISSUE THREAD

**Issue by Yasir-Zafar** [elkowar/eww#1201]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

After updating my eww package, the buttons on my bar stopped responding to sccs color changes, while padding and margins work fine. --debug and the logs report no issue 

![1726765778_grim](https://github.com/user-attachments/assets/925622f7-606a-4d3f-928b-16eeee179dba)

### Reproducing the issue

Use latest arch linux build
use latest eww build from either the AUR or gituhub

### Expected behaviour

the background of the buttons should have been same as bar and have proper forground colors as follows

### Additional context

eww.yuck
`(defwindow bar
  :monitor 0
  :exclusive true
  :windowtype "dock"
  :geometry (geometry :x "0%"
                      :y "0px"
                      :width "100%"
                      :height "30px"
                      :anchor "top center")
  (bar))

(defwidget bar []
  (box :class "bar" :orientation "h"
    (left)
    (center)
    (right)))

(defwidget left []
  (box :class "left" :orientation "h" :space-evenly false :halign "start"
    (icon)
    (three-dots)
    (workspaces)
    (three-dots) 
    (dnd-toggle)
    (focused-app)))

(defwidget workspaces []
  (box :class "workspaces" :orientation "h" :space-evenly true
    (for workspace in workspaces
      (button 
        :class {workspace.id == current_workspace ? "active" : "inactive"}
        :onclick "hyprctl dispatch workspace ${workspace.id}"
        {workspace.icon}))))

(defvar workspaces '[
  {"id": 1, "icon": " "},
  {"id": 2, "icon": " 󰖟"},
  {"id": 3, "icon": " 󰅴"},
  {"id": 4, "icon": " 󰉋"},
  {"id": 5, "icon": " 󰝚"},
  {"id": 6, "icon": " 󰙯"}
]')

(defpoll current_workspace :interval "40ms"
  "hyprctl activeworkspace | grep -oP '(?<=workspace ID )\\d+'")

(defwidget dnd-toggle []
  (box :class "dnd-module" :orientation "h" :space-evenly false
    (button :onclick "scripts/toggle_dnd"
      (label :class "icon" :text dnd_icon))))

(defpoll dnd_icon :interval "1s"
  "scripts/dnd_status")
`

eww.scss
`// Color aliases
$background: #282828;
$foreground: #ebdbb2;
$selection: #282828;
$comment: #a6adc8;
$red: #fb4934;
$orange: #fe8019;
$yellow: #fabd2f;
$blue: #83a598;
$green: #b8bb26;
$magenta: #d3869b;
$cyan: #8ec07c;

* {
  all: unset;
  font-family: "JetBrainsMono Nerd Font", monospace;
}

.bar {
  background-color: $background;
  color: $foreground;
  padding: 5px;
}

.icon {
  font-size: 16px;
  min-width: 16px;
  min-height: 16px;
}

.workspaces button {
  background-color: $selection;
  color: $foreground;
}

.workspaces button.active {
  color: $cyan;
}

.workspaces button.inactive {
  color: $foreground;
}

.dnd-module {
  background-color: $selection;
  padding-left: 2px;
  color: $magenta;
}
`

**Comment by w-lfchen** [comment]
could you do me a favour and try to minimize the config to reproduce the issue so i can look into it?
thanks in advance

**Comment by Yasir-Zafar** [comment]
eww.yuck

`(defwindow bar
:monitor 0
:exclusive true
:windowtype "dock"
:geometry (geometry :x "0%"
:y "0px"
:width "100%"
:height "30px"
:anchor "top center")
(bar))

(defwidget bar []
(box :class "bar" :orientation "h"
(left)))

(defwidget left []
(box :class "left" :orientation "h" :space-evenly false :halign "start"
(workspaces)))

(defwidget workspaces []
(box :class "workspaces" :orientation "h" :space-evenly true
(for workspace in workspaces
(button
:class {workspace.id == current_workspace ? "active" : "inactive"}
{workspace.icon}))))

(defvar workspaces '[
{"id": 1, "icon": " "},
{"id": 2, "icon": " 󰖟"},
{"id": 3, "icon": " 󰅴"},
{"id": 4, "icon": " 󰉋"},
{"id": 5, "icon": " 󰝚"},
{"id": 6, "icon": " 󰙯"}
]')

(defpoll current_workspace :interval "40ms"
"hyprctl activeworkspace | grep -oP '(?<=workspace ID )\d+'")
`
eww.scss

`// Color aliases
$background: #282828;
$foreground: #ebdbb2;
$selection: #282828;
$magenta: #d3869b;
$cyan: #8ec07c;

* {
    all: unset;
    font-family: "JetBrainsMono Nerd Font", monospace;
 }

.bar {
background-color: $background;
color: $foreground;
padding: 5px;
}

.icon {
font-size: 16px;
min-width: 16px;
min-height: 16px;
}

.workspaces button {
background-color: $selection;
color: $foreground;
}

.workspaces button.active {
color: $cyan;
}

.workspaces button.inactive {
color: $foreground;
}
`
@w-lfchen i have seperated the config enough and tested it so that only the only module is being used and edited in scss
though keep in mind this will only work on hyprland

andother thing i wanted to mention is that when i change 
{workspace.icon}
to

(label :text {workspace.icon})

and edit the label in scss the background and foreground work fine, so i think this is an issue with how i config the box module or is a bug.

**Comment by w-lfchen** [comment]
i am having a hard time understanding the issue. could you please describe it further?
also, your bar doesnt really do anything on my machine, is the config incomplete?

**Comment by Yasir-Zafar** [comment]
![image](https://github.com/user-attachments/assets/0441d71c-b9b9-421a-aa6c-0a16664f3f0d)
in this image the workspace buttons have style that i did make in the config
if i try to  change the background colors and foreground colors of the buttons, they dont change and remain the same as the image
however if i change padding or margins, they do change, making this an issue only with the colors
the rest of the bar works fine and edits in the scss show predictable behavior

here are the configs of the bar, i tested this config on arch linux and hyprland, the workspace defpoll only work on hyprland and if you have 6 workspaces, sorry i havent figured out to how to make it work with anything other than 6

eww.yuck
```
(defwindow bar
:monitor 0
:exclusive true
:windowtype "dock"
:geometry (geometry :x "0%"
:y "0px"
:width "100%"
:height "30px"
:anchor "top center")
(bar))

(defwidget bar []
(box :class "bar" :orientation "h"
(left)))

(defwidget left []
(box :class "left" :orientation "h" :space-evenly false :halign "start"
(workspaces)))

(defwidget workspaces []
(box :class "workspaces" :orientation "h" :space-evenly true
(for workspace in workspaces
(button
:class {workspace.id == current_workspace ? "active" : "inactive"}
{workspace.icon}))))

(defvar workspaces '[
{"id": 1, "icon": " "},
{"id": 2, "icon": " 󰖟"},
{"id": 3, "icon": " 󰅴"},
{"id": 4, "icon": " 󰉋"},
{"id": 5, "icon": " 󰝚"},
{"id": 6, "icon": " 󰙯"}
]')

(defpoll current_workspace :interval "40ms"
"hyprctl activeworkspace | grep -oP '(?<=workspace ID )\d+'")
```

eww.scss
```
// Color aliases
$background: #282828;
$foreground: #ebdbb2;
$selection: #282828;
$magenta: #d3869b;
$cyan: #8ec07c;

.bar {
background-color: $background;
color: $foreground;
padding: 5px;
}

.icon {
font-size: 16px;
min-width: 16px;
min-height: 16px;
}

.workspaces button {
background-color: $selection;
color: $foreground;
}

.workspaces button.active {
color: $cyan;
}

.workspaces button.inactive {
color: $foreground;
}
```

**Comment by w-lfchen** [comment]
how do you change the colors?
if i change the variables, the changes seem to be properly reflected.

**Comment by Yasir-Zafar** [comment]
Using the scss i provided
I suppose its not a bug then.
the bar isnt affected by gtknconfig in /usr/share or other places is it?
Thats the only thing i can think of that might affect the bar

**Comment by w-lfchen** [comment]
your gtk theme does affect the bar.
if you want to disable all gtk influences, add `all: unset;` before any other styling for the component.
if you want to unset everything gtk adds, add this at the top of your config:
```css
* {
    all: unset;
}
```
after adding `(defvar current_workspace "1")`, this is what your bar looks like for me:
![image](https://github.com/user-attachments/assets/932638ac-1813-424b-8ea3-4e5ddfba842b)
if i add `$selection: #ff0000;`, i get this:
![image](https://github.com/user-attachments/assets/8d433d7a-6dda-4fd2-96b3-bd19831da7ec)
what exactly is the issue?
it seems like your styling is wrong in some way to me

**Comment by Yasir-Zafar** [comment]
i will just reinstall my system and hope it works next time
thanks
