### ISSUE TITLE
[BUG] Installation Issues

### ISSUE THREAD

**Issue by Narky404** [elkowar/eww#1207]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Hi, 
I'm kinda new with Linux.  I'm running Linux Mint 21 and Xfce 4.16. 
I was following the step to install eww but I got this line. I don't really know how to resolve it, like I said I'm new.

### Additional context

![bug](https://github.com/user-attachments/assets/b690c7d1-c665-46aa-a557-1f8f6d89a58e)

**Comment by ovalkonia** [comment]
See https://github.com/elkowar/eww/issues/1186

**Comment by ovalkonia** [comment]
You just need to install all the required packages listed here -> https://elkowar.github.io/eww/eww.html. Note, they need to be development versions. In your case I think it's `libdbusmenu-gtk3-dev`

**Comment by Narky404** [comment]
It work. Thank you !
