### ISSUE TITLE
[BUG] Incorrect handling of an empty string by the safe access operator

### ISSUE THREAD

**Issue by mexanoz** [elkowar/eww#1209]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

The safe access operator (?.) fails to recognize an empty string on the left side and return null (as it should according to the [documentation](https://elkowar.github.io/eww/expression_language.html#features)), instead throwing an error.

### Reproducing the issue

The way I encountered this issue was using a `deflisten` on `playerctl` output, which outputs a JSON string but produces an empty string when all players are shut down. Here's a minimal `eww.yuck` (for Wayland):
```
(deflisten playerctlstatus 'playerctl metadata -aFf \'{"status": "{{status}}"}\'')

(defwidget playerctl []
    (label :text {playerctlstatus?.status}))

(defwindow test
    :geometry (geometry
                  :width "100%"
                  :height "22px"
                  :anchor "bottom center")
    :exclusive true
    :stacking "fg"
    :monitor 0
    (playerctl))
```
When there is an active player, the label correctly contains its state. However, when the player shuts down, `playerctl` outputs "" and the logs show an error:
```
error: Failed to turn `` into a value of type json-value
  ┌─ /home/mex/.config/eww/test-bug/eww.yuck:4:19
  │
4 │     (label :text {playerctlstatus?.status}))
  │                   ───────────────
```

### Expected behaviour

Either
1. The operator returning a `null` with an empty string on the left, or
2. The [documentation](https://elkowar.github.io/eww/expression_language.html#features) explicitly stating that the operator only works with a `null` on the left side and not an empty string.

**Comment by w-lfchen** [comment]
will be closed by #1176

note that the docs don't lie, they are just misleading.
currently, the empty string is not supported, a string consisting of 2 `"` (also referred to as an empty json string) is.

this behavior will be removed by #1176, that pr currently makes indexing `""` an error, and adds support for the empty string.
