### ISSUE TITLE
[BUG] "Error while resolving attributes: Unknown variable 'foo' referenced"

### ISSUE THREAD

**Issue by Swexti** [elkowar/eww#122]
## Describe the bug
It basically can't load the "foo" variable for some unknown reason. Doesn't tell my why, or what's causing it. It just can't do it.

## Reproducing the issue
Uhhhh, i have no idea how to reproduce. It's random?? idk

config here: https://hatebin.com/mygqbebvhj
## Expected behaviour
For it to use the var

## Additional context
no

**Comment by elkowar** [comment]
Can you show the output of `eww debug`?

**Comment by Swexti** [comment]
https://hatebin.com/hruomvlayh

**Comment by Swexti** [comment]
edit: it seems to be a bit random, if i do some changes in the config, suddenly it might work, and i won't get the error anymore. i don't know what's causing, since uncommenting a line fixed it. but if you figure it out, maybe you should add that to the `eww logs` output?

**Comment by elkowar** [comment]
please update to the latest master and then try it again, if it still doesn't work also send eww debug again

**Comment by Swexti** [comment]
okay now it works. thanks
