### ISSUE TITLE
[FEATURE]  add the ability to control the number of decimals in the EWW_CPU.avg variable

### ISSUE THREAD

**Issue by muezabdalla** [elkowar/eww#1254]
### Description of the requested feature

when using the `EWW_CPU.avg` variable it shows the cpu usage with about 16 digits after the decimal whic take a lot of space
I searched in the internet and in the documentation but did not find a way to reduce the digits or remove them

**Comment by ovalkonia** [comment]
You can just use the `round` expression. Something like

```(label :text {round(EWW_CPU.avg, 3)})```

for example.

Check out all the features -> https://elkowar.github.io/eww/expression_language.html#features

**Comment by muezabdalla** [comment]
thanks that worked
