### ISSUE TITLE
[FEATURE] add examples to the Magic Variables

### ISSUE THREAD

**Issue by muezabdalla** [elkowar/eww#1258]
### Description of the requested feature

I think that some of the Magic Variables are obvuis like the `EWW_RAM`
but the `EWW_CPU` is a lot harder I just see it used in the config file as `{EWW_CPU.avg}` but could not know how to show the frequancy or the usage of a specific core
here are some of the methods I tried:
`{EWW_CPU[1].freq.avg}`
`{EWW_CPU[cores].freq.avg}`
`{EWW_CPU[cores].freq}`
also the `EWW_NET` variable is giving null value probably there is a wrong syntax but I couldn't find the right way
here is the variables:
`{EWW_NET["wlo1"].down}`

**Comment by andi242** [comment]
with `eww debug` you can get all the vars and more as json output.

**Comment by muezabdalla** [comment]
in the `eww debug` they use it like this `{EWW_CPU["1"]["avg"]}` which give me blank space
does the `EWW_CPU` variable different from system to another
I think the difference in these variables are in the temperature sensor and the internet interface
I tried to use the internet interface like this
`{EWW_NET["wlo1"]["down"]}`
but it gives a null value

**Comment by andi242** [comment]
It might help if you posted the code you are using.
I do not have interface wlo1, so I can't tell what it should look like in the debug.

I assume you pasted the output of the debug as value of your output?
You get a null value because the json parse does not find the key/values.

for CPU avg I use this:
`{round(EWW_CPU.avg,0)}`

in context
```yuck
(defwidget foo []
  (label 
    :text {EWW_CPU.avg}  ; no quotes
  )
)
```
or a bit more human readable...
```
(defwidget bar []
  (label 
    :text {round(EWW_CPU.avg,0)}  ; no quotes, function in {}
  )
)
```

just assumptions on your issue, though.

**Comment by muezabdalla** [comment]
here is my code
```
(defwidget left []
  (box
    :orientation "horizontal"
    :halign "start"
    {EWW_CPU["2"]["avg"]}
))
```
I know how to show the cpu usage but I want every core useg and the frequancy

for the network I tried `{EWW_NET.wlo1.NET_DOWN}`  and it worked

**Comment by andi242** [comment]
I don't feel like you're even trying... 

anyways... happy holidays. :gift: 
here's code for a test window putting out every core with name, freq, usage.
```
(defwindow testwindow
  :monitor 0
  :geometry (geometry
    :width "50%"
    :height "10%"
    :anchor "top center"
  )
  :stacking "fg"
  :exclusive false
  (box
    (for i in {EWW_CPU.cores}
      (box 
        :orientation "v"
        (label :text {i.core})
        (label :text {i.freq} )
        (label :text {i.usage} )
      )
    )
  )
)
```
I have an 8c/16t cpu, so every thread gets his own stat (also system dependend, nothing eww can do about).

it looks something like this (depending on css)
![image](https://github.com/user-attachments/assets/9b767f1f-4cd3-4b9b-80b5-7ccdc331592e)
not a stat window I personally would find very useful. though.

**Comment by muezabdalla** [comment]
I was try but I did not understand the text in the `eww debug` command
here is the output of it about the cpu
```
"EWW_CPU": "{"avg":1.9313364028930664,"cores":[{"core":"cpu0","freq":741,"usage":1},{"core":"cpu1","freq":720,"usage":1},{"core":"cpu2","freq":400,"usage":2},{"core":"cpu3","freq":400,"usage":1},{"core":"cpu4","freq":400,"usage":2},{"core":"cpu5","freq":774,"usage":2},{"core":"cpu6","freq":400,"usage":3},{"core":"cpu7","freq":400,"usage":1}]}",
```

thank you very much that help me alot
