### ISSUE TITLE
[FEATURE] add documentation about ifs, loops and case statements

### ISSUE THREAD

**Issue by muezabdalla** [elkowar/eww#1262]
### Description of the requested feature

currently there is no documentation about the ifs, loops and  case statements. I even thought that there is no suck a thing but someone teach me that on another feature request(#1258)

**Comment by w-lfchen** [comment]
yuck isn't really a programming language.
as far as i'm aware `if` and `case` don't exist, and the closest thing to a loop is the [`for`](https://elkowar.github.io/eww/configuration.html#generating-a-list-of-widgets-from-json-using-for) structure.
i'm really confused how you came up with this as your linked issue doesn't seem to mention any of that

**Comment by muezabdalla** [comment]
at the begging I thought that it is a language made just for configuration so it will not have an if or case or loops but when I seen the for loop I thought it might have an if and case and while loop.
sorry for that.
