### ISSUE TITLE
[BUG] Daemon fails to start after installation

### ISSUE THREAD

**Issue by nixin72** [elkowar/eww#129]
## Describe the bug
When trying to run `eww daemon` I get the following error
```
❯ ./eww daemon
Failed set paths

Caused by:
    No such file or directory (os error 2)
```

## Reproducing the issue
1) Install from AUR or compile from source
2) Run `eww daemon` or `target/release/eww daemon`

## Expected behaviour
The daemon process starts up 

## Additional context
Running on Manjaro with KDE + i3

**Comment by undefinedDarkness** [comment]
`        let paths = opts
            .config_path
            .map(EwwPaths::from_config_dir)
            .unwrap_or_else(EwwPaths::default)
            .context("Failed set paths")?;`
  This is causing the error but I have no idea why

**Comment by undefinedDarkness** [comment]
Do you have a .config/eww dir made?

**Comment by nixin72** [comment]
Yea, I have a `~/.config/eww` directory

**Comment by legendofmiracles** [comment]
As far as i understand, config path is none (because you didn't pass it as a argument). 
Then it gets the the default config path but that fails somewhere.
What happens if you `./eww -c /home/$USER/.config/eww daemon`?

**Comment by nixin72** [comment]
Oh crap, `zsh` wasn't auto-completing the config path - I hadn't symlinked it yet from my `dotfiles/.config/eww` :facepalm: 

I'm so sorry, that's my bad. Starting the daemon and opening windows works now...

**Comment by undefinedDarkness** [comment]
Close issue if problem is resolved 😀
