### ISSUE TITLE
Scientifica doesn't load?

### ISSUE THREAD

**Issue by der-zonk** [elkowar/eww#132]
Sorry if this is a dumb question, I'm fairly new to this and I don't know whether this is a Scientifica issue or eww issue..
All fonts I tried work, but not https://github.com/NerdyPepper/scientifica
I don't get any errors when setting it as font but it seems like eww is just loading a fallback mono font. None of the formats work.
Even the siji icons work..

And a second question.. Is there a way to disable the antialiasing in eww? It just doesn't look good when drawing 1-2px borders or using pixelfonts like siji..
I wouldn't want to disable antialiasing systemwide.
Thanks a lot for your work. =)

**Comment by undefinedDarkness** [comment]
Eww is more or less a fancy wrapper over GTK, GTK uses pango rendering which since moving to the harfbuzz shaper has dropped support for bitmap fonts unfortunately, as such unless you downgrade pango (a difficult process at this stage I think) you could 
[(see this issue)](https://gitlab.gnome.org/GNOME/pango/-/issues/386)
Use a non-bitmap vector font
Convert it into a vector font 
iirc scientifica has a vector version & so does cozzete idk about siji

I dont think there is any real way from eww to disable antialiasing unfortunately, maybe some sort of fontconfig trick

I havent really researched any of this, so it might be possible i dunno

**Comment by der-zonk** [comment]
Excuse my stupidity for I am not familar with most of the terms your using. So this Scientifica release is not in pcf or bdf format, It's in scalable ttf and otb. It works in dmenu, dwm, my gtk stuff, terminal..
I know about the pango stuff, that's why I got my siji and scientifica font as ttf and otb So I could still use it in polybar.. The stuff on top is polybar
The siji icons work well in eww, Scientifica doesn't.. I'm too dumb to understand this probably..
![scrotty](https://user-images.githubusercontent.com/80225209/110741658-55d78f80-8235-11eb-9b02-530a19c6112f.png)

**Comment by undefinedDarkness** [comment]
Im just as confused as you are, how are you setting the fontr

**Comment by undefinedDarkness** [comment]
From what I can see in the screenshot, it doesn't look correct

**Comment by der-zonk** [comment]
I tried everything that I understand so far.. I just started playing with this yesterday.
font: 18px Cozette;
or
font-family: Cozette;
font-size: 18px;
I tried every naming theme fc-list spit out for cozette & scientifica.

to your last comment: It is correct, you can read here https://developer.gnome.org/gtk3/stable/chap-css-properties.html

**Comment by undefinedDarkness** [comment]
![pr](https://user-images.githubusercontent.com/38278035/110747698-baf6a980-8264-11eb-9a2b-bc6b12046f14.png)
You were so close, you forgot "
¯\_(ツ)_/¯

**Comment by undefinedDarkness** [comment]
that or the fonts are not installed correctly

**Comment by der-zonk** [comment]
It's not the ", it works for other fonts... I'll look into the "fonts not installed correctly" stuff. xD
Thanks for trying.
But man.. with antialiasing those fonts just don't work.. Not sure if it's even worth it anymore xD

**Comment by undefinedDarkness** [comment]
You should probably be using a vector font anyway
If you find a way to do it from within eww, feel free to contribute

**Comment by der-zonk** [comment]
Problem solved. Arch Wiki comes to the rescue like always.
https://wiki.archlinux.org/index.php/font_configuration#Custom_settings_for_certain_fonts_or_font_styles

**Comment by undefinedDarkness** [comment]
Close the issue if you solved it :)
