### ISSUE TITLE
[BUG] while bilding

### ISSUE THREAD

**Issue by aagradwan** [elkowar/eww#137]
Running `rustc --crate-name eww --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="gdkx11"' --cfg 'feature="x11"' --cfg 'feature="x11rb"' -C metadata=5ed49f34bda5e3b3 -C extra-filename=-5ed49f34bda5e3b3 --out-dir /home/radwan/eww/target/release/deps -L dependency=/home/radwan/eww/target/release/deps --extern anyhow=/home/radwan/eww/target/release/deps/libanyhow-97535be7c8e652d1.rlib --extern async_stream=/home/radwan/eww/target/release/deps/libasync_stream-8116f3fd3d5650ad.rlib --extern base64=/home/radwan/eww/target/release/deps/libbase64-4713c7b2791df680.rlib --extern bincode=/home/radwan/eww/target/release/deps/libbincode-6510468eb75950f5.rlib --extern debug_stub_derive=/home/radwan/eww/target/release/deps/libdebug_stub_derive-affd25c8b2cee6d4.so --extern derive_more=/home/radwan/eww/target/release/deps/libderive_more-aebbaf43412726a8.so --extern dyn_clone=/home/radwan/eww/target/release/deps/libdyn_clone-fcf441f9d8ca4f10.rlib --extern extend=/home/radwan/eww/target/release/deps/libextend-09e0337c233b2ee1.so --extern futures_core=/home/radwan/eww/target/release/deps/libfutures_core-061a00d6e5095855.rlib --extern futures_util=/home/radwan/eww/target/release/deps/libfutures_util-17c834e9b304e456.rlib --extern gdk=/home/radwan/eww/target/release/deps/libgdk-f0e22c88a649bfe9.rlib --extern gdk_pixbuf=/home/radwan/eww/target/release/deps/libgdk_pixbuf-2ee5996daa0f5632.rlib --extern gdkx11=/home/radwan/eww/target/release/deps/libgdkx11-d33628bfe6d91143.rlib --extern gio=/home/radwan/eww/target/release/deps/libgio-86cce1491d7583c8.rlib --extern glib=/home/radwan/eww/target/release/deps/libglib-f230f91fa8cc6559.rlib --extern grass=/home/radwan/eww/target/release/deps/libgrass-55a6550038acc649.rlib --extern gtk=/home/radwan/eww/target/release/deps/libgtk-767a30733da92366.rlib --extern inotify=/home/radwan/eww/target/release/deps/libinotify-2e48b29df5eff9e6.rlib --extern itertools=/home/radwan/eww/target/release/deps/libitertools-41978a6ec1e02f05.rlib --extern lazy_static=/home/radwan/eww/target/release/deps/liblazy_static-3bc74deaf381691c.rlib --extern libc=/home/radwan/eww/target/release/deps/liblibc-d245d3a605967786.rlib --extern log=/home/radwan/eww/target/release/deps/liblog-d9d672927650d070.rlib --extern maplit=/home/radwan/eww/target/release/deps/libmaplit-d315c8af77d0fcd3.rlib --extern nix=/home/radwan/eww/target/release/deps/libnix-12fced105f2e4b40.rlib --extern nom=/home/radwan/eww/target/release/deps/libnom-1f61f0dc0550989a.rlib --extern num=/home/radwan/eww/target/release/deps/libnum-4a45a61d7c6e6129.rlib --extern pretty_env_logger=/home/radwan/eww/target/release/deps/libpretty_env_logger-85aaad99714eb665.rlib --extern regex=/home/radwan/eww/target/release/deps/libregex-00a009a9a3618493.rlib --extern roxmltree=/home/radwan/eww/target/release/deps/libroxmltree-d2a8064b4a54e714.rlib --extern serde=/home/radwan/eww/target/release/deps/libserde-b46db81eac8d71e2.rlib --extern simple_signal=/home/radwan/eww/target/release/deps/libsimple_signal-4c3afab2f0ffbf7a.rlib --extern smart_default=/home/radwan/eww/target/release/deps/libsmart_default-92af2efc2b627956.so --extern structopt=/home/radwan/eww/target/release/deps/libstructopt-bf34c7b967fa5bd3.rlib --extern tokio=/home/radwan/eww/target/release/deps/libtokio-4d08a635b26ced37.rlib --extern tokio_stream=/home/radwan/eww/target/release/deps/libtokio_stream-73bf4debb488df68.rlib --extern tokio_util=/home/radwan/eww/target/release/deps/libtokio_util-ed23414d397c59c3.rlib --extern unescape=/home/radwan/eww/target/release/deps/libunescape-6856280b46b8ae68.rlib --extern wait_timeout=/home/radwan/eww/target/release/deps/libwait_timeout-c1d6d5d467eee048.rlib --extern x11rb=/home/radwan/eww/target/release/deps/libx11rb-55422f4cbbcc3eea.rlib`

**Comment by undefinedDarkness** [comment]
What is the error

**Comment by aagradwan** [comment]
no im using cargo

**Comment by elkowar** [comment]
U godda provide more info than a single line of the error output

**Comment by undefinedDarkness** [comment]
I don't think that's error output, just looks like the command cargo runs to build things

**Comment by aagradwan** [comment]
> U godda provide more info than a single line of the error output

how ?

**Comment by undefinedDarkness** [comment]
Uhhhhh

**Comment by legendofmiracles** [comment]
Read the docs on how to compile eww properly. https://elkowar.github.io/eww/main/
If anything goes wrong, please provide the entire output from all commands.

**Comment by aagradwan** [comment]
> Read the docs on how to compile eww properly. https://elkowar.github.io/eww/main/
> If anything goes wrong, please provide the entire output from all commands (copy paste it).

i did it and the same things happend

**Comment by undefinedDarkness** [comment]
You still need to provide more error output or a screenshot at the very least

**Comment by elkowar** [comment]
I'll close this, as either the user has managed to fix the issue, or is unwilling to actually give the necessary information to help us fix it, in which case this issue won't ever get resolved. 🤷🏻  If you still have the issue and want to provide a full screenshot with the error message etc, feel free to reopen
