### ISSUE TITLE
[BUG] Failed to initialize eww paths 

### ISSUE THREAD

**Issue by marvelman3284** [elkowar/eww#138]
## Describe the bug
After following all the steps listed on the website running `./eww daemon` returns this error: 
```sh
Failed to initialize eww paths

Caused by:
    Configuration directory /root/.config/eww does not exist
```
## Reproducing the issue
Follow the tutorial listed [here](https://elkowar.github.io/eww/main/). Then run `./eww daemon` and you might get this error.
## Expected behaviour
I believe that it should return nothing but I am not sure.
## Additional context
If applicable, provide additional context or screenshots here
This is my third time trying to install eww. 
The first time failed because I didn't have rustup.
The second time failed for this reason.
The third time failed for this reason.

### System Information
![Screenshot_20210317_085704](https://user-images.githubusercontent.com/58921302/111471050-db0fe800-86fe-11eb-9f8d-282a06c54b54.png)

**Comment by undefinedDarkness** [comment]
are you running as sudo

**Comment by legendofmiracles** [comment]
You have to create the eww config dir, and then populate it with a `eww.xml` and `eww.scss`. Read the docs for more information: https://elkowar.github.io/eww/main/the-basics-of-how-to-configure-eww.
Despite that, what does `whoami` return? You shouldn't really be running eww as root.

**Comment by marvelman3284** [comment]
I am in school right now, I will try the solutions after.
