### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by travankor** [elkowar/eww#139]
Can you start tagging releases for eww? Helps with packaging. Thanks.

**Comment by legendofmiracles** [comment]
No, as eww isn't production ready yet, and many features prone to change. It shouldn't be packaged yet.

**Comment by undefinedDarkness** [comment]
Exactly

**Comment by travankor** [comment]
Have you heard of semver scheme? https://semver.org/

>Major version zero (0.y.z) is for initial development. Anything MAY change at any time. 

>How should I deal with revisions in the 0.y.z initial development phase?
>The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

**Comment by elkowar** [comment]
Yes, don't worry. Main point is: Eww won't guarantee any kind of stability right now. Most users wouldn't care for semver (as in, would still get anoyed if i break everything). Thus, I'm generally a fan of making it somewhat difficult to set up until it's ready - gives the users enough need to actually understand that it's not done. having it be packaged properly already would conflict with that. SemVer will happen once eww is stable-ish

**Comment by travankor** [comment]
ok i'll install -git eww until you get bored breaking everything

**Comment by undefinedDarkness** [comment]
![655941807246540819](https://user-images.githubusercontent.com/38278035/111784757-c93a6a80-88e1-11eb-833b-e3c05393510b.png)

**Comment by legendofmiracles** [comment]
lol
