### ISSUE TITLE
[BUG] Auto Start in i3

### ISSUE THREAD

**Issue by n04x** [elkowar/eww#142]
## Describe the bug
I have this bug when I am trying to run it from i3 config file to autostart it. It used to works fine. Here are the explanation of issues

Code: 
```
exec_always --no-startup-id eww daemon
exec_always --no-startup-id sleep 1; eww open bar
```

I added the sleep 1 because it tried to execute eww open bar too fast, so with that it should work (usually I only use exec). I switched to exec_always because now whenever I boot or reboot my laptop, bar is not showing anymore. But! with exec_always whenever I restart i3 wm (mod+shift+r by default), the bar show up and works fine. Also, when I looks at eww logs, there is no error and it says that eww daemon is started. So by that logic, the first line (`exec_always --no-startup-id eww daemon`) is working fine but doesn't seem to trigger the `eww open bar` one.

## Reproducing the issue
I am not sure how this issue would be reproduceable but basically in the i3 config file (~/.config/i3/config by default), you add these exec code as mentionned earlier. I have also tried variant below:
`exec_always --no-startup-id eww daemon; eww open bar`
I also tried without `sleep 1` function:
```
exec_always --no-startup-id eww daemon
exec_always --no-startup-id eww open bar
```
and the issue is still there...
the default one that should be working:
```
exec --no-startup-id eww daemon
exec --no-startup-id sleep 1; eww open bar
```

## Expected behaviour
The expected behavious is the bar should be shown at each boot automatically.

## Additional context
Personally, I am sure this is a stupid small issue but I want to eliminate every possible that eww is the cause, because my i3 config is running every other exec without problem such as nitrogen. Thank you

**Comment by legendofmiracles** [comment]
If it was working before, did you update eww?
Any other component of the system? 

Can you please try launching it with `--debug` in your i3 config and then checking the logs again?

**Comment by n04x** [comment]
Hi, 

It was working before under Manjaro. I reformat and use Arch instead for peformance reason. On my VM (Oracle VM Machine) it works fine and everything under Arch. Then I installed Arch on this laptop and now eww doesn't work. 

For the eww logs here what I got:
```
DEBUG eww::app                > Handling event: KillServer
 INFO  eww::app                > Received kill command, stopping server!
 DEBUG eww::script_var_handler > Stopping script-var-handlers
 INFO  eww::server             > main application thread finished
 INFO  eww::server             > Forward task received exit event

┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛

```

It really looks like the command is not called in the i3 config. Here the link to the config pastebin: https://pastebin.com/bdedQyvy

I know it is not a typo in the script because like I mentionned earlier, whenever I restart i3 it works.

Thanks for your help

**Comment by undefinedDarkness** [comment]
I tried doing something like this ~ it was an issue with X not being available & gtk so what I did was have a while loop that continuously ran `eww open test` till `eww windows` reports that it is open with `*test` try doing that in a shell script

**Comment by n04x** [comment]
> I tried doing something like this ~ it was an issue with X not being available & gtk so what I did was have a while loop that continuously ran `eww open test` till `eww windows` reports that it is open with `*test` try doing that in a shell script

Sound like a good idea... Can you give me an example of code to check that? Because I am unfamiliar with X and gtk issues so it might be a good suggestion...

**Comment by undefinedDarkness** [comment]
```
eww daemon
while [[ "$(eww windows)" != *"*test"* ]]
do
  eww open test
done
echo "Opened Window!"
```
replace test for whatever window name you have

**Comment by nixin72** [comment]
Thanks for this snippet @undefinedDarkness! My strategy before was just sleeping for a second, but this is probably better hahah.

**Comment by n04x** [comment]
Thanks @undefinedDarkness for that, it works! Oh my god... finally! I can go ahead and customize it instead of Polybar :)

**Comment by VuiMuich** [comment]
> ```
> eww daemon
> while [[ "$(eww windows)" != *"*test"* ]]
> do
>   eww open test
> done
> echo "Opened Window!"
> ```

I use this for use with `open-many`
```shell
while [[ -z "$(eww windows | grep '[*]')" ]]; do
  eww open-many left tags right
done
```

**Comment by mipimipi** [comment]
Just for the sake of sharing information: The solutions/workarounds mentioned above did not work for me. I use this code to let i3 / sway launch eww windows:

    # Make sure that the eww daemon is running
    eww daemon &> /dev/null
    while [ -z  $(eww ping 2> /dev/null) ]; do
       sleep 0.2s
    done

    # Open window
    eww open my-window &> /dev/null
 
The code is contained in a script file which is executed by i3 / sway at startup.
