### ISSUE TITLE
[BUG] script-vars passed through attributes are not refreshed on change

### ISSUE THREAD

**Issue by RaisonBlue** [elkowar/eww#144]
Hi, thanks for making eww :D !

## Describe the bug
When data is fetched with script-var and passed to a user-defined widget through an attribute, the widget is not re-rendered when the variable is updated.

## Reproducing the issue
* Create an easy-to-refresh script-var
* pass it to a defined-widget through an attribute
* Update it
* Widget wont be updated

Or don't and just clone my reproduction repo :
[https://github.com/RaisonBlue/eww-definition-attributes](https://github.com/RaisonBlue/eww-definition-attributes)

## Expected behaviour
I'm expecting to pass variable to definitions through attributes so I can reuse my definitions.

**Comment by undefinedDarkness** [comment]
Are you using eww expressions

**Comment by undefinedDarkness** [comment]
Hmm ~ I think since the second line 2 is empty eww ignores it as it should, just put a blank unicode char there or a space & test

**Comment by undefinedDarkness** [comment]
Its possible I misunderstood entirely 😅

**Comment by RaisonBlue** [comment]
I've removed line2 from my repo since it is indeed not related to the issue. If it's still unclear I guess the question we could ask is : why isn't the value held by default_sink_vol updated in the definition when one change the volume, whereas it is updated when used directly in the window template.

**Comment by RaisonBlue** [comment]
Were you able to reproduce it ?Lemme know if you guys need any other info about this bug :)

**Comment by undefinedDarkness** [comment]
Yeah I was ~ but have no idea why
The script & attribute code is a mess only elkowar can navigate

**Comment by RaisonBlue** [comment]
I don't know Rust (yet :D) so I can't be any further assist I guess. Thanks for your assist. Glad to help @elkowar if needed.

**Comment by elkowar** [comment]
Please try again with the newest build, this should be fixed now! If it isn't please reopen the issue

**Comment by RaisonBlue** [comment]
Works like a charm ! Thanks, definitions will make a lot of sense now :D
