### ISSUE TITLE
[BUG] Variables not updating (Possibly caused by wayland?)

### ISSUE THREAD

**Issue by Apppppppple** [elkowar/eww#145]
## Describe the bug

Using the basic config from [here](https://elkowar.github.io/eww/main/the-basics-of-how-to-configure-eww/), the variable date is not set (the window says  "The time is: currently."). Setting the script-var to have an interval of 1s does set the var, but it isn't updated until the window is restarted. `eww open main_window` gives `Failed to get x11 window for gtk window` and then opens the window.

`eww logs` gives
```md
(eww:443643): Gdk-CRITICAL **: 10:44:23.890: gdk_screen_get_monitor_geometry: assertion 'monitor != NULL' failed
Gdk-Message: 10:44:23.912: Window 0x55eecf9f55f0 is a temporary window without parent, application will not be able to position it on screen.
```

## Reproducing the issue

My exact config is
```xml
<eww>
	<includes>
		<!-- Put your <file>'s in here -->
	</includes>

	<definitions>
		<!-- Put your <def>'s in here -->
		<def name="clock">
			<box>
				The time is: {{my_time}} currently.
			</box>
		</def>
		<def name="main">
			<box>
				<clock my_time="{{date}}"/>
			</box>
		</def>
	</definitions>

	<variables>
		<!-- Put your <script-var> and <var>'s in here -->
		<script-var name="date">
			date
		</script-var>
	</variables>

	<windows>
		<!-- Put your window blocks here -->
		<window name="main_window" stacking="fg" focusable="false" screen="1">
			<geometry anchor="top left" x="300px" y="50%" width="25%" height="20px"/>
			<reserve side="left" distance="50px"/>
			<widget>
				<main/>
			</widget>
		</window>
	</windows>
</eww>
```
and I have an empty eww.scss.

The command I'm using to run it is
```bash
eww kill && eww daemon && sleep 1 && eww open main_window || eww logs
```

## Additional context

OS: Arch Linux x86_64
WM: sway

![screenshot_2021-03-29_10-38-17_530522582](https://user-images.githubusercontent.com/19359968/112855160-8ebc9480-907c-11eb-9a03-8e7c7b824f34.png)

**Comment by Apppppppple** [comment]
Didn't realize there wasn't wayland support, my bad.

**Comment by undefinedDarkness** [comment]
Yeah umm there is a pr for it but it's not been merged yet
