### ISSUE TITLE
[FEATURE] Non-primitive values (JSON)

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#146]
## Description of the requested feature
Eww `PrimitiveValue` could actually support non-primitive data structures by just allowing JSON.
This would mean that another option for the PrimitiveValue would be treating it as a json string, that would get parsed on access. This would happen if the value is accessed via dot-access notation (i.e. `foo.bar`) as well as list-indexing (`foo[2]`).

To implement, this would just re-parse the string every access (pretty much only happens when it changes, so not really an issue) using serde, and then do the desired field-access.

**Comment by undefinedDarkness** [comment]
https://cdn.discordapp.com/emojis/689559165584408595.png
