### ISSUE TITLE
[BUG] Double quotes don't work

### ISSUE THREAD

**Issue by rayes0** [elkowar/eww#147]
## Describe the bug
Escaped double quotes do not work in newer versions of eww (after [commit #121](https://github.com/elkowar/eww/commit/a18901f187ff850a21a24c0c59022c0a5382ffd9))

## Reproducing the issue
Using a version of eww after commit #121:
- Put `&quot;` (escaped double quotes in XML) anywhere in the text field of a `<label>`
- A raw `&quot;` will be displayed instead of a double quote

Using versions before commit #121, the double quotes show as expected

## Expected behaviour
A `"` should be shown instead of `&quot;`

## Additional context
Here is a screenshot of the problem:

![out](https://user-images.githubusercontent.com/70722312/113218792-ad36b180-926f-11eb-8963-ef3575032fd8.png)

**Comment by rayes0** [comment]
Sorry for the edits, I hit the enter key by accident.

**Comment by undefinedDarkness** [comment]
It's good that you were able to narrow it down to one commit :)
