### ISSUE TITLE
[BUG]  eww.xml does not have a root node

### ISSUE THREAD

**Issue by Spectralitree** [elkowar/eww#150]
Would fix this myself if I knew rust, but I do not (yet).

### Describe the bug
When initializing the daemon, and then running the logs, this error is shown:
```
Failed to load eww config file /home/pals/.config/eww/eww.xml

Caused by:
    the document does not have a root node
```

### Steps to reproduce
I basically followed everything in the docs, used curl to install rustup, cloned the repo, created an xml file and scss file at `/.config/eww/` and built the code. When initialize to run `./eww daemon`, the above error is shown in logs. I installed rustup and cloned the repo today, so it is the most recent version.

Not sure if this matters, but I am using arch linux with the xfcde4 desktop environment. I can provide the xml and scss file if needed.

**Comment by elkowar** [comment]
Im assuming the error tells u exactly what is wrong: ur missing the root node. Eversthing in the xml must be wrapped inside a `<eww>` tag

**Comment by Spectralitree** [comment]
I did wrap it, though!
```
<eww>
    <includes>
        <!-- Put your <file>'s in here -->
    </includes>

    <definitions>
        <def name="main">
            <box spacing="3px">
                <label text="hello!" wrap="true" valign="start" halign="fill"/>
            </box>
        </def>
    </definitions>

    <variables>
        <!-- Put your <script-var> and <var>'s in here -->
    </variables>

    <windows>
        <window name="main_window" stacking="bg" focusable="false" screen="1">
            <geometry anchor="top right" x="30px" y="30px" width="15%" height="50%"/>
            <reserve side="right" distance="30px" />
            <widget>
                <main/>
            </widget>
        </window>
    </windows>
</eww>
```
This is my config file, not sure if I messed anything up inside of it, but it's wrapped in `<eww>` tags.

**Comment by undefinedDarkness** [comment]
:thinking: god xml is so shit

**Comment by elkowar** [comment]
Are you sure you're actually loading that config properly? it works for me 🤔

**Comment by undefinedDarkness** [comment]
Yeah no need to use -c or anything if the config is @ `~/.config/eww/eww.xml`

**Comment by Spectralitree** [comment]
OH. nevermind lol turns out the config file was completely empty. I swore I saved it. My bad.
