### ISSUE TITLE
a wifi [WIDGET] 

### ISSUE THREAD

**Issue by xukongwen** [elkowar/eww#151]
## Description of the widget
i want have a wifi bar or widget for my xmonad WM.

## Implementation proposal
sorry i know nothing about GTK....

Please include links to the respective GTK documentation pages.

## Example usage
Provide an example snippet of configuration showcasing how the widget could be used, including the attributes the widget should support.
For anything non-obvious, include an explanation of how the properties should behave.

## Additional Context
Provide any additional context if applicable.

**Comment by legendofmiracles** [comment]
If anything, this could be done with magic vars - but because of several implementations this is unlikely to happen. I'll see what I can do, once the necessary PR is merged.

**Comment by undefinedDarkness** [comment]
Yeah magic vars make sense for this

**Comment by undefinedDarkness** [comment]
If anything I'm worried about all the ppl that dont use nm asking for compatavility making things convoluted ~ might be easier to just have some scripts users can use depending on what they use

**Comment by elkowar** [comment]
I think more complex network-related stuff  is a bit too complex to include in basic predefined variables. Network usage will be included in the magic vars, for anything more, it's time for scripting.
