### ISSUE TITLE
[BUG] special characters (ie. <) do not display when defined in xml

### ISSUE THREAD

**Issue by PsychicNoodles** [elkowar/eww#154]
## Describe the bug

Currently xml files cannot contain special characters like `<` or `{` in attribute values, such as in the following:

```xml
<label text="<" />
```

This is not terribly surprising as I think typically in xml you would need to use an xml entity for special characters like that, but unfortunately if you switch to something like this:

```xml
<label text="&lt;" />
```

then it appears as the literal text `&lt;` rather than translating properly. The same thing happens if you try defining a variable with `&lt;` and then inserting it like:

```xml
<label text="{{lt}}" />

...

<var name="lt">&lt;</var>
```

or if you try including it as a raw value:

```xml
<box>
  &lt;
</box>
```

However, it should be possible to fix this by decoding the xml entity as if you update the variable from the command line like `eww update lt="<"` then it will start displaying the character as desired.

## Reproducing the issue

As described above, try inserting either a `<` or `&lt;` into any context (raw value, attribute value, variable value) within xml.

## Expected behaviour

Either the `<` case or the `&lt;` case should translate into displaying `<`. Although the former might work when quoted within a attribute value it'd probably be better and more consistent to go with the latter case.

## Additional context
If applicable, provide additional context or screenshots here

**Comment by elkowar** [comment]
This is the same issue as #147, I really need to start fixing this :(

**Comment by undefinedDarkness** [comment]
Kotlin DSL config when
So we wont have to deal with stinky XML

**Comment by PsychicNoodles** [comment]
> This is the same issue as #147, I really need to start fixing this :(

Ah, sorry about the duplicate issue! I did some light peeking at the xml parsing and seems like it's simply a matter of running the strings through a conversion, although if you want to add a param to enable entity conversion then that'd of course be a bit more work.

**Comment by elkowar** [comment]
I fear that it's not as simple, as it _did_ work before - something i did to the attribute expressions broke this. I'll look into this right now....

I really want to start doing the config language, honestly. This is pain. Existence is pain.
