### ISSUE TITLE
Failed install on Debian Sid

### ISSUE THREAD

**Issue by isaac025** [elkowar/eww#155]
## After running cargo build --release
the following build error is given:
`failed to run custom build command for gdk-sys v0.10.1`

Am I missing a library on my system? Or is this an issue with Debian?

**Comment by undefinedDarkness** [comment]
You're missing dependencies probably
Show the entire error

**Comment by legendofmiracles** [comment]
See [this](https://github.com/elkowar/eww/issues/152) for all the dependencies. 
Once eww is released (when?) it'll hopefully become easier to install, and all the deps will be listed.

**Comment by elkowar** [comment]
Closing this as there is missing information, and I'd assume the user has probably fixed it themselves already.
