### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by creio** [elkowar/eww#156]
Show an example of an input with opening a URL in a browser?

`<input value="open url"/>`, write address, Enter, open url browser.

**Comment by elkowar** [comment]
Please don't abuse issues for questions like this - If you have a concrete question about how to achieve something, ask people (many knowledgeable people are found on the r/unixporn discord), or use the Discussions page to ask your question

**Comment by creio** [comment]
> Please don't abuse issues for questions like this - If you have a concrete question about how to achieve something, ask people (many knowledgeable people are found on the r/unixporn discord), or use the Discussions page to ask your question

And couldn't you translate in one click Discussions(https://i.imgur.com/cHZZ66H.png). But it's easier to close and write this comment.
