### ISSUE TITLE
[BUG?] Buttons inside of literal widgets are unclickable if the script-var interval is too low.

### ISSUE THREAD

**Issue by Apppppppple** [elkowar/eww#157]
## Describe the bug
I'm trying to replicate the workspace behavior of the default swaybar where only workspaces with open windows in them are shown using a `<literal>` widget and a bash script. My script is mostly working, but if the script-var update interval is too low, the buttons are not clickable. Setting the interval higher works, but it results in a noticeable delay (it has to be set around 400ms to be able to be clicked consistently).

## Reproducing the issue
Define a widget with
```xml
<literal content="{{test-buttons}}"/>
```
and the `script-var`
```xml
<script-var name="test-buttons" interval="100ms">
./scripts/test-buttons
</script-var>
```
`./scripts/test-buttons`:
```bash
#!/bin/env bash
echo '<button onclick="kitty">button</button>'
```
You should be unable to click the button. Changing the interval to 400ms should make it clickable.

## Expected behaviour
The button should (ideally) be clickable regardless of the interval setting.

**Comment by elkowar** [comment]
Hmmmmm this is indeed weird. I assume GTK just takes a bit too long to make the button pressable again. 

General recommendation here: Use a script-var without an interval that watches for output continuously. Then, make your script only output new xml whenever the state actually changed - for that, find some way to listen events from your window-manager/compositor. on X, you can use `xprop -spy -root _NET_CURRENT_DESKTOP` for example. on wayland no idea.

**Comment by Apppppppple** [comment]
Thanks, will do
