### ISSUE TITLE
[BUG] Reserve no longer working?

### ISSUE THREAD

**Issue by Apppppppple** [elkowar/eww#158]
## Describe the bug
Until now I was using an older version of the wayland fork, after updating I cannot get eww to reserve a screen area. (compiled with `cargo +nightly build --release --no-default-features --features wayland`)

## Reproducing the issue
If possible, provide a simple example configuration that shows the issue.
```xml
<window name="bar" sreen="0" focusable="false">
	<geometry anchor="top left" x="0%" y="0%" width="100%" height="1%"/>
	<reserve side="top" distance="0px" layer="top" stacking="ov" exclusive="true" x="0%" y="0%"/>
	<widget>
		<bar/>
	</widget>
</window>
```
doesn't work, but I've also tried a number of other configurations.

## Expected behaviour
The screen space is reserved correctly,

**Comment by elkowar** [comment]
https://elkowar.github.io/eww/main/the-basics-of-how-to-configure-eww/
check the docs, the wayland implementation has been changed a bit to streamline the process with reserve. Also see the last few comments in #125

**Comment by Apppppppple** [comment]
tried with this
```xml
<window name="bar" sreen="0" focusable="false" exclusive="true" stacking="fg">
	<geometry anchor="top left" x="0%" y="0%" width="100%" height="1%" exclusive="true"/>
	<widget>
		<bar/>
	</widget>
</window>
```
and it still doesn't seem to work :(. Also tried the eww-bar window definition and that also didn't reserve space.

**Comment by snakedye** [comment]
`exclusive` goes in windows only.

This is what I have in my configuration.

```
    <window name="bar" screen="1" stacking="bt" exclusive="true">
      <geometry anchor="top center" x="0" y="0" width="100%" height="35"/> <!--Specifies geometry-->
      <widget>
        <bar/> <!--This is the def we created earlier-->
      </widget>
    </window>

```

**Comment by Apppppppple** [comment]
Thanks, that works perfectly! Looks like somehow having `anchor="top left"` in my geometry element was what was breaking it, `anchor="top center"' works normally.

**Comment by elkowar** [comment]
So, can we close this, or is there still some issue?

**Comment by Apppppppple** [comment]
Yeah this can be closed sorry
