### ISSUE TITLE
[BUG] Eww doesn't load variables if no <variables> block is provided

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#165]
## Describe the bug
if the eww config does not contain a `<variables>` block, the config behaves weirdly. It does not load the variables correctly.

**Comment by Axarva** [comment]
...Isn't that fine though?

**Comment by elkowar** [comment]
ehh, `eww state --all` should still work. generally, this is of course rarely an issue, but it is weird behaviour that I should try to understand nonetheless

**Comment by elkowar** [comment]
Well, there's no variables block anymore,... fixed i guess 💯
