### ISSUE TITLE
Remove the box shadow when box has a transparent background.

### ISSUE THREAD

**Issue by 0xsapphir3** [elkowar/eww#170]
Adding a transparent background to a box works fine. However, I want to remove the box shadow. I used the syntax box-shadow: none; in the scss file but the box shadow was still visible.

**Comment by elkowar** [comment]
Share your configuration, please

**Comment by 0xsapphir3** [comment]
Sorry it was my fault. I misspelled "eww-greeting" in the picom shadow exclusions.
I am closing the issue.

Btw, great project :)
