### ISSUE TITLE
[BUG] Starting eww

### ISSUE THREAD

**Issue by WitherCubes** [elkowar/eww#172]
Today, I came across this project and I planned to try it out, but my widgets aren't starting and I don't know how to start eww.
I checked the troubleshooting page, but the link in the page is not working. 

(https://elkowar.github.io/eww/main/troubleshooting/starting-eww)

Please check and help me

**Comment by undefinedDarkness** [comment]
Im confused
First do `eww daemon`
Then `eww open WIDGETNAME`

**Comment by legendofmiracles** [comment]
window name* instead of widget name

But what happens when you run `cargo run --release -- logs &; cargo run --release -- deamon`?

Can you send the output of that here?

**Comment by 0xsapphir3** [comment]
Can You Provide Your Config?

**Comment by thyeun** [comment]
You can find your window name inside file `eww.xml`, once you have the window name.

then run it as `eww open <window name>`

**Comment by legendofmiracles** [comment]
Isn't there also the list-windows command, can't check right now.

**Comment by undefinedDarkness** [comment]
`eww windows`

**Comment by WitherCubes** [comment]
I think the problem is on my PC and I think it is not supporting it, no problem, but please fix your troubleshooting page. The link is above and it is showing as 404 not found.

**Comment by elkowar** [comment]
yes, fixed the page - link is no longer there :P
