### ISSUE TITLE
[BUG] Windows on sway are always sticky

### ISSUE THREAD

**Issue by eulertour** [elkowar/eww#182]
## Describe the bug
I haven't been able to find a way to make a window appear on only a single window.

## Reproducing the issue
[Using the bar example.](https://github.com/elkowar/eww/tree/master/examples/eww-bar)

## Expected behaviour
An option to tie a window to a given workspace.

**Comment by snakedye** [comment]
Layershell surfaces like eww are not windows (despite the name in the config) and therefore are not treated the same by compositors. It isn't a bug. It's just the way layershell is and how sway implements it. 

Personally, I don't think it's Eww's job to fiddle with the specificity of each Wayland compositor out there. This is something you could fix on your end using Sway's IPC.

**Comment by eulertour** [comment]
In case anyone else ends up running into this problem, I ended up writing this.

```sh
#!/bin/bash

while true; do
    # Listen to workspace events from sway.
    jq_output=$(swaymsg -t subscribe "['workspace']" | jq '.change,.current.name,.old.name')

    # Parse json into variables.
    tokens=($jq_output)
    change="${tokens[0]}"
    workspace="${tokens[1]}"
    previous_workspace="${tokens[2]}"

    if [ "$change" = "\"focus\"" ] || [ "$change" = "\"init\"" ]; then
        if [ "$workspace" = "\"1\"" ]; then
            eww open datetime
            eww open profile
        elif [ "$previous_workspace" = "\"1\"" ]; then
            eww close datetime
            eww close profile
        fi
    fi
done
```
