### ISSUE TITLE
[BUG] Eww daemon fails to start with default configuration file

### ISSUE THREAD

**Issue by anh0516** [elkowar/eww#183]
The Eww daemon fails to start with the default config file. I read the documentation and can't see what the issue is.

I followed the instructions to install rustup and cargo nightly. The compilation failed a few times until I installed some dependencies.
If possible, provide a simple example configuration that shows the issue.

I expected a window to pop up with the current date, as per the default XML file.

This was the error:

Failed to load eww config file /home/avraham/.config/eww/eww.xml
Caused by:
    0: Error parsing eww config file /home/avraham/.config/eww/eww.xml
    1: Error parsing window definition at /home/avraham/.config/eww/eww.xml:19:2
    2: 19:2 | Tag needed to be of type 'window', but was: <box >

<eww>
    <includes>
        
    </includes>

    <definitions>
        
    </definitions>

    <variables>
        
	<script-var name="date" interval="5s">
		date +%H%M
	</script-var>
    </variables>

    <windows>
        
	<box>
		{{date}}
	</box>
    </windows>
</eww>

Edit: I fixed the issue. I changed the box tag to window and specified a name attribute in the right place. I guess I need to learn how XML works.

**Comment by snakedye** [comment]
You have "window"s in the the "windows" block.
