### ISSUE TITLE
[BUG] Build fails with `failed to parse version requirement '' for 'gdk'`

### ISSUE THREAD

**Issue by OctoSlurp** [elkowar/eww#186]
## Describe the bug
After installing rust nightly (with rustup), running `cargo build --release` fails to parse these 3 lines
```
gdk = { version = "", features = ["v3_22"] }
gio = { version = "", features = ["v2_44"] }
glib = { version = "", features = ["v2_44"] }
```

## Reproducing the issue
1. Install rustup
2. `rustup default nightly`
3. `cargo build --release`

## Expected behaviour
I expected the program to compile

## Additional context
changing the version from `""` to `"*"` fixes the issue for me

**Comment by elkowar** [comment]
_should_ just work either way, but 🤷🏻‍♂️ doing * is definitely cleaner. fixed it!
