### ISSUE TITLE
Can't compile in Alpine Linux

### ISSUE THREAD

**Issue by rogerpanza** [elkowar/eww#188]
## Describe the bug
When running `cargo build --release` on Alpine Linux, at any part of the compilation it will error (has happened on different parts):
`error: linking with `cc` failed: exit status: 1`
`  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory`
`collect2: error: ld returned 1 exit status`

## Reproducing the issue
- Install Alpine Linux
- Install the `gcc` and `clang` packages to have the `cc` command
- Run `cargo build --release`

## Expected behaviour
`eww` compiles correctly, like on other distros

## Additional context
![Screenshot from 2021-06-04 18-15-02](https://user-images.githubusercontent.com/67978777/120867858-cbb37480-c560-11eb-830c-9ce84787ebc4.png)

**Comment by elkowar** [comment]
well, clearly, you're missing `crti.o`. How you get that on alpine I don't know - but that's more of a distribution thing than a eww issue.
