### ISSUE TITLE
When var has several lines of text it only displays the first, but it shows all of it, if you add a interval

### ISSUE THREAD

**Issue by alx365** [elkowar/eww#19]

**Comment by elkowar** [comment]
this is a result of script-vars being tail-based if you don't provide an interval. it will set the value once the command prints out a line, and then wait until the next line from the commad. 

What i could maybe add is a way for script-vars to be only ran once at the start, and then allow for refreshing them manually with a command.

**Comment by alx365** [comment]
Having a command that would refresh the contents would be very cool!
cause i'm making a epic games store frontend (pls no bully) and if you download a new game, it should be able to update

**Comment by elkowar** [comment]
i mean you can always `eww update your_variable your_new_value`

**Comment by elkowar** [comment]
for non-script vars

**Comment by alx365** [comment]
you know you can edit shit?

**Comment by elkowar** [comment]
i'm confused

**Comment by elkowar** [comment]
I'll close this in favour of #28 , as that seems to be the feature we're looking for here!
