### ISSUE TITLE
[BUG] "No package 'glib-2.0' found" no matter what during attemped installation

### ISSUE THREAD

**Issue by countchrisdo** [elkowar/eww#190]
## Describe the bug
"cargo build --release" during installation not working because :"No package 'glib-2.0' found" even though I've downloaded and updated the glib-2.0 package multiple times now. I've also tried reinstalling Rustup but I keep getting this same error.

## Additional context
Ubuntu 20.04

End of the error log in terminal after I run "cargo build --release" is here:
```

error: failed to run custom build command for `glib-sys v0.10.1`

Caused by:
  process didn't exit successfully: `/home/countchrisdo/eww/target/release/build/glib-sys-29f3f3be6c5598c0/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GLIB_2.0_STATIC
  cargo:rerun-if-env-changed=GLIB_2.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.44"` did not exit successfully: exit status: 1
  --- stderr
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found

warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by undefinedDarkness** [comment]
You need to install the glib 2.0 dev package or the one with C headers
Its `libglib2.0-dev` or something like that try finding it with `apt search`

**Comment by AndreiSva** [comment]
This is happening to me on void

**Comment by undefinedDarkness** [comment]
As I said you need the headers

**Comment by AndreiSva** [comment]
@undefinedDarkness I'm using musl libc, is eww only going to work on glibc systems then?

**Comment by undefinedDarkness** [comment]
I dont know but if other gtk apps work in that enviroment eww can too, you need to build it correctly and that involves installing the header files for your respective distrubion

**Comment by countchrisdo** [comment]
I'm guess I'm having trouble finding the specific headers, because I downloaded `libglib2.0-dev ` and I'm still getting the same issue. I'm confused about how do I go about that?

**Comment by undefinedDarkness** [comment]
![](https://cdn.discordapp.com/emojis/796430714228834314.png?v=1)
that should have worked so ummm no idea

**Comment by AndreiSva** [comment]
@countchrisdo what was the fix

**Comment by wine** [comment]
`sudo xbps-install pkg-config libglib-devel cairo-devel pango-devel atk-devel gdk-pixbuf-devel gtk+3-devel`
and then compile like usual :)
