### ISSUE TITLE
[BUG] eww doesn't wait until daemon is successfully launched

### ISSUE THREAD

**Issue by ahmedkhalf** [elkowar/eww#201]
## Describe the bug

I have this in my i3 config:

```
exec_always --no-startup-id eww daemon
exec_always --no-startup-id eww open bar_window
```

eww starts the daemon but doesn't start the window

## Expected behaviour
I expect `eww daemon` to wait until it makes sure that the daemon is launched and can be connected to by the next command `eww open bar_window`

**Comment by undefinedDarkness** [comment]
#142

**Comment by ahmedkhalf** [comment]
The proposal of continously running 'eww open window' until its starts is a hack that works for now. But I think it should be fixed from the root.

**Comment by undefinedDarkness** [comment]
Blame X or GTK not starting fast enough, idk

**Comment by snakedye** [comment]
Doubt it's gtk, the issue is probably in how eww is initialized

**Comment by undefinedDarkness** [comment]
Hmm maybe

**Comment by elkowar** [comment]
it's both, lol. I'll definitely need to fix this. for now, there is also `eww ping` as a simple workaround

**Comment by undefinedDarkness** [comment]
Lmao, Im always ready to blame gtk :)

**Comment by elkowar** [comment]
Since the config rework, this is now fixed!
Now, eww will automatically start a daemon when you try to open a window and no daemon is running. Additionally, it will attempt to connect to the daemon a couple times before, thus giving it enough time to start in case it didn't initialize fully yet.
