### ISSUE TITLE
[BUG] can't open config file

### ISSUE THREAD

**Issue by rqcoon** [elkowar/eww#202]
## Describe the bug
eww daemon doesn't start due to being unable to load the config xml file

## Reproducing the issue
I am unclear as to how this happened, so I'm not sure how repeatable this is and how pedantic I am being here creating a bug report.
I can provide a link to my eww xml here here: https://pastebin.com/aY1SPpyD

## Expected behaviour
Regular startup of the program.

## Additional context
output from eww logs after running eww daemon
I have tried eww -c ~/eww.xml daemon (with a copy of eww.xml in my home folder), but it only returns the exact same issue.
┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon    ┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛
    
 2021-07-09T09:03:42.266Z INFO  eww::server > Loading paths: config-dir: /home/worm/.config/eww, ipc-socket: /run/user/1000/eww-server_L2hvbWUvd29ybS8uY29uZmlnL2V3dw==, log-file: /home/worm/.cache/eww_L2hvbWUvd29ybS8uY29uZmlnL2V3dw==.log
 2021-07-09T09:03:42.267Z ERROR eww         > Failed to load eww config file /home/worm/.config/eww/eww.xml

Caused by:
    0: Error parsing eww config file /home/worm/.config/eww/eww.xml
    1: invalid digit found in string

any help would be appreciated as I am not all that well versed in xml or the inner workings of eww

**Comment by undefinedDarkness** [comment]
![1625827283](https://user-images.githubusercontent.com/38278035/125066210-40b72400-e0a2-11eb-8051-0de686a9b0e1.png)
might be that other than that looks okay to me

**Comment by rqcoon** [comment]
> ![1625827283](https://user-images.githubusercontent.com/38278035/125066210-40b72400-e0a2-11eb-8051-0de686a9b0e1.png)
> might be that other than that looks okay to me

ah yeah true, my bad
sorry for starting an issue thread here

**Comment by undefinedDarkness** [comment]
no worries
