### ISSUE TITLE
[BUG] Problem while starting eww

### ISSUE THREAD

**Issue by Jasylum** [elkowar/eww#203]
## Describe the bug
I just installed eww through the documentation and have reached the step where i have to start the daemon . For that I used `./eww daemon`  as instructed in the documentation.
The output are:
`2021-07-08T23:00:03.769Z INFO  eww > Initializing Eww server. (/run/user/1000/eww-server_L2hvbWUvamliZXNoLy5jb25maWcvZXd3)
Run `eww logs` to see any errors, warnings or information while editing your configuration.`
Then I tried to open it with `./eww open <window_name>` but it says to start the daemon process which i have already done. The output of the error:
` 2021-07-08T23:00:31.638Z INFO  eww > Trying to find server process at socket /run/user/1000/eww-server_L2hvbWUvamliZXNoLy5jb25maWcvZXd3
Failed to connect to the eww daemon.
Make sure to start the eww daemon process by running `eww daemon` first.` 

## Reproducing the issue
First `cd/eww/target/release`
Then `./eww daemon`
Finally `./eww open <window_name>`

![2021-07-09-053135_1920x1080_scrot](https://user-images.githubusercontent.com/52153618/125073845-4893ba00-e0dc-11eb-9c4c-48777eb0d2e7.png)

**Comment by VuiMuich** [comment]
Just to be clear:
You have also followed the steps in the [configuration instructions](https://elkowar.github.io/eww/configuration.html), right?
You need to have both `eww.xml` and `eww.scss` in `~/.config/eww/`:
```
$HOME
└──.config
   └─eww
     ├──eww.xml
     └──eww.scss
```
You can compy them from the `examples` folder in the git-repository.

**Comment by undefinedDarkness** [comment]
You should put eww in your system's $PATH I dunno if that affects this issue but try 
and run eww logs

**Comment by legendofmiracles** [comment]
As @undefinedDarkness darkness said, `eww logs` should give a log of what went wrong.

**Comment by Swexti** [comment]
yeah you get this when something breaks in your configs

**Comment by mitinarseny** [comment]
I have the same problem. I simply copied a bar example from repo to `~/.config/eww` and tried to start daemon, but then `eww open bar` says:
```sh
$ ./eww open bar
 2021-08-07T16:40:33.949Z INFO  eww > Trying to find server process at socket /run/user/1000/eww-server_L2hvbWUvbWl0aW5hcnNlbnkvLmNvbmZpZy9ld3c=
Failed to connect to the eww daemon.
Make sure to start the eww daemon process by running `eww daemon` first.
```
Then I even tried to remove everything from `~/.config/eww/eww.xml`:
```xml
<eww>
  <definitions>
    <!-- This is the place where you structure your widgets, align them and stuff. -->

    <def name="bar"> <!-- Starts the definition of a widget named main -->
      <box orientation="h" hexpand="true">
        <!-- <workspaces/> -->
        <!-- <music/> -->
        <!-- <sidestuff/> -->
      </box>
    </def>
  </definitions>

  <variables>
  </variables>

  <windows>
    <!-- These are the windows -->
    <window name="bar" screen="0" focusable="true" windowtype="dock">
      <geometry x="0%" y="0%" width="100%" height="4%"/> <!--Specifies geometry-->
      <reserve side="top" distance="4%" layer="top"/>
      <widget>
        <bar/> <!--This is the def we created earlier-->
      </widget>
    </window>
  </windows>
</eww>
```
And result is the same

**Comment by legendofmiracles** [comment]
Can you send the log output and try launching the daemon in debug mode for even-more output @mitinarseny?

**Comment by elkowar** [comment]
Given that there hasn't been any response from the OP here in a long while, I assume this issue has been resolved. 
If this is still an issue, please feel free to reopen or create a new issue

**Comment by mitinarseny** [comment]
Nope, the issue has not been magically resolved... Even with new YUCK configuration language.
```sh
$ ./eww --debug --logs --restart daemon
 2021-08-31T19:46:49.858Z INFO  eww > Initializing Eww server. (/run/user/1000/eww-server_L2hvbWUvbWl0aW5hcnNlbnkvLmNvbmZpZy9ld3c=)
 2021-08-31T19:46:49.858Z INFO  eww::server > Loading paths: config-dir: /home/mitinarseny/.config/eww, ipc-socket: /run/user/1000/eww-server_L2hvbWUvbWl0aW5hcnNlbnkvLmNvbmZpZy9ld3c=, log-file: /home/mitinarseny/.cache/eww_L2hvbWUvbWl0aW5hcnNlbnkvLmNvbmZpZy9ld3c=.log

┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛


┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛


┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛
```
And then I then:
```sh
./eww open example
 2021-08-31T19:46:54.654Z WARN  eww > Failed to connect to daemon: Failed to connect to daemon
 2021-08-31T19:46:54.654Z INFO  eww > Initializing eww server. (/run/user/1000/eww-server_L2hvbWUvbWl0aW5hcnNlbnkvLmNvbmZpZy9ld3c=)
Run `./eww logs` to see any errors while editing your configuration.
 2021-08-31T19:46:54.654Z INFO  eww::server > Loading paths: config-dir: /home/mitinarseny/.config/eww, ipc-socket: /run/user/1000/eww-server_L2hvbWUvbWl0aW5hcnNlbnkvLmNvbmZpZy9ld3c=, log-file: /home/mitinarseny/.cache/eww_L2hvbWUvbWl0aW5hcnNlbnkvLmNvbmZpZy9ld3c=.log
```

With following contents of `${XDG_CONFIG_DIR}/eww/eww.yuck`:
```yuck
(defwindow example
           :monitor 0
           :geometry (geometry :x "0%"
                               :y "20px"
                               :width "90%"
                               :height "30px"
                               :anchor "top center")
           :stacking "fg"
           :reserve (struts :distance "40px" :side "top")
           :windowtype "dock"
           :wm-ignore false
  "example content")
```
