### ISSUE TITLE
[FEATURE] Keeping widgets on a certain workspace in sway.

### ISSUE THREAD

**Issue by ErikBolumburu** [elkowar/eww#207]
I hope this is already a feature but it would be ncie to be able to keep all my widgets on workspace one without them following me and overlapping my browser.

**Comment by VuiMuich** [comment]
Is this #176 also related to wayland, or is this only relevant in X?

**Comment by elkowar** [comment]
that's only a X thing.
@snakedye could you take a look at this?

**Comment by snakedye** [comment]
You could write a script for sway that would hide or show your widget depending on the workspace

**Comment by legendofmiracles** [comment]
Can't this be done by setting focusable to true?

**Comment by elkowar** [comment]
Sadly, wayland does not have a standard notion of a "workspace". Thus, the wayland protocol (and the layershell extension protocol) does not allow for a window to request a "sticky" or "non-sticky" state the same way an application can on X. Thus, as a result of how wayland works, this _has_ to be implemented on the compositor side, so you'll need to follow snakedyes advice and write a script for that.
