### ISSUE TITLE
[BUG] compile errors

### ISSUE THREAD

**Issue by Euro20179** [elkowar/eww#213]
## Describe the bug
When running `cargo build --release` it says `error #![feature] may not be used on the stable release channel`.

## Reproducing the issue
run `cargo build --release` on the latest commit on master branch

## Additional context
I also tried running `cargo build` which gave the same error.
I'm not a rust programmer so this is probably a horrible idea, but I also tried removing the lines of code that gave the error, but it just gave tons more errors.

### Screenshot
![image](https://user-images.githubusercontent.com/56898436/125506314-781475a5-c97d-4e00-bb43-9f641ac3d2d6.png)

**Comment by TheRealKizu** [comment]
Use the nightly version of Rust

**Comment by undefinedDarkness** [comment]
Read the bloody docs
