### ISSUE TITLE
[BUG] Black background around rounded corners.

### ISSUE THREAD

**Issue by nipunravisara** [elkowar/eww#215]
I'm having rounded corners in my widgets but there's a black background under the widget which ruins border radius. Here's a [screenshot](https://im.ge/i/2rCN6).

I'm using [adi1090x's](https://github.com/adi1090x/widgets) configs. Just followed the instructs [here](https://github.com/adi1090x/widgets#create-a-replica).

**Comment by nipunravisara** [comment]
To fix the issue I had to install [picom](https://aur.archlinux.org/packages/picom-git/).

**Comment by max-ishere** [comment]
TIL that for the entire window to have rounded corners you need to have

eww.scss
```css
window {
    border-radius: 10px;
}
```

Just adding this in so that someone later doesnt have to guess.
