### ISSUE TITLE
[BUG] eww not initalizing when installing as normal

### ISSUE THREAD

**Issue by NXBuilder** [elkowar/eww#220]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
eww failing to initialize when booting up for the first time and outputs error:

```
 2021-07-22T20:28:37.994Z ERROR eww > Failed to initialize eww paths

Caused by:
    Configuration directory /home/abi/.config/eww does not exist
```

## Reproducing the issue
Install as normal from https://elkowar.github.io/eww/eww.html
cd into target/release
run `chmod +x ./eww`
run `./eww daemon`

## Expected behaviour
Eww should start as normal and not give an error.

**Comment by undefinedDarkness** [comment]
just read the error message...?

**Comment by VuiMuich** [comment]
Is the issue here that you have config files in `/home/abi/.config/eww` but eww cannot load see them for some reason?

IMO this is quite the prime example for a 'common user error', btw. 

If you think the necessity of placing a configuration in `$HOME/.config/eww/` isn't documented well enough please change the title of this issue.

**Comment by NXBuilder** [comment]
Yes that is the issue, I have the .xml and .scss files in the correct folder but eww can't load them for some reason. I should have clarified that in my original post.

**Comment by VuiMuich** [comment]
Have you tried `eww logs`?

**Comment by NXBuilder** [comment]
Yes I have tried that but it gives me the error `Command 'eww' not found`

**Comment by undefinedDarkness** [comment]
put the eww binary in your $PATH

**Comment by VuiMuich** [comment]
> put the eww binary in your $PATH

I actually prefer to put a symlink in `/usr/bin` so I can quickly switch between release and debug builds

**Comment by legendofmiracles** [comment]
> Yes that is the issue, I have the .xml and .scss files in the correct folder
What are the permissions on those files?
Are they owned by your user? Can you double-check that they really exists?

Furthermore, can you try to launch eww in debug mode, and then send the log output here?
```
./eww daemon --debug
./eww logs
```

**Comment by elkowar** [comment]
Given that there hasn't been any response to this in a long while, I'll assume this has been resolved. If this issue still exists, and you think represents a bug in eww, feel free to re-open the issue!
