### ISSUE TITLE
[BUG] timeout too low for eg https://github.com/Axarva/dotfiles-2.0 powermenu.sh

### ISSUE THREAD

**Issue by redgloboli** [elkowar/eww#224]
on Axarva's github is this issue https://github.com/Axarva/dotfiles-2.0/issues/83 that the powermenu.sh isn't working.

it can be resolved with this workaround https://github.com/Axarva/dotfiles-2.0/issues/83#issuecomment-886145342

It seems the timeout set here https://github.com/elkowar/eww/blob/4f59424e0e82eb7ce76badb266974dd3e7ea6d8c/src/widgets/mod.rs#L29 is too low to even enter 'y'.

**Comment by elkowar** [comment]
ohh, I never considered that usecase 😄 I think the reasonable solution would be adding a `timeout` option on anything that can take a script, no? Something along those lines at least

**Comment by Axarva** [comment]
I was going to report this but kept forgetting... well, at least it's been reported :)

**Comment by elkowar** [comment]
This is fixed since the config rework! there is now a timeout property everywhere where a command can be set, such that the timeout can now be specified depending on what's happening
