### ISSUE TITLE
[FEATURE] A circle progress bar

### ISSUE THREAD

**Issue by SkyLissh** [elkowar/eww#233]
## Description of the requested feature
I try make it by myself, just with css and xml, but no luck. While looking if someone tried the same, I found a repo of the implementation with GTK in vala.

## Proposed configuration syntax
May use
```xml
 <progress circle="true" />
```

# Additional context
![image](https://user-images.githubusercontent.com/72633267/129667503-7355095c-f504-4077-9838-95d67a68e27e.png)
Repo of [phastmike](https://github.com/phastmike/vala-circular-progress-bar)

**Comment by undefinedDarkness** [comment]
Oooo, that is a nice example

**Comment by druskus20** [comment]
working on this woo

**Comment by legendofmiracles** [comment]
Will be closed by #328 (read: elkowar please link lol)

**Comment by elkowar** [comment]
Was indeed implemented by #328!
