### ISSUE TITLE
Build fails at Panga

### ISSUE THREAD

**Issue by Kaktoose** [elkowar/eww#236]
I have been trying to install but I get this error every time.

error: failed to run custom build command for `pango-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/home/jack/eww/target/release/build/pango-sys-566b72be2607a247/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=PANGO_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PANGO_STATIC
  cargo:rerun-if-env-changed=PANGO_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "pango" "pango >= 1.36"` did not exit successfully: exit status: 1
  --- stderr
  Package pango was not found in the pkg-config search path.
  Perhaps you should add the directory containing `pango.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'pango' found
  Package pango was not found in the pkg-config search path.
  Perhaps you should add the directory containing `pango.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'pango' found

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by elkowar** [comment]
Well, have you
- [ ] read the error message
- [ ] checked prior issues similar to this
?

If you do either, you'll realize that you're missing a system-level dependency, that you first need to install so eww can compile

**Comment by Kaktoose** [comment]
I'm not very good with Rust sorry. its Pango I have to install with cargo?

**Comment by elkowar** [comment]
no, with your system package manager
