### ISSUE TITLE
[BUG] cant make window on background? its always on top

### ISSUE THREAD

**Issue by xeome** [elkowar/eww#238]
## Describe the bug
tried :stacking bg and fg, tried :wm-ignore true and false, all the combinations i can think of, window is still on top

## Reproducing the issue
make any window and try to make it so its not on top

## Expected behaviour
window staying in background, not on top of other windows

**Comment by elkowar** [comment]
stacking being problematic is/has been already discussed in several other issues (#178 #198  #191), closing as duplicate ^^
