### ISSUE TITLE
[FEATURE] Use caching with nix-flakes

### ISSUE THREAD

**Issue by shaunsingh** [elkowar/eww#240]
## Description of the requested feature
I was wondering if you could set up cachix for nix? (via eww.cachix.org). I use eww + nixos, by putting it as an input in my `flake.nix` file which allows me to use the latest eww as a regular nixos package. However, since it doesn't have a cache, it takes forever to build and install on my slow laptop.

# Additional context
If you would like an example of another rust tool that uses flakes and provides cache, you can reference https://github.com/emacs-ng/emacs-ng

**Comment by elkowar** [comment]
While I do like nix, I don't use it myself, at least for this. Maintaining such build utilities on platforms that I barely ever touch is sadly not sustainable for me, as It'd imply constant overhead of making sure that these things _still_ work after any changes, which would require me to actually have a setup that can make use of them. I'd be more than happy if someone wants to community-maintain such a cache, if possible ^^
