### ISSUE TITLE
[FEATURE] Scrollable version of box?

### ISSUE THREAD

**Issue by Animeshz** [elkowar/eww#247]
## Description of the requested feature
For quick navigation of dynamic content like `dynamic workspaces`, music player's `song name`, etc. we can use the scroll wheel to swipe horizontally left / right, or vertically top / bottom. For music player, probably #101 be more appropriate, but for large growing and shrinking workspaces (& other things which should be interacted when coming towards it) I guess this is better option is to have manual on-time scrolling feature.

## Proposed configuration syntax
```yuck
(scrollbox :orientation "h" :maxwidth "150px" :scrollspeed "24px"
  (thing1)
  (thing2)
  ...)
```

# Additional context
🤔🤔 I'm not so sure

**Comment by elkowar** [comment]
If I'm not mistaken, this could be implemented as a wrapper widget using https://docs.gtk.org/gtk3/class.Viewport.html
