### ISSUE TITLE
[FEATURE] Going away animation for revealer?

### ISSUE THREAD

**Issue by Animeshz** [elkowar/eww#249]
## Description of the requested feature
Incoming of the widget from revealer is very smooth, but when it goes away instantly the nearby widgets reposition themselves that is not very smooth. Can it possibly have a going away animation (expected to be opposite of how it came)?

https://user-images.githubusercontent.com/26714676/131457692-c7fc364f-5a82-43d0-af0e-f28cddec4b2d.mp4

## Proposed configuration syntax
\-

# Additional context
`¯\_(ツ)_/¯`

**Comment by VuiMuich** [comment]
I have a revealer for my power menu and it animates in and out.
Would you share a snippet of your revealer config, please?

I have this `(revealer :transition "slideright" :reveal pwmen-open (pwmen))))
` and `(defvar pwmen-open false)` which I update with `(button :onclick "eww update pwmen-open=${!pwmen-open}" "⏻")`

**Comment by Animeshz** [comment]
@VuiMuich Ah, sorry. I was actually checking the variable containing string being not equal to `""`  as condition for open/close. While also displaying that variable on the screen. I guess the time it was going to slide back, it became of length 0 so it refreshed out 😅😅.
