### ISSUE TITLE
Make eww kind of quitable, by e.g. hitting the escape key

### ISSUE THREAD

**Issue by alx365** [elkowar/eww#25]
Right now, unless you have a button to quit eww, you can't quit it, except when signalling the terminal to stop, which doesn't work if you opened the widget through a keybind. 

Maybe add some button with which you can kill eww...

**Comment by elkowar** [comment]
you can add a button yourself ;D just create a button that run's `eww close <window-name>` when clicked, and place it wherever you want. 

if you want to fully kill eww (as in, stop the daemon process, if you start eww daemonized), you can run `eww kill`.
