### ISSUE TITLE
[BUG] Event based actions doesn't work on most widgets

### ISSUE THREAD

**Issue by Animeshz** [elkowar/eww#251]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
Most of listening properties don't work, like `:onhover`, `:cursor`, etc. due to wrong implementation (listening to wrong events).

Listen to leave notify event without leave event mask ([EventMask::LEAVE_NOTIFY_MASK](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.EventMask.html#associatedconstant.LEAVE_NOTIFY_MASK)).
https://github.com/elkowar/eww/blob/70285e0ebf928df4d78725dfb02d9eae2273630c/crates/eww/src/widgets/widget_definitions.rs#L157

Listen to button press event without masking to button press event ([EventMask::BUTTON_PRESS_EVENT](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.EventMask.html#associatedconstant.BUTTON_PRESS_MASK)). Although this one works somehow 🤔
https://github.com/elkowar/eww/blob/70285e0ebf928df4d78725dfb02d9eae2273630c/crates/eww/src/widgets/widget_definitions.rs#L447-L449

Listen to value change event without masking property change mask ([EventMask::PROPERTY_CHANGE_MASK](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.EventMask.html#associatedconstant.PROPERTY_CHANGE_MASK))
https://github.com/elkowar/eww/blob/70285e0ebf928df4d78725dfb02d9eae2273630c/crates/eww/src/widgets/widget_definitions.rs#L205-L207

## Reproducing the issue

```
(box :class "cyan" :cursor "text" :onhover "kitty" "some text to make box visible")
```
Try hovering, neither cursor changes, nor command runs.

## Expected behaviour
Self explainatory, should do what is expected.

## Additional context

https://user-images.githubusercontent.com/26714676/131550687-6b8d3828-2d92-4212-ab06-1d2385ad136e.mp4

**Comment by legendofmiracles** [comment]
I can reproduce what you're facing here.
`onhover` seems to work fine for buttons, which is where most people would probably want an such an event; maybe you can use that as a *temporary* workaround?

**Comment by Animeshz** [comment]
@legendofmiracles I'd like to debug & contribute if possible. But I don't think these events are any useful in buttons 🤔🤔, they already have click events available.

**Comment by Animeshz** [comment]
So while its true there are some bugs due to the copy-pastes (incorrect masks), but actually even after fixing the masks the events still aren't received in most widgets.

The GTK docs shows that some widgets don't receive events [GTK 3.0 list](https://developer-old.gnome.org/gtkmm-tutorial/3.0/chapter-widgets-without-xwindows.html.en) for the sake of performance concerns and as we move further down the road [GTK 3.24 list](https://developer-old.gnome.org/gtkmm-tutorial/3.24/chapter-widgets-without-xwindows.html.en), the list becomes smaller, that is more and more widgets are allowed to receive events... And the solution is to wrap around the window within a widget called [`EventBox`](https://developer-old.gnome.org/gtkmm-tutorial/3.24/sec-eventbox.html.en) if we have configured (yuck) to be handling those events.

<sup>Also note that button is marked to be not receiving events in 3.24 docs, but does receive hover/mouse-in events as you confirmed for you and as well as me. (I'm using gtk version 3.24.29 checked via `pkg-config --modversion gtk+-3.0`) (might/might not receive other events as I didn't confirmed but seems like it alteast receives hover events which is only thing we need for our purpose for now)</sup>

Possible implementation may have a problem, that is we have to find if we want to wrap the gtk widget into event box or not for the specific version. If we just take list of 3.0 as a reference, all the widgets should be happy, but it might be redundant for many widgets in newer versions... @legendofmiracles @elkowar any thoughts on this how should we properly implement this? I'm happy to help on this :)

**Comment by Animeshz** [comment]
Another potential solution would be to revoke actions such as `:cursor`, `:onhover` altogether from all of the widgets, and provide a simple and separate `(eventbox ...)` widget just like `(box ...)` which is manually wrapped by the user if he wants to receive the events.

This is far more easy to implement internally as well as easier to debug from the end user.
