### ISSUE TITLE
[FEATURE] label should be able to indicate when it is truncated

### ISSUE THREAD

**Issue by ThreeFx** [elkowar/eww#257]
## Description of the requested feature

Truncated labels (using `:limit-width`) are currently cut. I want to be able to see when the label has been truncated.

## Proposed configuration syntax

Add a `:limited-indicator` (or similar) attribute, which allows the user to pass a custom string which gets appended if the string was limited.

If this makes sense then I can look into implementing this.

Cheers!

**Comment by Animeshz** [comment]
`limit-width: int maximum count of characters to display`

I guess its the "length" of character to be max and not the width in px. So you should already know if `len(text) > limit-width` you are on right track. Maybe use Eww-expressions to evaluate what you trying to do...

**Comment by undefinedDarkness** [comment]
Seems a pretty niche usecase :/
depending on where you get the value from - you could simple script it from there

**Comment by ThreeFx** [comment]
For n sources and one label component, it would make more sense to add it in the label component IMO.

It makes it clear whether truncation occured when the cut looks natural, e.g. `BBC News -- Dog eats cat` when the actual title is `BBC News -- Dog eats cat-shaped object` the latter could be renderd as `BBC News -- Dog eats cat...` (truncate + append string) or `BBC News -- Dog eats...` (string is truncated earlier so that the total length is still `:limit-width`).

**Comment by Animeshz** [comment]
Again you can pass this through a shell script 😶

Eww is anyway a declarative language and not imperative, where you be doing if/else or truncation?

**Comment by VuiMuich** [comment]
The only use case where it would make sense to have truncation inside eww would be if the the text would be able to crawl to show the full text.

**Comment by snakedye** [comment]
I think this is pretty valid and not a niche use case. If there's a wrap despite it being scriptable than making it explicit that the text is overflowing would be a nice default behavior. Internally it's much easier to just check the length than calling a shell script each time the string changes.

**Comment by undefinedDarkness** [comment]
For wrapping then ye, its eww's problem - just truncating text eh

**Comment by VuiMuich** [comment]
> For wrapping then ye, its eww's problem - just truncating text eh

 So introduce a `:wrap Bool` then?  Also use `:limit-length` instead of `:limit-width` as there is also a `.width <px,%>` to avoid confusion.

**Comment by snakedye** [comment]
The change in eww is so minimal compared to the latency introduced by running a shell script on each change. I assume that's the main reason why eww expressions exist in the first place.

**Comment by Animeshz** [comment]
@snakedye Not exactly, I'm expecting the text comes from a shell script or shell-invokable binary, if it is, its so simple to check and perform actions over it with pipes, not just truncation and size determination but also some specific search for what to truncate and what to choose as title with, for example `awk`. I don't think it makes huge latency since it already comes from shell command and standard streams.

**Comment by Animeshz** [comment]
Also,

[Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Mike_Gancarz:_The_UNIX_Philosophy) suggests:
> 1. Small is beautiful.
> 2. Make each program do one thing well.
> 4. Choose portability over efficiency.
> 7. Use shell scripts to increase leverage and portability.
> 8. Avoid captive user interfaces.
> 9. Make every program a filter (a filter is a program that gets most of its data from its standard input and writes its main results to its standard output).

Also [`"Worse is better"`](https://en.wikipedia.org/wiki/Unix_philosophy#%22Worse_is_better%22) as long as you are not simplifying by adding more complexity.

**Comment by snakedye** [comment]
Assuming the var is formatted directly like the string you want yes but if it's JSON which is to be expected, it's more complicated, you'll have to write a script and use multiple binaries and probably run multiple times the same binary/scripts because you need the other fields in that json.

**Comment by Animeshz** [comment]
But like how does this help in parsing json 🤔🤔 (just curious 👀)

**Comment by snakedye** [comment]
You can just use eww's json interpreter which doesn't alter your variable.
