### ISSUE TITLE
[BUG] Widget opens as a normal windows in DWM

### ISSUE THREAD

**Issue by Rashad-707** [elkowar/eww#266]
## Describe the bug
when i open the bar example widget, it opened alongside other windows in tiling mode not as a bar.

## Reproducing the issue
 when i set wm-ignore true or false, nothing changed.

## Expected behaviour
I expected it to open as a bar in the top in all tags (like polybar do), but it opens as a normal windows only in the tag I have opened it on.

## Additional context
when I view ./eww logs I get
`** (eww:5726): CRITICAL **: 12:20:05.991: gtk_wayland_init_if_needed: assertion 'GDK_IS_WAYLAND_DISPLAY (gdk_display)' failed

** (eww:5726): CRITICAL **: 12:20:05.991: layer_surface_new: assertion 'gtk_wayland_get_layer_shell_global ()' failed

** (eww:5726): WARNING **: 12:20:05.991: Falling back to XDG shell instead of Layer Shell (surface should appear but layer features will not work)

** (eww:5726): CRITICAL **: 12:20:05.991: xdg_toplevel_surface_new: assertion 'gtk_wayland_get_xdg_wm_base_global ()' failed

** (eww:5726): WARNING **: 12:20:05.991: Shell does not support XDG shell stable. Falling back to default GTK behavior

** (eww:5726): CRITICAL **: 12:20:05.991: GtkWindow is not a layer surface. Make sure you called gtk_layer_init_for_window ()

error: **Failed to turn `{"total_mem": 16704909, "free_mem": 11225690, "total_swap": 4294963, "free_swap": 4294963, "available_mem": 13003718, "used_mem": 3701191, "used_mem_perc": 22.156307}` into a value of type f64**
   ┌─ /home/rashad/.config/eww/eww.yuck:13:20
   │
13 │             :value EWW_RAM
   │                    ─────── `{"total_mem": 16704909, "free_mem": 11225690, "total_swap": 4294963, "free_swap": 4294963, "available_mem": 13003718, "used_mem": 3701191, "used_mem_perc": 22.156307}` is not of type `f64`
   │
   → invalid float literal
`

**Comment by VuiMuich** [comment]
Are you using DWM with wayland? This looks a bit odd to me, but not sure if related.

But on you Error regarding `EWW_RAM` you might want to use e.g. `EWW_RAM.free_mem` to access the individual values.

**Comment by Rashad-707** [comment]
No I'm using it with X11.
I tried your suggestion and I get, `No variable named `EWW_RAM.free_meme` in scope`

**Comment by VuiMuich** [comment]
I just tried this widget and it works fine for me:
```lisp
        (metric :label ""
                :label-class "icon"
                :value '${EWW_RAM.used_mem_perc}'
                :onchange "")
```

**Comment by Rashad-707** [comment]
I tired an empty widget just to see how it work on DWM and, its the same I get 
```
 layer_surface_new: assertion 'gtk_wayland_get_layer_shell_global ()' failed
layer_surface_new: assertion 'gtk_wayland_get_layer_shell_global ()' failed
Falling back to XDG shell instead of Layer Shell (surface should appear but layer features will not work)
xdg_toplevel_surface_new: assertion 'gtk_wayland_get_xdg_wm_base_global ()' failed
```
 and it also opens in the tiling mode.

**Comment by VuiMuich** [comment]
Tbh I'm not too familiar with DWM, but thos errors 'get_wayland_...' are a bit sus IMO.

Could you use xprop on the tiled eww window?
Is you `defwindow` explicitly setting `:windowtype "dock"`?

**Comment by Rashad-707** [comment]
this is xprop
```
_NET_WM_USER_TIME(CARDINAL) = 8069098
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x5400001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 88080389, 88080390
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x5400004
WM_CLIENT_LEADER(WINDOW): window id # 0x5400001
_NET_WM_PID(CARDINAL) = 54743
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "RaShaD"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 1920 by 500
		program specified base size: 0 by 0
		window gravity: Center
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "eww", "Eww"
WM_ICON_NAME(STRING) = "Eww - widgetbox"
_NET_WM_ICON_NAME(UTF8_STRING) = "Eww - widgetbox"
WM_NAME(STRING) = "Eww - widgetbox"
_NET_WM_NAME(UTF8_STRING) = "Eww - widgetbox"
```

and this is eww.yuck
```
(defwidget widgetbox []
    (box :orientation "v"))

(defwindow widgetbox
   :monitor 0
           :geometry (geometry :x "0px"
                               :y "0px"
                               :width "50%"
                               :height "500px"
                               :anchor "center")
            :stacking "fg"
            :reserve (struts :distance "40px" :side "top")
            :windowtype "dock"
            :wm-ignore false
  (widgetbox))
```

**Comment by VuiMuich** [comment]
Hmm, so to me this looks like dwm is ignoring `_NET_WM_WINDOW_TYPE` sent by `eww`

xprops of one of my windows (I use three as a kind of 'floating bar') is this:
```
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0xa00001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 55, 0, 0, 0, 0, 0, 0, 2559, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 55, 0
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 10486939, 10486940
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0xa0049a
WM_CLIENT_LEADER(WINDOW): window id # 0xa00001
_NET_WM_PID(CARDINAL) = 1085
WM_LOCALE_NAME(STRING) = "de_DE.utf8"
WM_CLIENT_MACHINE(STRING) = "manjobook"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 498 by 44
		program specified base size: 0 by 0
		window gravity: Center
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "eww-tags", "eww-tags"
WM_ICON_NAME(STRING) = "Eww - tags"
_NET_WM_ICON_NAME(UTF8_STRING) = "Eww - tags"
WM_NAME(STRING) = "Eww - tags"
_NET_WM_NAME(UTF8_STRING) = "Eww - tags"
```

**Comment by Rashad-707** [comment]
That's right it's ignoring eww config, I tried xprop on polybar and I get `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK`

**Comment by Rashad-707** [comment]
I've just reinstalled it now and it works now as a widget, I don't now why but it works fine now, maybe something went wrong with the build the first time.

**Comment by VuiMuich** [comment]
Yeah I got this a couple of times, around the time, when I tested yuck on the feature branch and switched to master when it got merged. `cargo clean` helped a lot to get rid of some awkward behaviour..
