### ISSUE TITLE
Add script-var that is only executed once

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#28]
A script-var that is only executed once, such as to display static content, should be added.

**Acceptance criteria**
- `<script-var>` supports `interval="never"` (or something better, if there are any proposals), which will only run the script once.
- said script-vars are not included in the `script-var-handler` schedulers at all.

**Comment by elkowar** [comment]
It's really unclear how this would work. Would it execute once after daemon startup? How does that interact with the lazyness features? Would it execute once as soon as it is being used?

Will close this for now, as I haven't seen/heard anyone ask for this in a long while, and as the implementation is really unclear. If anyone still has a valid usecase, I'd be fine with reopening this.

**Comment by isaacbrown92** [comment]
Hey there. I would actually really love this. I manage all my systems through a shared NixOS configuration with Colmena. So the same EWW setup is used on my laptop and desktop. I only want my battery to be visible when the hostname is "laptop". I've achieved this with polling, but it feels sorta weird to have the script needlessly run multiple times. Ideally it would just run once at startup. 

(Also thank you for making this amazing tool, love it.)

**Comment by SkyLeite** [comment]
I would also like this. The ability to set the value of a variable from a script when the window is opened, without having to needlessly poll it, would be great.
