### ISSUE TITLE
[BUG]  Cannot use Image Widget

### ISSUE THREAD

**Issue by ParanoidNemo** [elkowar/eww#285]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
When defining an image widget no image is generated inside the widget itself

## Reproducing the issue
Add an image widget using

```
(defwidget sidebar_toggle []
    (box :class "sidebar_toggle"
         :orientation "h"
    (button :class "sidebar_button"
            :onclick "~/.config/eww/scripts/sidebar-toggle"
            (image :path "~/.config/eww/icons/fingerprint.svg")))
)
```
also not nesting the image in the button definition but use it instead of the button doesn't generate any image inside the widget.
Already tried with full path instead of ~ and with $HOME var (that as far as I know shouldn't work but I've tried anyway)

The image I'm using for this is taken from [here](https://fonts.google.com/icons?selected=Material+Icons), tried with svg and png also (changing the extension in path the image widget)

## Expected behaviour
An image get shown in the widget

## Additional context
No SCSS style is applied yet, only a background for the box widget. Tried changing color in CSS or set width/height in image widget but nothing change.

**Comment by elkowar** [comment]
Does it work with non-svg images? not sure if SVG support in GtkImage is all that great / existant

**Comment by ParanoidNemo** [comment]
Tried with .png and it doesn't work either. Should I try with jpg? but that doesn't support transparency.

**Comment by iSparsh** [comment]
@elkowar Here are my logs while replicating the issue. The file exists. 

![Screenshot_2021-11-06-02-23-33_1920x1080](https://user-images.githubusercontent.com/57213270/140603985-a81075b1-a192-405a-ae99-da3694f49220.png)

This happens when I try to use a PNG:
![Screenshot_2021-11-06-02-27-20_1920x1080](https://user-images.githubusercontent.com/57213270/140604080-12d6155d-b111-4903-8ec2-2d592e7cb6bc.png)
 
Here are the directory permissions:
![Screenshot_2021-11-06-02-27-52_1920x1080](https://user-images.githubusercontent.com/57213270/140604087-db91e551-02a9-49c8-8772-bfd46f2ea75f.png)

**Comment by elkowar** [comment]
Hmm, it seems that gtk doesn't handle `~` at all - if you type out the full path I'd assume it works. That's obviously not great. Paths relative to the eww config directory _do_ seem to work, however.

**Comment by iSparsh** [comment]
@elkowar when I do try to use the full path, eww infact crashes my WM. It logs me out of the session.. I can't seem to screen record it as well (it corrupts the save file) Here are some things I did manage to get after the crash though.
As you can see, nothing suspicious in the logs.. but the widget window with the image has disappeared. This doesn't get fixed after a hot reload or a cold one, rather proceeds to crash the system again. No success with eww relative paths as well. im on `0.2.0`

![Screenshot_2021-11-06-09-44-05_1920x1080](https://user-images.githubusercontent.com/57213270/140616509-0b652b99-a2db-440b-bf05-c2a91368fe98.png)
![Screenshot_2021-11-06-09-45-13_1920x1080](https://user-images.githubusercontent.com/57213270/140616511-7ec72607-12b9-4aa8-a191-10c3f94fb15a.png)

**Comment by iSparsh** [comment]
Okay so I got the reason why the system crashed (thanks @elkowar ) this was a problem with my system only.. as it ran out of memory. Nothing to worry about. 
So @ParanoidNemo, to get the image working, you have to explicitly set the height and width in the widget. This is what made it work
```(image :path "path/to/file.svg" :width <int> :height <int>)```

This bug is fixed in the State rework (pr 335) and will be solved when merged. For now, the above solution works.

**Comment by ParanoidNemo** [comment]
Only one last question, when the State rework will be merged also ~ will work (or eww relative path handling) or only the fact that right now is necessary to explicitly set width and height?
Thanks for the solution

**Comment by VuiMuich** [comment]
> Only one last question, when the State rework will be merged also ~ will work (or eww relative path handling) or only the fact that right now is necessary to explicitly set width and height?
> 
> Thanks for the solution
> 
> 
> 
> EDIT: still doesn't works if I put an image inside a button, no error shown in logs tho. The button actually works, but no image is shown.

I am not sure if this is entirely true for eww, but Rust has poor support for home-directories by the standard library in general. There once was some, but it was dropped as it was not fully platform agnostic.

**Comment by iSparsh** [comment]
> Only one last question, when the State rework will be merged also ~ will work (or eww relative path handling) or only the fact that right now is necessary to explicitly set width and height? Thanks for the solution
> 
> EDIT: still doesn't works if I put an image inside a button, no error shown in logs tho. The button actually works, but no image is shown.

I can't replicate this issue. All types of paths work, and the image is displayed no matter the res or format. Maybe try using a different path/ changing the image? There may also be a conflict within your css/window properties.
This is a workaround solution until the state-rework is done. It will solve everything.

**Comment by elkowar** [comment]
Should be fixed now!

**Comment by traeanto** [comment]
image widget need full path
`eww 0.4.0 d58d91de78d2b9984a1bbb8314be197bc0e283dc`

if using the home variable an error will occur
![image](https://user-images.githubusercontent.com/126303616/231372181-369ec1ca-c38c-4e55-9eef-eaf20dc7709c.png)

**Comment by viandoxdev** [comment]
> image widget need full path `eww 0.4.0 d58d91de78d2b9984a1bbb8314be197bc0e283dc`
> 
> if using the home variable an error will occur ![image](https://user-images.githubusercontent.com/126303616/231372181-369ec1ca-c38c-4e55-9eef-eaf20dc7709c.png)

Eww isn't a shell, it doesn't replace $HOME with your home, you should use either `~` or use a yuck variable for home.

**Comment by traeanto** [comment]
> 

same result, image doesnt appear. 
![image](https://user-images.githubusercontent.com/126303616/231628701-76a64d28-c94d-45da-98cc-5230b7de99f2.png)


`(defpoll profile-face :interval "5m" "echo $HOME/.face")` work for me, but still need to be fixed.
