### ISSUE TITLE
[BUG] Gtk doc links in the docs should be updated

### ISSUE THREAD

**Issue by Nooo37** [elkowar/eww#286]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
Gnome developer documentation has been updated a couple months ago and broke every link in existence. Old links usually just get thrown on the startside of the new docs. I think that is including the links in the eww docs.

## Reproducing the issue
Open https://elkowar.github.io/eww/working_with_gtk.html and try the first two links.

## Expected behaviour
The links should redirect to helpful resources.

## Additional context
You can quick-fix it by changing the first `developer` to `developer-old` (ie https://developer.gnome.org/gtk3/stable/chap-css-overview.html becomes https://developer-old.gnome.org/gtk3/stable/chap-css-overview.html). Maybe you can refind the tutorial on the new documentation side though.

**Comment by elkowar** [comment]
Fixed in e49d39e108ecbff86518941f1cd92b4183ad808b
