### ISSUE TITLE
[BUG] deflisten doesn't work when scripts include awk or grep

### ISSUE THREAD

**Issue by vladimirlucifer** [elkowar/eww#292]
## Checklist before submitting an issue
- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
As the title suggests, using awk and grep or either one by themselves while running commands such as the one suggested in the documentation for this kind of variable (xprop -spy -root _NET_CURRENT_DESKTOP) ends with no text being reproduced in the widget despite it outputting perfectly on the terminal.

## Reproducing the issue
Create a variable as such:

``` yuck
(deflisten TAG :initial "| Tag:1 |"
  `xprop -spy -root _NET_CURRENT_DESKTOP | awk '{ print "| Tag:" $NF+1 " |" }'`)
```
## Expected behaviour
It should output | Tag: INDEX_OF_WORKSPACE | , as it does in the terminal, to a widget, instead leaves blank space.

## Additional context
I have tried this as a  script or part of the configuration file. This was supposed to be my Current Workspace indicator, as i am building a desktop UI with eww.

**Comment by elkowar** [comment]
This seems to be an issue with how `awk` does its buffering. One solution is to change the command to
`xprop -spy -root _NET_CURRENT_DESKTOP | stdbuf -oL awk '{ print "| Tag:" $NF+1 " |" }'`, as indicated here (and specifically in the comments of this post) https://stackoverflow.com/a/33448495.

Not sure if there is any way for eww to specifically address this.

**Comment by AkumaSebastian** [comment]
@elkowar Huh. Amazing. Thank you for the solution, closing the thread.

**Comment by vladimirlucifer** [comment]
@elkowar Uh, amazing. Thanks. Regarding eww, I also have no idea how you would fix this, as I don't understand these buffering problems. Thanks you, again for the help, though. Closing.
