### ISSUE TITLE
Maintain a button in the :active subclass so that he can be styled properly with css

### ISSUE THREAD

**Issue by ParanoidNemo** [elkowar/eww#294]
Maybe I'm dumb and I don't see how to do it, but basically what I'm trying to do is have a button that turn on/off my VPN (that I've already done) and that when the VPN is on maintain the :active sub-state so that I can style it correctly in CSS and I don't have to create a specific class for every button/indicator. That already works when clicking (obviously), but it doesn't stay active.

Any thoughts?

**Comment by druskus20** [comment]
You probably want to use a checkbox instead

**Comment by ParanoidNemo** [comment]
checkbox only show a check mark when clicked, but the "button" come back to the inactive state. Have you an example at hand for it or it was just an hunch?

**Comment by ParanoidNemo** [comment]
sorry but I don't get it. But no problem really, I've "fixed" it for me using this
```
(s_info_button :class {wifi_class ? "s_info_button_active" : "s_info_button"}
                        :onclick ""
                        :label "")
```
and a variable that I update inside the script that toggle wifi (in this case) on and off.

Thanks for your time and your work.
