### ISSUE TITLE
How to install on ubuntu

### ISSUE THREAD

**Issue by FrighteningCat** [elkowar/eww#312]
I used this [https://elkowar.github.io/eww/eww.html](url) to try and install EWW, and these are the errors i got. https://pastebin.com/9LJZgSqh 
and yes i am using the nightly thing

**Comment by legendofmiracles** [comment]
Can you run `rustc --version`, just to double check? The error log also says something about atk, I believe the package name for that on ubuntu is `libatk`, can you try instaling that?

**Comment by FrighteningCat** [comment]
> Can you run `rustc --version`, just to double check? The error log also says something about atk, I believe the package name for that on ubuntu is `libatk`, can you try instaling that?

tried to install libatk it said Unable to locate package libatk and my rust version is rustc 1.51.0

**Comment by elkowar** [comment]
Closing, as I assume this has been resolved
