### ISSUE TITLE
[BUG] (children ...) widget doesnt find local variable 

### ISSUE THREAD

**Issue by druskus20** [elkowar/eww#325]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
This is an issue regarding custom widget childrens. 
Because of how state is handled (not at all lmao) in eww, children widgets fail to find variables that are not declared in the context of their parent. 

## Reproducing the issue
```clojure
(defwindow test
  :geometry (geometry :x 350 :y 0 :width "100px" :height "100px")
  (box 
    (example :icon "ICON")))

(defwidget widget-with-children []
  (box :orientation "h"
    (children :nth 0)))

(defwidget widget-with-children-WITH-ICON [icon]
  (box :orientation "h"
    (children :nth 0)))

(defwidget example [icon]
  (box 
    (widget-with-children                        ; Doesnt work
;   (widget-with-children-WITH-ICON :icon icon   ; Would work

      ; `icon` needs to be present in the context of
      ;   widget-with-children
      (label :text icon))))                   
```

## Expected behaviour
```
error: Unknown variable icon
   ┌─ /home/druskus/.config/eww-testing/eww.yuck:21:20
   │
21 │       (label :text icon))))
   │                    ────
   │
   → Hint: If you meant to use the literal value "icon", surround the value in quotes
```

## Additional context
To work around this issue, we can define `icon` as an argument for our parent widget: 
 ```clojure
(widget-with-children [icon] ...) 
```

**Comment by elkowar** [comment]
this is solved in the state rework now!
