### ISSUE TITLE
[WIDGET] Graph custom widget

### ISSUE THREAD

**Issue by druskus20** [elkowar/eww#329]
## Description of the requested feature
A widget that displays a graph (a line representing timed events). 

# Additional context
The graph widget would have to internally store previous values to be able to draw time series.

**Comment by iSparsh** [comment]
Vouch for this. It would be great to have something like the cpugraph from conky. Although someone could fiddle around with variables and css to pull this off, it would be great to have a premade widget for this.

**Comment by druskus20** [comment]
This is definitely not something one does with css variables. Cairo would do just fine

**Comment by iSparsh** [comment]
I don't know if its appropriate here or not, but i'll go ahead... is it possible to add "smoothness" to the graph? As in the showcase, the graph is spiky. If there was a smoothness attribute (lets say from 1 to 10? 1 to 100?) the curves could get smoother (and non-spiky.). Please let me know if this can be done with SCSS for example.

**Comment by druskus20** [comment]
Will close this for now, might come back to do some smooth animations in the future
^^
