### ISSUE TITLE
[WIDGET] Widget to transform contents

### ISSUE THREAD

**Issue by druskus20** [elkowar/eww#331]
## Description of the widget
Currently users dont have the ability to rotate widgets, implementing a wrapper widget that rotates its content should be pretty easy using cairo.

**Comment by elkowar** [comment]
Imo this should be a more generic `transform` widget if possible, that could also support translation and scaling

**Comment by druskus20** [comment]
Sounds good to me

**Comment by elkowar** [comment]
Implemented by #348
