### ISSUE TITLE
[FEATURE] Proper Magic Variable Documentation

### ISSUE THREAD

**Issue by iSparsh** [elkowar/eww#332]
## Description of the requested feature
Not enough documentation for the eww magic variables. There is no way to know which values to use on the wiki. For example: `EWW_CPU` has a `.avg` value that can be accessed, but I only know that through example configurations. There is no easy way to know these values easily on the Wiki page.

**Comment by legendofmiracles** [comment]
Can this be assigned to me?

**Comment by legendofmiracles** [comment]
@iSparsh This is what I got so far, quick and ugly. 
![image](https://user-images.githubusercontent.com/30902201/140592753-38aeb28a-a49a-4586-9950-24fab2addf39.png)
Anything that you don't like?

**Comment by iSparsh** [comment]
That's perfect @legendofmiracles ! Thanks so much.

**Comment by legendofmiracles** [comment]
That was my plan originally - when i first added them, but elkowar didn't like it because they would have to be maintained. 
The one example that exists only exists because I wanted to showcase the special syntax.

**Comment by iSparsh** [comment]
Alright then! I guess its resolved. Thanks!

**Comment by legendofmiracles** [comment]
Uhh, I haven't opened the PR yet.
I'd rather have it open to remind to finish it
