### ISSUE TITLE
[FEATURE] Opening/Closing window with `toggle` command

### ISSUE THREAD

**Issue by iSparsh** [elkowar/eww#333]
## Description of the requested feature
There should be a command to open and close (ie. toggle) the state of a window in a simple way. It should open a window when its closed, and close it if open (no matter the visibility).

## Proposed configuration syntax
The proper command-line syntax can be as follows:
```bash
$ eww toggle <window_1> <window_2> ..
```

## Additional context
While mapping eww widgets to keys, it becomes hard to open and close the widget(s) with one single key-bind, like Rofi does. For example, `<super> + <space>` opens/closes a rofi window. If the same implementation is possible, it should be done with `eww toggle` (or a similar name). This allows us to use the same keybind to spawn and de-spawn a window for example.

**Comment by VuiMuich** [comment]
There already is an `--toggle` flag for the open subcommand:
```
(button :onclick "eww open --toggle window-name")
```

**Comment by iSparsh** [comment]
Ahh didn't know.. thanks!
