### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by owenrumney** [elkowar/eww#336]
Hey, love eww and yuck!!! 

At first yuck didn't seem intuitive till I got using it and it's fantastic.

How should I contribute my i3 bar replacement (https://GitHub.com/owenrumney/eww-bar)? Do you want PR adding to readme with a link?

Again, thanks for this, it's awesome

**Comment by druskus20** [comment]
Its gonna be even more awesome very soon (#335)  
Also keep track of #338 and #328.
