### ISSUE TITLE
Boolean option for setting _NET_WM_STRUT

### ISSUE THREAD

**Issue by RossComputerGuy** [elkowar/eww#34]
It would be nice if `<window>` had an attribute called `use-struts` and that would then make whatever window manager treat the eww window as a panel by having it only take up its own space. This can be done by setting `_NET_WM_STRUT` for X11.

**Comment by elkowar** [comment]
I'm afraid this isn't that simple. The _NET_WM_STRUT field needs to know which part of the screen the window takes up, and how to deal with it. This can't easily be decided based on the information we have about window-placement etc.

If you have a concrete implementation plan for this, I'd be more than happy to accept a PR! The only viable option i can see currently would be to allow setting the strut-values manually, which i feel is kind of a bad UX, and should thus only be done if there is no alternative.

**Comment by RossComputerGuy** [comment]
Can't just set it to `[x,y,w + x, y + h]`? It supports a minimum of 4 values.

**Comment by elkowar** [comment]
the values are not x, y, width, height tho.
they are `left bottom top right`,  distance from the edge of the screen (not sure about the order, but you get the point)

**Comment by RossComputerGuy** [comment]
https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html, freedesktop's spec shows it's left, right, top, bottom. And can't that be calculated from just using the x, y, w + x, h + y?

**Comment by elkowar** [comment]
left,right,top,bottom in "distance that windows should have from the corners". so if you had a bar at the top, it would be `0, 0, 20, 0`

**Comment by RossComputerGuy** [comment]
Lemonbar's code is probably a good implementation since you can specify the geometry of the window.

**Comment by elkowar** [comment]
This is more of a conceptual question tho. If the user places the window in the exact center of the screen, with all sizes being the same. What should the struts be?

**Comment by elkowar** [comment]
The more I think about it, the more reasonable `reserve-top`, `reserve-left` etc properties on `<window>` seem like a perfect option. Ofc I could theoretically derive these from window geometry, but only by doing a bit of guess work, which might have non obvious behaviour. Setting it explicitly seems sensible.

**Comment by elkowar** [comment]
I've been looking into this for a good bit now, but couldn't quite figure out how the  `_NET_WM_STRUT` stuff actually is supposed to work. I tried setting  the values from `xprop` manually, which did nothing. Also, as gtk does not provide any way to set X Properties directly, implementing this is quite tedious,...
Not saying it won't happen, because it definitely should. Just saying that i can't be bothered to screw around with this at the moment, and that i'd be very open to PRs in that regard.

I already added the strut tag to the configuration, thus the only thing left to do is to actually apply the configuration to the window.

**Comment by RossComputerGuy** [comment]
Yeah, the docs are confusing me as well. [I found this but its python](https://stackoverflow.com/questions/13455527/cant-change-net-wm-strut-partial-property#23607619), maybe it can be adapted.

**Comment by elkowar** [comment]
believe me, i've looked at that quite a few times, as it's literally the best resource available about this apparently,.... but I still don't quite get it. If noone PRs this, i'll at some point likely read the code in polybar or lemonbar and try to figure it out

**Comment by RossComputerGuy** [comment]
I might take a look at polybar later and PR the strut calculations if the rest can be done.

**Comment by elkowar** [comment]
Currently I just have a `<struts>` tag in the window definition, where the use can explicitly specify the struts. That should mostly be enough, although having it be fully dynamic and based on the window position and size (then also setting `_NET_WM_STRUT_PARTIAL`) would definitely be nice

**Comment by RossComputerGuy** [comment]
Maybe to do the partial strut, a `partial` attribute could be used. Example:
```xml
<struts>
0, 0, 10, 10
</struts>
<struts partial>
0, 0, 10, 10, 0, 0, 0, 0, 0
</struts>
```

**Comment by elkowar** [comment]
not really a fan of that syntax tbh, i'd preffer them to be normal properties on the struts tag (as in `<struts top="2" left="5" etc>`

**Comment by elkowar** [comment]
This has been implemented in the gtk4 branch with https://github.com/elkowar/eww/commit/59906306772dd1cc0875bccf6c033e13624b4d85 - so now let's just wait until the gtk4 branch is ready to be merged :D

**Comment by elkowar** [comment]
I'll close this, as the feature is implemented and, if you use the GTK4 branch, already usable
