### ISSUE TITLE
[BUG] eww commands stop responding to commands

### ISSUE THREAD

**Issue by snakedye** [elkowar/eww#341]
## Describe the bug

When I set the `tray` variable to `false`, it toggles a revealer widget which hides its child. eww then stop responding to any following command.

## Reproducing the issue
[configuration](https://github.com/elkowar/eww/files/7492589/eww.txt)

graph before setting the `tray` variable to `false`
[eww-graph-before.txt](https://github.com/elkowar/eww/files/7492595/eww-graph-before.txt)
graph after setting the `tray` variable to `false`
[eww-graph-after.txt](https://github.com/elkowar/eww/files/7492599/eww-graph-after.txt)

## Expected behaviour
eww responds to commands.

**Comment by elkowar** [comment]
any logs that seem relevant? (specifically, anything related to the IPC, maybe with `--debug`)?

**Comment by snakedye** [comment]
More logs
[eww.log](https://github.com/elkowar/eww/files/7527395/eww.log)
[eww.txt](https://github.com/elkowar/eww/files/7527397/eww.txt)

**Comment by snakedye** [comment]
https://user-images.githubusercontent.com/49378990/141524342-93d68b89-3b45-4e19-8c35-bf975e62d972.mp4

**Comment by elkowar** [comment]
According to snakedye on discord, this has been fixed!
