### ISSUE TITLE
Package Request for Void Linux.

### ISSUE THREAD

**Issue by basicfunc** [elkowar/eww#346]
Hey, there! I'm using `eww` on [Void Linux](https://voidlinux.org), really loving it and I've created a template for [xbps-src](https://github.com/void-linux/void-packages). Here it is,

````
# Template file for 'eww'
pkgname=eww
version=0.2
revision=0
archs="x86_64"
wrksrc=${pkgname}-${version}.${revision} 
hostmakedepends="curl pkg-config glibc-devel libgcc-devel"
makedepends="gtk+3-devel gtk-layer-shell-devel pango-devel gdk-pixbuf-devel cairo-devel glib-devel"
depends=""
short_desc="ElKowars wacky widgets"
maintainer=" <>"
license="GPL-3.0-or-later"
homepage="https://github.com/elkowar/eww"
distfiles="${homepage}/archive/refs/tags/v${version}.${revision}.tar.gz"
checksum="c384a6c2f611b3b4ffb88a0d5ec14130db53aebae6043d535ace59546a524299"
dir=/usr/bin
mode=0755


do_install(){
    # Installing Rust Nightly Toolchain
    curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --profile minimal --default-toolchain nightly -y
    source /host/cargo/env
    # Compilation
    cargo +nightly build --release --no-default-features --features=wayland
    # Installation
    echo ${PKGDESTDIR}
    vbin target/release/eww
    install -Dm755 target/release/eww "${PKGDESTDIR}/usr/bin/${pkgname}"
    vlicense LICENSE
    mkdir -p "${PKGDESTDIR}/etc/xdg/${pkgname}"
    cp -r examples/eww-bar "${PKGDESTDIR}/etc/xdg/${pkgname}"
}
````

 Its not a perfect template. Please check out [Manual](https://github.com/void-linux/void-packages/blob/master/Manual.md)

**Comment by elkowar** [comment]
I'm sadly not gonna be able to maintain packages for all the distros out there myself, as maintaining packages for distros I don't use myself would be a _lot_ of effort and overhead. However, feel free to submit and maintain this in your package repos yourself! I don't know exactly how this works on void, but I'm always happy about user-maintained packages!

**Comment by basicfunc** [comment]
Thanks for your reply! I'll maintain =eww= package for Void Linux.

**Comment by jcgruenhage** [comment]
I wanted to follow up on this so that people looking at it can find it: People have requested an `eww` package for void downstream too, but it's blocked on the nightly thing. What specific unstable features does `eww` need that aren't available in stable yet, and would PRs for getting those replaced using other means be accepted as well?
