### ISSUE TITLE
[BUG]  Can't apply CSS styles to image

### ISSUE THREAD

**Issue by ImDevinC** [elkowar/eww#358]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
image widget doesn't use class properly

## Reproducing the issue
```
eww --version
eww 0.2.0
```
yuck
```
cat eww.yuck
(defwidget music [] 
    (image :class "album_art" :path COVER)
)
(defwindow music :stacking "fg" :focusable "false" 
    :geometry (geometry :x 515 :y 490 :width 610 :height 280)
      (music)
)
```
scss

```
.album_art {
	background-size: 240px;
	min-height: 240px;
	min-width: 240px;
	margin: 20px;
	border-radius: 6px;
}
```

## Expected behaviour
The image should have the styles applied to it but they are not

**Comment by iSparsh** [comment]
Can you link the image you are using?

**Comment by ImDevinC** [comment]
I've tried with tons of images, and it happens to all of them. But here's the current one on my system
![cover](https://user-images.githubusercontent.com/3997333/143273296-5794776f-9943-43b6-a6e6-8538dc416863.png)

And to clarify, here's what the image looks like in eww
![2021-11-24_00-12-20](https://user-images.githubusercontent.com/3997333/143274602-f45cbcf1-8d5a-47b8-87f7-ca4ad8c4c50f.png)
Much too big, breaking out of the bounds and not having a radius

**Comment by iSparsh** [comment]
Ok, just to confirm, do inline styles for radius work (along with https://elkowar.github.io/eww/widgets.html#image width and height properties) ?

**Comment by elkowar** [comment]
The issue here miiiiiiiight just be that gtk itself doesn't support those CSS properties on images,... in which case fixing this would be quite difficult (not impossible tho). Would be interesting to see if one can make them apply manually in the gtk debugger (run `eww inspector` to open the debugger, there you can manually look at and change the CSS properties of everything)

**Comment by Vermoot** [comment]
Can't you wrap your image in a `(box )` and apply your CSS rules to that?

**Comment by nautilor** [comment]
Same problem here, wrapping everything in a box does not work

this is in the yuck file

```yuck
(box :orientation "h" :space-evenly "false" :class "music-album"
    (image :path {album} :image-width 100 :image-height 100)
)
```

and this is the css

```css
.music-album {
	border-radius: 10px;
}
```
and no round corner is shown

if I change the css to this

```css
.music-album {
	border-radius: 10px;
  border: 10<px solid #4C566A;
}
```
I get this result

![eww](https://user-images.githubusercontent.com/9730983/152792909-28b2a9cf-2b1e-489f-a328-1a707965d5b0.png)

as you see in the picture, the border is rounded but the picture is not

**Comment by snakedye** [comment]
Don't use images. Set the background of the box as an image using css.

**Comment by nautilor** [comment]
clever idea

**Comment by snakedye** [comment]
yes if you use the style attribute in yuck irrc
