### ISSUE TITLE
[BUG] Delay does not respect absolute time after suspend-resume (polls).

### ISSUE THREAD

**Issue by Animeshz** [elkowar/eww#367]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
Let's say a poll-var is refreshed at a rate of 5 minutes, we suspend the laptop 1 min after a refresh, we resume it later on maybe say 1 hour, now it needs 4 minutes for it to refresh itself, its very inaccurate specially for battery and weather status... 

## Reproducing the issue
```
(pollvar :name test_field :interval "1m" `cat /sys/class/power_supply/BAT1/capacity`)
```
On resume, value doesn't update immediately if 1min is elapsed, counted from last refresh.

## Expected behaviour
It should rather work at absolute clock differences, and if not atleast listen to suspend events and add a timestamp and utilize it in next resume.

## Additional context
Might be a bit related to https://github.com/rust-lang/rust/issues/79462

**Comment by elkowar** [comment]
I'm afraid making polls work like that would require quite a bit of a rework, which at least currently doesn't really seem worth it for such an edge case.

I'd recommend handling the important variables manually via `eww update` in a script that runs on suspend/resume, that way you can just make sure those variables get immediately updated when you need them too. Note that it's not an issue to run `eww update` on listen or poll vars
