### ISSUE TITLE
[FEATURE] Class and style attributes for windows

### ISSUE THREAD

**Issue by eddsalkield** [elkowar/eww#371]
### Description of the requested feature

I'm trying to achieve a fade-in effect for windows when opened, and to do this I'm looking to set/unset a class attribute of the window and match it in the CSS.

When I set the class like so:

```
(defwindow example
        :class "testclass"
           :monitor 0
           :geometry (geometry :x "0%"
                               :y "20px"
                               :width "90%"
                               :height "30px"
                               :anchor "top center")
           :stacking "fg"
        "testcontent")
```
 And with the following CSS:

```
.testclass {
        color: red
}
```

I get:
![actual](https://user-images.githubusercontent.com/30939717/145718434-d0c1309e-7922-4f35-be02-fed75b7b429f.png)

When it would be nice to have:
![expected](https://user-images.githubusercontent.com/30939717/145718443-d61ade33-5099-4440-808c-5e8900bb1127.png)

### Proposed configuration syntax

Class to mirror widget syntax a bit more, to include attributes `:class` and `:style`.

### Additional context

The gtk inspector shows that the problem is that the class isn't getting set:
![inspector](https://user-images.githubusercontent.com/30939717/145718475-dd54d09e-e4b4-4189-afae-d45505068f79.png)

**Comment by godalming123** [comment]
For your fade/unfade effect I was able to tweek a few window property's on wayland to get my compositers animation to play however if this does not work for you try:
```
@keyframes fade {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}

window {
    animation: fade 150ms;
}
```
Note this will only work for windows coming in to the screen however I cannot find a way for windows coming out.

**Comment by viandoxdev** [comment]
> Note this will only work for windows coming in to the screen however I cannot find a way for windows coming out.

This can be done with scripts and no css: put your whole window into a revealer bound to a `reveal` (or any other name) var that is set to  `false`, then, instead of calling `eww open ...` and `eww close ...` make scripts for that:
```bash
# open.sh
eww open your-window
eww update reveal=true
```
```bash
# close.sh
(
eww update reveal=false
sleep the-transition-duration
eww close your-window
) &
# the & and the () are here to make the script end instantly.
```

**Comment by elkowar** [comment]
I made eww now add the window name as a default class of a window. With the current structure, having variable references / dynamic values in the window class wouldn't be possible either way, so I don't think there'd be _that_ much added value in an explicit class property on windows, would there?

**Comment by eddsalkield** [comment]
With a default class per window as now in 77adfbca6b3ece5b4872138d48c90d738d2afa90, I also don't see much value in adding an explicit class property on windows, other than perhaps consistency with the widgets.  Thanks so much, and to the others for suggesting other solutions.
