### ISSUE TITLE
[BUG] WM does not comply in certain situations

### ISSUE THREAD

**Issue by SystematicError** [elkowar/eww#375]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

This issue occurs when opening the eww bar after the window manager starts up. When using the `:stacking "bg"` option in your window, sometimes the WM follows this, at other times it stays in you foreground. More details are given down below.

### Reproducing the issue

1. Add the `:stacking "bg"` option in your `defwindow`
2. Add `eww open <window>` to the startup in your wm
3. Open an application in fullscreen
4. Close the fullscreen app
5. In your terminal, run `eww close <window> && eww open <window>`
6. Open another app at fullscreen

Please substitute the `<window>` with whatever your eww window is called.

### Expected behaviour

In both situations, the eww window should stay behind the fullscreen application. However, this only happens the first time. The second time the window sticks out in front of the fullscreen window.

### Additional context

I have only tested and confirmed this in bspwm so far. Here are some screenshots after step 6:

![image](https://user-images.githubusercontent.com/63366086/146937269-34ffe93c-c536-4eab-b5b9-6275c90a86c4.png)

![image](https://user-images.githubusercontent.com/63366086/146937449-6a6da26e-af87-458f-bd49-16f801fcbe80.png)

Here you can see my eww bar staying in foreground when fullscreen. This also happens to floating windows.

**BSPWM Version:** `0.9.10`
**Eww Version:** `0.2.0`

**Comment by SystematicError** [comment]
```lisp
(defwindow bar
    :monitor 0
    :geometry (geometry
        :x "0px"
        :y "0px"
        :width "100%"
        :height "30px"
        :anchor "top center"
    )
    :stacking "bg"
    :reserve (struts
        :distance "35px"
        :side "top"
    )
    :windowtype "dock"
    :wm-ignore "false"
    
    "Sample Text"
)
```

Here is a sample config

**Comment by SystematicError** [comment]
Oh also, this may not be a bspwm bug, polybar works fine by setting the `wm-restack` variable to `bspwm`

**Comment by SystematicError** [comment]
Update: This issue happens when stacking both `fg` or `bg`, the issue also occurs when eww config is reloaded

**Comment by oldwomanjosiah** [comment]
I am also seeing this currently

**Comment by elkowar** [comment]
Stacking definitely is one of the more broken things currently -- This is already being tracked in #178 (and I think a couple other issues, lol)

thus closing this as a duplicate ^^
