### ISSUE TITLE
[BUG] (i think it's not really a bug) compiling error

### ISSUE THREAD

**Issue by minimelonn** [elkowar/eww#376]
### Checklist before submitting an issue

- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2021-08-10-x86_64-unknown-linux-gnu' toolchain

### Reproducing the issue

cargo build --release --no-default-features --features=wayland

### Expected behaviour

compiling

**Comment by minimelonn** [comment]
bazinga

**Comment by viandoxdev** [comment]
update tour toolchain ? that really looks like a rust installation problem more than an eww problem

**Comment by elkowar** [comment]
Yea, this should be solved by updating your rust installation. Also yes, this is definitely not a bug in eww, thus I'll close it! Good luck
