### ISSUE TITLE
[FEATURE] keepalive on listen variables

### ISSUE THREAD

**Issue by viandoxdev** [elkowar/eww#377]
### Description of the requested feature

A keepalive property on deflisten that would make the variable continue to get updated even when not used in any windows.

### Proposed configuration syntax

```yuck
(deflisten var
  :keepalive true
  `command`)
```

### Additional context

Currently variables defined with `deflisten` which aren't used in any open window don't get updated (which is good most of the time). But this can cause problems: a side bar (which stays closed more often than) with a workspace display (updates rarely) doesn't keep up with the last focused workspace if it is closed, and shows an outdated value when opened. A work around for this is to use the variable in an hidden (0px width/height) window that stays open.

**Comment by elkowar** [comment]
I'd recommend just making whatever script you're using have a way to read the current value (i.e. which workspace is focused) immediately, in addition to listening to changes. that way, your value will be accurate on startup of eww, too.
