### ISSUE TITLE
Styling Calendar Widget

### ISSUE THREAD

**Issue by Bennett-Wendorf** [elkowar/eww#378]
I realize this probably isn't the best place to ask a question like this, but I can't seem to find a better place, so please let me know if there is somewhere else that would be better to post a question like this.

I can't seem to figure out how to get the selected day to show up properly in the calendar widget when I apply my own styling to it. The selected day does show up properly if I don't apply any of my own theming and just let gtk take care of it though, so I know that the widget is receiving the correct selected day. I did already look through the GTK debugger as suggested in the documentation, but I can't seem to figure out what css property actually styles that selected day.

I attached what it currently looks like and the relevant code that I have so far. My goal with it is to have some sort of background or border around the selected day.

Any insight you could provide would be greatly appreciated!

![Cal_pic](https://user-images.githubusercontent.com/49812183/147838344-870ea8b7-982d-4f3b-8be7-46ccc9be6ea3.png)

```
(defwidget cal []
    (box :class "border-box extra-bottom-margin"
      (calendar :halign "center" :valign "center" :class "cal" :month current_month :year current_year :day current_day)
    )
)

;;  Calendar vars
(defpoll current_year :interval "1m" "date +'%Y'")
(defpoll current_month :interval "1m" "date +'%m'")
(defpoll current_day :interval "1m" "date +'%d'")

(defwindow calendar
    :wm-ignore: true
    :windowtype "dock"
    :geometry (geometry :x "8px" :y "52px" :width "340px" :height "260px" :anchor "top left")
            (cal)
)
```

```
.border-box {
    border-width: 3px;
    border-style: solid;
    border-color: $widget-border-color;
    background-color: $sidebar-widget-bg-color;
    border-radius: $widget-border-radius; 
    margin: $sidebar-widget-margins;
}

.cal {
    color: $light-blue;
    padding: 5px;
    padding-bottom: 1px;
}

.extra-bottom-margin {
    margin-bottom: 20px;
}
```

**Comment by SystematicError** [comment]
I just whipped up a quick example, you can style the current day using the selected state.

```css
.calendar {
    padding: 12px;
}

.calendar:selected {
    background: teal;
}
```

![image](https://user-images.githubusercontent.com/63366086/147870150-760e088c-0930-4e9e-a318-38fcf74bb4bf.png)

**Comment by Bennett-Wendorf** [comment]
That would do it. That's exactly the property I needed, I just couldn't seem to find that mentioned in the documentation. Thanks a ton!

**Comment by beyond9thousand** [comment]
> I just whipped up a quick example, you can style the current day using the selected state.
> 
> ```css
> .calendar {
>     padding: 12px;
> }
> 
> .calendar:selected {
>     background: teal;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/63366086/147870150-760e088c-0930-4e9e-a318-38fcf74bb4bf.png)
> 
> Note: This highlights the selected day, by default the selected day will be the current day however other days will be selected when you click on them.

Did anyone figure out how to center the days? This is so unusable
