### ISSUE TITLE
[BUG] Variable being ignored

### ISSUE THREAD

**Issue by Tartopohm** [elkowar/eww#392]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I have a listener variable in my main config file whose existence seems to be ignored.
It never shows up in `eww state`. If I initialise it, `eww get` prints the initial value; if I don't, it does not print anything.

I tried changing the variable name; changing its type (from listener to poll); and using a dummy script instead of the actual one (even though it works as expected when run in a terminal). Nothing seems to make any difference, nor restarting eww or even rebooting my computer (which solved a minor font inconvenience in the past).

I run the AUR Wayland package (Sway WM) and I have been using eww for a couple of months without any issue.

### Reproducing the issue

eww.yuck MWE:

```
(deflisten cvl
  :initial true
  "./scripts/get_cloc1.sh")

(defpoll poll_ctime
  :interval "5s"
  :run-while cvl
  "date '+%H:%M'")
(defpoll poll_cdate
  :interval "5s"
  :run-while cvl
  "date '+%A %d %B'")

(defwindow clock
  :monitor 0
  :geometry (geometry :x "100px"
                      :y "100px"
                      :width "300px"
                      :height "200px"
                      :anchor "bottom left")
  :stacking "bottom"
  (box :orientation "vertical"
    (label :markup poll_ctime)
    (label :markup poll_cdate)))
```

### Expected behaviour

I expect the variable to expect as all its variable friends.

### Additional context

Content of .config/eww/scripts/get_cloc1.sh (dummy and actual version). The idea is to identify whether the active workspace is empty.

```
#!/bin/sh

send_value() {
    echo false
}

send_value
swaymsg -t subscribe -m '["window", "workspace"]' | while read -r _ ; do
    send_value
done 
```

```
#!/bin/sh

send_value() {
    windows=$(swaymsg -t get_tree | jq --argjson visible "$(swaymsg -t get_workspaces | jq -c '[.[] | select(.visible) | .id]')" -c '. | .nodes[] | .nodes[] | select(.type=="workspace" and .id == $visible[]) | .nodes' | jq length)
    if [ $windows -gt 0 ]; then
        echo false
    else
        echo true
    fi
}

send_value
swaymsg -t subscribe -m '["window", "workspace"]' | while read -r _ ; do
    send_value
done 
```

**Comment by viandoxdev** [comment]
Maybe try to have cvl appear in your window, eww optimizes away unused variables.

**Comment by Tartopohm** [comment]
> Maybe try to have cvl appear in your window, eww optimizes away unused variables.

That did the trick. Cheers!
