### ISSUE TITLE
[FEATURE]  onclick and onrightclick can be done in same icon

### ISSUE THREAD

**Issue by thyeun** [elkowar/eww#395]
### Description of the requested feature

`(button :class "launcher_icon"
			:tooltip "Start"
		   	:onclick "j4-dmenu"  ""
                        :onrightclick "def-dmenu" "")`

Is that a way to perform onclick and onrightclick in same icon?

**Comment by druskus20** [comment]
Dont quite remember off the top of my head, but take a look at `eventbox`

**Comment by thyeun** [comment]
No, `eventbox` for the `onhover` only execute per one command (if you mention using `eventbox` + `button`, that will be two different way of doing things), not prefer to write long code.

What i want is, using mouse with `onclick` execute one command and `onrightclick` execute another command but on the same button.

Current version can not put both inside the same button.

**Comment by druskus20** [comment]
I had assumed that worked. Yea this definitely needs to be a thing

**Comment by thyeun** [comment]
@druskus20 if you prefer, sure it will work with your way but, why not enhance it to make it better?

**Comment by viandoxdev** [comment]
I can't reproduce, it works for me.
![](https://i.imgur.com/j8AxXRA.png)
![](https://i.imgur.com/NxZsuDn.png)

**Comment by thyeun** [comment]
@viandoxdev which version are you using?

My current version is `0.2.0`

`;; Launcher Widgets ;;
(defwidget launcher []
	(box :orientation "h" 
		 :space-evenly "false" 
		 :spacing "-10"
  	(button :class "launcher_icon"
			:tooltip "Start"
		   	:onclick "j4-dmenu"  ""
		   	:onrightclick "def-dmenu"  "")))`

That my original code, but it wont work, once i put in onrightclick, i cant start my eww-bar

**Comment by thyeun** [comment]
@viandoxdev i found out the error, if both click with an  icon, it wont work, the icon only can put at the end of the last click.

```
(defwidget launcher [] (box :orientation "h" :space-evenly "false" :spacing "-10" (button :class "launcher_icon" :tooltip "Start" :onclick "j4-dmenu"  :onrightclick "def-dmenu" "")))
```

**Comment by druskus20** [comment]
> @viandoxdev i found out the error, if both click with an icon, it wont work, the icon only can put at the end of the last click.
> 
> ```
> (defwidget launcher [] 
> (box     :orientation "h" 
>             :space-evenly "false" 
>             :spacing "-10" 
> (button :class "launcher_icon" 
>             :tooltip "Start" 
>             :onclick "j4-dmenu"  
>             :onrightclick "def-dmenu" "")))
> ```
> 
> Thank you for point it out my mistake

That is because the icon "" is not part of the properties of the widget.
The icon text is the content of the widget. Instead of a string literal, it could also be another widget that's nested inside `launcher_icon`.
I suggest you format the code like this to see it more clearly.
```
(button :class "launcher_icon" 
            :tooltip "Start" 
            :onclick "j4-dmenu"  
            :onrightclick "def-dmenu" 
            "")))         
```

**Comment by thyeun** [comment]
@druskus20 here are not align nicely, inside my original code it is align nicely as you can see from the below picture

![Screenshot_2022-02-07-11-17-22_1366x768](https://user-images.githubusercontent.com/1939446/152719175-68da933f-3ae2-4798-be33-3795d73c9a86.png)
e

**Comment by druskus20** [comment]
The point is that the icon goes on the line bellow

**Comment by thyeun** [comment]
@druskus20 , no need goes on the line below, as from my code, it work fine like that. 

Any way thanks for your suggestion and have a good day.
