### ISSUE TITLE
[BUG] Eww doesn't acknowledge that windows have been closed

### ISSUE THREAD

**Issue by druskus20** [elkowar/eww#405]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Eww doesn't acknowledge that a window has been closed if that window was closed through the window manager. 

### Reproducing the issue

1) Open a floating eww window (such as the following, by running `eww open test`)
```lisp
(defwindow test
  :windowtype "normal"
  :monitor 0
  :hexpand false
  :vexpand false
  :geometry (geometry :x 350 :y 10 :width "500px" :height "500px")
  (box :class "bar"
       :space-evenly true))
```
2) Close it using your window manager (in my case, bspwm)
3) Run `eww open test` again

### Expected behaviour

After `3`, the window should be opened.
However, it currently isn't. At the moment, we need to let eww know that the window has been closed. We can do that by running `eww close test`. This should not be necessary, as eww should listen to closing window events from the WM. 

### Additional context

Have fun :D

**Comment by elkowar** [comment]
This should be fixed by 3ab53b0323460d586fb54125e06583486890ef8e
