### ISSUE TITLE
[FEATURE] update variable to inital value

### ISSUE THREAD

**Issue by godalming123** [elkowar/eww#418]
### Description of the requested feature

Ability to update a variable to the value specified by defpoll so you do not have to specify the new value

### Proposed configuration syntax

```
eww update VarName
```

**Comment by elkowar** [comment]
What's the usecase? This seems like a veeeery minor quality-of-life improvement for veeery rare edgecases

**Comment by godalming123** [comment]
I have a menu widget that updates the menu items when you search in a textbox

**Comment by elkowar** [comment]
I don't quite see how that would be helped by this issue?

**Comment by godalming123** [comment]
It's a _slight_ convince improvement and it does not particularly matter if you don't want to add it.

**Comment by elkowar** [comment]
Yea, I feel as though this is more confusing than helpful, sorry. I'll close it, if you don't mind
