### ISSUE TITLE
`limit-width` does not work

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#42]
Since migrating the `limit-width` attribute on `<label>` over to make use of `set_max_width_chars` in gtk, it doesn't work anymore. This needs to be fixed.

Best case: We understand why it doesn't work right now, and continue to make use of the GTK function.
As long as that is not done, we should revert back to the initial implementation that manually shortened the string.

## Acceptance Criteria
- `limit-width` if possible makes use of the GTK function `set_max_width_chars`, and correctly limits the character width of a label

**Comment by elkowar** [comment]
I've implemented the temporary fix in 4b86f844798aba3164de1035b16e540d39cdeda1

**Comment by Rayzeq** [comment]
Hello, I have a fix for this, but it removes the `show-truncated` property to allow support for pango markup truncation

The only solution I can think of to support both `show-truncated` and pango markup truncation would require adding `pango-limit-width` and `pango-truncate-left`.
`show-truncated` won't work for pango markup, but I don't think that's a problem, as pango markup currently don't support `limit-width` anyway.

You can find my changes [here](https://github.com/Rayzeq/eww/commit/d686b62afa308a1365c969bf0465c3a90ad90774). Could you tell me what you think of the solutions I've proposed?
