### ISSUE TITLE
[FEATURE] Checkbox: Custom checked vs unchecked label

### ISSUE THREAD

**Issue by reeseovine** [elkowar/eww#423]
### Description of the requested feature

Currently the checkbox widget shows the label, and then when checked shows a checkmark next to it. I would like to have one label to show when it's unchecked, and another to show when it's checked (sans checkmark).

### Proposed configuration syntax

```
(defwidget notification_muter []
	(checkbox
		:onchecked      'dunstctl set-paused true'
		:onunchecked    'dunstctl set-paused false'
		:labelchecked   ''
		:labelunchecked ''
	)
)
```

(The labels are nerd font icons: a bell with a slash through it, and a bell ringing)

#### Current:

| Unchecked | Checked |
|---|---|
| ![image](https://user-images.githubusercontent.com/1340784/161361394-c3e62354-c2d3-429f-b07c-e0496ed66032.png) | ![image](https://user-images.githubusercontent.com/1340784/161361379-fb862865-6cc2-4b5c-9387-8758cadd45b9.png) |

#### Proposed:

| Unchecked | Checked |
|---|---|
| ![image](https://user-images.githubusercontent.com/1340784/161361394-c3e62354-c2d3-429f-b07c-e0496ed66032.png) | ![image](https://user-images.githubusercontent.com/1340784/161361417-6980f979-df0a-4e6c-b20b-f1b08e801448.png) |

**Comment by elkowar** [comment]
at that point, why not just use a label widget and change the text depending on the state?

**Comment by reeseovine** [comment]
Oh, I didn't consider that. Thank you lol
