### ISSUE TITLE
[BUG] Input value within EWW expressions

### ISSUE THREAD

**Issue by TitouanLazard** [elkowar/eww#452]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Hello,

I wanted to use input and the onchange properties. However I need to be able to enter complex strings with potential bad characters. (I initially intended to use this input as password field).

So i tried to use eww expressions with replace function in order to escape char before using them in a command line. And it doesn't seems to work. I really don't understand the behavior.
```
           (input :class 'hidden_input' :onchange 'echo ${replace("AABB","A","X")}') => XXBB
           (input :class 'hidden_input' :onchange 'echo ${replace({},"A","X")}') => AABB even if {} is AABB
           (input :class 'hidden_input' :onchange 'echo ${replace({},".","X")}') => XX because "{}" is matched instead of it's value
```

Am i missing something ? 

### Reproducing the issue

The following input prints only XX
```
 (input :class 'hidden_input' :onchange 'echo ${replace({},".","X")}') 
``` 

### Expected behaviour

I think replace function should evaluate the actual value of {} instead of matching the characters "{}".
```
 (input :class 'hidden_input' :onchange 'echo ${replace({},".","X")}') 
``` 
Should therefore print as many X as input length.

### Additional context

I hope this bug is usefull, sorry to bother you if it's one of my one mistake.
This behavior has been observed on eww version 0.2.0

**Comment by elkowar** [comment]
Currently, the way eww works is that the expression is first evaluated (so the string `echo ${replace("AABB, "A", "X")}` is turned into `echo XXBB`, and _then_ passed to the input widget. Thus, currently there is no way to cleanly use the eww expression functions to change the placeholders in event handlers.

in #324, we're (among other things) working on a rework of these event handlers, in a way that _will_ allow something like this in the future.

**Comment by elkowar** [comment]
I'll close this issue for now, as it's not something that is gonna get improved before the larger rework of event handlers -- but it is going to happen!
