### ISSUE TITLE
[BUG] Can't compile in linux mint 20

### ISSUE THREAD

**Issue by Besufikad17** [elkowar/eww#454]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

It throws `#![feature]` may not be used on the stable release channel error when i tried to install with this command cargo build --release --no-default-features --features=wayland 

[Compiling glib-sys v0.14.0.log](https://github.com/elkowar/eww/files/8679883/Compiling.glib-sys.v0.14.0.log)

**Comment by elkowar** [comment]
Check the [common user errors related to problems compiling eww](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed+sort%3Aupdated-desc+compile) (again, as I assume you _did_ do that given that you checked the checkbox :P), you'll find a lot of people with exactly the same issue, and the solution for it.
