### ISSUE TITLE
Custom script timing out

### ISSUE THREAD

**Issue by ragreenburg** [elkowar/eww#455]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Custom scripts time out intermittently. My `yuck` file is [here](https://gitlab.com/greenbeast/ppp-sway-dotfiles/-/blob/eww-dock-pagination/.config/eww/eww.yuck. Essentially what I have is a dock with icons on it and am trying to pagination to work on there. This is done by having an arrow icon that when clicked launches a custom script that kills the open window then launches the new window ([here](https://gitlab.com/greenbeast/ppp-sway-dotfiles/-/blob/eww-dock-pagination/.config/eww/scripts/pagination1.sh)). The issue is that this script seems to time out about 90% of the time but 10% of the time it works just fine. When launching either dock on it's own, it runs just fine but when doing the transition it fails. Also when I run the scripts outside of eww (while the dock is still open), it runs without failure. The eww logs are less than helpful because it seems to just say the script timed out. 

### Reproducing the issue

Get the config and the script from above, run it and click on the double arrow in the far right of the dock.

### Expected behaviour

The custom script runs without failure.

**Comment by viandoxdev** [comment]
I mean I don't know if you should really expect a script that closes the window to continue running once the window (that runs the script) is killed.

You can do pagination fairly simply (and with animations) in yuck: have a parent box with multiple revealers (the pages) as children, have a page variable, and set the revealer's visible property to something like this `:visible {page == 0}` (changing the 0 with the number of the page for each revealer) and have the arrows be buttons that change that page variable.

**Comment by ragreenburg** [comment]
I should have added this in additional context, but I played around with the placement of the open and close functions. I tried closing then opening and vice versa. Originally I opened it then closed it and when that wasn't working I tried switching it up. 

Thanks for the idea on how to change this, I'll look into that.

**Comment by elkowar** [comment]
You should be able to specify the timeout of the script with the `:timeout` property on buttons, thus allowing you to prevent them from timing out ^^
