### ISSUE TITLE
[BUG] progress widget cannot be made smaller than the default size by using the `width` property

### ISSUE THREAD

**Issue by jokeyrhyme** [elkowar/eww#458]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Howdie, thanks again for sharing this excellent project! <3

I'm trying to create a widget to display Wi-Fi signal strength, and I'm trying to use the progress widget for this, but it seems to ignore the `width` property

I prefer to use the progress widget for this use case, because the scale widget is a little bit more complicated to style/configure

### Reproducing the issue

Using the [scale](https://elkowar.github.io/eww/widgets.html#scale) widget, I can properly control the `width` property with the expected effect:

```
(defwidget wifi []
  (scale :class "wifi" :orientation "h" :valign "center" :width 48
	     :tooltip {wifi.SSID}
             :visible {wifi.SSID != ''}
	     :value {wifi.SIGNAL}))
```

However, using the [progress](https://elkowar.github.io/eww/widgets.html#progress) widget, no matter what value I set as `width`, it always seems stuck on the same default width:

```
(defwidget wifi []
  (progress :class "wifi" :orientation "h" :valign "center" :width 48
	     :tooltip {wifi.SSID}
             :visible {wifi.SSID != ''}
	     :value {wifi.SIGNAL}))
```

### Expected behaviour

It would be great if either the documentation were updated to regarding how to control the width of a progress widget (if I'm doing it wrong), or updated to mention that it doesn't work on that widget, or if the widget itself could be updated to honour this setting

### Additional context

I also tried putting the progress widget in a box widget with `width` set on both, and this didn't work

I also tried using CSS, however the `max-width` and `width` properties do not seem to be valid in GTK / eww CSS

**Comment by jokeyrhyme** [comment]
@viandoxdev hmmm, for me, I can use `(box :width ...` and `(progress :width ...` to make it larger than the default size, but neither seems able to make it smaller than the default size, regardless of `:space-evenly true`

**Comment by viandoxdev** [comment]
That's weird, it worked last time I checked. I'll try to get a minimal working example tomorrow

**Comment by viandoxdev** [comment]
Ok, found how to resize them through css, as well as why it doesn't work. The base gtk style applies this css:

```css
progressbar.horizontal > trough {
    min-width: 150px;
}
```

so setting `min-width` to any other number changes the width. Additionally setting it to 1px (0 doesn't work for some reason) lets you control the width of the progress bar with the `width` prop.

**Comment by jokeyrhyme** [comment]
@viandoxdev awesome, changing `min-width` on the `trough` CSS node is exactly what I needed!

Note that `:class "wifi"` on the widget seems to replace all the default GTK CSS class names, so the `.horizontal` part doesn't work for me

Thanks!

**Comment by elkowar** [comment]
hmm, so would this be fixed if the progress widget would override gtks default CSS to set a min-width of 1px?

**Comment by jokeyrhyme** [comment]
@elkowar that would be one way of addressing it, yes

We might also want to consider overriding `min-height` as well, and also what happens when the progress widget is in vertical orientation?

**Comment by elkowar** [comment]
Decided to just document it, as setting a default of 1px would probably also be very confusing (as it'd probably result in the progressbar not showing up at all for many people) and as gtk is making is _painful_ to set style properties of these fake child elements, lol
