### ISSUE TITLE
[FEATURE] Export EWW daemon metadata.

### ISSUE THREAD

**Issue by pagankeymaster** [elkowar/eww#460]
### Description of the requested feature

I was wondering if any environment variables are set (injected?) when a EWW daemon runs a script? Kinda like [dunst](https://dunst-project.org/documentation/#SCRIPTING) does. Also, it would be nice if there was a way of getting the config path the EWW daemon was using (in the form of a environment variable.) kinda like Neovim `vim.fn.stdpath "config"`. EWW already has the framework like using magic variables so maybe export it to that? Thanks!

### Proposed configuration syntax

```lisp
;; test.yuck 
(defwidget test [] (button :onclick "./scripts/logger.zsh ${EWW_CONFIG_DIR}" "Click me!"))
```
```zsh
## logger.zsh
typeset EWW_CFG="$1"

function msg() { print "$EWW_CFG" }
```

### Additional context

Not applicable.

**Comment by elkowar** [comment]
6b5c35cbf9e921beb68b4a108762775f3674acf5 Exposes three new magic variables: `EWW_CONFIG_DIR`, `EWW_EXECUTABLE`, and `EWW_CMD` (which is pretty much `"${EWW_EXECUTABLE}" --config "${EWW_CONFIG_DIR}"`)

Not yet as environment variables tho, as that'd be quite annoying implementation wise. Are there any good reasons why this _wouldn't_ be sufficient? (Yes you'd have to pass in the config dir manually to scripts, but that doesn't sound toooooo bad for now)

**Comment by pagankeymaster** [comment]
Hello @elkowar sorry for the delay! My area had a huge thunderstorm today.
And yes I just was looking for a way to get eww's config path/dir. This is fine.
And, thanks for such a quick change!

**Comment by pagankeymaster** [comment]
This can be closed.
