### ISSUE TITLE
Not working after last commits

### ISSUE THREAD

**Issue by elkrien** [elkowar/eww#462]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Can You explain if there was any breaking changes in last commits? I’m using aur installed eww-git and after last 3 commits my all eww widgets don’t start. I downgraded eww to version from commit “ Improve error message for missing default monitor on wayland” and everything works. Tested on two computers with the same config.

**Comment by elkowar** [comment]
Could you share some logs? Nothing should have been broken by any recent commit

**Comment by elkrien** [comment]
> Could you share some logs? Nothing should have been broken by any recent commit

No windows is open. I tried to reload config and this what i get:
```
eww reload
error: No variable named `EWW_CPU` in scope
    ┌─ /home/mm/.config/eww/eww.yuck:243:37
    │
243 │                             :value {EWW_CPU.avg}
    │                                     ─────── Used here
    │
    → Hint: Either define it as a global variable, or add it to the argument-list of your `defwidget` and pass it as an argument
    → Hint: If you meant to use the literal value "EWW_CPU", surround the value in quotes
```

**Comment by elkowar** [comment]
Thanks for the report -- stupid oversight in the code on my part ^^
