### ISSUE TITLE
[BUG] Failed to get primary monitor from GTK

### ISSUE THREAD

**Issue by WillPower3309** [elkowar/eww#465]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Running eww 0.2.0 on nixOS, using the `eww-wayland` package. Upon trying to open a window, am met with `Failed to get primary monitor from GTK`. Have checked the nixpkgs repo for any related bugs to confirm it's not a packaging issue with including gtk.

Example:
```
❯ eww open github
failed to open window `github`

Caused by:
    Failed to get primary monitor from GTK
```

I realize this is still likely a nixOS issue, but am looking for some insight on what the underlying issue could be, so that if it is on the nixOS side, I can submit a PR to nixpkgs to fix it :)

**Comment by elkowar** [comment]
You'll have to explicitly specify your monitor in the window definition. I've improved the error message for this on master at this point, will be included in the next release
