### ISSUE TITLE
[FEATURE] SCSS parsing errors don't accurately point to the faulty file/line

### ISSUE THREAD

**Issue by Vermoot** [elkowar/eww#466]
### Description of the requested feature

I just got this while messing with files/names/locations:

```
eww/modules/volume on  main [✘!] took 3s
❯ eww reload
Encountered SCSS parsing error: SassError { kind: ParseError { message: "Can't find stylesheet to import.", loc: SpanLoc { file: File("stdin"), begin: LineCol { line: 0, column: 8 }, end: LineCol { line: 0, column: 9 } }, unicode: true } }
```

### Proposed configuration syntax

The error should at least point to the file and line where the problematic import occurs. Right now I don't know where I need to fix stuff.

**Comment by elkowar** [comment]
Somewhat of a duplicate / extension of #446 , mind just commenting there? :eyes:
