### ISSUE TITLE
Noob Issues

### ISSUE THREAD

**Issue by GreenFishy** [elkowar/eww#468]
Hi there!
Been having this issue where I cannot get eww to work. Now I don't know if this is a issue related to either me compiling it into the wrong directory. Or some how me just being completely stupid.
The first time I compiled it both once at a time under .config and my Home Dir to see if it was a directory issue. Both times didn't work out well as after I get ./eww daemon to run I cannot run a eww command. (eww open for example). I run it under debugging mode and everything seems fine no error output. I tried putting eww.yuck & eww.scss both times in either its own folder (./config/eww) or in home/eww to see if it would change anything nothing happens either.
Any help would be appreciated thanks.

system:
endeavouros
i3wm

**Comment by elkowar** [comment]
No errors and no logs seems weird. What exactly are you running, and what does your config look like?

**Comment by elkowar** [comment]
What command are you running to start eww?

**Comment by GreenFishy** [comment]
just as told ./eww daemon
./eww open <window_name> (the given example)
I don't quite know what other information I can give sorry.

**Comment by elkowar** [comment]
Is there any relevant output in `eww logs`?

**Comment by GreenFishy** [comment]
I solved the issue It had a directory issue where parts were moved incorrectly. I apologize for taking up your time, thanks you for helping me.
