### ISSUE TITLE
[BUG] unable to cast to json

### ISSUE THREAD

**Issue by EmiOnGit** [elkowar/eww#470]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm not quite sure if I simply misunderstand something or something is not working correctly but I assume that others might have similar problems.

I'm writing a json string from a python script to eww and try to use it in an for loop but doesnt seem to be able to get it to work properly.

### Reproducing the issue

```
(defpoll FOLDER :interval "1m" 'python scripts/folder') 

(defwidget folderview [] 
    (box
        (for name in FOLDER
            (box name)
        ))
)
```
where as my python script: scripts/folder
```
print("[\"a\",\"b\"]")
```

Fails with error:
Failed to turn '[a,b]' into a value of type json-value

### Expected behaviour

2 boxes are created with the text "a" and "b"

**Comment by viandoxdev** [comment]
try to quote `a` and `b` again

**Comment by EmiOnGit** [comment]
> try to quote `a` and `b` again
Tried but didn't change the error :disappointed:

**Comment by viandoxdev** [comment]
Well that's weird because this works for me
```python
# test.py
print("[\"a\",\"b\"]")
```
```yuck
; eww.yuck
(defpoll FOLDER :interval "5s" 'python test.py') 
(defwidget folderview [] 
    (box
        (for name in FOLDER
            (box name))))

(defwindow test :monitor 0
  :geometry (geometry :x "0%"
    :y "0%"
    :width "100px"
    :height "100px"
    :anchor "center right")
 :stacking "overlay"
 :exclusive false
  (folderview))
```
Result:
![](https://i.imgur.com/BAyXURd.png)

The error message is implying that eww receives the string as `[a, b]` instead of the `["a", "b"]` that it should, so maybe look into that ?

**Comment by elkowar** [comment]
I'll close this, as I assume it's solved! If not, feel free to reopen

**Comment by LamprosPitsillos** [comment]
> I'll close this, as I assume it's solved! If not, feel free to reopen

Since its ok to reopen,
I have the same issue but checking the json seems to be fine...

![image](https://github.com/elkowar/eww/assets/61395246/a0a3b1c3-543f-4435-a6a5-149ce36f27e7)

Command used in eww config:
`(defpoll calendar_json :interval "20s" "date +'{\"day\": %d ,\"month\": %m ,\"year\" : %Y }'")`

**Comment by EmiOnGit** [comment]
If I were you, I'd open a new issue and just link this one. Hast been to much time for this issue to gain any attention :)
