### ISSUE TITLE
[BUG] no GTK cursor style under wayland

### ISSUE THREAD

**Issue by paulhersch** [elkowar/eww#476]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

GTK cursor style isnt applied when hovering over eww under wayland (see screenshots)

### Reproducing the issue

apply a gtk cursor theme, use eww under wayland and watch

I use the home manager gtk module under nixos, so if someone else doesnt have that problem with Arch or another distro, i would be happy to know

### Expected behaviour

My cursor theme is still there when i hover over the bar

### Additional context

![06-12-160610](https://user-images.githubusercontent.com/74120050/173239258-fd62a6cb-cc2d-4ac7-9d62-998c5ec9b7eb.jpg)
![06-12-160601](https://user-images.githubusercontent.com/74120050/173239261-2da122e6-892b-4235-8ff0-770a9322b938.jpg)

**Comment by RicArch97** [comment]
I use EWW on Sway and cannot reproduce this, perhaps you should make sure to **also** set your cursor according to XDG spec. For home-manager an example for that would simply be something like:
```nix
home.file.".local/share/icons/default/index.theme".text = ''
  [icon theme]
  Name=Default
  Comment=Default Cursor Theme
  Inherits=Bibata-Original-Classic
'';
```
See https://wiki.archlinux.org/title/Cursor_themes#XDG_specification as well.

**Comment by paulhersch** [comment]
i was setting the cursor with the gtk module already, works now, so i guess this is already set that way.
thanks for the reply!
