### ISSUE TITLE
[BUG] [Wayland/sway] eww stops displaying widgets when monitor sleeps+resumes

### ISSUE THREAD

**Issue by dmfay** [elkowar/eww#477]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

* eww 0.3.0
* gtk+ 3.24.34
* Arch Linux
* AMD cpu and gpu, open source drivers
* Sway compositor with swayidle managing DPMS
* I do get the "probably a red herring" warning that gtk-layer-shell v0.7.0 may not work on GTK v3.24.34

When the monitor powers off and wakes up, eww widgets disappear.

### Reproducing the issue

.config/eww/bar2/eww.yuck, imported in .config/eww/eww.yuck

```
(defwindow bar2
  :monitor 0
  :exclusive true
  :stacking "bottom"
  :hexpand false
  :vexpand false
  :geometry (geometry :anchor "top center" :x 0 :y 0 :width "100%")
  :reserve (struts :distance "10px" :side "top")
  (bar :screen 0))

(defpoll time :interval "10s" "date '+%a %Y-%m-%d %I:%M:%S %p'")

(defwidget bar [screen]
    (box :halign "end"
         :hexpand true
         :space-evenly false
      time
    ))
```

```
eww daemon --debug
eww open bar2
eww logs
```

This displays a bar with the time in the upper right. Leave for a while and let swayidle turn the monitor off. On resuming, the bar will have disappeared and any open window expanded into the now-available space. The logs show no errors or warnings, and eww continues to run the time poll every ten seconds:

```
 2022-06-13T14:48:23.366Z DEBUG eww::config::script_var > Running command: date '+%a %Y-%m-%d %I:%M:%S %p'
 2022-06-13T14:48:23.368Z DEBUG eww::app                > Handling event: UpdateVars([("time", "Mon 2022-06-13 10:48:23 AM")])
```

`eww state` is blank; `eww ping` pongs; `eww graph` has a single node for the time as expected; `eww windows` shows `*bar2` indicating it's still open. Nothing displays until you `eww reload` whereupon the bar returns.

### Expected behaviour

The bar should still be there on wake.

**Comment by dmfay** [comment]
swayidle can work around this issue:

```
exec swayidle -w \
    timeout 900 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on" && sleep 5 && eww reload'
```

The `sleep` is required although I haven't tested shorter durations; without it, the reload doesn't appear to do anything.

**Comment by elkowar** [comment]
Given that eww windows are basically just regular windows that set some specific properties, I don't think this is actually an issue with eww itself, as I couldn't see _how_ eww would even know about the monitor sleeping.  the only thing I could imagine would be that the monitor just disappears completely, and thus ewws window gets moved somewhere else by your compositor, and then obviously not moved back properly -- which too would be a compositor issue
