### ISSUE TITLE
[BUG] Error while running script-var command: invalid utf-8 sequence of 1 bytes from index 0 invalid utf-8 sequence of 1 bytes from index 0

### ISSUE THREAD

**Issue by Swexti** [elkowar/eww#48]
## Describe the bug
A `Error while running script-var command: invalid utf-8 sequence of 1 bytes from index 0
invalid utf-8 sequence of 1 bytes from index 0` error from a specific `<script-var>`, i have similar script vars that doesn't give this error.

The script is this: 
```xml
<script-var name="radius" interval="500s">
  curl wttr.in/stocka | awk '{if (NR&gt;5) if (NR&lt;7) print}' | tr -d [:blank:\] | sed 's .\{55\}  ' | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' | tr -d '‘' | sed 's .\{2\}  '
</script-var>
```

It's only this script-var as well, i get the error even if i don't {{refrence}} it anywhere. The script worked yesterday (At the time of writing.) I have a similar script var that looks *almost* identical other than it `awk's` another line. (Basically changes the `awk '{if (NR&gt;5) if (NR&lt;7) print}'` to `awk '{if (NR&gt;4) if (NR&lt;6) print}'`)

If i run the same command in a terminal it works just fine.

## Reproducing the issue
Add 
```xml
<script-var name="radius" interval="500s">
  curl wttr.in/stocka | awk '{if (NR&gt;5) if (NR&lt;7) print}' | tr -d [:blank:\] | sed 's .\{55\}  ' | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' | tr -d '‘' | sed 's .\{2\}  '
</script-var>
```
to `<variables>`

## Expected behaviour
Run the script and show what's it's supposed to show.

## Additional context

It gives the error, but continues on starting eww, but no eww window shows, says it's running in htop and i can kill it will `pkill eww`

![image](https://user-images.githubusercontent.com/68186933/97180765-c3a98000-179a-11eb-95f7-85f81384c83a.png)

**Comment by undefinedDarkness** [comment]
The command doesnt run for me :confused:

**Comment by elkowar** [comment]
@Swexti does this still happen, actually?

**Comment by undefinedDarkness** [comment]
Ive had rust's string.truncate have some weird utf8 issues at times, probably not it but maybe it's being used somewhere?

**Comment by elkowar** [comment]
Dont think thats used anywhere, and dont think thats the issue here. Has this bug even occurred again recently?

**Comment by elkowar** [comment]
closing this, as I haven't gotten any reports of this in ages. If you do encounter this again, feel free to reopen!
