### ISSUE TITLE
[BUG] Sliders when used with music player don't perform well

### ISSUE THREAD

**Issue by Syndrizzle** [elkowar/eww#482]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

So apparently I was making a slider for controlling spotify via dbus. What eww does it even tho we are not changing the track position, there is a slight lag at every second, this arises due to eww executing the `:onchange` at every second. This is not a bug from dbus side as it does the same for mpd, and awesomewm seems to do it perfectly fine.
Look at the video below, notice how sound works without any lag when eww is not opened. And changing the value of the position poll makes it do it at the specified time intervals.

https://user-images.githubusercontent.com/96112833/174568337-333007f5-a970-45bd-8ce5-9030070ffde3.mp4

### Reproducing the issue

You can use the below code to create a sample eww window with the player (requires spotify and playerctl):
```lisp
(defpoll length :interval "0s" "dbus-send --dest=org.mpris.MediaPlayer2.spotify --print-reply /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | grep uint | awk '{print $3}'")
(defpoll position :interval "1s" "dbus-send --dest=org.mpris.MediaPlayer2.spotify --print-reply /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Position | awk 'FNR==2 {print $3}'")
(defpoll trackid :interval "1s" "playerctl -p spotify metadata mpris:trackid")

(defwidget player[]
 (scale :orientation "h" :class "music-slider" :space-evenly "false" :min 0 :max length :value position :onchange "dbus-send --type=method_call --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.SetPosition objpath:${trackid} int64:{}"))

(defwindow main
  :windowtype "normal"
  :wm-ignore true
  :monitor 0
  :geometry (geometry :anchor "center" :height 400 :width 800)
  (player))
```

### Expected behaviour

The slider should not invoke the `:onchange` value even when eww is open.

**Comment by Syndrizzle** [comment]
Can you share the code for that hover thing? because I tried that but all it does for me is play the track again from beginning :(

**Comment by viandoxdev** [comment]
IIRC smth like that :
```clojure
(defvar hover false)
(defpoll value `[poll command]`)
; ...
(event-box :onhover "eww update hover=true" :onhoverlost "eww update hover=false"
  (scale :value {value} :onchange { hover ? "[update command]" : "" }))

```

**Comment by Syndrizzle** [comment]
okay, thanks <3 ill try this as a workaround

**Comment by Kibouo** [comment]
The given work-around will still result in glitchy sound when hovering so I used a different approach. 

The `onchange` action uses a wrapper script to seek. In this script, I take the difference between the current progress and the requested one, and only perform the actual seek if the difference is above a certain threshold. Determine this threshold experimentally by checking the automatic requests by eww's `onchange`. Somewhere between 5-10sec works in my setup.
