### ISSUE TITLE
[BUG] Image doesn't display with polling variable. 

### ISSUE THREAD

**Issue by FlareStormGaming** [elkowar/eww#483]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When adding an image widget to my bar linked to playerctl's mpris:artUrl field, it doesn't show anything. 
Do note that I have verified the command works by both running it in terminal. Also when actually putting the variable as a text variable (as I did above the image widget) it works as expected. Paths are in the format `/home/zlare/.mozilla/firefox/firefox-mpris/27669_79.pg` where the number at the end seems to be relatively random. 

### Reproducing the issue

```
(defpoll SONG_ART
    :interval "1s"
    :initial ""
    `playerctl metadata mpris:artUrl | awk '{split($0,a,"//"); print a[2]}'`
)
(defwidget music []
    (box
        :class "musicBox left"
        :orientation "h"
        :halign "start"
        SONG_ART_URL
        (image
            :class "musicLabel albumArt"
            :path SONG_ART
            :image-height "50px"
            :image-width "50px"
        )
    )
)
```

### Expected behaviour

I expected EWW to display the image in a 50x50 square. If it wasn't a square, I don't know whether eww would stretch it or not, and I don't really care (though not stretching would be nice), but I would have expected it to display everything. 

### Additional context

![image](https://user-images.githubusercontent.com/70780971/174891721-cadab5ac-32fc-4a67-a8b9-3e96915211b3.png)
By setting a background color to the image widget through a SCSS class, you can see that the image widget is indeed there, and has width. It just doesn't show the image. 
![image](https://user-images.githubusercontent.com/70780971/174891878-061c3d15-5d7f-492e-bf6a-ee23cfa02409.png)

**Comment by elkowar** [comment]
The inconsistencies in the API definitely need some improvement, yea. I'll close this issue tho ^^
