### ISSUE TITLE
[FEATURE] Pass web URL for image path

### ISSUE THREAD

**Issue by FlareStormGaming** [elkowar/eww#487]
### Description of the requested feature

Allow the passing of an `http://` or `https://` url to fetch the image being shown in the widget from, similar to how in HTML lets you with the src tag. 
This could be useful for example when trying to show an image which is hosted on a server and queried from a database, like if I were to write something that would get the album art for a song by querying the internet. Right now, this script would have to download the image and then return a path for the EWW widget to show it, which is inefficient (even if it does just go in /tmp and gets deleted at next restart) for space and for responsiveness. 

### Proposed configuration syntax

```yuck
(defwidget urlImage [path]
    (image
        :path path
        :image-width 100
        :image-height 100
    )
)
```

**Comment by elkowar** [comment]
This would be somewhat annoying to implement, and there's an easy workaround: You can use the css `background-image` property on sth like a box instead of the image widget, which _does_ support using URLs.

**Comment by FlareStormGaming** [comment]
Interesting...
My particular use-case needs to be more dynamic than that, though, as I'm getting the album art for the currently playing song. It's linked to a dynamic variable that I parse from playerctl to a URL using a python script.

**Comment by elkowar** [comment]
you should be able to use `:style 'background-image: url("${image-url}")'` on your box to dynamically change the image
