### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by rufevean** [elkowar/eww#489]
i tgave all the perms to the files and even did chmod +x /eww and chmod +x ./eww , still when am tryna run it , its just showing permission denied

**Comment by viandoxdev** [comment]
could you provide a little more info ? Like logs and precision on how you built eww

**Comment by viandoxdev** [comment]
> try using sudo
> 

Eww isn't a program that needs root privilege and shouldn't be run as root (although I don't think it would cause problems, it's bad practice to just sudo on every permission denied you get)

**Comment by elkowar** [comment]
I'll close this, as it's most definitely an issue related to how they built, and they're not providing more info that would suggest otherweise

**Comment by webbb82** [comment]
I have this same issue

**Comment by EverWinter23** [comment]
In my case, I was had included the directory eww inside my `bin` folder. Placing `eww` executable directly inside the `bin` folder, resolved my issue.
