### ISSUE TITLE
[BUG] Tooltips not showing up (wayland)

### ISSUE THREAD

**Issue by notusknot** [elkowar/eww#495]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Simply put, my tooltips aren't showing up. When I hover over a widget that has a `tooltip` set, nothing happens. There are no errors in the logs, and nothing else indicating as to why this could be happening. It could be a Wayland issue, but I doubt it since clicking on buttons in the bar does what it is supposed to do; the only thing not working is tooltips. Using eww version 0.3.0.

### Reproducing the issue

Install my dotfiles at `https://github.com/notusknot/dotfiles-nix` (eww config found in `modules/eww`)
Run `eww open bar`

### Expected behaviour

Hovering over items such as the time, wifi, cpu, disk, and memory widgets should have a tooltip, but doesn't.

**Comment by Pebor** [comment]
This *was* a Hyprland issue, fixed in https://github.com/hyprwm/Hyprland/commit/ee15ad12154fc5c33e725a0f46d72bdef5945906.
