### ISSUE TITLE
[BUG] Padding for whole widget no longer works

### ISSUE THREAD

**Issue by siduck** [elkowar/eww#497]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Before I was able to set the padding to ".eww" selector but now it doesnt work at all

made the whole widget blue for better viewability of the bug

![image](https://user-images.githubusercontent.com/59060246/177678056-57e58a56-27a3-403d-87fb-47f6e0eacddc.png)

### Reproducing the issue

```css
.eww {
  padding: 1rem;
}
```

### Expected behaviour

Padding to work like before, example 

![image](https://user-images.githubusercontent.com/59060246/177678237-1e12cf1f-a037-4eee-80e9-41384dd84367.png)

**Comment by siduck** [comment]
@elkowar  D:

**Comment by viandoxdev** [comment]
Isn't that because the windows now have their name as class ? might be wrong but it should be somewhere in the  changelog for 0.3

**Comment by elkowar** [comment]
Hmm, this is interesting. the change makes it such that the css class is applied to the actual window, rather than the root widget -- as adding it to the root widget did not seem to consistently work. I'm not sure why the padding here doesn't work...
what _should_ then work is just doing
```css
.eww > * {
  padding: 1rem;
}
```
(not 100% sure, depends on how GTK widget hierarchy looks here)

**Comment by siduck** [comment]
@elkowar thanks a lot that worked

**Comment by notthewave** [comment]
Same seems to be true for shadows, but the workaround above does not work for them.
To be more specific: they are cut off at the window border (visible with rounded corners)
