### ISSUE TITLE
[FEATURE] Automatically align the whole widget to specified place

### ISSUE THREAD

**Issue by Swexti** [elkowar/eww#50]
## Description of the requested feature
Just like the title says, i want something that sets position of the widget, just like you can do with `halign`, and `valign`. Something like `<pos x="center" y="center">` or `<pos x="left" y="center">` instead of manually aligning it yourself.

## Proposed configuration syntax
As stated above, manually aligning the widget is annoying as frick and i want something simpler. Since now you have to do tons of math or measure by eye - which doesn't always work. Simply to align a widget. And if i change the size of it a bit i have to re-position it again.

# Additional context
nope.

**Comment by elkowar** [comment]
By widget do you mean window?

**Comment by elkowar** [comment]
I don't think that alignment logic that works across multiple windows is viable at the moment, although a "center" flag might very well be doable.
For a replacement for window alignment, have you considered using only a single window with a transparent background, and then using the normal layout `<box>` system to position the elements, making it _look_ like it's separate windows?

**Comment by Swexti** [comment]
> For a replacement for window alignment, have you considered using only a single window with a transparent background, and then using the normal layout `<box>` system to position the elements, making it _look_ like it's separate windows?

That's what i did for the latest widget i did. But i had already aligned the elements off-center. And since i wanted the window in the middle if would have to re-align it, which would take some time.

> I don't think that alignment logic that works across multiple windows is viable at the moment

I get that but just being able to align a single window that way would be nice.

**Comment by elkowar** [comment]
so do you just mean a "center" option? or what kind of flexibility would you want there

**Comment by Swexti** [comment]
Yes a "center" option would be nice. Extra pog would be the option of `left`, `right`, `up`, and `down` or something like that. ofc you would still be able to align the window manually.

**Comment by elkowar** [comment]
I'll look into that. Thanks for the request!

**Comment by elkowar** [comment]
```xml
<window name="foo">
  <pos anchor="bottom right" offset-x="12px" offset-y="50%"/>
</window>
```

**Comment by Swexti** [comment]
beautiful
