### ISSUE TITLE
[BUG] Buttons in overlays are not clickable

### ISSUE THREAD

**Issue by DiedByDisgust** [elkowar/eww#503]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When an overlay widget is set as a button content, it can not be clicked.

### Reproducing the issue

An overlay as content
`(button :onclick "notify-send 'something'" (overlay (label :text " " :style "color: #000000" )"1"))`
then try to click the button.

### Expected behaviour

it suppose to be be clickable like any of the following examples.

a box as contet:
`(button :onclick "notify-send 'something'" (box (label :text " " :style "color: #000000") "-" "1"))`

a label as content:
`(button :onclick "notify-send 'something'" (label :text " " :style "color: #000000"))`

**Comment by viandoxdev** [comment]
This is probably due to the overlay widget literally being over the button. This could be fixed with `overlay.set_overlay_passthrough`, idk if that should be the default behavior tho.

**Comment by DiedByDisgust** [comment]
> This could be fixed with `overlay.set_overlay_passthrough`

Thanks for the answer, where do i put this line?

**Comment by viandoxdev** [comment]
in `crates/eww/src/widgets/widget_definitions.rs`, in `build_gtk_overlay` (after the `gtk_widget.add_overlay(...)`)
```diff
for child in children {
    let child = child?;
    gtk_widget.add_overlay(&child);
+   gtk_widget.set_overlay_passthrough(&child, true);
    child.show();
}
```
