### ISSUE TITLE
[FEATURE] Make variable changes propagate to widgets they're passed to

### ISSUE THREAD

**Issue by lapraswastaken** [elkowar/eww#504]
### Description of the requested feature

When you pass a widget defined with `defwidget` an argument, if you use a defined variable (with `defvar`, etc.), it uses the current value of that variable. I think it would be useful to make it pass the variable into the widget so that, when the variable is updated, the widget updates as well.

For my current use case, as an example, I'm using multiple windows that each have a copy of one widget in them, and I'd like each of those windows to pass their widgets a json string that will be updated with an outside script.

Here's my current use case. 
```yuck

; This is the only widget I'm defining. Each of the below windows uses it.
(defwidget tabbar [control] ; Control is the argument that I'd like to pass a variable, so that this widget updates when that variable sees changes.
    (box
        :orientation "horizontal"
        :space-evenly true
        (for linked in control
            (button
                :onclick "bspc node ${linked} --layer above"
                linked))))

(defvar control0 "[]") ; This variable is controlled by a Python script, a script which adds windows to the list.
; The Python script also spawns these windows dynamically (via eww open bar{n}).
(defwindow bar0
    :stacking "fg"
    :wm-ignore false
    :windowtype "toolbar"
    (tabbar :control control0)) ; Currently, this evaluates to "[]" and doesn't update once it's been evaluated.

(defvar control1 "[]")
(defwindow bar1
    :stacking "fg"
    :wm-ignore false
    :windowtype "toolbar"
    (tabbar :control control1))

(defvar control2 "[]")
(defwindow bar2
    :stacking "fg"
    :wm-ignore false
    :windowtype "toolbar"
    (tabbar :control control2))

; ...repeated an indefinite number of times (in my case 6).
```

I'm realizing that this could also be a feature added to eww windows themselves, since it doesn't seem like they update when a variable they're using is updated(?).

There are workarounds to this, and I'll be trying out a couple, but I think this would be a neat functionality.

**Comment by elkowar** [comment]
I'm confused, the variables should _very much_ update, otherwise there'd not be any way to have state changes at all 🤔

If changes actually don't propagate, can you send the output of `eww graph` and `eww debug` so I can analyze?

**Comment by lapraswastaken** [comment]
```
digraph {
  "ScopeIndex(8)"[label="bar0\ndata: [], listeners: []"]
  "ScopeIndex(5)" -> "ScopeIndex(8)"[label="ancestor"]
  "ScopeIndex(5)"[label="global\ndata: [('control5', '[]'), ('control0', ''[23068675]''), ('control3', '[]'), ('control2', '[]'), ('control', ''), ('control4', '[]')], listeners: []"]
  "ScopeIndex(9)"[label="tabbar\ndata: [('control', ''[23068675]'')], listeners: ['on control: [\'[\\\'control\\\']\']']"]
  "ScopeIndex(8)" -> "ScopeIndex(9)"[label="ancestor"]
  "ScopeIndex(8)" -> "ScopeIndex(9)" [color = "red", label = ":control `control0`"]
  "ScopeIndex(8)" -> "ScopeIndex(5)" [color = "blue", label = "inherits({'control0'})"]
  "ScopeIndex(9)" -> "ScopeIndex(5)" [color = "blue", label = "inherits({})"]
}
```

It seems like the bar window itself isn't set to listen to anything.

Here's a part of the python script that's doing the `eww update`, since that might be relevant if EWW is supposed to make what I want to happen work but isn't.

```python
@dataclass
class TabBar:
    id: int
    tabs: list[int] = field(default_factory=list)

    def addTab(self, tabID: int):
        # The `tabID` is the ID of a window that's meant to be displayed
        #  by the window manager when its button is clicked.
        if tabID in self.tabs: return # We don't want to do anything if
                                      #  the window already has a tab on
                                      #  the bar.
        self.tabs.append(tabID)

        # `json.dumps` converts `self.tabs` into a string of json. String
        #  interpolation, in Python f-strings, happens in-between the
        #  curly brackets.
        args = f"update control{self.id}=\"{json.dumps(self.tabs)}\""
        # The hope is that this command makes the `for linked in control`
        #  update in the yuck file, which makes buttons (tabs) in the bar
        #  that correspond to each of the windows that have their IDs set
        #  in this object's `self.tabs`.

        # When a tab is added to an empty `TabBar`, this prints:
        #     update control0="[23068675]"
        #  with the number in the "" string replaced by whichever window
        #  ID is meant to be focused when its tab button is clicked.
        print(args)
        eww(args) # Helper function to run `eww` with the given args.
```

There's a good bit more to this script, but this should be the most relevant part. I'll post more if needed.

**Comment by viandoxdev** [comment]
Isn't the problem that eww seems to receive control0 with extra quotes? Eww debug shows `control0: ""[...]""`

**Comment by lapraswastaken** [comment]
@viandoxdev It looks like it!

I wasn't certain on whether or not `eww update` required its parameter to be quoted. Python's `json.dumps` defaults to adding spaces in between elements, which made me think that in order to capture those spaces correctly, the parameter should be quoted. Luckily there's a way to make `json.dumps` compact by using the `separators=(",", ":")` keyword argument. I've removed the unnecessary quotes and it looks like it's working as it should. Thank you both for the help.

**Comment by lapraswastaken** [comment]
I thought I remembered testing both ways, but I believe I had other unfixed issues when I did the testing and neither way worked, so I continued to be unsure of which was correct.
