### ISSUE TITLE
[BUG] Anchors to "bottom" "right" revert to center

### ISSUE THREAD

**Issue by TheEgghead27** [elkowar/eww#508]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When trying to make a window with `x` and `y` padding `anchor`ed to the `bottom` and/or `right`, the window appears to be centered on that axis, rather than being aligned to the edge as expected. The `top` and `left` arguments work as expected.

### Reproducing the issue

All that is needed is for a window to have an anchor specification containing either `bottom` or `right`, along with non-zero values set for `x` and `y`.
If `x` and `y` are set to `0px`, the anchoring works as expected.

Example config:
```
(defwindow test
           :monitor 0
           :geometry (geometry :x "1px"
                               :y "1px"
                               :anchor "bottom right")
           :stacking "fg"
           :windowtype "dialog"
           :wm-ignore false
        "test"

)
```

### Expected behaviour

The padding should offset from the specified edge, rather than the center.

**Comment by viandoxdev** [comment]
Can't reproduce on sway with last commit, but tbh I don't exactly understand what you're saying, wdym by "offset from the center rather than the edges". What WM/DE are you using ? wayland or x11 ?

**Comment by TheEgghead27** [comment]
I'm on dwm (X11), and the issue is that a widget set to "bottom right" (with some `x`/`y` value set) ends up in the center like so.
![image](https://user-images.githubusercontent.com/45245358/181861334-e4044c68-abb3-4a26-9442-ae3ef4fdad31.png)

**Comment by TheEgghead27** [comment]
Nevermind, I see the issue: I was supposed to set the `x` and `y` value to be negative.
