### ISSUE TITLE
[BUG] Horizontal bar is vertically stretched after commit 77adfbc

### ISSUE THREAD

**Issue by Animeshz** [elkowar/eww#512]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Right after the commit 77adfbca6b3ece5b4872138d48c90d738d2afa90 The bar seems to be vertically stretched

### Reproducing the issue

Any commit latter the specified seems to have this bug.

And a small repro is just a box with a string:

eww.yuck
```lisp
(defwindow topbar
  :monitor 0 :stacking "fg" :wm-ignore false :windowtype "dock"
  :reserve (struts :side "top" :distance "32px")
  :geometry (geometry :x "0" :y "0" :width "100%" :height "30px" :anchor "top center")
  (box "hi"))
```

eww.scss
```scss
* {
  all: unset;
  font-family: "Material Design Icons", "CaskaydiaCove Nerd Font";
}

.topbar {
  font-size: 16px;
}
```

### Expected behaviour

Expected:
![05-08-22-08h46m18s](https://user-images.githubusercontent.com/26714676/182994184-821c4e97-60ca-4204-bb42-12b03f589828.jpg)

Actual after that commit:
![05-08-22-08h47m28s](https://user-images.githubusercontent.com/26714676/182994189-055ca55e-8470-4f60-9b3e-0672fadb660b.jpg)

**Comment by elkowar** [comment]
My assumption is that your font-size field doesn't apply anymore now, try `.topbar > *` or sth -- that change was more breaking than I thought 👀

**Comment by elkowar** [comment]
I'll close this for now, as I assume no response means that worked ^^ If there's some bug here I'm missing, feel free to reopen

**Comment by Animeshz** [comment]
Hello! I forgot about this for a long time keeping my build at old commit, recently when packaging for void I noticed it is still misbehaving with my config, and `.topbar > *` isn't working either.

However if I put everything in a literal, like so:
```
(defwindow topbar ...
  (literal :content '(centerbox :orientation "h"
    (barleft) (barmiddle) (barright))'))
```

all the widgets inside *mostly* renders to their correct height:

![23-04-14-01h59m51s](https://user-images.githubusercontent.com/26714676/231876117-22c79639-6baa-4293-8dc1-437d728ca188.jpg)

except the fact that the vertical height of the whole *encapsulating window* is still exceeding the given window size. Idk what literal has to do here in the style_context, I'll investigate further and report back.

This is not fixed, sorry for being inactive for months :sweat_smile:.

**Comment by gandalf3** [comment]
I'm also experiencing this, but the minimal example actually does work for me.

I'm guessing it may be related to the font family; on my machine I don't have either of the specified fonts, and `fc-match` resolves them both to `Noto Sans`.

The height of the topbar window only shrinks down to 21px tall with Noto Sans, even with the font size set to `0px`, no matter how small i make the window's height in yuck.

As an experiment, I changed the font family to Fira Code, and then with the height of the topbar window shrinks down to 19px tall, but again no further.

**Comment by gandalf3** [comment]
Using a `.background` rule like this works; the window is no longer stretched unnecessarily:
```
* {
  all: unset;
}
.background {
  font-family: "Fira Code";
  font-size: 7pt;
}
```
(if it doesn't appear to work at first, try fully restarting the eww daemon)

I don't understand why this is necessary though. Looking at the inspector, "topbar" and "background" are both classes on the same element, and a `.topbar` rule like this *does* set the font size on the window (and every child widget), just as `.background` does:

```
* {
  all: unset;
}

.topbar {
  font-family: "Fira Code";
  font-size: 7pt;
}
```

...yet the window is still stretched vertically. It feels as though there's a default font size on some hidden higher-level widget which is forcing it to request more space, which the `.background` rule somehow catches.
