### ISSUE TITLE
[BUG] unpredictable `monitor` values

### ISSUE THREAD

**Issue by xxxserxxx** [elkowar/eww#516]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When monitors are dynamically added (as in, docking events), the `monitor` references can change to which monitor they refer. In particular, even when the WM (e.g. bspwm) and X think the monitors are the same configuration, it's a coin toss as to which monitor eww will think is `1`, and which is `2`. This results in bars sometimes swapping monitors on which they appear between dock events.

Of note is that monitor `0` on a laptop (the integrated screen) is always assigned the integrated monitor.

### Reproducing the issue

1. Have a laptop and two external monitors connected to a dock
2. Configure 3 different bars (`bar0`, `bar1`, `bar2`), one on each monitor (laptop gets `:monitor 0`, the others get `:monitor 1` and `:monitor 2`)
3. `eww daemon`
4. `eww open-many bar0 bar1 bar2`
5. Undock the laptop
6. Close the bars, (`eww close-all`)
7. Open one just for the laptop (`eww open bar0`) -- this and step 9 can probably be omitted
8. Dock the laptop
9. Close the one bar (`eww close bar0`)
10. Re-open the bars: `eww open-many bar0 bar1 bar2`

### Expected behaviour

When the WM (bspwm) and X consistently identify the monitors and monitor geometry, eww should also always assign monitors the same identifiers. 

### Additional context

When I dock my laptop, X invariably assigns the left monitor the name `DP2-2` and the right `DP2-1`. bspwm uses the X monitor names, and therefore scripts to put desktops on monitors can consistently lay out workspaces.

A wild guess is that the eww `:monitor` identifiers are simply array indexes, and that the array is built in an order that is not consistent, probably as a result of some underlying system returning an unordered monitor list -- that is, in eww, monitor ordinality is not preserved between monitor connection events. 

A fix would be to use display identifiers instead of indexes. Another fix would be to sort the indexes by display name so that the order is consistent. A third would be to use monitor edid ([eds](https://github.com/compnerd/eds) has some sample code), but edids can be troublesome for a number of reasons.

My preferred solution would be to use display names; X is pretty consistent with assigning consistent display names, and it's a common way to refer to monitors in X programs: `xrandr`, `bspc -M -m --names`, `i3-msg -t get-outputs`, etc. all return the X identifier names, and those names are commonly used in configuring window managers and other X tools.

**Comment by danielphan2003** [comment]
+1 on this. I think eww should also be able to get Wayland outputs as well.

**Comment by xxxserxxx** [comment]
#522 confirmed working, under X, in any case.

**Comment by theRealCarneiro** [comment]
This issue should be reopened since it's still a problem in wayland, and it probably wont get much attention since it's closed.

**Comment by viandoxdev** [comment]
> This issue should be reopened since it's still a problem in wayland, and it probably wont get much attention since it's closed. I have a really bad monitor that randomly powers off (and it's still better than my other 2), causing the ids to be completely unreliable.

There already has been some attempts at fixing this (#522) but wayland doesn't make this easy. I'll look if things have changed but I don't think so. The best you could get is probably a patch that only works on recent versions of GTK.
