### ISSUE TITLE
[FEATURE]  Add dynamically loaded widgets

### ISSUE THREAD

**Issue by Saul-Dickson** [elkowar/eww#517]
### Description of the requested feature

As the title says, this feature would add dynamically loaded widgets. Essentially, this would allow a given config to flip a variable to true and another widget would appear in the window; similarly to the behavior of the gnome bar. 

In gnome, when an additional feature is in use like location services or bluetooth, a new icon appears in the system tray(?). For examle:

Location services off:
![Screenshot from 2022-08-06 03-52-27](https://user-images.githubusercontent.com/58606766/183242151-1c0a8bd7-f8be-4893-99c9-67a375940325.png)

Location services on:
![Screenshot from 2022-08-06 03-53-55](https://user-images.githubusercontent.com/58606766/183242180-17d1aa56-e1ac-4304-ade1-445fcc74fa20.png)

The use case of this feature is fairly straightforward; to enable a widget that may not always be in use through some automated process. From only showing the status of bluetooth and location services, to embeding notifications into the bar, this could allow for a lot more flexability in creating highly customized eww applications.

### Proposed configuration syntax

Implementing this feature in eww configs could be as simple as using the preexisting conditionals that are already in yuck.

```
;; Render bar
(defwindow bar
  :monitor 0
  :geometry (geometry
              :x "0%"
              :y "40px"
              :width "100%"
              :height "35px"
              :anchor "top center"
            )
  :stacking "fg"
  :reserve (struts :distance "20px" :side "top")
  :windowtype "dock"
  :wm-ignore false
  (bar-content)
)

(defvar example-widget-visible false)

(defwidget example []
  (box
    :class "example-box"

    "example-content"
  )
)

(defwidget bar-content []
  (box
    (box
      :halign "end"
      :spacing 2
      :space-evenly false

      ; CONFIG EXAMPLE BEGINS HERE
      {example-widget-visible ? (example) : "" }
    )
  )
)
```

Simply flipping `example-widget-visible` to true using `eww ... update example-widget-visible=true` would load the widget.

**Comment by snakedye** [comment]
[visible: bool visibility of the widget](https://elkowar.github.io/eww/widgets.html)

**Comment by viandoxdev** [comment]
Also [revealer](https://elkowar.github.io/eww/widgets.html#revealer), [literal](https://elkowar.github.io/eww/configuration.html#dynamically-generated-widgets-with-literal) and css with `opacity: 0` if you want to keep the space the widget takes.

**Comment by Saul-Dickson** [comment]
Goddamnit.
