### ISSUE TITLE
[FEATURE] Lazy variable evaluation

### ISSUE THREAD

**Issue by alx365** [elkowar/eww#52]
## Description of the requested feature
Script-variables should only be executed if they are used in any window that is _open_.

**Comment by elkowar** [comment]
Thanks for the detailed description...

**Comment by elkowar** [comment]
Updated the description and title to make sense

**Comment by alx365** [comment]
well as long as i didn't have to do it. i'm lazy

**Comment by elkowar** [comment]
Implemented in #58
