### ISSUE TITLE
[FEATURE] is it possible to hide the dock or lock the dock in 1 workspace (i3 if specific)

### ISSUE THREAD

**Issue by porudev** [elkowar/eww#524]
### Description of the requested feature

i wanted to either hide the dock type window or just lock it in 1 workspace, im currently using i3-gaps

### Proposed configuration syntax

bind-workspace true
workspace-to-bind $ws1
bind Super+H hide-dock-type-window

### Additional context

at the moment the dock follow me all around, and it overlaps other window and it kinda annoying
here is an example

![image](https://user-images.githubusercontent.com/81072838/184398602-a85037a7-4fcc-4095-877d-7e3c17cae7ff.png)

**Comment by VuiMuich** [comment]
You can toggle a window with `eww open --toggle window-name`
In i3 you have rules to stick a window to a workspace iirc, but it cannot be of type `Dock`. Why would you want this window have this type anyways?

**Comment by porudev** [comment]
> You can toggle a window with `eww open --toggle window-name` In i3 you have rules to stick a window to a workspace iirc, but it cannot be of type `Dock`. Why would you want this window have this type anyways?

Thank you, i have tried changing the window type to normal and the thing still follow me around :( and behave the same way as a dock, except the fact that it can be dragged around via floating modifier

**Comment by elkowar** [comment]
Eww doesn't have a specific feature to restrict itself to specific workspaces, no. Using whatever your WM provides for this is the way to go ^^

**Comment by VuiMuich** [comment]
> > You can toggle a window with `eww open --toggle window-name` In i3 you have rules to stick a window to a workspace iirc, but it cannot be of type `Dock`. Why would you want this window have this type anyways?
> 
> Thank you, i have tried changing the window type to normal and the thing still follow me around :( and behave the same way as a dock, except the fact that it can be dragged around via floating modifier. Do you know any workaround for this?

Not really, sorry. I haven't been using i3 in quite some time, so besides the memory of some rules that exist to spawn windows on a specified workspace I don't have any thing. Maybe there is a way to pin or sticky a window to its workspace...
