### ISSUE TITLE
[PROJECT] Donations, support

### ISSUE THREAD

**Issue by Pebor** [elkowar/eww#526]
Hello!
Eww is an excellent project and a project I've been very excited about.
It can be seen on r/unixporn almost daily now and it finally brings some eye candy with animations, easy styling support and ease of use to bars and other parts of the linux desktop.
It cannot be denied, making this project better can only make the desktop experience better. _Offering quality widgets to people not using big DEs._
With this, I was surprised to not find any donation links.
I would love to be a supporter of this project, and I hope more people would be too.
I am no magic millionaire, but I would like to contribute at least a few bucks!

Would it be possible to create a Ko-fi page, open Github sponsors or be open to donations (one-time/repeating) in any way?

**Comment by elkowar** [comment]
Thanks a lot for the praise!
I've been meaning to set up some donation thing for a while, you've motived me to actually finally do it! Now I'm just waiting for getting my github sponsors thing approved ^^
