### ISSUE TITLE
[BUG] Example not working under wayland ("Failed to get x11 window for gtk window").)

### ISSUE THREAD

**Issue by Soliprem** [elkowar/eww#527]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I used the example given in the docs, with nothing added. I tried removing each module, but there was no difference. Tried both with the wayland version present on the AUR and by manually building with the correct flags. In both cases there were no build errors. Follows the full error message:
```
failed to open window 'example'
 
Caused by:
        Failed to get x11 window for gtk window
```

The only steps I tried to troubleshoot have been reinstalling, making sure the flags were correct, and tinkering with the config (for example taking someone else's wayland config). Got the same error message:
```
failed to open window 'bar'

Cause by:
        Failed to get x11 window for gtk window
```
Any help would be appreciated :)

### Reproducing the issue

Simply followed the installation steps

### Expected behaviour

widgets/windows should launch

### Additional context

![image](https://user-images.githubusercontent.com/73885403/185102983-3de46c44-acc7-4fc5-91fc-4e6d086fd9b6.png)

**Comment by IllustratedMan-code** [comment]
Did you make sure to compile with the correct flags? If you are on Arch then https://aur.archlinux.org/packages/eww-wayland-git this might be your  best bet. On NixOS I had to install the `eww-wayland` package to stop getting this error.

**Comment by Soliprem** [comment]
That's the package I have currently installed (I run arch, btw). No luck :/

**Comment by elkowar** [comment]
On Wayland, you'll need to explicitly specify the monitor the window should be on, see the docs for how to do so.

**Comment by elkowar** [comment]
The only place where that error message may occur is in code that is only compiled when you're using X11 -- that error message _can't_ happen when you're compiling eww for wayland

**Comment by Soliprem** [comment]
I changed nothing from when I reported this, and now it... magically works? Not sure what happened

**Comment by ttmx** [comment]
I have the same issue, on eww-wayland, with the example bar.
![20221004_00h56m48s_grim](https://user-images.githubusercontent.com/12669467/193706242-e1cdfa90-013c-4029-a7ed-b24214257d22.png)

Am I doing something wrong?
Apologies if I'm wasting time, but I have been at this for a few hours now, and am completely new to eww.

**Comment by ttmx** [comment]
Welp, started working after doing nothing as well. Very weird.
Thanks!

**Comment by viandoxdev** [comment]
If you initially built eww for x11, started the daemon (through eww open for example), then built the wayland version, calling eww will still communicate to the original eww daemon (the x11 one) unless it is shutdown or the config path is changed (starts another daemon). So this could be the reason

**Comment by EysseW** [comment]
I have the very same issue. Tried to kill the daemon and start it back up again, tried to change the display to 0,1,2 and every monitor name of my 3 monitors. Also tried to reboot. Nothing worked. Any idea what's up?

**Comment by nmattela** [comment]
I had a similar issue (eww was starting in XWayland) and it turns out that I was running `eww open` in a terminal inside VSCode (which runs on XWayland). Opening a terminal outside VScode and running `eww open` there made it work.
