### ISSUE TITLE
[FEATURE] local variables

### ISSUE THREAD

**Issue by IllustratedMan-code** [elkowar/eww#528]
### Description of the requested feature

It would vastly improve ease of use if variables could be defined within a local context. This almost exists already in the form of arguments.

```
(defwidget [local] (button local))
```

 However, these "local" variables are hobbled by the fact that they do not respect updates. For example,

```
(defpoll time :interval "1s"
              :initial "initial-value"  ; optional, defaults to poll at startup
              :run-while time-visible   ; optional, defaults to 'true'
  `date +%H:%M:%S`)

(defwidget  clock [local] (label :text local))

(defwindow :monitor 0 (clock :local time))
```
This would not update as time passed. It would be great if there was some way to pass the variables without losing the ability to update.

### Proposed configuration syntax

The syntax would be exactly the same if the old "pass by value" method is no longer used. 

If both types of local variables are desired, then I think an `*` would be a good identifier:

```
(defpoll time :interval "1s"
              :initial "initial-value"  ; optional, defaults to poll at startup
              :run-while time-visible   ; optional, defaults to 'true'
  `date +%H:%M:%S`)

; * indicates pass by reference (preserving updates)
(defwidget  clock [*local] (label :text local))

(defwindow :monitor 0 (clock :local time))
```

### Additional context

This feature would be very useful for multiple monitor setups, as (similar) literal widgets could be passed to different windows easily. This problem would be made even easier with the ability to have some sort of window template, but I see there are already issues for that.

**Comment by viandoxdev** [comment]
Duplicate of #324 no ?

**Comment by IllustratedMan-code** [comment]
You're right! I'll go ahead and close.
