### ISSUE TITLE
[FEATURE] Predefined variables for CPU/Memory usage, etc

### ISSUE THREAD

**Issue by caffeine01** [elkowar/eww#53]
**Description**
CPU and RAM usage variables for cpu and ram usage monitors.

**Configuration syntax**
In a box you could put like, `<cpu></cpu>` or something like that and then configuration and label formatting goes elsewhere

**Comment by elkowar** [comment]
If anything, these would be added as "magic variables". For that, we'll first need to implement the #52 lazy evaluation ticket, to avoid having code run unnecessarily.

**Comment by Swexti** [comment]
Wait why do we need to implement #52 first? Isn't the issue wanting Haskell in eww or something?

**Comment by elkowar** [comment]
yea, that issue was incredibly stupidly framed. I updated the description, now it should actually explain what it does ;D

**Comment by alx365** [comment]
it wasn't stupid.. i was lazy

**Comment by undefinedDarkness** [comment]
Well that issue is closed now but im not sure if this is a good idea maybe if its under a feature or something or as part of example eww widgets or smth

**Comment by elkowar** [comment]
@legendofmiracles has started working on this in https://github.com/legendofmiracles/eww/tree/predefined-variables

**Comment by legendofmiracles** [comment]
@elkowar this can be closed

**Comment by elkowar** [comment]
Implemented in #117
