### ISSUE TITLE
[BUG] Clicking on scale changes value by 1 

### ISSUE THREAD

**Issue by bekaertruben** [elkowar/eww#533]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Clicking on a scale widget with left mouse button increases or decreases its value by 1 instead of corresponding to where the user actually clicks.
Interestingly, the middle mouse button works as expected.

### Reproducing the issue

A sample bar that shows the behaviour:
```
;; =================== WIDGETS =====================
(defwidget brightness []
  (box :class "brightness-box" :orientation "h" :space-evenly "false"
    (label :class "brightness-icon" :text "")
    (scale :class "brightness-scale" :width 100 :value 50 :min 0 :max 101 :orientation "h" :onchange "notify-send b:{}%")
  )
)

(defwidget volume []
  (box :class "volume-box" :orientation "h" :space-evenly "false"
    (label :class "volume-icon" :text "墳")
    (scale :class "volume-scale" :width 100 :value 50 :min 0 :max 101 :orientation "h" :onchange "notify-send v:{}%")
  )
)

(defwidget bar []
  (box :orientation "h" :space-evenly "false"
    (volume)
    (brightness)
  )
)

;; =================== WINDOWS =====================

(defwindow panel
  :geometry (geometry :x "0%" :y "5px" :width "90%" :height "50px" :anchor "top center")
  :monitor 0
  :stacking "bg"
  :exclusive true
  (bar)
)
```
The notifications show that clicking on a scale increments/decrements the value by 1.

### Expected behaviour

Tapping on the scale should set the value of the scale corresponding to where you clicked.

### Additional context

This is happening on Manjaro, using [eww-wayland-git](https://aur.archlinux.org/packages/eww-wayland-git) from the AUR, in both X11 and Wayland sessions of Plasma, as well as Hyprland.

**Comment by bekaertruben** [comment]
It appears fault may actually be mine. In the scss stylesheet I had copied from elsewhere, it had
```
* {
  all: unset;
}
```
Commenting out ```all: unset``` shows the round slider button. It's kinda ugly, but it means this is likely expected behaviour.

**Comment by viandoxdev** [comment]
> It appears fault may actually be mine. In the scss stylesheet I had copied from elsewhere, it had
> ```
> * {
>   all: unset;
> }
> ```
> Commenting out ```all: unset``` shows the round slider button. It's kinda ugly, but it means this is likely expected behaviour.

`unset: all` completely disables the default GTK theme for sliders, making them take no size most of the time, if you want to style them you can look through the css nodes category of the GTK inspector (`eww inspector `) and style the sub element (contents, trough, highlight)

**Comment by bekaertruben** [comment]
> `unset: all` completely disables the default GTK theme for sliders, making them take no size most of the time, if you want to style them you can look through the css nodes category of the GTK inspector (`eww inspector `) and style the sub element (contents, trough, highlight)

Thanks, I've now figured out how to theme it as I want.
