### ISSUE TITLE
[BUG]  `graph` crashes daemon

### ISSUE THREAD

**Issue by danjenson** [elkowar/eww#540]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When I try to make a graph of download/upload speeds, everytime I hover, it kills my whole bar. Relevant part of config:
```
(defwindow network
  :monitor 0
  :geometry (geometry
      :x "-65px" 
			:y "-12px" 
			:height "100" 
			:width "375"
      :anchor "bottom right")
  (network))

(defwidget network []
  (box
    :class "network box"
    :orientation "vertical"
    :space-evenly true
    (graph
      :class "network"
      ; :value {EWW_NET['wlp82s0'].NET_DOWN}
      :value download
      :duration "10s"
      :thickness 2
      :line-style "miter"
      :max 5000
      :min 0)))
(defpoll download :interval "2s" "shuf -i 0-5000 -n 1")
```

At first I thought it might be the magic variable ` {EWW_NET['wlp82s0'].NET_DOWN}`, so I tested it with `shuf -i 0-5000 -n 1` and that failed too. It seems like the graph fails any time there is data feeding into it.

### Expected behaviour

We see a graph.

**Comment by viandoxdev** [comment]
I can reproduce, the error happens because of the `100.0` [here](https://github.com/elkowar/eww/blob/17d91f8a44293721d0d84bd4070002fe3b29edaf/crates/eww/src/widgets/graph.rs#L71) that caps the value to 100, the  thousands reported by EWW_NET are then out of range and gtk rs panics. Not sure why there is a max value tho.
Using an expression which caps at a hundred can be a workaround: `{EWW_NET.wlp82s0.NET_DOWN / 50 > 100 ? 100 : EWW_NET.wlp82s0.NET_DOWN / 50}` and removing the max seems to work somewhat.

Otherwise this simple patch
```diff
diff --git a/crates/eww/src/widgets/graph.rs b/crates/eww/src/widgets/graph.rs
index e37a79a..5a8e2dd 100644
--- a/crates/eww/src/widgets/graph.rs
+++ b/crates/eww/src/widgets/graph.rs
@@ -68,7 +68,7 @@ impl ObjectImpl for GraphPriv {
         use once_cell::sync::Lazy;
         static PROPERTIES: Lazy<Vec<glib::ParamSpec>> = Lazy::new(|| {
             vec![
-                glib::ParamSpecDouble::new("value", "Value", "The value", 0f64, 100f64, 0f64, glib::ParamFlags::READWRITE),
+                glib::ParamSpecDouble::new("value", "Value", "The value", 0f64, f64::MAX, 0f64, glib::ParamFlags::READWRITE),
                 glib::ParamSpecDouble::new(
                     "thickness",
                     "Thickness",
```
Seems to works, but I haven't really tested it too much

**Comment by danjenson** [comment]
Here is what I get 
![image](https://user-images.githubusercontent.com/4793438/187084812-0f8e5eae-6ba0-43d9-a850-7821b719b5da.png)
with 

```yuck
(defwidget wifi []
  (eventbox 
    :onhover "./neww 'eww-open network'"
    :onhoverlost "./neww 'eww-close all'"
    (box
      :orientation "vertical" 
      (button
        :onrightclick "./neww 'configure wifi'" 
        :class "wifi icon" wifi-icon))))
(defpoll wifi-icon :interval "1s" "./neww 'wifi icon'")
(defpoll wifi-name :interval "1s" "./neww 'wifi name'")

(defwindow network
  :monitor 0
  :geometry
  (geometry
    :x "-70px"
    :y "-175px" 
    :height "100" 
    :width "375"
    :anchor "bottom right")
  (network))

(defwidget network []
  (box
    :class "network box"
    :orientation "vertical"
    :space-evenly true
    (graph
      :class "network"
      ; TODO(danj): https://github.com/elkowar/eww/issues/540
      :value {EWW_NET['wlp82s0'].NET_DOWN * 0.000008} ; Mbps
      :duration "1m"
      :thickness 2
      :line-style "miter"
      :dynamic true
      :min 0)))
```
