### ISSUE TITLE
[FEATURE] Open multiple eww windows at once

### ISSUE THREAD

**Issue by Antikyth** [elkowar/eww#545]
### Description of the requested feature

This is a pretty minor feature, but I've found myself wanting the ability to open multiple eww windows at once when using the `eww open` command. I think it would be good if you could open multiple windows by using a syntax like the following:
```sh
eww open dock dock2 wmbar1
```
(Where `dock`, `dock2` and `wmbar1` are my eww windows)

While I don't know if these would be run asynchronously in a script (i.e., that the commands are sent as fast as possible, not waiting for each result), they definitely aren't when running directly from a terminal emulator normally. Since I have multiple monitors, I have a few eww windows I work on at once so that I can have bars on all monitors - it would be nice to be able to write a single command, not waiting for the previous one to finish (which takes around a second or so).

I don't believe this should cause any interference - flags and options can still be specified in the same way, and can be differentiated by the fact they start with `-`. The existing `eww open` syntax would remain unchanged; it simply allows for additional windows to be added at the end of the command.

### Proposed configuration syntax

I'm not sure if this is the correct area, but the command syntax would look like:
```
eww open [OPTION]... WINDOW...
```
Where `[OPTION]...` refers to an optional list of options/flags each prepended with `-`, and `WINDOW...` refers to a list of one or more windows.

**Comment by VuiMuich** [comment]
There is the `open-many` command, that comes with a note that it is intended to be included to the `open` command, but I have no idea if this is worked on by someone.
