### ISSUE TITLE
[BUG] `deflisten` only keeps last line while `defpoll` keeps all lines

### ISSUE THREAD

**Issue by danjenson** [elkowar/eww#546]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I have a widget that displays my todos in a nice table format:
![image](https://user-images.githubusercontent.com/4793438/187515077-c2464a14-5f24-40f6-b959-e8bdb0d6ab34.png)
Right now, I'm using `defpoll` to define the `todos` content: `(defpoll todos :interval "15s" "./neww todos")`

However, this content rarely changes, so I set up a simple script to simply update when there are changes to the file:
`todos.sh`
```bash
#!/bin/bash
nu --config ~/.config/eww/eww.nu -c todos
inotifywait -q -m -e close_write ~/todos.txt |
while read -r filename event; do
  nu --config ~/.config/eww/eww.nu -c todos
done
```
I tried to listen to this with `(deflisten todos "./todos.sh")`, but it only ever grabs the last line of output
![image](https://user-images.githubusercontent.com/4793438/187515644-16b184e7-3401-4116-b917-46a75f7ff661.png)

### Reproducing the issue

1. Print something with multiple lines
2. Record it with `defpoll`
3. Record it with `deflisten`

Notice that deflisten only takes the most recent line.

### Expected behaviour

`deflisten` would be able to capture all output since last change

**Comment by viandoxdev** [comment]
Not a bug, See the Listening variables paragraph of [the documentation](https://elkowar.github.io/eww/configuration.html#adding-dynamic-content). In your case I'd recommend making your script return a json array of todos instead and use a `for` special widget to render each line.

You could try substituting the newline character in the command for another (i.e by piping `tr '\n' '\f'`) and using the `replace` function, but [this line](https://github.com/elkowar/eww/blob/956f96fd76cff7af5bf7207f2e6deb24e5f8bf17/crates/simplexpr/src/eval.rs#L286) seems to make replacing with new lines impossible.

**Comment by danjenson** [comment]
It's hacky but it works! It might be nice to capture _all_ output since last change, instead of only the last line since the last change. It would be really useful for files you are watching with `inotify`. Nonetheless, grateful for the help!

**Comment by elkowar** [comment]
> It's hacky but it works! It might be nice to capture _all_ output since last change, instead of only the last line since the last change. It would be really useful for files you are watching with `inotify`. Nonetheless, grateful for the help!

How would eww know what the "last change" is? as in, how would eww differenciate between the program outputting 7 lines as one value and outputting 7 lines because 7 changes happened?

**Comment by xyangst** [comment]
> Not a bug, See the Listening variables paragraph of [the documentation](https://elkowar.github.io/eww/configuration.html#adding-dynamic-content). In your case I'd recommend making your script return a json array of todos instead and use a `for` special widget to render each line.
> 
> You could try substituting the newline character in the command for another (i.e by piping `tr '\n' '\f'`) and using the `replace` function, but [this line](https://github.com/elkowar/eww/blob/956f96fd76cff7af5bf7207f2e6deb24e5f8bf17/crates/simplexpr/src/eval.rs#L286) seems to make replacing with new lines impossible.
> 
> Edit: using the replace trick seems to work, you just need a character you're sure won't be returned by the command:
> 
> * add `| tr '\\n' ' '` to the end of your command in the deflisten (the character in the second quotes isn't a space but [this](https://www.compart.com/en/unicode/U+2000))
> * instead of using  `{variable_name}` use:
> 
> ```clojure
> ;           use special character here v
> (whatever ... {replace(variable_name, " ", "
> ")} ... ) ; the new line is intended
> ```

how could i use such a for loop widget over json? any example? the docs dont have anything like that..
