### ISSUE TITLE
[BUG] Weird glyphs/symbols on EWW boxes

### ISSUE THREAD

**Issue by RochaLAJ** [elkowar/eww#550]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm trying to use archnews to parse and display news about arch linux with the following command:
`archnews -b -n 5 | cat - | sed -n '2,3p; 6,7p; 10,11p; 14,15p; 18,19p'` (using sed -n to skip lines that present https) 

My terminal is showing the following info (kitty with FiraCode fonts)
![image](https://user-images.githubusercontent.com/43121804/188295117-08c007c4-6128-47c9-89fb-9426f79eec23.png)

However, when i try to use the same code with box function, i obtain the following:
![image](https://user-images.githubusercontent.com/43121804/188295144-ee0dfd57-ce3c-4af7-acd7-24c346ea3a78.png)

As you see...the terminal is not reproducing the same and i still do not know how to fix. Using the same font on both environments.

### Reproducing the issue

Inside **eww.yuck**, my codes are:
```
(defpoll checknews    :interval "24h" `archnews -b -n 5 | cat - | sed -n '2,3p; 6,7p; 10,11p; 14,15p; 18,19p'`)

(defwidget news [?first]
 (box :orientation "vertical"
 	  :class "news"
 first 
 )
)

(defwindow newsfeed
		   :monitor 0
		   :geometry (geometry :x "1100px"
		   				      :y "350px"
		   				      :width "5px"
		   				      :height "5px"
		   				      :anchor "top left")
		   	:stacking "bg"
		   	:class "feed"
		   	:wm-ignore false
		 (news :first checknews)
)
```

inside **eww.scss**
```
*{
	all: unset;
	font-family: "FiraCode Nerd Font Mono";
	font-size: 15;
	color: #02F2E4;
}
.newsfeed{
	background-color: #2A2020;
	border: 1.5px ridge #0CE3DB;
	border-radius: 1px;
	font-weight: bold;
	min-height: 15px;
	min-width: 100px;
}
```

### Expected behaviour

I expect the same or similar output on the EWW box. 

### Additional context

I'm trying to create a dashboard-like structure where i have some essential information about my system to decide how i will start my day. Infos like: archnews, number of pacman/yay updates pending, free disk size, ram memory statistics, top 10 process by CPU, whoami and date. I still need to improve my aesthetics but this is what i achieved so far.
![image](https://user-images.githubusercontent.com/43121804/188295269-c0369c73-2257-4bdb-9e05-aef1d79ffb11.png)

Thank you for your time.

**Comment by VuiMuich** [comment]
Looks like the color escape codes are included, has `archlinuxnew` a option to print uncolored?
Or maybe there is another utility you can pipe it to, to remove those escape codes.

**Comment by elkowar** [comment]
Ye, this is just archnews printing colored output unconditionally, resulting in your code keeping the escape sequences that the terminal uses for colors -- which eww obviously doesn't parse, and just prints verbatim.

**Comment by RochaLAJ** [comment]
Thank you! 
It is "fixed" now. Sorry, i never thought about colors. Was not Eww fault. 
![image](https://user-images.githubusercontent.com/43121804/188333200-06d44fec-ab6a-497c-9f7c-136da77f36d8.png)
@VuiMuich Archnews has a option to omit colors, it is represented by the "c" flag. 
`-c, --color           do not print in color, default is colorized output`

new version
`(defpoll checknews    :interval "24h" `archnews -b -cn 5 | cat - | sed -n '2,3p; 6,7p; 10,11p; 14,15p; 18,19p'`)`
