### ISSUE TITLE
Provide example configurations

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#56]
now that documentation is mostly taken care of, the main thing missing to make eww approachable is good examples. These examples should include both the css and xml and explain how and why things are used the way they are. It should also be shown how a script can be used to change the eww-state from outside. The use of the literal tag as well as script vars (both interval and tail) should be included. 

These examples may in the future be used in the CI-pipeline as a means of veryifying that changes don't brake existing functionality.

## acceptance criteria
- example widget config fulfilling the criteria stated above is implemented.
- screenshots showing the widgets are provided.
- examples are mentioned in the appropriate places in the documentation.

**Comment by elkowar** [comment]
@Swexti would you be willing to look into this? just writing a couple minimal, functional examples that showcase the functionality and configuration of eww

**Comment by Swexti** [comment]
uh, idk, how in-depth do i have to go with "explain how and why things are used the way they are"? Like a tutorial? Or just a short description of what it does?
so e.g:

```
If we take a look at this script we can see that once it gets the weather information (shown by the `weather=$("curl wttr.in")`), it tries to find what `if` tag equals the weather. So if the weather is Rain and we have two if fuctions that look like this:
`
if [ $weather = 'Sun']; then;
   eww update weather Sunny
elif [ $weather = 'Rain';] then;
   eww update weather Rain
`
It matches the secon if tag (the elif) with 'Rain' since the $weather = Rain. And since the $weather isn't Sunny, it doesn't match with `$weather = 'Sun'

After that it updates the `<script-var>` to match what weather information it gave with `eww update weather <weather>`
```
or something like
```
This script updates the `<script-var>` once the weather information matches the `if` tag.
```

**Comment by elkowar** [comment]
just some actual, full configurations with a couple short comments that explain the non-obvious stuff. so more like version 2 :D

**Comment by Swexti** [comment]
> non-obvious stuff

ah okay i thought i had to explain everything. But i don't have to do like `This is the <image> tag, it displays an image with the specified width and height`? Since the widget documentation takes care of that?

**Comment by elkowar** [comment]
yea, exactly. no need to explain everything, it's mostly just about having examples. just write some stuff and i'll tell u where some comments may be good

**Comment by Swexti** [comment]
ah okay

**Comment by elkowar** [comment]
perfect, I'll assign you!

**Comment by 6gk** [comment]
bruhhh, i know this is an example, but still

> ```
> if [ $weather = 'Sun']; then;
>    eww update weather Sunny
> elif [ $weather = 'Rain';] then;
>    eww update weather Rain
> ```

You quote the plaintext argument, but not the variable, which should be in double quotes

you don't put a space before the end bracket, which will just not work

on the second one you put the `;` before the end bracket, and you put `;` after `then`, but not after the eww command? I can understand preferring lines to end with `;`, but i dont even know here

**Comment by Swexti** [comment]
bruh

**Comment by mellipa** [comment]
Has there been any progress on this? I'd really like to see some example configs since the docs only cover so much. For example, I've seen the templates when the link to this repository is shared and it looks great! I'd really love to see some sample configs but I understand we all have our lives and managing time can be hard. Still, I'd really like to see some progress on this subject

**Comment by 6gk** [comment]
Oh wow, you created a gh account (presumably) just to comment here

@elkowar you're famous

**Comment by elkowar** [comment]
@Axarva you started work on this, correct?

**Comment by Axarva** [comment]
Yes, it's going a bit slow but it definitely is going on
One question, where are we going to provide these configurations? In a subdirectory of the repository on some other place?

**Comment by elkowar** [comment]
@Axarva any progress on this?

**Comment by Axarva** [comment]
I'm finished, here's a screenshot
![image](https://user-images.githubusercontent.com/66304313/105122268-ff37ba00-5afd-11eb-9a43-6e9c440a963d.png)
I'll add some more comments in the XML file, and I'll be fully done, except if you have something to edit here.

**Comment by Swexti** [comment]
Since there is no updates on this, i thought to myself "Why don't you go back and do it? ~~You're~~ I was assiged anyways." Although Axarava did one, i thought widget like examples would fit better. So i'm taking the task to do it, and I'm *actually* gonna do it this time.

**Comment by Axarva** [comment]
@Swexti After all, the more the merrier :)

**Comment by elkowar** [comment]
Examples are there! Although there is still room for improvement, I'll close this for now
