### ISSUE TITLE
[FEATURE] Different Wayland LayerSurface namespaces for different defwindows

### ISSUE THREAD

**Issue by colin-heffernan** [elkowar/eww#587]
### Description of the requested feature

It would be useful if different defwindows could have different LayerSurface namespaces. This would allow for blurring specific widgets in compositors like Hyprland.

### Proposed configuration syntax

Perhaps `:namespace foo` as a defwindow property?

### Additional context

I want to be able to blur specific widgets on Hyprland, but this is currently impossible since all widgets share a namespace.

**Comment by latipun7** [comment]
Hyprland relied on layer surface namespace to [blur specific layer surface](https://wiki.hyprland.org/Configuring/Keywords/#blurring-layersurfaces). The default layer surface for eww window is `gtk-layer-shell`, it would be useful if this feature implemented with `gtk_layer_shell::set_namespace`.
