### ISSUE TITLE
can't run eww

### ISSUE THREAD

**Issue by TripleBaka** [elkowar/eww#588]
im following the instructions here https://elkowar.github.io/eww/ and im stuck on ./eww open <window_name>
all i get is   bash: syntax error near unexpected token `newline'   
i tried it without the '<>' but no matter what name i put all i get is
No window named 'window_name' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.

 i have looked in everything that says config inside eww to find the window name and i have tried like every name i thought could work

i have only been using linux for like two months what am i doing wrong help

**Comment by VuiMuich** [comment]
`<window_name>` is supposed to be replaced with the name of a window the is defined in your `.yuck` config file. If you want to use the example from the GitHub repo you need to copy the contents of the folder `examples/eww_bar` to `~/.config/eww/` and then use the window name `bar`.
Assuming you have a terminal and your working directory is the root of the cloned repo you can use this commands:
```sh
mkdir ~/.config/eww
cp examples/eww_bar/* ~/.config/eww/
```

_Note: it is common practice to use `<...>` when something is supposed to be replaced as a whole, but without the brackets._

**Comment by viandoxdev** [comment]
You should replace <window_name> with the name of the window you want to open. Windows are defined in your eww config, you can refer to the [eww documentation](https://elkowar.github.io/eww/) for how (and where) to write one.
