### ISSUE TITLE
[BUG] eww window fails to render if multiple widgets are inside a revealer

### ISSUE THREAD

**Issue by Saul-Dickson** [elkowar/eww#589]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm trying to use a revealer to show/hide multiple buttons when hovered over. I've encountered a confusing issue, though. The revealer widget, it seems, when given multiple widgets at once will refuse to render. There is one button in this widget that is always visible, and three other buttons hidden behind a revealer triggered using the usual `:onhover` and `:onhoverlost` arguments of the eventbox widget.

In short, then, multiple widgets underneath a revealer widgets make the revealer widget break.

### Reproducing the issue

In a simple configuration with an empty `eww.scss`, paste this code into the `eww.yuck`:

```
;; Power Widget
(defvar test-visible false)

(defwidget test []
  (eventbox
    :onhover "eww update test-visible=true"
    :onhoverlost "eww update test-visible=false"

    (box
      :class "test-box"
      :orientation "h"
      :space-evenly "false"
      :spaceing "2"

      (revealer
        :transition "slideleft"
        :reveal test-visible
        :duration "550ms"

        (button
          :class "first-button"
          :onclick "echo test"
          "󰜉"
        )

        (button
          :class "second-button"
          :onclick "echo test"
          "󰤂"
        )

        (button
          :class "third-button"
          :onclick "echo test"
          "󰤄"
        )
      )

      (button
        :class "visible-button"
        :onclick "echo test"
        "󰐥"
      )
    )
  )
)

;; Render bar
(defwindow bar
  :monitor 0
  :geometry (geometry
              :x "0%"
              :y "5px"
              :width "2250px"
              :height "65px"
              :anchor "top center"
            )
  :stacking "bg"
  :reserve (struts :distance "69px" :side "top")
  :windowtype "dock"
  :wm-ignore false
  (bar-content)
)

(defwidget bar-content []
  (box 

    (box
      :halign "end"
      :spacing 2
      :space-evenly false
      
      (Power)
    )
  )
)
```

This code is just a somewhat modified version of what I already wrote in my EWW bar config, you can see the whole config if you believe it relevant at [my dot files.](https://github.com/Saul-Dickson/dotfiles)

### Expected behaviour

The expected behavior is fairly self-explanatory. Reveal all three buttons as shown in the sample config.

### Additional context

I'm trying to define a widget for quick access to login buttons; poweroff, hibernate, suspend, reboot, etc.

**Comment by viandoxdev** [comment]
Check eww logs, it should say something along the lines of GTK::Bin can't have more than one child. This isn't really a bug you just need to put your buttons in a box and that box in the revealer
