### ISSUE TITLE
[FEATURE] copr package

### ISSUE THREAD

**Issue by NicTanghe** [elkowar/eww#596]
### Description of the requested feature

a copr package we can download.

Trying to compile on fedora is a pain as it you get the error that gdk-pixbuf-2.0 is not in the pkg-config search path.

even though the package is installed .

```
sudo dnf install gdk-pixbuf2
Last metadata expiration check: 0:17:08 ago on Wed 12 Oct 2022 12:29:39 CEST.
Package gdk-pixbuf2-2.42.9-2.fc36.x86_64 is already installed.
Package gdk-pixbuf2-2.42.9-2.fc36.i686 is already installed.
Dependencies resolved.
```

Everyone having to resolve dependency hell on their own is a pain, so it would be nice if there was a copr package available

I dont realy know how to go in adjust the build config to point to the correct location or even what file it is.

**Comment by NicTanghe** [comment]
now I`m stuck on 
```bash
warning: `"pkg-config" "--libs" "--cflags" "gtk-layer-shell-0" "gtk-layer-shell-0 >= 0.1"` did not exit successfully: exit status: 1
error: failed to run custom build command for `gtk-layer-shell-sys v0.4.1`
```

**Comment by Marius-Le-Houezec-Lacaze** [comment]
If you are still stuck here you have to install  `libgtk-layer-shell-dev` on your system

**Comment by NicTanghe** [comment]
Thx i shwitch to RHEL so eww is not something feasable atm

**Comment by Carlisle96** [comment]
I would also enjoy a copr package
