### ISSUE TITLE
[BUG] "no disk space left on device" during rustup installation 

### ISSUE THREAD

**Issue by coderj001** [elkowar/eww#598]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

![image](https://user-images.githubusercontent.com/39460245/196120223-6c7a5a0e-325e-46b1-8138-4300177e88a6.png)
unable to install via yay package manager 

### Reproducing the issue

use arch distro and yay package manager

**Comment by fiamiral** [comment]
> error: failed to extract package (perhaps you ran out of disk space?): No space left on device (os error 28)

> Archlinux eww theme.vdi(Normal, 8.00 GB)

How about more vm storage?

**Comment by coderj001** [comment]
@fiamiral already has 50 GB how much space dose it needed?

**Comment by viandoxdev** [comment]
Well this is definitely not an eww bug (or a bug for that matter), and the error happens on rust install. You can use lsblk to get an idea of available disk space.
