### ISSUE TITLE
[FEATURE] Overlap waybar's exclusive zone.

### ISSUE THREAD

**Issue by jkim5959** [elkowar/eww#608]
### Description of the requested feature

I know this is completely useless for 99% of the users, but I think it would be cool if eww widgets could invade waybar's reserved space. I'm trying to make a fullscreen eww widget and waybar is in the way. Same thing happens when I set a eww bar and make it exclusive. If I were in X I guess I could just fullscreen eww with wm because it can be, but on wayland I can't since it's not a window.

**Comment by viandoxdev** [comment]
I don't think this is really up to eww to decide, from what I understand of [zwlr_layer_shell](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) (Wayland protocol extension that eww uses) surfaces can set an exclusive zone (where other surfaces shouldn't overlap), although the exact behavior is compositor dependent that would mean you'd need to disable that in waybar.

I could be wrong tho

It's also possible that changing the layer would work, but idk how to do that

**Comment by jkim5959** [comment]
> I don't think this is really up to eww to decide, from what I understand of [zwlr_layer_shell](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) (Wayland protocol extension that eww uses) surfaces can set an exclusive zone (where other surfaces shouldn't overlap), although the exact behavior is compositor dependent that would mean you'd need to disable that in waybar.
> 
> I could be wrong tho
> 
> It's also possible that changing the layer would work, but idk how to do that

I see. Apparently it's hard :( Thanks for replying tho.

**Comment by viandoxdev** [comment]
It could be possible, especially considering I can't really reproduce, what compositor do you use and do you have MRE ?

**Comment by jkim5959** [comment]
> 

Wait, are you telling me that you've actually made it possible that eww overtakes waybar's exclusive zone? I'm on Hyprland. I'm sorry I don't know what MRE is. I tried googling but it says military meals.

**Comment by viandoxdev** [comment]
Should be fixed by #609 if exclusive is set to `"ignore"`, not sure if or when this it'll get merged tho.

**Comment by jkim5959** [comment]
> 

Wow. Thank you. I should apologize for my noobness though, how can I test this in my machine?

Also I think the minimal reproducible example is pretty much just installing both eww and waybar and set waybar first then open eww. I'm not sure what more information I should give since this is pretty much a minimal hyprland setup under a virtual machine.

Could screenshots or config files help?

**Comment by viandoxdev** [comment]
Don't worry about that, I already reproduced with hyprland and waybar (to test my fix).
To use the fix you should either wait for it to be merged, or [build eww from source](https://elkowar.github.io/eww/eww.html#how-to-install-eww) from my branch:
Instead of
```
git clone https://github.com/elkowar/eww
```
do
```
git clone -b exclusive --single-branch --depth 1 https://github.com/viandoxdev/eww
```
(you could also clone the regular eww directory, add a new remote and git switch to the branch)

There might be better solutions depending on your distro (local pkgbuild on arch, or patch on gentoo, ...) tho, which one are you on ?

**Comment by jkim5959** [comment]
> 

I am on arch linux. I know it's not for noobs like me but I really liked Hyprland's wacky animation and it's easiest to install through aur XD

Thank you so much for the fix. It's too late in australia so gotta sleep but I'll definitely do it tomorrow.

**Comment by jkim5959** [comment]
I just removed elk's eww with yay -R eww-wayland and compiled viandoxdev's eww from source. But when I set `:exclusive "ignore"`and do `eww reload` it says :exclusive needs to be either true or false.

Here is my eww.yuck:

`(defwidget blur []
 (box :class "blur" :vexpand "false :hexpand "false"
 (button :class "blur" :onclick "sh /home/arch/.config/.scripts/eww_close")
))
(defwindow blur
 :monitor 0
 :stacking "overlay" :focusable "false"
 :geometry (geometry :width "100%" :height "100%")
 (blur))`

**Comment by viandoxdev** [comment]
You need to kill the previous daemon with eww kill

**Comment by jkim5959** [comment]
> You need to kill the previous daemon with eww kill

It works now. I can't appreciate enough :)
