### ISSUE TITLE
[FEATURE] change color of a widget based on variable 

### ISSUE THREAD

**Issue by Le-Kat** [elkowar/eww#611]
### Description of the requested feature

(Not sure if this is already implemented, but I couldn't find out how to do this) I'm currently using a desktop widget to manage some connection status, including wether my bluetooth is currently on. I'm currently doing this by having a variable `(defvar bluetoothPowered false)` that gets updated every time I click the bluetooth widget (which also turns bluetooth on/off). However it's currently not conveying this information, and I had planned to have the button itself switch from being the standard text color, to bluetooth™ blue (though the use of the powered variable).

### Proposed configuration syntax

I'm not sure how any proposed syntax would look like (since I'm 50% sure there's already a way to do this that I don't know), but in waybar I'm currently achieving something similar to this by having:
```scss
#bluetooth {
	color: #00f;
}
#bluetooth.off {
	color: #fff;
}
```
in waybar's css file

### Additional context

I guess I'm either looking to add a property to the bluetooth widget that lets me set a different CSS based on the state of the `bluetoothPowered` variable, or some way of changing bluetooth's class based on said variable (so it would be affected by a different glob of CSS)

**Comment by viandoxdev** [comment]
[link](https://elkowar.github.io/eww/expression_language.html)

**Comment by Le-Kat** [comment]
> [link](https://elkowar.github.io/eww/expression_language.html)

...Thanks, sorry for asking dumb question.
