### ISSUE TITLE
[Question] Is possible to generate children widgets at runtime?

### ISSUE THREAD

**Issue by D4yvid** [elkowar/eww#612]
Example, i want to create a wi-fi menu with all networks available, but those networks can be different at any moment

Something like:
```
 Wifi list

    Some_SSID                       [Connect]
    Another_SSID                    [Connect]
```

This will probably need to generate children widgets at runtime to change those values

Is that possible?

**Comment by viandoxdev** [comment]
What you want is [for](https://elkowar.github.io/eww/configuration.html#generating-a-list-of-widgets-from-json-using-for) and to some extent (you rarely really need it tho) [literal](https://elkowar.github.io/eww/configuration.html#dynamically-generated-widgets-with-literal)

**Comment by D4yvid** [comment]
> What you want is [for](https://elkowar.github.io/eww/configuration.html#generating-a-list-of-widgets-from-json-using-for) and to some extent (you rarely really need it tho) [literal](https://elkowar.github.io/eww/configuration.html#dynamically-generated-widgets-with-literal)

Wowwww, that can give what i need, thanks!
