### ISSUE TITLE
[BUG] some css borders styles don't work

### ISSUE THREAD

**Issue by danielgafni** [elkowar/eww#614]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

For some reason, some of the borders options don't get applied from the config file. But the same styles work correctly from the gtk inspector.
![image](https://user-images.githubusercontent.com/49863538/200903295-c2b20d3e-6c5a-4743-ae22-ee1adb88966c.png)

![image](https://user-images.githubusercontent.com/49863538/200903135-a568af43-9164-4161-a056-2464d3dd8f2d.png)

### Reproducing the issue

My window (with placeholders for my custom variables)

```yuck
;; weather
(defwidget weather [] 
	(box :class "genwin" 
		(box :orientation "v" :spacing 10 :space-evenly "false" :vexpand "false" :hexpand "false" 
			(box :orientation "h" :vexpand "false" :hexpand "false" 
				(label :class "iconweather" :halign "start" :style "color: red" :text "icon")
				(label :class "label_temp" :halign "end" :text "${round(0, 0)}°C"))
			(box :orientation "v" :spacing 10 :halign "center" :space-evenly "false" :vexpand "false" :hexpand "false" 
				(label :class "label_description" :text "rofl")
				(label :class "label_quote" :text "rofl")))))

;; weather
(defwindow weather :stacking "bg" :focusable "false" :screen 1 :monitor 0
	    :geometry (geometry :x 1990 :y 10 :width 300 :height 220)
					(weather))
```
My style (with placeholders for my colors)
```cscc

/** Global *******************************************/
*{
	all: unset;
	font-family: "Fira Code Nerd Font";
}

/** Background ***************************************/
.bg {
//	background-color: black;
	opacity: 1;

}

/** Generic window ***********************************/
.genwin {
	background-color: transparentize(grey, 0.7);
    border-color: @nord1; 
    border-width: 4px;
    border-style: solid;
}


/** Weather ***************************************/
.iconweather {
	font-family: "Fira Code Nerd Font";
	font-size : 120px;
	font-weight : normal;
	margin : 15px 0px 0px 30px;
}

.label_temp {
	color : #A6D1DD;
	font-size : 80px;
	font-weight : bold;
	margin : -15px 30px 0px 0px;
}

.label_description {
	color : #BF616A;
	font-size : 38px;
	font-weight : bold;
}

.label_quote {
	color : #E5E5E5;
	font-size : 18px;
	font-weight : normal;
}
```

### Expected behaviour

The border-color, border-style and border-width should work.

### Additional context

I'm running wayland with hyprland

**Comment by viandoxdev** [comment]
eww log ?

**Comment by danielgafni** [comment]
hmm sorry, seems like it's a weird behavior of scss. I was using `@define-color` and `@mycolor` which worked in the `waybar` css. I don't know much about css and thought it would work here too. The logs actually had errors about these lines. 

The borders styling actually works.

Thanks! Closing the issues.
