### ISSUE TITLE
[BUG] input widget not working even with `:focusable true` on the window

### ISSUE THREAD

**Issue by D4yvid** [elkowar/eww#617]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I wanted to create a search menu to launch apps, i was reading the widget documentation and i've found the `input` widget, on the documentation says:
`"For this to be useful, set focusable="true" on the window"`

On my window, i've added the `:focusable true` and added the input widget inside of a overlay, to add a search icon, but it doesn't work anyway. I've already tested without the overlay widget, doesn't work anyway

> The window:
![2022-11-12_12-47](https://user-images.githubusercontent.com/115833146/201482287-5fd0f2c8-0b4c-457c-8975-b4748e4d9537.png)

> The search box container (is inside of a overlay widget):
![2022-11-12_12-49](https://user-images.githubusercontent.com/115833146/201482372-7f5cf197-55a9-43ca-aba5-365526625361.png)

I don't know why this isn't working

### Reproducing the issue

1. Create a focusable window
2. Create a input widget in the focusable window layout
3. Try to type on the input layout

### Expected behaviour

The window be focused and the input receive characters

### Additional context

eww --version: `eww 0.4.0 7a0e1b77f24ee89d627e552f9abc55eb636aaaa6`

**Comment by viandoxdev** [comment]
Can't reproduce on sway

**Comment by D4yvid** [comment]
> Can't reproduce on sway

Oh, i use bspwm, for sure

**Comment by TiagoDamascena** [comment]
In my case it only works if there's any window on current display, if a window is open it keeps focusing the background window. I'm using leftwm.

**Comment by simonasGit** [comment]
> In my case it only works if there's any window on current display, if a window is open it keeps focusing the background window. I'm using leftwm.

Using BSPWM. Only works if there is no other window in background (if there is, it focuses that one) but regardless of window type.
