### ISSUE TITLE
[BUG] eww looks for xml config only.

### ISSUE THREAD

**Issue by fahimscirex** [elkowar/eww#632]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

```
eww logs

┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛

 2022-11-28T05:47:55.650Z INFO  eww::server > Loading paths: config-dir: /home/fahim/.config/eww, ipc-socket: /run/user/1000/eww-server_L2hvbWUvZmFoaW0vLmNvbmZpZy9ld3c=, log-file: /home/fahim/.cache/eww_L2hvbWUvZmFoaW0vLmNvbmZpZy9ld3c=.log
 2022-11-28T05:47:55.659Z ERROR eww         > Failed to load eww config file /home/fahim/.config/eww/eww.xml
```

As the `eww.yuck` file exists in the directory, shouldn't it look for that also? I'm using the wayland build.

**Comment by elkowar** [comment]
Eww hasn't supported xml for a loooong while now, I assume you're just on a very old version. Try reinstalling or building the latest version or eww!

**Comment by fahimscirex** [comment]
> Eww hasn't supported xml for a loooong while now, I assume you're just on a very old version. Try reinstalling or building the latest version or eww!

well, i did installed the latest versin. tried installing manually and from aur also, still getting this.
