### ISSUE TITLE
[BUG] When piping playerctl output into sed, no media info displays

### ISSUE THREAD

**Issue by Senhek** [elkowar/eww#639]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Hello! Recently started using the basic eww bar and noticed that when the media info gets too long, the bar expands beyond screen borders, so I attempted to pipe the `playerctl` output into `sed` to truncate strings beyond a certain length, as in:
```
(deflisten music :initial ""
  "playerctl --follow metadata --format '{{ artist }} - {{ title }}' | sed 's/\(.\{80\}\).*/\1.../'")

```
Also tried with `cut`, but to no avail. The result in both cases is that no media info displays.

**Comment by lucasvreis** [comment]
This is actually an issue with `sed`, you can see this by piping your command to `cat` (it also prints nothing).

You can fix this by using the `-u` flag, like so:
```sh
playerctl --follow metadata --format '{{ artist }} - {{ title }}' | sed 's/\(.\{80\}\).*/\1.../' -u
```

**Comment by lucasvreis** [comment]
I think this partially an issue with `sed`, you can see this by piping your command to `cat` (it also prints nothing).

I tought you could fix this by using the `-u` flag, like so:
```sh
playerctl --follow metadata --format '{{ artist }} - {{ title }}' | sed -u 's/\(.\{80\}\).*/\1.../'
```

But this is only working for me if I place this script in a file, if I put it directly in the `deflisten` then the part after the pipe seems to be ignored for some reason 🤔. Anyway, the `-u` flag + placing it in a file works for me.
