### ISSUE TITLE
[BUG] Unable to build on macOS

### ISSUE THREAD

**Issue by Rougemoot** [elkowar/eww#64]
## Describe the bug
I've been trying to build eww on macOS (currently 10.14.6 but that shouldn't matter much) after installing rustc and cargo as told in the instructions, and I've run into some hurdles:

First I got a `no cairo package found` message, so I installed `cairo`, then it was `pango`, then `atk`, at which point I learned that this was all gtk related so I installed the `gtk+3` package with homebrew (the unofficial but widespread package manager on macOS)

Following that I tried building eww again, and here's the result:

```
➜  eww git:(master) cargo build --release
   Compiling gdkx11-sys v0.10.0
error: failed to run custom build command for `gdkx11-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/Users/vermoot/Projects/eww/target/release/build/gdkx11-sys-63812bde4a87a546/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=GDK_X11_3.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GDK_X11_3.0_STATIC
  cargo:rerun-if-env-changed=GDK_X11_3.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gdk-x11-3.0" "gdk-x11-3.0 >= 3.14"` did not exit successfully: exit code: 1
  --- stderr
  Package gdk-x11-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gdk-x11-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gdk-x11-3.0' found
  Package gdk-x11-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gdk-x11-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gdk-x11-3.0' found
```

According to [what I found](https://apple.stackexchange.com/questions/205404/how-can-i-get-gdk-x11-3-0-on-os-x) there is no way to install gdk-x11 on macOS, so I've hit a dead end and I'm not able to build eww.

## Reproducing the issue
Be on macOS. Try to build eww with my limited knowledge.

## Expected behaviour
Build eww.

## Additional context
MacbookPro11,1
macOS Mojave 10.14.6

**Comment by elkowar** [comment]
@Rougemoot thanks for the report! I just merged #63, which removes the dependency on gdk-x11 (as nothing X-specific has been implemented yet, it isn't yet necessary). Could you try building it again, with that new change?

**Comment by Rougemoot** [comment]
That worked, I got eww to build properly without any errors. Time to make some widgets!

**Comment by druskus20** [comment]
Oh so my awesome PR fixed stuff. Thank me later @elkowar.

**Comment by elkowar** [comment]
fixed by #63

**Comment by RossComputerGuy** [comment]
> Hey, FWIW, I tried:
> 
> ```
> git clone https://github.com/elkowar/eww
> cd eww
> brew install gtk+3 atk
> rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy
> cargo +nightly build --release
> ```
> 
> And I was unable to build:
> 
> ```
> $ cargo build --release
>    Compiling glib-sys v0.10.1
>    Compiling simplexpr v0.1.0 (/Users/steve/Documents/git/eww/crates/simplexpr)
>    Compiling yuck v0.1.0 (/Users/steve/Documents/git/eww/crates/yuck)
>    Compiling gobject-sys v0.14.0
>    Compiling cairo-sys-rs v0.14.9
>    Compiling atk-sys v0.14.0
>    Compiling gdk-pixbuf-sys v0.14.0
>    Compiling gio v0.14.8
>    Compiling gobject-sys v0.10.0
>    Compiling gdk-sys v0.14.0
>    Compiling gio-sys v0.10.1
>    Compiling gdk-pixbuf-sys v0.10.0
>    Compiling gio v0.9.1
>    Compiling gtk-sys v0.14.0
>    Compiling gdkx11-sys v0.14.0
>    Compiling gdk-pixbuf v0.9.0
> The following warnings were emitted during compilation:
> 
> warning: `"pkg-config" "--libs" "--cflags" "gdk-x11-3.0" "gdk-x11-3.0 >= 3.18"` did not exit successfully: exit status: 1
> 
> error: failed to run custom build command for `gdkx11-sys v0.14.0`
> 
> Caused by:
>   process didn't exit successfully: `/Users/steve/Documents/git/eww/target/release/build/gdkx11-sys-7fda3b467363f7c4/build-script-build` (exit status: 1)
>   --- stdout
>   cargo:rerun-if-env-changed=GDK_X11_3.0_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-apple-darwin
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_apple_darwin
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:warning=`"pkg-config" "--libs" "--cflags" "gdk-x11-3.0" "gdk-x11-3.0 >= 3.18"` did not exit successfully: exit status: 1
>   --- stderr
>   Package gdk-x11-3.0 was not found in the pkg-config search path.
>   Perhaps you should add the directory containing `gdk-x11-3.0.pc'
>   to the PKG_CONFIG_PATH environment variable
>   No package 'gdk-x11-3.0' found
>   Package gdk-x11-3.0 was not found in the pkg-config search path.
>   Perhaps you should add the directory containing `gdk-x11-3.0.pc'
>   to the PKG_CONFIG_PATH environment variable
>   No package 'gdk-x11-3.0' found
> ```

Same here

**Comment by max397574** [comment]
same here
