### ISSUE TITLE
Calendar misaligned labels

### ISSUE THREAD

**Issue by raflchan** [elkowar/eww#652]
I have a question regarding the styling of the calendar widget.
Whenever any padding is added to days it causes a top aligned date to display.
Is there any way to center these?
This question has been asked in another issue, however that one was marked as closed before the question was asked:

> I just whipped up a quick example, you can style the current day using the selected state.
> 
> ```css
> .calendar {
>     padding: 12px;
> }
> 
> .calendar:selected {
>     background: teal;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/63366086/147870150-760e088c-0930-4e9e-a318-38fcf74bb4bf.png)
> 
> Note: This highlights the selected day, by default the selected day will be the current day however other days will be selected when you click on them.

Did anyone figure out how to center the days? This is so unusable

_Originally posted by @beyond9thousand in https://github.com/elkowar/eww/issues/378#issuecomment-1249791129_

**Comment by victorz** [comment]
In general the documentation is super lacking for this particular widget (`calendar`). As you say it's basically unusable as there's no way to know how to target the elements within it. Very limited ability to customize it overall. 🤷 Might as well implement our own calendar widget.

**Comment by elkowar** [comment]
The general issue is that these are GTK questions -- Whilst the GTK documentation is definitely lacking, especially in the CSS context, ensuring that every bit of available GTK css is fully documented as part of eww is sadly _very_ out of scope, effort wise. Thus, your best bet for these sort of things is to either check if you can find sufficient GTK documentation about the CSS structure of the calendar widget, or to play around in `eww inspector` until you find something :/

**Comment by victorz** [comment]
Oh I see, so this isn't an eww widget, but a GTK widget. That makes a lot of sense -- I see now why it isn't very useful to us.

Thanks for clarifying!
