### ISSUE TITLE
[BUG] memory usage increases when array used in for loop is updated

### ISSUE THREAD

**Issue by QaidVoid** [elkowar/eww#664]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When using for loop to update widget, the memory usage keeps on increasing every time the array is updated.

### Reproducing the issue

To reproduce the issue, following example, which is taken from eww's documentation can be used:
https://elkowar.github.io/eww/configuration.html#generating-a-list-of-widgets-from-json-using-for
```lisp
(defvar my-json "[1, 2, 3]")

(defwidget testwidget []
 (box
   (for entry in my-json
     (button :onclick "notify-send 'click' 'button ${entry}'"
       entry))))
```
Then, update the the array with
```sh
eww update my-json="[1, 2, 3]"
```
Every time the array is updated, the memory usage grows.

### Expected behaviour

The memory usage should not grow every time the value in the array changes.

**Comment by siduck** [comment]
unable to reproduce issue, can you provide a video?

**Comment by QaidVoid** [comment]
Looks like the issue was fixed long before I posted the issue. I somehow didn't test the git version.
