### ISSUE TITLE
[FEATURE] A -c flag to specify config location. 

### ISSUE THREAD

**Issue by Swexti** [elkowar/eww#67]
## Description of the requested feature
Just a -c flag to specify config location, e.g `eww open main_window -c ~/Documents/eww.xml` 

## Proposed configuration syntax
```
 `eww open main_window -c ~/Documents/eww.xml` 
```
# Additional context
just like polybar does

**Comment by druskus20** [comment]
@elkowar You can asign this to me :)

**Comment by undefinedDarkness** [comment]
Now with the new daemon stucture, this argument would be used when lauching the daemon I think?

**Comment by elkowar** [comment]
yes, exactly. should probably be turned into a flag on the daemon command, ig

**Comment by undefinedDarkness** [comment]
I've implemented something that works, but I should probably add something that checks if the given user input is valid

**Comment by elkowar** [comment]
This has been implemented and merged in #104
