### ISSUE TITLE
[BUG] Updating variable through "eww update var=..."

### ISSUE THREAD

**Issue by leg7** [elkowar/eww#674]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When updating a specific variable through "eww update" the UI changes and updates just fine but eww logs gives me a huge list of the same error repeated dozens of times.

Here's the error:
```
Caused by:
    Couldn't upgrade reference, widget got deallocated
 2023-01-26T22:30:02.715Z ERROR eww::error_handling_ctx > Error while updating UI after state change
```

### Reproducing the issue

This happens any time I update the variable "i" with this setup:
```
; Workspaces

(defpoll workspace-data :interval "0.3s"
  "hyprctl -j workspaces")

; this variable gets updated through the hypr-workspaces script
; to highlight the focused workspace in the status bar
(defvar i 0)

(defwidget workspaces []
  (box :spacing 6
       :orientation "h"
       :space-evenly true
       :valign "center"
       :halign "start"
    (for workspace in workspace-data
      (button :class {i == workspace.id ? "focused-button" : "button"}
              :onclick "hyprctl dispatch workspace ${workspace.id}"
        {workspace.id}))))

(defwidget center-widgets []
  (box :spacing 8
       :orientation "h"
       :space-evenly false
       :class "center-widgets"
       :valign "center"
       :halign "center"
    (workspaces)))
```
For example "eww update i=5" would cause this error message to get spammed in the logs.

### Expected behaviour

I don't see why this would spam the logs with errors.

### Additional context

I'm using the hyprland window manager.

**Comment by viandoxdev** [comment]
This message is caused by the hotfix from aac4c3aef4fa7dd42b3464be86d26debad66d7c1, used to be a crash IIRC, not sure the reason tho, I never found a minimal reproducible example, but looking at yours there probably is something wrong with the for widget. Things should work regardless. Just in case, are you on the latest version ?

**Comment by leg7** [comment]
> This message is caused by the hotfix from [aac4c3a](https://github.com/elkowar/eww/commit/aac4c3aef4fa7dd42b3464be86d26debad66d7c1), used to be a crash IIRC, not sure the reason tho, I never found a minimal reproducible example, but looking at yours there probably is something wrong with the for widget. Things should work regardless. Just in case, are you on the latest version ?

Indeed this is fixed in the latest version. Sorry for the bother.
