### ISSUE TITLE
[BUG] Structured variables do not work in for loop

### ISSUE THREAD

**Issue by mipimipi** [elkowar/eww#686]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

An error is raised when a structured variable is used in a for loop.

For example: `... (for core in EWW_CPU.cores ...` leads to the error message:
```
error: No variable named `EWW_CPU.cores` in scope
   ┌─ /MY_CONFIG_PATH/eww.yuck:95:16
   │
95 │         (for core in EWW_CPU.cores
   │                      ───────────── Used here
   │
   → Hint: Define it as a global variable
   → Hint: If you meant to use the literal value "EWW_CPU.cores", surround the value in quotes
```

### Reproducing the issue

This config leads to the error:
```
(defwindow popup-cpu
  :monitor 0
  :geometry (geometry :anchor "top right"
			       :x "-220"
			       :y "30")
           :stacking "fg"
           :wm-ignore true
   	   (box :orientation "vertical"
		(for core in EWW_CPU.cores
		     (scale :width "200"
			    :orientation "horizontal"
			    :min "0"
			    :max "100.0"
			    :value "${core.usage}"
			    :draw-value "true"))))
```

### Expected behaviour

The for loop can deal with structured variables such as `EWW_CPU` - i.e., the example above works and no error is raised.

### Additional context

This is a workaround:
```
(defwindow popup-cpu
  :monitor 0
  :geometry (geometry :anchor "top right"
			       :x "-220"
			       :y "30")
           :stacking "fg"
           :wm-ignore true
	   (cpu-details :cores "${EWW_CPU.cores}"))

(defwidget cpu-details [cores]
	   (box :orientation "vertical"
		(for core in cores
		     (scale :width "200"
			    :orientation "horizontal"
			    :min "0"
			    :max "100.0"
			    :value "${core.usage}"
			    :draw-value "true"))))
```

**Comment by viandoxdev** [comment]
I don't think this is a bug, structured variables aren't really a thing, its just json strings and simplexpr has a dot operator for json access.

**Comment by mipimipi** [comment]
> I don't think this is a bug, structured variables aren't really a thing, its just json strings and simplexpr has a dot operator for json access.

The for loop does not seem to apply the dot operator correctly. Thus, I consider this behavior as bug.

**Comment by viandoxdev** [comment]
> > I don't think this is a bug, structured variables aren't really a thing, its just json strings and simplexpr has a dot operator for json access.
> 
> The for loop does not seem to apply the dot operator correctly. Thus, I consider this behavior as bug.
> 

The dot operator is a simolexpr feature and not present in yuck, if you want to use it you need to wrap it in accolades or an interpolated string

**Comment by mipimipi** [comment]
OK, got it. Putting `EWW_CPU.cores` into curly brackets did the trick. Thanks!
