### ISSUE TITLE
[FEATURE] control eww through socket

### ISSUE THREAD

**Issue by flick0** [elkowar/eww#687]
### Description of the requested feature

it would be nice to control eww through socket, this lets ppl make wrappers for the socket and possibly allow to config eww  in any language

it would let eww work more like the awesomewm widget system

**Comment by elkowar** [comment]
How would that work? the Eww CLI already connects to the eww daemon through socket-based IPC, so in that sense that's already how it works -- `eww update` is a good example of how you can control your eww instance from any outside language. Eww, at it's core, is a declarative system that is primarily concerned about its state management, so just going "pls render a square here uwu" won't _quite_ work out in that architecture, although you can always have a `literal` widget and then use `eww update` to set the contents of that dynamically from anywhere

**Comment by flick0** [comment]
i was talking about the *"pls render a square here uwu"* type of socket so you can possibly make a proper widget without ever writing any yuck.

if its not possible with how eww works, well looks like i gotta learn yuck then

**Comment by dmgolembiowski** [comment]
> How would that work? the Eww CLI already connects to the eww daemon through socket-based IPC, so in that sense that's already how it works -- `eww update` is a good example of how you can control your eww instance from any outside language. Eww, at it's core, is a declarative system that is primarily concerned about its state management, so just going "pls render a square here uwu" won't _quite_ work out in that architecture, although you can always have a `literal` widget and then use `eww update` to set the contents of that dynamically from anywhere

What if the socket was didn't support the lower-level kinds of controls that the daemon does but instead just sat above a sandbox shell that could rewrite files, make daemon command invocations, etc.?

If the socket was just a dirty hack, and only required work on the serialization/deserialization to support intentional behavior, I would think this gets a lot easier.

**Comment by elkowar** [comment]
If you're talking about updating the UI directly, there's the `literal` widget -- that's more or less directly what you're asking for. just set the content to some variable, and then use `eww update` to change the displayed contents through the socket.
