### ISSUE TITLE
[BUG] size of log file is 18G

### ISSUE THREAD

**Issue by shaeinst** [elkowar/eww#689]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

i was running out of spaces. so after some investigation, i found that the size of  eww log file is 18G. 

### Reproducing the issue

make syntax errors in your eww config file and it will keep record of it.

### Expected behaviour

there should be config to limit the log size.

**Comment by w-lfchen** [comment]
can be closed now
