### ISSUE TITLE
[BUG] Checkbox check doesn't work as expected

### ISSUE THREAD

**Issue by RobWalt** [elkowar/eww#693]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I wanted to implement a new `prop` on `checkbox` widgets. The new prop was just supposed to handle initial toggle of the checkbox. When I added what I thought to be the solution to this problem, the buttons became unresponsive, perhaps because of a wrong downcast (?)

I'll see if I can get more information, for now I just wanted to report this.

### Reproducing the issue

I added

```rust 
  // @prop active - is the checkbox active on initialization?
  prop(active: as_bool = true) {
      gtk_widget.set_active(active);
  },
```

to the widget definition in `widget_definitions.rs`. Not specifying `active` the prop on the checkbox or setting it to `true` results in unresponsive checkboxes (clicking them doesn't add the checkmark)

### Expected behaviour

If I set the prop to `true` the checkbox is checked on startup and responsive (i.e. I can unceck the checlbox)

### Additional context

I'm trying to call [this function of the `ToggleButtonExt`] trait, but I fear, some other function is called instead, which just deactivates widgets. Maybe it's a`gtk.rs` issue aswell. 

Also note that I already unsuccessfully tried to be more specific by using

```rust 
  // @prop active - is the checkbox active on initialization?
  prop(active: as_bool = true) {
      ToggleButtonExt::set_active(&gtk_widget, active);
  },
```

instead of the code above.

**Comment by RobWalt** [comment]
Just verified, that it isn't an issue with `gtk-rs`. I used their `basics` example and just added a checkbox to it

```rust
use gtk::prelude::*;

fn build_ui(application: &gtk::Application) {
    let window = gtk::ApplicationWindow::new(application);

    window.set_title("First GTK+ Program");
    window.set_border_width(10);
    window.set_position(gtk::WindowPosition::Center);
    window.set_default_size(350, 70);

    let button = gtk::Button::with_label("Click me!");
    let checkbutton = gtk::CheckButton::new();
    checkbutton.set_active(true);

    window.add(&checkbutton);

    window.show_all();
}

fn main() {
    let application =
        gtk::Application::new(Some("com.github.gtk-rs.examples.basic"), Default::default());

    application.connect_activate(build_ui);

    application.run();
}
```

This works as expected and opens the app with a checked box

![image](https://user-images.githubusercontent.com/26892280/221039765-a1c97bbf-59f8-4362-a510-892b7080a694.png)

**Comment by levnikmyskin** [comment]
Hey,  
writing here just to let you know that the only issue in your code was that you were using `active` which is a property already used by all widgets by default.  
I have fixed it and opened a pull request here.  
  
Cheers :D
