### ISSUE TITLE
[FEATURE] Add documentation around "duration" data type

### ISSUE THREAD

**Issue by victorz** [elkowar/eww#698]
### Description of the requested feature

It would be helpful to provide documentation on how to provide "durations" to widget properties that require it, such as :timeout, etc.

It's not clear if it's a numeric value, or a string. In one case, a string seems to work for me ("200ms", when using a revealer), but in other cases doesn't work at all no matter what values I try -- numeric, strings, whatever (when using an eventbox widget with a :timeout and :onhoverlost event in combination; the :timeout is just ignored completely and executes the :onhoverlost command immediately).

### Proposed configuration syntax

Just text. Just descriptive documentation.

**Comment by musjj** [comment]
Having the same problem, would really love a clarification of this. `:timeout` have no effect on `eventbox` for me, no matter what value I put in it.

**Comment by elkowar** [comment]
`:timeout`, in most places, will determine after how much time a command gets canceled -- it won't have effect on when onhoverlost is triggered, for example.

Either way, I made sure that the parse-errors you'd get from an invalid duration are more meaningful and added some documentation that should help clarify!

**Comment by victorz** [comment]
Thanks @elkowar! I appreciate it. What you've added does help. I see you added some 'Default: "200ms"' where there is a `duration` expected.

It would be even more helpful if we knew what datatype it is and what the options are for it. From what I can gather:

- it's a string
- it is parsed into a time-based duration
- there is at least one supported unit, `ms`

Would love to know more, like can we use a number? Are other units available? `s`, `m`, `mins`, `h/hours`, combinations like `1m30s`?

Would be awesome 🙏 Thanks for the update though!
