### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by iggut** [elkowar/eww#708]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

HI! I am trying to install eww-wayland-git but the install fails telling me there was a problem importing the gpg keys. I noticed there was a comment from EWW maintainer saying: Make sure to fetch the signing keys from GitHub and import them before building. I have no idea how to get the new keys. 

### Reproducing the issue

` Repo (1)             Old Version  New Version           Make Only
community/rustup                  1.25.2-1              Yes

Aur (1)              Old Version  New Version           Make Only
aur/eww-wayland-git               0.4.0.r20.g8ff4142-1  No

:: Proceed with installation? [Y/n]: y

:: Downloading PKGBUILDs...
 (1/1) eww-wayland-git-0.4.0.r20.g8ff4142-1          [-------------------------------------------------]
:: keys need to be imported:
     B558974128820CB473BD9807E321AD71B1D1F27F wanted by: eww-wayland-git-0.4.0.r20.g8ff4142-1
     5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23 wanted by: eww-wayland-git-0.4.0.r20.g8ff4142-1
:: import? [Y/n]: 
gpg: key 4Axxxxxxxxxxxxx: no user ID
gpg: Total number processed: 1
error: failed to run: gpg --recv-keys B558974128820CB473BD9807E321AD71B1D1F27F 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23:  `

**Comment by Mango0x45** [comment]
I’m having the same issue. Where can the GPG keys be grabbed from?

**Comment by andradei** [comment]
This is very well not a bug, but I can't install `eww` due to the same issue. Tried adding other keyservers ([listed here](https://wiki.archlinux.org/title/GnuPG#Key_servers)) and nothing works.

**Comment by andradei** [comment]
Here's what I get
```
❯ yay eww-wayland
1 aur/eww-wayland 0.4.0-5 (+20 3.19)
    Standalone widget system made in Rust (Wayland backend)
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
AUR Explicit (1): eww-wayland-0.4.0-5
Sync Dependency (1): gtk-layer-shell-0.8.1-1
:: PKGBUILD up to date, skipping download: eww
  1 eww                              (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  1 eww                              (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: eww 0.4.0-5 (Tue 17 Oct 2023 06:57:50 PM MDT)
==> Retrieving sources...
  -> Updating eww git repo...
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with b2sums...
    eww ... Skipped
:: (1/1) Parsing SRCINFO: eww
pub   rsa3072 2021-05-03 [SC] [expired: 2023-05-03]
      B558974128820CB473BD9807E321AD71B1D1F27F
uid           [ expired] Leon Kowarschick <5300871+elkowar@users.noreply.github.com>

pub   ed25519 2023-03-14 [SC]
      94E8F34BCE4F4BA8ED9B29BD50E76B4711E4C3E4
uid           [ unknown] Leon <5300871+elkowar@users.noreply.github.com>
sub   cv25519 2023-03-14 [E]

gpg: error reading key: No public key

 :: PGP keys need importing:
 -> 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23, required by: eww
:: Import? [Y/n]
:: Importing keys with gpg...
gpg: key 4AEE18F83AFDEB23: no user ID
gpg: Total number processed: 1
 -> problem importing keys
```

**Comment by Mango0x45** [comment]
@elkowar any input?
