### ISSUE TITLE
[FEATURE] Conditional Rendering of Widgets

### ISSUE THREAD

**Issue by sebastianrakel** [elkowar/eww#709]
### Description of the requested feature

Hi,

i have a laptop and a workstation and they share the same bar. but my workstation does not have a battery. so there is currently following error in my configuration.

```
error: Failed to turn `` into a value of type json-value
   ┌─ /home/sebastian/.config/eww/eww.yuck:17:15
   │
17 │           :text {EWW_BATTERY["BAT1"].capacity + "%"} )))
   │                  ───────────
```

so my idea is an option/property which skips the rendering of the module. like an enable option/property.

### Proposed configuration syntax

(label
  :enable false
  :text { EWW_BATTERY["BAT1"].capacity + "%" })

**Comment by viandoxdev** [comment]
see #517 (comments)

Also, take a look at the [eww documentation](https://elkowar.github.io/eww/).

**Comment by sebastianrakel** [comment]
Okay, i tested it with the visible property, but the widget is still processed and throws errors, cause there is no battery in this device

**Comment by viandoxdev** [comment]
You could try literal then, or use simplexpr features to avoid throwing errors (the recently merged json safe acess could work)

**Comment by sebastianrakel** [comment]
Will have a look into that, thanks!

**Comment by Kage-Yami** [comment]
As an alternative to `literal`, I came up with using a `for` loop over an eww-expression that resolves to a JSON array with either 0 or 1 element(s), depending on a boolean value:

```lisp
(defvar _cfg_showBattery true)

(defwidget battery [bat])

; ...

(
  for bat in {_cfg_showBattery ? ["BAT0"] : []}
  (
    battery :bat bat
  )
)
```

**Comment by hypernova7** [comment]
See [eww expressions](https://elkowar.github.io/eww/expression_language.html)

You can do

```
EWW_BATTERY?.["BAT0"]
```

**Comment by elkowar** [comment]
Closing this, as conditional rendering is already implemented, and simplexpr errors like these can be avoided using the `?.` notation as mentioned above!
