### ISSUE TITLE
Problem with styling

### ISSUE THREAD

**Issue by Qpernicus** [elkowar/eww#724]
I'm creating this issue because i could use a pointer, and have no clue where to start. 

- Using Arch + Hyprland (https://codeberg.org/qpernicus/Dotfiles) 
- Did a update yesterday to.. amongst other things Hyprland and eww-wayland-git. 
All of sudden my complete EWW styling is gone. In the link above you can see a screenshot from my current config. But since the update it looks like below..and i don't know where to start/how to troubleshoot this:

![2023-03-27_18-03-1679934545](https://user-images.githubusercontent.com/60620868/228004677-0a05975f-8003-43b9-9290-4a802fe86df5.jpg)

If you need anything, happy to, but i don't know what to deliver. My config is unchanged (and on my codeberg repo) and my EWW doesn't error on startup, it just doesnt load the styling.. 

I saw EWW has a new option namespace: i don't use that, but not sure what to put in it either..

**Comment by justinesmithies** [comment]
I too have an issue since the last couple of days updates running on Arch. I had eww-wayland-git installed and my styling suddenly stopped loading with no errors in eww logs but if i run `eww reload` i get

```
SCSS parsing error: Error: Expected identifier.
   ╷
80 │ .0, .01, .02, .03, .04, .05, .06, .07, .08, .09, .011, .022, .033, .044, .055, .066, .077, .088, .099 {
   │  ^
   ╵
./stdin:80:2
```

I found if I installed eww-wayland from the AUR which is obvs behind right now `eww 0.4.0 d58d91de78d2b9984a1bbb8314be197bc0e283dc` it all works as expected.

In case it helps my dots are [here](https://codeberg.org/JustineSmithies/hyprland-dotfiles)

**Comment by Qpernicus** [comment]
I can config that by only reverting to eww-wayland package it works as it should and my styling is correct again.

**Comment by colin-heffernan** [comment]
I believe that this is due to CSS class naming rules. Class names aren't supposed to start with numbers. When I changed this in my script, everything worked again.

**Comment by Qpernicus** [comment]
> > I believe that this is due to CSS class naming rules. Class names aren't supposed to start with numbers. When I changed this in my script, everything worked again.
> 
> Thank you you're absolutely right ! I prefixed all with w and everything is good in the world again. Can't believe I overlooked this and just couldn't see the wood for the trees. ;)

I can confirm that these edits to config fixed the styling issue. And haven't overlooked this..just didnt know :)
