### ISSUE TITLE
[FEATURE] Load multiple variables from JSON file

### ISSUE THREAD

**Issue by s3rj1k** [elkowar/eww#728]
### Description of the requested feature

It would be nice to have the ability to populate multiple variable at once using pulling from a pre generated JSON file located at some location in filesystem

This will allow to limit forking by just writing a daemon application that generates needed variables data and dumps them into single JSON file that EWW can digest.

**Comment by oldwomanjosiah** [comment]
Would this use-case already be supported by having said daemon output an object containing all the vars you need, and then accessing those individual fields where needed? There's no direct file integration, but you could do

```clojure
(defpoll
  :interval "2s"
  `cat ./path/to/file.json`)
```

to pull the updated information

**Comment by s3rj1k** [comment]
@oldwomanjosiah The idea is to avoid spawning extra processes

**Comment by oldwomanjosiah** [comment]
In that case, assuming that the daemon could be configured to output the data on `stdout`, you could use [`deflisten`](https://elkowar.github.io/eww/configuration.html) since it only forks once and just updates the variable with each new line.

**Comment by s3rj1k** [comment]
> [`deflisten`](https://elkowar.github.io/eww/configuration.html)

I am not sure how this will work, If I handle external daemon using systemd service how would `eww` read stdout of that daemon without the help of additional subprocess as `tail`?

**Comment by oldwomanjosiah** [comment]
If you're writing the daemon, you could just have it as a child process of eww, no?

**Comment by s3rj1k** [comment]
> If you're writing the daemon, you could just have it as a child process of eww, no?

How it would work if multiple widgets would want to access variables from that daemon?

Also I would want daemon to handled by init system.

**Comment by maralorn** [comment]
@s3rj1k that is not a problem. A variable defined by deflisten can be accessed by all widgets.

Is it really necessary to launch the daemon by the init system if it is only serving eww? Seems lower complexity to me to let eww control it. That’s what I did at least, I have a setup like this.

If you really want to have the daemon be controlled by the init system you can let the daemon write to a unix socket and listen to it with socat or something similar.

**Comment by s3rj1k** [comment]
> @s3rj1k that is not a problem. A variable defined by deflisten can be accessed by all widgets.
> 
> Is it really necessary to launch the daemon by the init system if it is only serving eww? Seems lower complexity to me to let eww control it. That’s what I did at least, I have a setup like this.
> 
> If you really want to have the daemon be controlled by the init system you can let the daemon write to a unix socket and listen to it with socat or something similar.

I still want the ability to load from file instead of forking, for me this is the main showstopper for using eww

**Comment by maralorn** [comment]
But my proposed solution would only do one exec fork at the start of eww.
If your concern is the one fork at the start of the program, of socat or whatever else streams the data into eww, then in my opinion you are running the risk of premature optimization. (But I am just a bystander here.)

You could also write a small script in whatever language you which watches the file and prints it to stdout whenever it changes. That as well means exactly one fork at the start of the program.

**Comment by s3rj1k** [comment]
> But my proposed solution would only do one exec fork at the start of eww. If your concern is the one fork at the start of the program, of socat or whatever else streams the data into eww, then in my opinion you are running the risk of premature optimization. (But I am just a bystander here.)
> 
> You could also write a small script in whatever language you which watches the file and prints it to stdout whenever it changes. That as well means exactly one fork at the start of the program.

Your proposal is a hack, there is a need for proper and sane solution, yes it would work but it tastes bad.

**Comment by elkowar** [comment]
how does this taste bad?
writing a file to the filesystem and then having to read that continuously definitely smells worse than... just having a deflisten.
Additionally, what i'd _actually_ recommend, if you wanna write a daemon yourself anyways, is to use `eww update` to set the variables directly -- that way, you can avoid all forking from inside eww, and all unnecessary filesystem access.

Feel free to reopen if there's some argument I'm missing here, but I don't see much reason to specifically support reading variables from a file continuously

**Comment by maralorn** [comment]
@elkowar  if I may ask: What do you estimate to be less overhead: A daemon writing to a socket on which I do a deflisten socat. Or just calling eww update everytime I would push something through the socket?
Currently using the first solution and it is working really well.

**Comment by s3rj1k** [comment]
> if you wanna write a daemon yourself anyways, is to use `eww update` to set the variables directly -- that way, you can avoid all forking from inside eww, and all unnecessary filesystem access.

So `eww update` does not spawn new processes? How that would avoid fork/exec?

>  writing a file to the filesystem and then having to read that continuously definitely smells worse than... just having a deflisten.

There can be multiple sources of files, there could be one, be forcing using only deflisten there is only one way of populating data to eww, and this make makes eww be in control of forking, what if eww crashes, I would want my variables be independent of UI processes, I would want for variables to be pulled in predictable time intervals and keep the data after eww restart.

**Comment by s3rj1k** [comment]
@maralorn Also are I happy now?

**Comment by maralorn** [comment]
@s3rj1k I just tried to be helpful. I think elkowar is doing excellent work and I agree with his assessment.

**Comment by elkowar** [comment]
> @elkowar if I may ask: What do you estimate to be less overhead: A daemon writing to a socket on which I do a deflisten socat. Or just calling eww update everytime I would push something through the socket? Currently using the first solution and it is working really well.

I assume the difference between those two to be less than irrelevant, potentially actually genuinely not measurable outside of extremely well controlled lab conditions. generally, eww update _is_ spawning a process inherently, so I guess the socket miiiiight be more efficient, but this should only matter if you're doing _extreme_ amounts of data, either by having 100000000 variables or updating them every 0.1 nanoseconds...

**Comment by s3rj1k** [comment]
@elkowar `Add jq function, offering jq-style json processing` ?

somehow related to this issue? can't find any example on how to use that.
