### ISSUE TITLE
Widget written in Rust examples

### ISSUE THREAD

**Issue by paolobettelini** [elkowar/eww#736]
Hello,
I would like to write widgets directly in Rust, without the Yuck layer.

I assume this is possible since the crates are separated, as they should be, but I haven't found any examples on how to do such a thing. Reading the [documentation](https://docs.rs/eww/0.0.1-alpha.2/eww/) is kind of hard, I would need to desperately dig through the code and see what happens after the Yuck code is parsed.

I did not find anything on the internet about this, any help is appreciated.

Thanks

**Comment by viandoxdev** [comment]
First of all, the documentation you linked is not for this eww (its for this [eww](https://github.com/LU15W1R7H/eww)) which is not the same thing.

Your best bet is probably to patch eww, and run your own binary. There is no runtime API to handle custom widget (none that I'm aware of anyways). Documentation wise just look at the other widgets in `crates/eww/src/widgets/widget_definitions.rs`. Most of those are 1 to 1 mappings to gtk widgets and are very simple. If you want to look at something more powerful, look at the transform, graph or circular progress widget (each have their own file in `crates/eww/src/widgets/`). You'll probably also want to check out the gtk-rs and gtk (3) documentation.

**Comment by paolobettelini** [comment]
Thanks, I already know gtk-rs so that should be good.

**Comment by elkowar** [comment]
I'd also strongly recommend against trying this: eww is more or less just a state management layer and configuration syntax on top of gtk-rs. If you try to interact with the gtk widgets wrapped by eww through the internal api, you'll have a NICER api if you just use gtk-rs directly, or even use something like relm (which is what I'd propose to look into, in your case).

If, of course, you primarily want to keep using eww, and just want to add a new widget, then go ham! And I'd of course appreciate a PR for any new interesting, reusable builtin widgets, if that's the case😉
