### ISSUE TITLE
[FEATURE] use json field in for widget

### ISSUE THREAD

**Issue by matthis-k** [elkowar/eww#737]
### Description of the requested feature

Use json fields with the `for` widget

### Proposed configuration syntax

```
(for workspace in ${var.list}
and/or
(for workspace in var.list
```

### Additional context

I think it would make many widgets with non-trivial state a lot easier when you do not have to use multiple listeners instead of one larger state. To effectively use that larger state you would have to be able to use array fields of JSON objects for the `for`-widget.
I think this would have a great synergy with allowing field updates, like in  #322

**Comment by elkowar** [comment]
This should already work, I'd you use the correct syntax to embed a simplexpr in yuck code, via `{foo.bar}`:
```
(for x in {foo.bar}
 ...)
```

**Comment by matthis-k** [comment]
I see, so my syntax was off, thank you for the heads up
