### ISSUE TITLE
[BUG] Failed to open window on wayland when compiled with both x11 and wayland backends

### ISSUE THREAD

**Issue by JSkold** [elkowar/eww#739]
If eww is built with the new default feature set (both x11 and wayland) windows fails to open on wayland with the error:
> Action failed with error: failed to open window `example`
>
>Caused by:
>    Failed to get x11 window for gtk window

Digging around in the code I tracked it to this x11 specific code block which is included regardless of the current display backend.
https://github.com/elkowar/eww/blob/e76206817de1cb86ec431dcff7d4b04c8b7d36fc/crates/eww/src/app.rs#L468
Removing it allows me to open windows as expected. This code block must only be executed when the x11 backend is in use, otherwise it breaks wayland.

**Comment by JSkold** [comment]
Sorry, I realize that I managed to bypass the bug template by selecting new issue on a specific line of code.

**Comment by viandoxdev** [comment]
I'm not sure if building with both X11 and Wayland is supposed to be supported ? I reckon removing the code block would break on X11 no ?

**Comment by JSkold** [comment]
I assumed it was since https://github.com/elkowar/eww/commit/642983a066931225aef43d4fba77c6d99e8d580d.

No removing the code block is not the solution, I just did that to confirm my suspicion that the block was the cause of my issue. The real solution would be to only run it for the x11 backend.

**Comment by xorander00** [comment]
I just ran into the same thing and saw this issue afterwards.  
  
Personally, my suggestion would be to get rid of the --force-wayland flag and have an explicit --prefer-x11 or --prefer-wayland flag to change the order in which they are tried, then remove those conditional compile blocks and replace them to use the appropriate backend at runtime based on those flags.   
  
Reason being that it doesn't necessarily have to be one or the other, but can be both. Checking for WAYLAND_DISPLAY and then DISPLAY or vice-versa.

**Comment by elkowar** [comment]
This has been fixed in the latest commit on master ^^ sorry
