### ISSUE TITLE
[FEATURE] Add option to return jq command with raw output

### ISSUE THREAD

**Issue by dtop129** [elkowar/eww#745]
### Description of the requested feature

For my use case, I retrieve the active window name from a JSON returned from Hyprland IPC, but since there is no option to get raw output, like with the command line option with `jaq --raw-output ....`, the output is `"somethinginsidequotes"`.

I could remove the quotes by wrapping the jq call inside a replace call that removes the first and last quote characters `"${replace(jq(...), "\(^\"\|\"$\)", "")}"`, but it would be cleaner to have this feature inside jq natively.

### Proposed configuration syntax

Maybe just add alongside the normal `jq` function a `jq_raw` function, as not to break current configurations.

**Comment by johnazule** [comment]
I have just come across the same thing. Would be a very useful feature, or just have an optional third argument for jq for flags such as `jq("[1,2,3]", ".[]", "rc")`
