### ISSUE TITLE
[BUG]     Couldn't upgrade reference, widget got deallocated (hyprland active workspace script)

### ISSUE THREAD

**Issue by jacekjarosz55** [elkowar/eww#746]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm getting this weird error in my logs while my bar is open
I don't really know what it means, and everything seems to work fine despite it being shown as an error

```
2023-04-11T20:10:08.785Z ERROR eww::error_handling_ctx > Error while updating UI after state change

Caused by:
    Couldn't upgrade reference, widget got deallocated

```

### Reproducing the issue

1. Use the config provided as attachment
2. Run a hyprland session
3. Open the 'bar' window
4. Open eww logs
5. Switch to a different workspace
[eww.zip](https://github.com/elkowar/eww/files/11204621/eww.zip)

### Expected behaviour

Preferably no error message there? I'm not really sure what the cause is.

### Additional context

I'm using an NVIDIA graphics card in hyprland (it's unsupported but everything else seems to work fine for now) 

The bar fully works but I don't know whether it causes any memory leaks

**Comment by jacekjarosz55** [comment]
It does seem related to #674

**Comment by jacekjarosz55** [comment]
Sorry, it seems to be fixed when compiling from master

**Comment by isaacbrown92** [comment]
I have this error too!

```
 2023-05-06T22:43:12.573Z ERROR eww::error_handling_ctx   > Error while updating UI after state change

Caused by:
    Couldn't upgrade reference, widget got deallocated
 ```
 
 I have a Haskell script which updates my workspaces. And it works great, but random starts failing with this error message. Rebooting does not resolve the issue.

**Comment by jbcaramar** [comment]
I'm setting up hyprland and eww for the first time running wayland on Arch and this is the main error I'm encountering in the eww log so far. It occurs whenever I change workspaces, using nearly verbatim the code provided on the hyprland site for setting up workspaces in eww. The message apparently gets generated several times for each of my 8 defined workspaces; I see the message repeated 23 or 31 times usually.

Fortunately, I've encountered no functional problems related to these errors. Still trying to pin down the exact cause, though, so I can fix it!

**Comment by jacekjarosz55** [comment]
> I'm setting up hyprland and eww for the first time running wayland on Arch and this is the main error I'm encountering in the eww log so far. It occurs whenever I change workspaces, using nearly verbatim the code provided on the hyprland site for setting up workspaces in eww. The message apparently gets generated several times for each of my 8 defined workspaces; I see the message repeated 23 or 31 times usually.
> 
> Fortunately, I've encountered no functional problems related to these errors. Still trying to pin down the exact cause, though, so I can fix it!

I have a very old laptop, and can tell that the bar gets progressively more slower over time with this error. Also the error  log file it generated was almost 20gb for me!

But, just as I said, the issue seems to be gone after compiling eww from master, so its likely it will be fixed with the next release
