### ISSUE TITLE
[BUG] Cannot compile due to cargo error

### ISSUE THREAD

**Issue by SUFandom** [elkowar/eww#754]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Debian 12 - sid/bookworm

latest cargo and rustc installed

cargo couldn't finish the compilation due to linker error

re-cloning and running cargo still persists (4 times now)

### Reproducing the issue

1. Downloading the latest rust libraries (cargo, rustc.
2. git clone the project
3. cd to directory ~/Downloads/eww
4. typed this: `cargo build --release --no-default-features --features x11 ` since im on x11
5. error about linker comes up.

### Expected behaviour

Finish compiling and eww should have been usable

### Additional context

![image](https://user-images.githubusercontent.com/70519093/234109502-7e0891b4-4069-4f89-9cd4-41e299b1db90.png)

**Comment by SUFandom** [comment]
the sudo part is just there because to ensure cargo is working (im also coding rust currently and that fixed my code compile propblem)

**Comment by dr-iroh** [comment]
I think you need to install build-essential

sudo apt install build-essential

**Comment by bert003** [comment]
I tried to compile on Debian Bookworm and also arrived at this step where I figured out I needed to install `build-essential`.

However, a lot of errors kept coming up later on related to glibc, libgtk etc.

Can someone please list the full dependencies to install in Debian before starting the actual installation process? I would really like to include eww in my OS without installing extra libraries simply by trial and error.

**Comment by SUFandom** [comment]
ok, thanks for the help
