### ISSUE TITLE
[BUG] error_handling_ctx > Failed to initialize eww paths (FIXED)

### ISSUE THREAD

**Issue by webbb82** [elkowar/eww#758]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I installed via the github instructions. Im running hyprland and when trying to start eww i get 
error_handling_ctx > Failed to initialize eww paths     Caused by:
    Configuration directory /run/user/1000/eww does not exist
cd: no such file or directory: 

after install i did

target/release
❯ cd eww
❯ cd target/release

❯ chmod +x ./eww

❯ ./eww daemon

 2023-04-28T03:11:47.521Z ERROR eww::error_handling_ctx > Failed to initialize eww paths

Caused by:
    Configuration directory /run/user/1000/eww does not exist

and this is the error given

### Reproducing the issue

Like i said i just did the install for hyporland and at the end that is the error

### Expected behaviour

to have eww start

**Comment by viandoxdev** [comment]
Well, looks like the directory /run/user/1000 doesn't exist, what system are you on ? It should be automatically by your login daemon. How do you run hypr ?

**Comment by webbb82** [comment]
i can confirm the dir is there i checked it out. im on arch linux hyprland

**Comment by elkowar** [comment]
Do you have any funky environment variables set up or something?

**Comment by webbb82** [comment]
> 

I cant say that im aware of any. Yesterday I added this to my .zshrc file and I think it fixed the issue 
```
if [ -z "$XDG_CONFIG_HOME" ] ; then                                                   
   23      export XDG_CONFIG_HOME="$HOME/.config"                                            
   24  fi                                                                                    
   25  if [ -z "$XDG_DATA_HOME" ] ; then                                                     
   26      export XDG_DATA_HOME="$HOME/.local/share"                                         
   27  fi                                                                                    
   28  if [ -z "$XDG_CACHE_HOME" ] ; then                                                    
   29      export XDG_CACHE_HOME="$HOME/.cache"                                              
   30  fi                                          
```
and after that im finally able to get past the issue. I also had another issue but Iwas able to fix that by downloading the eww program off yay along side the original install from the instructions. but I did get it working
