### ISSUE TITLE
[BUG] some eww commands creates extraneous new lines

### ISSUE THREAD

**Issue by ahmedkhalf** [elkowar/eww#76]
## Describe the bug
Some eww commands creates extraneous new lines even though they aren't supposed to output anything.
An extraneous new line is an unwanted newline character `"\n"` that gets printed on a blank like at the end of the command. This results in two double line character on the terminal `"\n\n"` creating blank space.

## Reproducing the issue
(when daemon running)
|Command|Extraneous new line?|
|--------------|--------------------------|
| eww open [window_name] | ✓ |
| eww close [window_name] | ✓ |
| eww kill | ✓ |
| eww daemon | ✓ |
| eww -d open [window_name] | ✓  |
| eww  | ✓ |
| eww update "x=5" | ✓ |
| eww state | ☓ |
| eww -h | ☓ |

(when daemon **not** running)
|Command|Extraneous new line?|
|--------------|--------------------------|
| eww close [window_name] | ☓ |
| eww kill | ☓  |
| eww daemon | ☓  |
| eww -d open [window_name] | ☓  |
| eww | ☓ |
| eww update "x=5" | ☓ |
| eww state | ☓ |
| eww -h | ☓ |

I believe there is a clear correlation between daemon running and new line characters getting printed. 

## Expected behavior
Don't print an extra line on commands that aren't supposed to output anything.

## Additional context
End my suffering and fix this please.
![image](https://user-images.githubusercontent.com/36672196/103149482-4478fe00-4783-11eb-9a4a-9bff0b96df17.png)

**Comment by elkowar** [comment]
Thanks a lot for this extremely well written and researched issue! Fixed now!
