### ISSUE TITLE
opening an exclusive window on hyprland crashes it [BUG] 

### ISSUE THREAD

**Issue by wylited** [elkowar/eww#760]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

My configuration is rather simple. 
```yuck
(defwindow bar
           :monitor 0
           :geometry (geometry :x "0%"
                               :y "97.5%"
                               :width "100%"
                               :height "2.5%"
                               :anchor "top center")
           :stacking "fg"
           :exclusive true
           :namespace "eww_bar"
  "wyli")
 ```
a simple what should be bar that takes up the bottom strip of the screen.

However, when I run this on hyprland, this first resets the screen so that I can only see the wall paper and the bar at the bottom. And then upon further interaction (when i attempt to spawn a kitty terminal with a keybind) crashes hyprland and sends me back to sddm's login screen.

This *does not occur* when it is set as `:exclusive false`

In plasma's wayland variant. this works as expected and there is a bar that can also be focused on.  

furthermore, `eww log` only shows this.
![image](https://user-images.githubusercontent.com/44154103/235309433-9dd0330c-6a4c-4d04-bdc3-fe596d4a509e.png)

### Reproducing the issue

On endeavour os using the linux zen kernel 6.2.10-zen1-1-zen
build eww using the wayland feature flag
`cargo build --release --no-default-features --features=wayland`

set your ~/.config/eww.yuck as
```yuck
(defwindow bar
           :monitor 0
           :geometry (geometry :x "0%"
                               :y "97.5%"
                               :width "100%"
                               :height "2.5%"
                               :anchor "top center")
           :stacking "fg"
           :exclusive true
           :namespace "eww_bar"
  "wyli")
 ```
 and clear eww.scc
 
 start the eww daemon
`eww daemon`

open the bar
`eww open bar`

### Expected behaviour

For Hyprland to not remove all windows and then crash when opening an eww window and provide exclusive space to the bar.

### Additional context

neofetch for additional system information:
![image](https://user-images.githubusercontent.com/44154103/235309339-696c85ca-0981-4fcd-8b27-6a43acb77f43.png)

the bar:
![image](https://user-images.githubusercontent.com/44154103/235309469-ff4321c0-8d18-4974-b6f7-d5768e5dfd28.png)

**Comment by wylited** [comment]
I also forgot to mention the additional debug logs if that may help

```
(eww:233501): Gtk-WARNING **: 23:05:40.596: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(eww:233501): Gtk-WARNING **: 23:05:40.596: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
 2023-04-29T15:05:40.610Z DEBUG eww::server > Initializing script var handler
 2023-04-29T15:05:40.628Z INFO  eww::ipc_server > IPC server initialized
 2023-04-29T15:05:41.928Z DEBUG eww::ipc_server > received command from IPC: Ping
 2023-04-29T15:05:41.928Z DEBUG eww::ipc_server > Waiting for response for IPC client
 2023-04-29T15:05:41.928Z DEBUG eww::app        > Handling event: NoOp
 2023-04-29T15:05:41.928Z DEBUG eww::ipc_server > received command from IPC: OpenWindow { window_name: "bar", screen: None, pos: None, size: None, anchor: None, should_toggle: false }
 2023-04-29T15:05:41.929Z DEBUG eww::ipc_server > Waiting for response for IPC client
 2023-04-29T15:05:41.929Z DEBUG eww::app        > Handling event: OpenWindow { window_name: "bar", pos: None, size: None, anchor: None, screen: None, should_toggle: false, sender: DaemonResponseSender(UnboundedSender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x7fe7d8001570, tail_position: 0 }, semaphore: Semaphore(0), rx_waker: AtomicWaker, tx_count: 1, rx_fields: "..." } } }) }
 2023-04-29T15:05:41.929Z INFO  eww::app        > Opening window bar
Gdk-Message: 23:06:11.909: Error reading events from display: Broken pipe
```
Hyprland crashes after
`2023-04-29T15:05:41.929Z INFO  eww::app        > Opening window bar`

furthermore, the exact signal given is

`fish: Job 1, 'Hyprland' terminated by signal SIGABRT (Abort)play error: Connection reset by peer_Tp&, const _Tp&) with [_Tp = double]: Assertion \`!(__hi < __lo)` falied.

**Comment by elkowar** [comment]
@vaxerski, I assume this is more of a hyprland issue than an eww issue 🤔

**Comment by vaxerski** [comment]
You've got the nerve to say my software has issues 😤
