### ISSUE TITLE
[FEATURE] `eww close-all` to close all active eww widgets

### ISSUE THREAD

**Issue by Axarva** [elkowar/eww#77]
## Description of the requested feature
When many windows are launched, it often becomes cumbersome to close them one by one. Instead, if eww supported a `close all` command, it would be helpful. `killall eww` or `eww kill` works, but that kills the eww server as well, which means widgets launch slower next time.

## Proposed configuration syntax
`eww close all`

# Additional context
I dunno

**Comment by elkowar** [comment]
I'd say we should add a new subcommand `close-all` instead, so we can do `eww close-all` - otherwise the syntax would be ambiguous, as you could theoretically have a window named `all` open.

**Comment by Axarva** [comment]
Yep that makes sense, will start working on it!

**Comment by elkowar** [comment]
fixed by #80
