### ISSUE TITLE
[BUG] deflisten not working on a python script

### ISSUE THREAD

**Issue by Angeloth2077** [elkowar/eww#773]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

It is pretty simple, I'm trying to make a hyprland workspaces widget. I created a simple python script to make it dynamic and then generate an output that can be read by a deflisten, however, it does not render on my bar like if no widget was specified there.

I'm not really sure if this is a bug or not. Everyone else uses a bash script rather than a python script for achieving this exact same task, maybe I should use a bash script?

### Reproducing the issue

# Python script
It is just a button right now, with no functionality 

```py
#!/usr/bin/env python
import subprocess
import time

workspaces = ["󰨞", "󰇧", "" ,"󰙯"]
current_workspace = subprocess.run("hyprctl activewindow | grep 'workspace: ' | cut -d' ' -f2", shell = True, capture_output = True, text = True)
current_workspace = int(current_workspace.stdout)
output = """
    (eventbox :onhover "eww update workspace_hover=true" :onhoverlost "eww update workspace_hover=false"
        (box :class "workspaces" :space-evenly false
            (button :class "workspace0" "󰨞")
            (revealer
                :reveal workspace_hover
                :transition "slideright" 
                :duration "250ms"
                (label :text "VScode")
            )
        ) 
    )
"""
print(output)
```

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# eww.yuck

```lisp
(defvar workspace_hover false)

(deflisten workspace :interval "1s" "scripts/workspace.py")       ;;here the issue

(defwidget workspaces []                                 
  (literal :content workspace)
)

(defwidget left []
  (box
    :orientation "h"
    :space-evenly false
    :class "left-module"

    (home)
    (workspaces)
    (music)
  )
)

defwidget bar_1 []
  (centerbox :class "bar_class"
    (left)
    (center)
    (right)
  )
)


(defwindow bar
  :stacking "bg"
  :class "bar"
  :orientation "horizontal"
  :exclusive true
  :windowtype "dock"
  :monitor 0
  :hexpand "false"
  :vexpand "false"
  :focusable false
  :geometry (geometry 
    :width "100%"
    :height "28px"
    :anchor "top center"
    :y "0px"
  )
  (bar_1)
)

```

### Additional context

If I paste the script's output onto the eww.juck file, it works perfectly, so I'm sure is the deflisten.
Also, I tried replacing the deflisten by a defpoll, and it works, but is not the most satisfactory way to solve the Issue, since the height of the icons is half of what it should be, and the SCSS font color defined (not in the script right now) reloads on each interval, making an annoying blink each interval

**Comment by charlesrocket** [comment]
Try to append `python` to the command string to explicitly point to the interpreter. Apparently you can't rely on shebang only yet as far as I can tell.

**Comment by viandoxdev** [comment]
See #514

**Comment by Angeloth2077** [comment]
> Try to prepend `python` to the command string to explicitly point to the interpreter (full path?). Apparently you can't rely on shebang only yet as far as I can tell. But looking at the script this might not be the case since swapping listen/poll should not be the cure. You just print out the output so theres nothing to listen? https://elkowar.github.io/eww/configuration.html#adding-dynamic-content

Hello and thank you for your attention, I tried adding python to the script and using the full path, it didn't work either. I also thought that being just a single output, it doesn't really have anything to listen to, so I simply made another version with everything inside an infinite while loop, so a new output is printed each second, that's why the time library is imported there, had no luck so far...

**Comment by exit91** [comment]
AFAIK deflisten requires the script to output one single line of data every time an update occurs. Therefore if multiple lines are outputted at once, eww will still parse each line as its own update.

Luckily all eww programs can be squished into a single line, so maybe try that.

**Comment by elkowar** [comment]
exit91 is exactly correct. If you try to output multiple lines of code to a deflisten, eww has no way of knowing how to split the output -- where does the next value start?

Thus, you'll need to make sure that each value is output on a single line.
