### ISSUE TITLE
Failed to turn `` into a value of type f64

### ISSUE THREAD

**Issue by HardoMX** [elkowar/eww#787]
Sorry if this is the wrong kind of thing to bring up here, if so please direct me to the correct sources. 
---
I am trying to get a sacle widget to show my current pipewire volume through a wpctl command. My `(defpoll)` looks like this:
```
(defpoll vol_perc :interval "3s"
    "wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -d 'Volume: ")
```

This outputs a string that says e.g 0.45, and I know it works as it outputs that in the terminal, and `:draw-value "${vol_perc}` shows 0.45. However, when I set `:value vol_perc` I get the error `Failed to turn '' into a value of type f64`

So my question is if anyone know how to get this to work, I have even tried to use a python script that for sure outputs just the float 0.45, but it still can't convert to f64

**Comment by HardoMX** [comment]
I have also tried to do just `:value 50`, and that doesn't work. Currently my entire scale code is like this: 
```
...
(scale :class "volume-bar"
           :width 100               (maybe not neede)
           :value 50                  (will be changed to vol_perc*100 when working)
           :draw-value false
           :tooltip "${vol_perc*100}"               (This shows correctly, unlike :value that complains)
           :orientation "horizontal"
           :max 100
           :min 0
           :onchange "wpctl set-volume @DEFAULT_AUDIO_SINK@ {}%")
...
```

**Comment by HardoMX** [comment]
When messing around with my scss file I notice´d that the slider works when the scss fails to load properly (so the "default" css is applied) so it seems to be a css issue and not actually a problem with converting to float, although it is still weird to get errors that aren't errors, also happens with a hashmap (or dict or whatever)

**Comment by HardoMX** [comment]
Still can't get it to show up though

**Comment by nativerv** [comment]
Also happens with `jq(workspaces, '.[] | select(.id == "${id}") | .windows') > 0` on `workspaces` values like `[{"id":"1","windows":4},{"id":"2","windows":0},{"id":"3","windows":4},{"id":"4","windows":1},{"id":"5","windows":4},{"id":"6","windows":0},{"id":"7","windows":0},{"id":"8","windows":1},{"id":"9","windows":0},{"id":"10","windows":0}]`
I think it's because it's `:initial "[]"`, but what's the problem after it's populated?

**Comment by newor0599** [comment]
From the example config, they use amixer to get the volume's value, and it work fine.

**Comment by Mathanet** [comment]
I found it works with setting the initial property. Could someone explain why?
