### ISSUE TITLE
[BUG] eww sometimes utterly breaks down and starts lamenting it's fate (JK. It laments with `OS error 98`)

### ISSUE THREAD

**Issue by Axarva** [elkowar/eww#79]
## Describe the bug
When launching multiple windows through a script (mainly to bind these sets of widgets to a keybind on a window manager) eww sometimes... well, just breaks down with `OS error 98: address not available.`

## Reproducing the issue
Take any sample script, make it ready to launch multiple ewws, and bind the script to your window manager. Pressing the keybind sometimes works, sometimes doesn't, not to mention starting of only some widgets, which, of course, looks weird.
`killall eww` or `eww kill` work, that's what I had been using to reproduce the issue. The issue happens a ~bit less often~ I haven't noticed it happening  if `eww -d` is running and you only close the windows

## Expected behaviour
All windows to be launched properly and without delay.

## Additional context
*Will upload screenshots soon*

**Comment by alx365** [comment]
Also happens to me sometimes.

**Comment by elkowar** [comment]
Has this appeared again since the rework of the daemon and since the introduction of async in #85 ?
If not, I'd say we could close this, right?

**Comment by Axarva** [comment]
No, hasn't appeared at all, I suppose we can now close this
