### ISSUE TITLE
[SURELY NOT A BUG] Couldn't compile

### ISSUE THREAD

**Issue by Darkpepito** [elkowar/eww#793]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I am not able to compile `eww` using cargo build. I tried some solutions in issues but they didn't work.

### Reproducing the issue

`cargo build --release --no-default-features --features x11`

It gives me multiple thing like this:  
```error[E0554]: '#![feature]' may not be used on the stable release channel  
 --> crates/simplexpr/src/lib.rs:6:12  
   |  
 6 | #![feature(once_cell)]  
   |            ^^^^^^^^^  
```

I tried to do this command :  
`rustup default nightly`  
but it changes nothing.

### Expected behaviour

Compiling normally.

### Additional context

```  
   Static hostname: darkpepito-Latitude-E5470
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: c86d35c6ea5f47a092e0fb3750d381eb
           Boot ID: e93752c6db2b4e1b87c48bee6167e332
  Operating System: Zorin OS 16.2
            Kernel: Linux 5.15.0-73-generic
      Architecture: x86-64
```

Thank you for your help !

**Comment by elkowar** [comment]
What rust version are you using? The error message you provided doesn't show the entire error, so I have no way of checking what causes it. This is indeed not a bug.

**Comment by Darkpepito** [comment]
rustc return me version 1.65.0  
I didn't find the needed version in documentation.  
Here is the complete error message:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:1:1
  |
1 | #![feature(box_patterns)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:2:1
  |
2 | #![feature(pattern)]
  | ^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:3:1
  |
3 | #![feature(try_blocks)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:4:1
  |
4 | #![feature(unwrap_infallible)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:5:1
  |
5 | #![feature(never_type)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:6:1
  |
6 | #![feature(once_cell)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:2:12
  |
2 | #![feature(pattern)]
  |            ^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:4:12
  |
4 | #![feature(unwrap_infallible)]
  |            ^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/simplexpr/src/lib.rs:6:12
  |
6 | #![feature(once_cell)]
  |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `simplexpr` due to 9 previous errors
```

**Comment by elkowar** [comment]
As the error (kind of) tells you, you're on stable rust, whilst eww requires you to ue a nightly compiler.

**Comment by Darkpepito** [comment]
I understood, but how can I switch to nightly ?

**Comment by viandoxdev** [comment]
The preferred method is using [rustup](https://rust-lang.github.io/rustup/concepts/channels.html), but you also might be able to go through your package manager (I wouldn't recommand)
