### ISSUE TITLE
[FEATURE] Construct json object from deflisten input

### ISSUE THREAD

**Issue by chronicc** [elkowar/eww#797]
## Scenario

I want to build a notification overlay for my eww config which displays all collected notifications from libnotify. This gives me the possibility to inspect those notifications at my custom pace (e.g. not inside a dnd/developing phase). I don't like the notification popups disturbing my focus.

For this to realize I plan on using a variable containing a json object. The object contains a list of all notifications since the start of eww (somehow collected from libnotify). Reading the eww documentation I did not find a plausible way of creating this json object. The only thing that is in the area of this is the `deflisten` function which I can use to run a cli command to collect the notifications. However from my understanding the variable only stores the last line of the cli output (e.g. when using playerctl or tail).

I need a way to construct the json object from the cli output. A function which collect the output like `deflisten` and appends it to the json object.

Also I would need a way to remove entries from this json object inside eww.

## Request

I would like to have a function (or multiple) which supports the above scenario. Is it possible for you to implement such a function in eww?

Otherwise I would need to create a file with a script which creates the json object while the file is constantly read by `deflisten` (e.g. by doing something like `watch cat $file`.

## Example Syntax

```yuck
(defjson notifications
  :initial ""
  :timestamp true
  `playerctl --follow metadata --format "Playing {{artist}} - {{title}}" || true`)
```

## Example Content of `notifications`

```json
{
  [
    {
      "timestamp": "1471283819",
      "text": "ArtistA - Song"
    },
    {
      "timestamp": "1278492182",
      "text": "ArtistB - Song"
    }
  ]
}
```

### Additional context

I'm not sure how the timestamps would be appended - if this is something, that is integrated to the `defjson` function or if I need to construct the json sub object which then is only appended to the variable.

**Comment by elkowar** [comment]
Parsing output of other applications into JSON is definitely out-of-scope for eww, i'd say. You should be able to write a script that does the same without writing to additional files or anything like that, just listen to the output of your playerctl command and work on the output of that command, i.e. with a `while read` loop
