### ISSUE TITLE
[FEATURE] Unique binary for both Xorg and Wayland

### ISSUE THREAD

**Issue by D3vil0p3r** [elkowar/eww#798]
### Description of the requested feature

For the users, it could be very useful to compile a unique binary that works for both Xorg and Wayland. It could be useful because, if a user switches often among both of the two environments, it avoids to rebuild eww, removing the previous conflicting one and installing the new one each time it switches.

### Proposed configuration syntax

A good approach could be adding this setting in the config file and/or as parameter for `eww` command, for example `eww --x11` or `eww -wayland`.

**Comment by elkowar** [comment]
642983a implemented exactly this, eww now allows to build for both wayland and X11 simultaneously, and does so by default. It will try to infer if it's running on wayland or X11, but allows you to force wayland-usage using `--force-wayland`

**Comment by D3vil0p3r** [comment]
@elkowar thank you for the answer. Where can I find the building instructions for eww to both Xorg and Wayland?
