### ISSUE TITLE
[BUG] EWW_TIME not recognised as variable

### ISSUE THREAD

**Issue by HardoMX** [elkowar/eww#801]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Having updated to the newest EWW version by rebuilding it from the main branch I tried to use the new `{EWW_TIME}` variable. However I get this error when trying to use it: 
```
error: No variable named `EWW_TIME` in scope
   ┌─ /home/arch/.config/eww/dashboard/eww.yuck:67:30
   │
67 │     (label :text {formattime(EWW_TIME, "%H") >= 5 && formattime(EWW_TIME, "%H") < 11 ? "Morning" : 
   │                              ──────── Used here
   │
   → Hint: Either define it as a global variable, or add it to the argument-list of your `defwidget` and pass it as an argument
   → Hint: If you meant to use the literal value "EWW_TIME", surround the value in quotes
```

I am pretty sure I have updated eww correctly, but i could of course be wrong and this just be me not doing that part correctly. 

### Reproducing the issue

For me this code gets the same issue: 
```
(defwidget time []
    (label :text {formattime(EWW_TIME, "%H")}))

(defwindow time
    :monitor 0
    :geometry (geometry :x "0%"
                        :y "1%"
                        :width "90%"
                        :height "5%")
    :stacking "fg"
    :exclusive false
    (time))
```

### Expected behaviour

To get the UNIX time from `EWW_TIME`

### Additional context

As I said above, this might just be me who did something wrong while rebuilding EWW

**Comment by viandoxdev** [comment]
Have you tried restarting the daemon (`eww kill`, or simply rebooting) ?

**Comment by d-hain** [comment]
Same thing here
![image](https://github.com/elkowar/eww/assets/57726396/b7e36f82-7c3c-4502-ba07-842fab2b5dbf)

**Comment by Gu-Ramos** [comment]
Also happening to me. 
![2023-06-17_20h04m55s](https://github.com/elkowar/eww/assets/72244255/4fe35e9d-0f08-43ed-960e-cd650994fae9)
![2023-06-17_20h13m52s](https://github.com/elkowar/eww/assets/72244255/746d9c94-6ac2-43a3-a7e1-c57b51161849)

**Comment by cleitondacosta** [comment]
This feature was recently added. See 4d63f6d.

So check if your eww is updated and if it's synced with git. For example, for Arch, I found [eww-x11-git](https://aur.archlinux.org/packages/eww-x11-git) and [eww-wayland-git](https://aur.archlinux.org/packages/eww-wayland-git). I haven't tried them out, so I recommend taking a look if you're going to install it.

Anyway, what I'm doing is compiling the master branch from source [following the instructions](https://elkowar.github.io/eww/eww.html#building). I can use things like `EWW_TIME` and `formattime` function without problems:

```
(label :text {formattime(EWW_TIME, "%H:%M:%S | %d/%m/%Y")})
```

![image](https://github.com/elkowar/eww/assets/19880317/3e3c6112-d2b7-435a-8cf6-225d46973bed)

**Comment by elkowar** [comment]
Yea, I assume you're on an outdated version of eww here -- ensure you're compiling from latest master! if that doesn't fix it, feel free to reopen the issue

**Comment by d-hain** [comment]
> Yea, I assume you're on an outdated version of eww here -- ensure you're compiling from latest master! if that doesn't fix it, feel free to reopen the issue

Yeah that was it as I was using the version in the fedora copr

**Comment by HardoMX** [comment]
This is now an old issue, but as I have gotten back into my configs I finally fixed my issue. 

It was that I had installed eww through a package manager, so even though I did compile everything correctly, I still used the old binary file
