### ISSUE TITLE
[BUG] some scss functions no longer work

### ISSUE THREAD

**Issue by Abaan404** [elkowar/eww#808]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

After updating eww to the latest commit (coming from the release branch) I noticed it no longer recognized common scss functions (notably `string.unique-id()` and possibly others I haven't checked).
After some digging I found that removing the `default-features` flag from grass in `Cargo.toml` fixes this issue

Seems like this change was made for [faster build times](https://github.com/elkowar/eww/commit/7a0e1b77f24ee89d627e552f9abc55eb636aaaa6) and should have no noticeable impact however I lack much knowledge of rust and this project so unsure if it has any unintended issues.

### Reproducing the issue

use the following scss code
```scss
@use "sass:string";

$unique: string.unique-id();
```
and it will not execute the function

### Expected behaviour

it should've ran the function as expected

**Comment by FieldofClay** [comment]
I have also come across this issue, except for the `math.random()` function. Confirming that removing `default-features` from grass resolves this.
