### ISSUE TITLE
[BUG] rust features rename drain_filter, hash_drain_filter

### ISSUE THREAD

**Issue by electric-tao** [elkowar/eww#810]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Due to changes in the rust nightly toolchain, compilation errors appear.
You need to rename features in main.rs

- drain_filter -> extract_if
- hash_drain_filter -> hash_extract_if 

as well as the corresponding methods.

**Comment by gh0stzk** [comment]
Same error here, trying from aur and manually git clone from eww page, gives that error.

**Comment by Ultra980** [comment]
I don't know if this is the place to report this, but a similar (similar cause) error that I get is `box_syntax has been removed`
