### ISSUE TITLE
Eww doesn't escape parenthesis in Yuck vars [BUG] 

### ISSUE THREAD

**Issue by sandraev** [elkowar/eww#814]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm currently writing an Eww config (thank you so much for this amazing program, btw!) and surprisingly, some of my `defpoll` var are not updated at all... It's really weird, since I've severval other vars that work very well. I thought I'd seen another problem similar to this one, but I can't find it, so here's my report. My code for the var is the following:

```
(defpoll bluetooth-state
    :interval "1s"
    "bluetoothctl show | pcregrep -o '(?<=Powered:\s)(yes|no)'"
)
```

As you can see, there's nothing suspicious, but maybe it's a question of privileges? Or because I'm using a regex in the var program?

`eww logs --debug` just outputs:

```
warning: The script for the `bluetooth-state`-variable exited unsuccessfully
   ┌─ ./_bar.yuck:48:5
   │
48 │     `bluetoothctl show | pcregrep -o '(?<=Powered:\s)(yes|no)'`
   │     ─────────────────────────────────────────────────────────── Defined here
   │
   → Failed with output:
```

And it's not really helpful... :sweat_smile: 

### Reproducing the issue

You should just repeat my config...

### Expected behaviour

Nothing to add.

### Additional context

I'm running Garuda Linux, with Wayland and Hyprland.

**Comment by sandraev** [comment]
I found a workaround to get the status of my bluetooth : get the value directly trough D-Bus instead of triggering the daemon. And it's _much simpler_ in terms of data pre-processing, but my question stay... (even if this issue is not fatal for anyone). At the moment, I'm leaning more towards a lack of permissions for Eww.

**Comment by sandraev** [comment]
In order to figure out what was happening, I changed the group used by the command when executed, using the Linux command `sg`, but nothing changed. So definitely not a question of privileges.

**Comment by sandraev** [comment]
However, I think I've figured it out... I looked for similarities between another problematic `defpoll` var and I guess **Eww doesn't like the use of parentheses in var commands** !
They don't seem to be enough escaped in Yuck syntax. I'd have to try using them in an XML configuration file to test this hypothesis, but I'm pretty sure... 😀

**Comment by sandraev** [comment]
For those who are currently facing the same issue, here's a workaround :

```
(defpoll bluetooth-state
    :interval "1s"

    `bluetoothctl show | pcregrep -o "(?<=Powered:\s)(yes|no)" `
)
```

You must enclose the command in **single quotes** and the problematic regex in **double quotes**. I hope this helps.

**Comment by elkowar** [comment]
I think what's happening is that the \s is getting unescaped by eww, rather than anything to do with parentheses... parens really shouldn't matter in a regex. note that you can always use `eww debug` to see what eww _reads_ your code as, so you can look at the parsers interpretation of your defpoll. In this case, it looks fine otherwise, and seems to be working for me as expected.
Feel free to reopen if I'm missing something here, but I haven't been able to reproduce any issues linked to parentheses in strings
