### ISSUE TITLE
Struts not working on Wayland. [BUG] 

### ISSUE THREAD

**Issue by Oglo12** [elkowar/eww#819]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

On Bspwm, an Xorg window manager, I used Eww to create a bar. Now I use Hyprland, and when I tried to use the bar, I noticed everything worked fine, except for the struts. Eww cannot reserve space for some reason! I know it is possible considering Waybar does it just fine!

### Reproducing the issue

Just specify a window that contains (struts :distance "40px" :side "top"), AKA, just make a bar.

### Expected behaviour

Expected behavior? Well, if it wasn't clear already, I want the Wayland compositor/WM to actually reserve space when Eww asks for it!

### Additional context

I am using the `eww-wayland` package on Arch Linux.

**Comment by CardboardTurkey** [comment]
I'm assuming you're using `struts` as part of the `reserve` property. `reserve` is only for X11, on wayland you've gotta use the `exclusive` property (which is just a bool). https://elkowar.github.io/eww/configuration.html#wayland

**Comment by dancaer69** [comment]
I think that the exclusive option doesn't work. I'm using both waybar and eww. I use waybar for tray icons and taskbar and eww for a sidebar. I have set the exclusive option to "true", but the space doesn't reserved. If I maximize a window, the window doesn't cover the wabar's space at the bottom of the screen, but doesn't respect the reserved space of eww sidebar and grows behind it. I suppose it should grow until the edge of the sidebar as it does for waybar.

**Comment by lugeha** [comment]
For whatever reason (wlroots, eww, I'm not sure), but it appears you can only have one exclusive client per side. I've hit this trying to have two eww windows exclusive on the same side which didn't work.

**Comment by elkowar** [comment]
struts are an X11 thing, as CardboardTurkey has stated. on wayland, there's the :exclusive property, which does similar thing. I'm not sure about concrete limitations with multiple clients per side, that miiiight be a wayland limitation, or a compositor specific thing -- it's sadly nothing eww can influence, I assume.
