### ISSUE TITLE
How to style tooltip

### ISSUE THREAD

**Issue by sxreyna** [elkowar/eww#826]
Is it possible to style tooltips ? Something like
```
nowplaying tooltip {
    margin: 15px;
}
```

**Comment by viandoxdev** [comment]
see [this](https://github.com/elkowar/eww/issues/359#issuecomment-1003637509) in #359 . Also whenever you have a problem like that the GTK debugger is always helpful in figuring out the class names of sub elements

**Comment by sxreyna** [comment]
> see [this](https://github.com/elkowar/eww/issues/359#issuecomment-1003637509) in #359 . Also whenever you have a problem like that the GTK debugger is always helpful in figuring out the class names of sub elements

![image](https://github.com/elkowar/eww/assets/131453552/a7965817-26ca-42dc-83db-fe1263edf1bf)
Sorry I don't see ?

**Comment by sxreyna** [comment]
Anyway thanks so much for your help, Much appreciated.
