### ISSUE TITLE
[BUG] Window Reservation Limited to Standard Positions

### ISSUE THREAD

**Issue by trueNAHO** [elkowar/eww#827]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

There appears to be no way to reserve space that is not relative to the following positions: [`bottom`, `center`, `left`, `right`, or `top`](https://elkowar.github.io/eww/configuration.html?highlight=reserve#defwindow-properties).

### Reproducing the issue

Add the following `example` window to the `$HOME/.config/eww/eww.yuck` configuration file:

```lisp
(defwindow example
 :geometry (geometry :height "100%" :width "60px" :x "0" :y "0")
 :monitor 0
 :reserve (struts :distance "60px" :side "left")
 :stacking "fg"
 :windowtype "dock"
 "text")
```

Execute the following three commands:

```bash
eww open --restart example
eww open --restart --pos 200x100 example
eww open --restart --size 200x100 example
```

### Expected behaviour

The first `eww open --restart example` command opens the window and properly reserves space for it. However, the reserved space of the other two commands does not move with the windows.

#### Motivation

This issue is especially important for [leftwm](https://github.com/leftwm/leftwm) users, where physical monitors can be split into any number of workspaces. Attempting to reposition `eww` windows to a custom location currently seems impossible.

#### Related discussion and issues

- https://github.com/elkowar/eww/discussions/592
- https://github.com/elkowar/eww/issues/519
- https://github.com/elkowar/eww/issues/582
- https://github.com/elkowar/eww/issues/820

#### Related `eww open` options

```txt
$ eww open --help
OPTIONS:
    -p, --pos <POS>          The position of the window, where it should open. (i.e.: 200x100)
        --restart            Restart the daemon completely before running the command
    -s, --size <SIZE>        The size of the window to open (i.e.: 200x100)
        --screen <SCREEN>    The identifier of the monitor the window should open on
```

**Comment by trueNAHO** [comment]
[leftwm](https://github.com/leftwm/leftwm) users can use its [Gutters](https://github.com/leftwm/leftwm/wiki/Theme-Config#gutters) functionality as a workaround:

> Gutters allow you to set a dedicated area for your dock if LeftWM cannot set this up automatically.

**Comment by elkowar** [comment]
Yea, the EWMH struts I think _have_ to be on a screen edge, thus this limitation is sadly just inherent to X (or rather, the EWMH spec). If leftwm has a specific workaround for this, then I'd recommend just going with that
