### ISSUE TITLE
[BUG] Safe access operator fails to parse

### ISSUE THREAD

**Issue by 0xC0ncord** [elkowar/eww#837]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm trying to make use of the safe access operator `?.` but it fails to parse with this error:
```
error: Unexpected token `Dot` encountered
  ┌─ windows/safe-access-test.yuck:5:14
  │
5 │   (box {data?.test}))
  │              ─ Token unexpected
```

### Reproducing the issue

I reproduced this with this yuck:
```
(defvar data "{\"test\":\"this should work\"}")

(defwindow test
  :monitor 0
  (box {data?.test}))
```

### Expected behaviour

The yuck should parse successfully.

### Additional context

This is using eww 0.4.0-r1 on Gentoo.

**Comment by vladaviedov** [comment]
I tried running this code on the latest git commit (25e50ed), and yuck did not throw any error.

**Comment by 0xC0ncord** [comment]
> Edit: This feature was not even implemented in the version you are using.

Ah ha, that explains it. Thanks!
