### ISSUE TITLE
[BUG] add support to newline in text box

### ISSUE THREAD

**Issue by windwp** [elkowar/eww#84]
## Description of the requested feature
when you display a text have `\n`. it is display \n but i want it to be a new line.

**Comment by elkowar** [comment]
Implemented!

**Comment by SpanishHans** [comment]
Sorry to reopen. 

Cant find a way to make it work with :tooltip "something \n something"

Am i missing something?

**Comment by netfri25** [comment]
I have the same issue with the tooltip.
currently it is possible to get a newline inside a tooltip, if you simply enter a newline:
```lisp
(defwidget disk-usage []
  (label
    :text "${round(disk-used-kb / disk-total-kb * 100, 1)}%(/)"
    :tooltip "${replace(formatbytes(disk-used-kb * 1024), " ", "")} out of ${replace(formatbytes(disk-total-kb * 1024), " ", "")} on /
free ${replace(formatbytes((disk-total-kb - disk-used-kb) * 1024), " ", "")}"
    :class "disk"
  )
)
```
but it forces you to remove indentation
