### ISSUE TITLE
Unable to actually do anything at all

### ISSUE THREAD

**Issue by alessandrobalbo** [elkowar/eww#842]
Hi all!

I'm kind of stuck before beginning. I'm using Manjaro Linux as a OS and trying to use eww in Code - OSS (VSCode).

I've got an endless list of issues. The instructions contained at https://elkowar.github.io/eww/eww.html are far too vague and unspecific for my little knowledge and I can't realize where and how to set things up as thereby suggested (after page one).

- First of all: in the "Writing your eww configuration" paragraph is not really contained anything about what I have to put in a config file, where this file should be located, and whether it exists or not already. It is just suggested what to use and which extensions to add (by the way, can't find yuck on VSCode, though following the instruction at the provided link)
- "Creating your first window" kind of the same issues, don't know in which directory to place my terminal and what kind of file should I create to fill with the suggested text, how to save it ect.
- Furthermore I accidentally forked the original eww repository in my github and it was automatically set to public, even though obviously I can't contribute in anyway to its development, and now can't delete it anymore...

DISCLAIMER: None of the above is intended to be a complain, I'm clearly too much of a noob to be able to to do this stuff without help, hence, if some angel passes by and has some hint to share on how I can sort this all out, I would be thankful.

PS: My final aim would be to build some widgets with temps and hardware monitoring data to be projected on an android device (secondary problem to solve, already tried Deskreen but the pairing doesn't work - error occurring on android browser)

**Comment by truefusion** [comment]
Everything that would have been written in response to this can be found at [https://elkowar.github.io/eww/configuration.html](https://elkowar.github.io/eww/configuration.html)

[Discussions](https://github.com/elkowar/eww/discussions) are a more appropriate place to ask for help.

**Comment by elkowar** [comment]
as truefusion says, the docs should provide the relevant information, if you look in the right places. I can't help you with your accidental fork, although you should be able to delete that in the repository settings without issue.
