### ISSUE TITLE
awk travesty

### ISSUE THREAD

**Issue by jnordwick** [elkowar/eww#856]
elkowar/eww/blob/master/examples/eww-bar/scripts/getvol
```
amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%' | head -1
```
to
```
amixer -D pulse sget Master | awk -F '[^0-9]+' '/Left:/{print $3}'
```
kids these days

**Comment by buffet** [comment]
fr what even is that, eww (get it)

**Comment by elkowar** [comment]
fixed, thanks!

**Comment by a-priestley** [comment]
This assumes stereo output. You still need to ensure a single value in the case of multiple left speakers:
```sh
amixer -D pulse sget Master | awk -F '[^0-9]+' '/Left:/{print $3}' | head -n 1
```

**Comment by Mango0x45** [comment]
> This assumes stereo output. You still need to ensure a single value in the case of multiple left speakers:
> 
> ```shell
> amixer -D pulse sget Master | awk -F '[^0-9]+' '/Left:/{print $3}' | head -n 1
> ```

Yet another incorrect use of `awk`. It can also take the place of `head`:

```shell
amixer -D pulse sget Master | awk -F '[^0-9]+' '/Left:/ { print $3; quit }'
```
