### ISSUE TITLE
Master fails to update on Gentoo

### ISSUE THREAD

**Issue by CaptainBloodz** [elkowar/eww#857]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Master just failed to update whereas initial install succeeded -24h ago:

     Running `rustc --crate-name eww --edition=2021 crates/eww/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="gtk-layer-shell"' --cfg 'feature="wayland"' -C metadata=754217f0a5108455 -C extra-filename=-754217f0a5108455 --out-dir /var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps -L dependency=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps --extern anyhow=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libanyhow-4b32b05970f48f26.rlib --extern bincode=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libbincode-d7a416855201962e.rlib --extern cairo=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libcairo-1262cd2700b83d54.rlib --extern cairo_sys=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libcairo_sys-92012bcbe557fc99.rlib --extern chrono=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libchrono-8cdcae107d6984b2.rlib --extern clap=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libclap-e5cc8ed47863eba5.rlib --extern codespan_reporting=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libcodespan_reporting-b2711cdbc284ac24.rlib --extern derive_more=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libderive_more-efdcc03ba064ad3b.so --extern eww_shared_util=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libeww_shared_util-e3c71119dda41c8e.rlib --extern extend=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libextend-6c73452d1f76cb7a.so --extern futures_core=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libfutures_core-29fbe2cd953fcae0.rlib --extern futures_util=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libfutures_util-295b79e723778f91.rlib --extern gdk=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libgdk-f2e644d7c33816f6.rlib --extern gdk_pixbuf=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libgdk_pixbuf-c5120c9e4dc20330.rlib --extern glib=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libglib-08562a3ba40d41b2.rlib --extern grass=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libgrass-357845cb99dd5950.rlib --extern gtk=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libgtk-4aa49ce179f686b2.rlib --extern gtk_layer_shell=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libgtk_layer_shell-e51a27def30c90c6.rlib --extern itertools=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libitertools-8ca895ddafe1edee.rlib --extern libc=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/liblibc-6f8936f8acda8306.rlib --extern log=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/liblog-c813e2bb71f6d743.rlib --extern maplit=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libmaplit-88d2002cddfd24ae.rlib --extern nix=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libnix-084d98c3b28c1de0.rlib --extern notify=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libnotify-904533c0cafb5390.rlib --extern once_cell=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libonce_cell-b3132d0fd5cb2268.rlib --extern pretty_env_logger=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libpretty_env_logger-99a361670c4c872f.rlib --extern regex=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libregex-3f2c3cd4270df3b7.rlib --extern serde=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libserde-45394d28929d0e66.rlib --extern serde_json=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libserde_json-fb4357e9f1cf0788.rlib --extern simple_signal=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libsimple_signal-01238ef33f1c4961.rlib --extern simplexpr=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libsimplexpr-1fdffc823e6c0e74.rlib --extern sysinfo=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libsysinfo-2332eeae2caba957.rlib --extern tokio=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libtokio-9c18ad6571242483.rlib --extern tokio_util=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libtokio_util-fb626c767c58d8ac.rlib --extern unescape=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libunescape-377e36582138fee8.rlib --extern wait_timeout=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libwait_timeout-36fa1f7c6775f7f5.rlib --extern yuck=/var/tmp/portage/gui-apps/eww-9999/work/eww-9999/target/release/deps/libyuck-b2bcb4f17d5dc1c8.rlib -Ctarget-cpu=native -Cllvm-args=-x86-branches-within-32B-boundaries`
error[E0635]: unknown feature `hash_extract_if`
 --> crates/eww/src/main.rs:6:12
  |
6 | #![feature(hash_extract_if)]
  |            ^^^^^^^^^^^^^^^

error[E0635]: unknown feature `extract_if`
 --> crates/eww/src/main.rs:2:12
  |
2 | #![feature(extract_if)]
  |            ^^^^^^^^^^

error[E0599]: no method named `extract_if` found for struct `std::collections::HashMap` in the current scope
   --> crates/eww/src/widgets/widget_definitions.rs:130:62
    |
130 |     let contained_deprecated: Vec<_> = bargs.unhandled_attrs.extract_if(|a, _| deprecated.contains(&a.0 as &str)).collect();
    |                                                              ^^^^^^^^^^ method not found in `HashMap<AttrName, AttrEntry>`

Some errors have detailed explanations: E0599, E0635.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `eww` (bin "eww") due to 3 previous errors

### Additional context

2023-07-27T18:35:50 >>> dev-lang/rust-1.71.0

**Comment by elkowar** [comment]
Make sure to update to the latest rust nightly, there have been recent updates to ensure future compatibility that are backwards incompatible with older nightly versions of the rust compiler

**Comment by CaptainBloodz** [comment]
Can you please confirm 2 weeks ago 1.71.0 is too old of a version for the 2023/07/29 commits to be build with, as everything committed beyond this date builds fine here.

**Comment by CaptainBloodz** [comment]
user@amd64 ~ $ rustc -V
rustc 1.73.0-nightly (32303b219 2023-07-29) (gentoo)

fixed it indeed.

**Comment by Skaterjess2012** [comment]
user@amd64
rustc 1.72.0-nightly (5680fa18f 2023-08-23) (gentoo)
works great too

**Comment by CaptainBloodz** [comment]
> user@amd64 rustc 1.72.0-nightly (5680fa18f 2023-08-23) (gentoo) works great too

So [https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=2517f38104a33594f530ff5c79d10862197c9ebe](url) is no longer active?

dev-lang/rust
 Installed versions:  1.71.1(stable/1.71)^t(19:26:26 28/08/2023)(clippy doc miri nightly profiler rust-analyzer rust-src rustfmt system-bootstrap verify-sig wasm -big-endian -debug -dist -llvm-libunwind -lto -parallel-compiler -system-llvm -test ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="64 -32 -x32" CPU_FLAGS_X86="sse2" LLVM_TARGETS="WebAssembly X86 -AArch64 -AMDGPU -ARM -AVR -BPF -Hexagon -Lanai -LoongArch -MSP430 -Mips -NVPTX -PowerPC -RISCV -Sparc -SystemZ -VE -XCore")

**Comment by CaptainBloodz** [comment]
Oh boy!

  The following REQUIRED_USE flag constraints are unsatisfied:
    miri? ( nightly )

**Comment by Skaterjess2012** [comment]
> > user@amd64 rustc 1.72.0-nightly (5680fa18f 2023-08-23) (gentoo) works great too
> 
> Oh boy! Because of https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=2517f38104a33594f530ff5c79d10862197c9ebe
> 
> Upgrading from Installed versions: 1.71.1-r1(0/llvm-16)(13:05:47 03/10/2023)(-rustfmt ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="64 -32 -x32") to 1.72.0 throws:
> 
> The following REQUIRED_USE flag constraints are unsatisfied: miri? ( nightly )

I didn't see the commit from the gentoo repos but yes. I just unmasked the nightly flag and seemed to compile alright. am I missing something?

**Comment by CaptainBloodz** [comment]
Checking with

 emerge -1 -p dev-lang/rust

should clear that out.

However, as far as eww is concerned, happy to know 1.72.0-r1 is reported as enough.
