### ISSUE TITLE
[BUG] EWW Widget fails to to launch EWW:error_ handling_ctx

### ISSUE THREAD

**Issue by thorrrr** [elkowar/eww#876]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Hi Guys
I am on ArcoLinux running Chadwm which as part of the bar launches a EWW widget.
For no reason i can see it has stopped launching i did a full Meld over the whole folder and could see no issue
I have read through you man-help  pages and nothing i try works no logs no debugging  i have closed the daemon but anything i type i get see below 

![image](https://github.com/elkowar/eww/assets/8170673/4fbef9db-b4ef-41cd-b82f-cfa1643a7bc5)

![image](https://github.com/elkowar/eww/assets/8170673/50e6db9c-33d8-4a72-9929-3e1fed7282bd)

### Reproducing the issue

i should click on icon top bar and it launched widget but nothing happens 

### Expected behaviour

opens widget

### Additional context

eww --version
eww 0.4.0 d58d91de78d2b9984a1bbb8314be197bc0e283dc

![image](https://github.com/elkowar/eww/assets/8170673/90619e60-5012-472e-937f-17fe550dbfb3)

**Comment by elkowar** [comment]
This looks like the daemon is just not running, which then obviously will make `eww state` and those sort of commands not work. your eww open would work if you give it a window name -- i'm confused what your issue here is. Please provide more details, ensure that the eww open command you're running actually is correct, and that an eww daemon is either running or started by said command.

**Comment by thorrrr** [comment]
HI 
This is built into the release and has worked for several months.
I have never even looked in EWW folder  but something is not correct it will not launch 
If i press eww open eww see image


![image](https://github.com/elkowar/eww/assets/8170673/84320ce6-f754-413c-aef3-674070837417)
![image](https://github.com/elkowar/eww/assets/8170673/8ae7ec9c-2c96-416b-8ddf-54721e3b361c)
But it does show window 
![image](https://github.com/elkowar/eww/assets/8170673/96f1a457-8715-40cb-8d9f-6d79de29425b)

**Comment by thorrrr** [comment]
See files here https://github.com/thorrrr/eww 
Need anything else please ask

**Comment by elkowar** [comment]
Try commenting out your includes one by one, I assume this is due to eww failing to load your config

**Comment by thorrrr** [comment]
> Try commenting out your includes one by one, I assume this is due to eww failing to load your config

what in the eww.yuck?
