### ISSUE TITLE
[Text transfomation] 

### ISSUE THREAD

**Issue by mrsnailo** [elkowar/eww#879]
### Description of the requested feature

I have searched the docs, but didn't found any property that can  uppercase text . Please let me know if i am mistaken, and close this issue.  I tried to do it with css, but failed. 

### Proposed configuration syntax

:text-transform "Capitalize/uppercase/lowercase"

**Comment by elkowar** [comment]
The label widget has a markup property that allows you to use [pango markup](https://docs.gtk.org/Pango/pango_markup.html), which should allow you to uppercase your string.
