### ISSUE TITLE
[BUG] hsl not recognized in sass

### ISSUE THREAD

**Issue by jacekjarosz55** [elkowar/eww#880]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

![image](https://github.com/elkowar/eww/assets/72438686/72a8d396-3ce2-4226-9d6b-c7af4d1c8a03)

seems like gtk doesnt understand hsl, can the sass compiler convert it into rgba instead? 

### Expected behaviour

working hsl color

### Additional context

hsl is also highlighted as an error in the gtk debugger: 
![image](https://github.com/elkowar/eww/assets/72438686/1ef0a344-4a34-4b84-a57d-ba34ca47beae)

**Comment by elkowar** [comment]
I don't think that our sass compiler can do this, so if gtk doesn't support hsl values, I fear we won't be able to make that work anytime soon :/

**Comment by jacekjarosz55** [comment]
Sorry for the late response, but I figured that you can do that in grass by just wrapping in in the rgba function

`rgba(hsl(100deg, 50%, 100%), 1.0)`

**Comment by jacekjarosz55** [comment]
Also made this function that makes hsla convert to rgba
```sass
@function hsla($h, $s, $l, $a) {
  @return rgba(hsl($h, $s, $l), $a)
}
```
