### ISSUE TITLE
[BUG] Incorrect parse of unit

### ISSUE THREAD

**Issue by yuchanns** [elkowar/eww#885]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When I specify geometry in percent units, it doesn't allow the user to use a decimal number.
```bash
error: Invalid unit ".6%", must be either % or px
    ┌─ /home/yuchanns/.config/eww/eww.yuck:339:32
    │
339 │                         :width "97.6%"

```
Seems that the program parses this value as decimal places.

### Reproducing the issue

Fill length value with any decimal number with a unit of percentage

### Expected behaviour

Parse the decimal number correctly.

### Additional context

```bash
❯ eww --version
eww 0.4.0 d58d91de78d2b9984a1bbb8314be197bc0e283dc
```

**Comment by CrumblyLiquid** [comment]
This seems to be fixed now (`eww 0.4.0 a9a35c1804d72ef92e04ee71555bd9e5a08fa17e`). For context I'm using the latest git build (`eww-wayland-git` from the AUR)
