### ISSUE TITLE
[FEATURE] Use stable instead of nightly

### ISSUE THREAD

**Issue by NovaAndrom3da** [elkowar/eww#905]
I'm on a distro that due to it using musl (rather than gnulibc) will likely never work with rust nightly. I love using EWW and I'd love to use it again, but unfortunately the reliance on nightly makes it impossible. I could compile nightly, but that would mean no updates, and is just in general discouraged.

**Comment by werdahias** [comment]
This would also help getting eww packaged for debian/ubuntu as we only support/ship stable rustc

**Comment by freijon** [comment]
Same issue on Gentoo, there is no good way to get `eww` packaged at the moment.

**Comment by elkowar** [comment]
Done in 9ca98448cca5b9b149d6106e1bc9933f96a65cbd!
