### ISSUE TITLE
[FEATURE] Reworking of the documention

### ISSUE THREAD

**Issue by Souliboi** [elkowar/eww#909]
### Description of the requested feature

Following the default [configuration](https://elkowar.github.io/eww/configuration.html results in multiple errors that make no sense to me (has no clue on why it is actually failing when the default configuration says to do the thing like that)

### Proposed configuration syntax

`(defwindow greeter [?text name]`
returns an array when it expected a list
`(defwindow greeter "[?text name]"`
seems to fix that
following that fix entering the remaining part of the first widget step
```(defwindow greeter "[?name text]"
  (box  :orientation "horizontal"
        :halign "center"
    text
    (button :onclick "notify-send 'Hello' 'Hello, ${name}'"
    "Greet")))
```
results in the error ```Did not expect any further elements here. Make sure your format is correct```
removing the closing parenthesis throws you `Input ended unexpectedly. Check if you have any unclosed delimiters` prompting you to add it back

### Additional context

I have very little clue as to what i am actually doing here and i would like to genuinely understand what i am doing wrong here

**Comment by arlohb** [comment]
The documentation is correct, the difference is that your code is:
`(defwindow greeter [?text name]`
where the documentation says:
`(defwidget greeter [?text name]`

**Comment by Souliboi** [comment]
i am blind, my b
