### ISSUE TITLE
[FEATURE] Variable styling

### ISSUE THREAD

**Issue by bin** [elkowar/eww#92]
## Description of the requested feature
I would like to have a variable CSS property, say, one that changes based on the time of day.

## Proposed syntax
Inline CSS via an XML property is already supported, so feeding that through the same expansion as existing text should do fine.  Users could then add a tag `style="color: {{my_color}}"` and have it updated appropriately.

**Comment by elkowar** [comment]
i'm confused, what exactly are you missing there? you can already use the style property like any other property 🤔 Are you looking for a `<style>` tag?

**Comment by Swexti** [comment]
@elkowar He wants to mention {{vars}} in the `style` property.

Lemme show u:
```
<eww>
<definitions>
  <def name="main">
   <label text="yes this" style="color: {{color}};"/>
  </def>
  </definitions>
  <variables>
    <var name="color">#ebdbb2</var> 
  </variables>
  <windows>
    <window name="main_window" stacking="fg" focusable="false" screen="1">
    <geometry anchor="center" x="1700px" y="110px" width="350px" height="170px"/>
      <widget>
        <main/>
      </widget>
    </window>
  </windows>
</eww>
```
And then be able to run `eww update color=#282828` to update the `label` text color.

**Comment by elkowar** [comment]
Is that not possible currently? 🤔

**Comment by undefinedDarkness** [comment]
I think you can do this, might play around with it to test et

**Comment by undefinedDarkness** [comment]
Hmm, I have a widget that uses attributes in style quite a bit & it works fine, maybe I'd is unique to vars?, What happens if you put #f00 in color?

**Comment by legendofmiracles** [comment]
The exact same error

**Comment by undefinedDarkness** [comment]
That's a bug then

**Comment by elkowar** [comment]
Is this still an issue?

**Comment by elkowar** [comment]
I'll close this, as there hasn't been a response in over a year
