### ISSUE TITLE
[BUG] defpoll result is an empty string

### ISSUE THREAD

**Issue by Raptorox** [elkowar/eww#927]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm trying to create a slider (scale), with a variable which gets its value from a defpoll, but the result is an empty string and at such cannot be parsed for a float. The command used in defpoll works correctly in a terminal.

### Reproducing the issue

Create a scale and set `:value current-volume`
create a `(defpoll current-volume :interval "1s" "amixer -D pulse sget Master | grep 'Left:' | awk -F '[][]' '{ print $2 }' | tr -d '%'")`

### Expected behaviour

Scale appears with it's value set to the result of the poll (20)

### Additional context

![image-10](https://github.com/elkowar/eww/assets/70806316/4571a26f-2d4c-49c8-9ffb-72fbb163a7c1)
![image-9](https://github.com/elkowar/eww/assets/70806316/3c8cb0f2-f720-48c4-a13c-966661af744f)

**Comment by luposmi** [comment]
The problem with your code is that you do not set an initial value.
What happens is that:
1. You call the function to open the window
2. The defpoll starts executing and the window reads current-volume
3. Tries to convert null ("") to a f64 which is not possible.

To fix this, you need to add an :initial "0" to your defpoll

**Comment by Raptorox** [comment]
That fixed it. Thanks!
