### ISSUE TITLE
[FEATURE] Conditional rendering

### ISSUE THREAD

**Issue by bin** [elkowar/eww#93]
## Description of the requested feature
It would be helpful to have the option to render based on a condition.  This would enable more flexible modifications, say, changing the layout based on user input.  This would remove the need for the current clumsy work-around: on a user action, run a script that closes the old window and opens a new one.

## Proposed configuration syntax
Just replicate `<script-var>`; maybe call it `<cond-var>` or similar.  Have it run the enclosed command, but just capture the shell return code.

**Comment by elkowar** [comment]
All widgets can already take a `visible` attribute, that may either be "true" or "false". Using that, you should be able to achieve everything with that, or am i missing something?

Closing this for now, but feel free to reopen if you think that something is missing here.
