### ISSUE TITLE
[FEATURE] Use for on the top-level

### ISSUE THREAD

**Issue by Froggo8311** [elkowar/eww#935]
### Description of the requested feature

I would like to use `for` on the top-level. I'm trying to create a window on every available monitor (number of monitor provided by an external command). For this, I'm trying to use this syntax:

```
(for m in monitors
  (defwindow bar_${m}
    :monitor m
    [some other values that aren't really important to this context]
  )
)
```

**Comment by eoli3n** [comment]
We need this yes !

**Comment by elkowar** [comment]
I'm not sure if something like that will happen anytime soon, as creating window definition dynamically definitely seems out of scope for now. However, #431  should more or less provide the same functionality: It'll allow you to define a single window and open it multiple times with different arguments, solving the same problem more cleanly. I'll close this issue as out of scope for now, referring to #431 instead as a more flexible and viable solution that's gonna be released soon (hopefully)
