### ISSUE TITLE
[BUG] No variable named EWW_TIME in scope

### ISSUE THREAD

**Issue by Asia4046** [elkowar/eww#938]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I was trying to use formattime in eww and it throws this error:

error: No variable named `EWW_TIME` in scope

I went through the documentation and it did had EWW_TIME as a magic variable
                       

### Reproducing the issue

This happens everytime i declare EWW_TIME variable

**Comment by stephentoth** [comment]
I also have this problem. 
I have included my error message to add more detail to this report.
```
error: No variable named `EWW_TIME` in scope
    ┌─ ./bars/main.yuck:111:32
    │
111 │       (label :text {formattime(EWW_TIME, "+%H")} :class "clock_hour" )
    │                                ──────── Used here
    │
    → Hint: Either define it as a global variable, or add it to the argument-list of your `defwidget` and pass it as an argument
    → Hint: If you meant to use the literal value "EWW_TIME", surround the value in quotes
```

I am not re-defining the variable as well.

**Comment by stephentoth** [comment]
Sure, I've extracted the minimum amount of code to get it to happen on my end.
```
(defwidget clock_module []
  (box :class "module module-clock" :space-evenly "false" :orientation "h"
    (label :text " " :class "clock_start_pad" )
    (label :text {formattime(EWW_TIME, "+%H")}  :class "clock_hour" )))


(defwindow main
  :geometry (geometry
    :x "0%"
    :y "8px"
    :width "99%"
    :height "36px"
  :anchor "top center")
  :stacking "fg"
  :namespace "dock"
  :exclusive true
  
  (box :class "bar_class" :orientation "h"
    (clock_module)))
```

Version Information:
```

Linux <HOSTNAME> 6.5.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 10 Oct 2023 21:10:21 +0000 x86_64 GNU/Linux

local/hyprland 0.30.0-1

eww 0.4.0 d58d91de78d2b9984a1bbb8314be197bc0e283dc
```

If there is any questions about specific environment information I am happy to provide that aswell.

**Comment by kshitijaucharmal** [comment]
The error is valid as EWW_TIME does not exist in the version you are using, and was added by this pr #792 in this [commit](https://github.com/elkowar/eww/commit/4d63f6deec7fd0cc1fe34907df1848ac2b94e90f). 
You are using the latest release from the releases section, which does not include this variable.
You could switch to the latest version by building eww from [source](https://elkowar.github.io/eww/) (check  the 'Building' section)

**Comment by istudyatuni** [comment]
I get the same error on latest eww `eww 0.4.0 65d622c81f2e753f462d23121fa1939b0a84a3e0`

Built with

```sh
cargo b --release --no-default-features --features=wayland
```

Repro

```lua
(defwindow example
           :monitor 0
           :geometry (geometry :x "0%"
                               :y "0px"
                               :width "100%"
                               :height "30px"
                               :anchor "top center")
           :stacking "fg"
           :reserve (struts :distance "40px" :side "top")
           :windowtype "dock"
           :wm-ignore false
    EWW_TIME
)
```

Error

```sh
   ┌─ /home/[..]/.config/eww/eww.yuck:12:5
   │
12 │     EWW_TIME
   │     ──────── Used here
   │
   → Hint: Define it as a global variable
   → Hint: If you meant to use the literal value "EWW_TIME", surround the value in quotes
```

Probably this is because `validate` never used

<details><summary>Details</summary>
<p>

```rs
warning: method `validate` is never used
  --> crates/eww/src/state/one_to_n_elements_map.rs:72:12
   |
11 | impl<I: Copy + std::hash::Hash + std::cmp::Eq + std::fmt::Debug, T> OneToNElementsMap<I, T> {
   | ------------------------------------------------------------------------------------------- method in this implementation
...
72 |     pub fn validate(&self) -> Result<()> {
   |            ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: method `validate` is never used
   --> crates/eww/src/state/scope_graph.rs:113:12
    |
65  | impl ScopeGraph {
    | --------------- method in this implementation
...
113 |     pub fn validate(&self) -> Result<()> {
    |            ^^^^^^^^

warning: method `validate` is never used
   --> crates/eww/src/state/scope_graph.rs:508:16
    |
400 |     impl ScopeGraphInternal {
    |     ----------------------- method in this implementation
...
508 |         pub fn validate(&self) -> Result<()> {
    |                ^^^^^^^^

warning: `eww` (bin "eww") generated 3 warnings
```

</p>
</details>
