### ISSUE TITLE
[BUG?] 

### ISSUE THREAD

**Issue by dancaer69** [elkowar/eww#950]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Positioning of the window is ignored most of the times on X11(tried compiz and openbox). Especially when start the WM is always at center while I specified to be at left top corner. Also it seems to be dependand from other windows on screen. If a window is occupied all space except the space in which the eww window supposed to be, only then it respects the position and only the x, the y sometimes is at 0(which I specified in config), but most times are some pixels down. Generally is not controlable.  I tried to change some properties on my configuration(wm-ignore true/false, struts side left/right, position % or pixels) but nothing works. Every time I reload the window goes to different positions and sometimes(if a window is at its supposed position) it opens on the oposite side of the screen(right, while I setted to left). I also tried to set properties for eww's window on openbox's config, but those also ignored. 

### Reproducing the issue

1. Set position in configuration
2. Start eww window

### Expected behaviour

The window opens in specified position

### Additional context

Distro: Archlinux
WM: Openbox
Version: eww-wayland 0.4.0-5(from aur)
Here is the config I use for window positioning:
`(defwindow bar
	  :monitor 0
	  :stacking "fg"
	  :wm-ignore "true"
	  :geometry (geometry :x "0%"
		  :y "0%"
		  :width "240px"
		  :height "1048px"
		  :anchor "left top")
	  ;;:exclusive "true"
      :reserve (struts :side "left" :distance "240px")
		  (box	:orientation "v"
      .......
      .......`

**Comment by kshitijaucharmal** [comment]
Have you tried the [eww-x11](https://aur.archlinux.org/packages/eww-x11) package, or even [building eww from source](https://elkowar.github.io/eww/) (which is the preffered way btw)?
Because you stated that the problems arise in X11, but you are using the eww-wayland package, which would explain the wrong positioning

**Comment by dancaer69** [comment]
Thanks, this seems that solved it. I didn't know that needed different build package for x11/wayland. I thought that the eww-wayland package just added support and for wayland. I've missed this info you posted in documentation, because I'm using aur packages if they exist and avoid build them.

**Comment by kshitijaucharmal** [comment]
Glad to help😁
You can close the issue if you don't have any questions
