### ISSUE TITLE
[ENHANCEMENT] Normalize `EWW_NET` Units

### ISSUE THREAD

**Issue by bbb651** [elkowar/eww#958]
Currently, the values in `EWW_NET` seems like they're in "bytes per 2 seconds", since magic variables are refreshed every 2 seconds, and from the `sysinfo` docs the network methods return [bytes since they were last called](https://docs.rs/sysinfo/latest/sysinfo/trait.NetworkExt.html#tymethod.received).

I think it would be nice to divide it by the interval to make it nicer to work with, or at the very least document it since it's currently very misleading (and it's close enough to being bytes per second that you wouldn't notice it's off by a factor of 2).

**Comment by GOKOP** [comment]
I second this. Just got here by looking up network speed being inaccurate
