### ISSUE TITLE
[BUG] key in AUR package has no User ID

### ISSUE THREAD

**Issue by Yusuf-Duran** [elkowar/eww#959]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When trying to install `eww-wayland` through `yay` (should be the same with any AUR installer though), I get an error stating that there was a problem importing a key
Relevant log:
```
gpg: error reading key: No public key
gpg: error reading key: No public key
gpg: error reading key: No public key

 :: PGP keys need importing:
 -> B558974128820CB473BD9807E321AD71B1D1F27F, required by: eww
 -> 94E8F34BCE4F4BA8ED9B29BD50E76B4711E4C3E4, required by: eww
 -> 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23, required by: eww
:: Import? [Y/n] 
:: Importing keys with gpg...
gpg: key 4AEE18F83AFDEB23: no user ID
gpg: key 50E76B4711E4C3E4: public key "Leon <5300871+elkowar@users.noreply.github.com>" imported
gpg: key E321AD71B1D1F27F: public key "Leon Kowarschick <5300871+elkowar@users.noreply.github.com>" imported
gpg: Total number processed: 3
gpg:               imported: 2
 -> problem importing keys
```

### Reproducing the issue

1. `yay -Sy eww-wayland`
2. try importing the keys
3. fail

### Expected behavior

Keys getting imported without any hiccups

### Additional context

When trying to import the key manually, I get this 
```
gpg --recv-key 4AEE18F83AFDEB23
gpg: key 4AEE18F83AFDEB23: no user ID
gpg: Total number processed: 1
```
It only worked once I switched the key server
```
gpg --keyserver pgp.mit.edu --recv-keys 4AEE18F83AFDEB23      Wed 25 Oct 2023 10:41:51 AM CEST
gpg: key 4AEE18F83AFDEB23: 1 duplicate signature removed
gpg: key 4AEE18F83AFDEB23: public key "GitHub (web-flow commit signing) <noreply@github.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
After this, the installation via the package works as expected and without any hiccups. The Problem here seems to be that on the default key server, one of the three keys has no User ID. Also, it is kinda suspicious that the key is now signed `noreply@github.com`.

**Comment by T0kyoB0y** [comment]
![image](https://github.com/elkowar/eww/assets/119447307/4fe4ac82-ddda-4fae-bfc1-7d636aab5e59)


```
curl -sS https://github.com/elkowar.gpg | gpg --import -i -
curl -sS https://github.com/web-flow.gpg | gpg --import -i -
```

**Comment by elkowar** [comment]
Please raise this issue with the maintainer of the AUR package -- which is not me!
