### ISSUE TITLE
Add a brightness magic variable [FEATURE] 

### ISSUE THREAD

**Issue by Frusadev** [elkowar/eww#960]
### Description of the requested feature

Add a brightness magic variable for actions related to controlling brightness

**Comment by Lanpingner** [comment]
Hi Dear 
I created the code i tested it on my system (Arch x86-64) it currently only works on Linux not macos(i don't have a mac )
Here is the branch [Brightness Magic var](https://github.com/Lanpingner/eww/tree/brightness_magic_var)
the use case is simple `{ <name_of_backlight>: { brightness, max_brightness, percent } }` similar like EWW_DISK

**Comment by Frusadev** [comment]
Thanks!
