### ISSUE TITLE
[BUG] unable to compile

### ISSUE THREAD

**Issue by JimitSoni18** [elkowar/eww#964]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I am unable to compile eww, I have gtk3 and gtk-layer-shell and gcc installed, I am using void linux on wayland, with Hyprland and when I run cargo build --release --no-default-features --features=wayland, i get the following errors

 = note: /usr/bin/ld: cannot find -lgtk-layer-shell: No such file or directory
          /usr/bin/ld: cannot find -lgtk-3: No such file or directory
          /usr/bin/ld: cannot find -lgdk-3: No such file or directory
          /usr/bin/ld: cannot find -lpangocairo-1.0: No such file or directory
          /usr/bin/ld: cannot find -lpango-1.0: No such file or directory
          /usr/bin/ld: cannot find -lharfbuzz: No such file or directory
          /usr/bin/ld: cannot find -latk-1.0: No such file or directory
          /usr/bin/ld: cannot find -lcairo-gobject: No such file or directory
          /usr/bin/ld: cannot find -lcairo: No such file or directory
          /usr/bin/ld: cannot find -lgdk_pixbuf-2.0: No such file or directory
          /usr/bin/ld: cannot find -latk-1.0: No such file or directory
          /usr/bin/ld: cannot find -lgdk-3: No such file or directory
          /usr/bin/ld: cannot find -lpangocairo-1.0: No such file or directory
          /usr/bin/ld: cannot find -lpango-1.0: No such file or directory
          /usr/bin/ld: cannot find -lharfbuzz: No such file or directory
          /usr/bin/ld: cannot find -lgdk_pixbuf-2.0: No such file or directory
          /usr/bin/ld: cannot find -lcairo-gobject: No such file or directory
          /usr/bin/ld: cannot find -lcairo: No such file or directory
          /usr/bin/ld: cannot find -lpango-1.0: No such file or directory
          /usr/bin/ld: cannot find -lharfbuzz: No such file or directory
          /usr/bin/ld: cannot find -lgdk_pixbuf-2.0: No such file or directory
          /usr/bin/ld: cannot find -lcairo-gobject: No such file or directory
          /usr/bin/ld: cannot find -lcairo: No such file or directory
          collect2: error: ld returned 1 exit status

warning: `eww` (bin "eww") generated 3 warnings
error: could not compile `eww` (bin "eww") due to previous error; 3 warnings emitted 

### Reproducing the issue

run cargo build --release --no-default-features --features=wayland

### Expected behaviour

compiles and generates a binary

**Comment by Lanpingner** [comment]
Hi dear
I am not sure its a eww bug since you system "void linux " can't find the file, although i don't have experience with that distor, try to lookup those file with "mc/find etc..." maybe your package manager installs it to a different place,
another option might be.
Did you installed the dev packages as if you want to compile eww you need the dev packages not just the runtime
Like this one [GTK layer shell devel](https://voidlinux.pkgs.org/current/voidlinux-multilib-x86_64/gtk-layer-shell-devel-32bit-0.8.1_1.x86_64.xbps.html)

**Comment by mia0x75** [comment]
try this in your template

```
depends="gtk-layer-shell gtk+3 cairo pango harfbuzz libharfbuzz atk glib gdk-pixbuf SDL2_Pango"
```

**Comment by JimitSoni18** [comment]
@Lanpingner Hello, yes I am sure that I have installed the dev packages, as you can see from this output :
`
eww on  master via  v18.16.0 via 🦀 v1.73.0-nightly
❯ sudo xbps-install gtk-layer-shell-devel
Package `gtk-layer-shell-devel' already installed.

eww on  master via  v18.16.0 via 🦀 v1.73.0-nightly
➜ sudo xbps-install gtk+3-devel

Package `gtk+3-devel' already installed.
`

Also I didnt understand what you meant by 
`

try to lookup those file with "mc/find etc..."
`

so i ran find in /etc and got this output
eww on  master via  v18.16.0 via 🦀 v1.73.0-nightly
➜ sudo find /etc -name gtk-layer

**Comment by JimitSoni18** [comment]
@mia0x75 
Hello, I don't know what template you are referring to, as I am not a contributor, can you help me locate the template...

**Comment by JimitSoni18** [comment]
sorry accidentally clicked close

**Comment by mia0x75** [comment]
> @mia0x75 
> Hello, I don't know what template you are referring to, as I am not a contributor, can you help me locate the template...

you build the source code on host machine directly? then you can install the packages in depends, include "-devel" packages, any try again.

**Comment by Lanpingner** [comment]
Hi dear
I will try it my self i will install void on vm and try to compile on it, if i face and solve the issue i will let you know

**Comment by JimitSoni18** [comment]
Hello @mia0x75 , I honestly have no idea what you mean by "install the packages in depends". if you mean to say that I should install the dependencies, please provide a link to the list of libraries that it depends on and I will try to compile again... 
Also I did install the packages that end with "-devel", but still facing the issue...
Thanks for replying

**Comment by JimitSoni18** [comment]
@Lanpingner Thank you very much for taking time from your busy day to do that, also please try the musl ISO as thats the one I'm using

**Comment by Lanpingner** [comment]
Hi there
I have good news and bad news.
The good news i managed to build eww on the system
The bad news its hard to do

Let me try to explain it to you
Now as i have no experience with voidLinux i went with the LIVE iso but installed manually everything via the advanced gide [GUIDE](https://docs.voidlinux.org/installation/guides/chroot.htmll)

These are the things i installed

1. cargo
2. git
3. vim (my choice for editing files)
4. pkg-config
5. glib
6. glib-devel
7. gtk+3-devel
8. rustup

Also any other deps that during compile he ask for it (might be missed something)

Before we get to there I don't know how much experience you have with Linux/Void or basically just compiling things but if you want to achieve the same result as me i suggest you test on a vm like me, also if you have no experience with Linux please try with something easier distro so you get the hang of it "Ubuntu, Fedora, Manjaro" or "Arch a bit advanced but still easy to use there are a ton of guides there"

So after I installed the dev deps i also had to install rustup which is not easy on void then you need to install a specif version of rust-toolchain via the rustup tool which is in the rust-toolchain.yml file in the repo

After that you need to set the deafult toolchian to that, then restart the pc via the rustup you should see something like this

run: rustup show
----------------------------- RESULT OF COMMAND -----------------------------
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/$USER/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2022-08-27-x86_64-unknown-linux-gnu
nightly-2023-07-14-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.71.1-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2023-07-14-x86_64-unknown-linux-gnu (overridden by '/home/romeo/Gits/eww/rust-toolchain.toml')
rustc 1.73.0-nightly (7bd81ee19 2023-07-13)
------------------------------------------------------------------------------------------------------------------------------------------------


"nightly-2023-07-14-x86_64-unknown-linux-gnu (overridden by '/home/$USER/Gits/eww/rust-toolchain.toml')" this is the important line

Note: if you go to the eww repo in the pc and run rusup update maybe rustup will install the correct rust-toolchian "Not tested"
Another note please run "cargo build"/"cargo build --release"

Now when you go to the eww repo and run cargo --version
you should get this "cargo 1.73.0-nightly (694a57956 2023-07-11)"

if you see it that means eww will compile without issue tested on void (fresh install) and my system arch

I hope this helps

**Comment by mia0x75** [comment]
> Hello @mia0x75 , I honestly have no idea what you mean by "install the packages in depends". if you mean to say that I should install the dependencies, please provide a link to the list of libraries that it depends on and I will try to compile again... Also I did install the packages that end with "-devel", but still facing the issue... Thanks for replying

try this:
# xbps-install -Su
# xbps-install -S gtk-layer-shell gtk+3 cairo pango harfbuzz libharfbuzz atk glib gdk-pixbuf SDL2_Pango gtk-layer-shell-devel gtk+3-devel cairo-devel pango-devel harfbuzz-devel atk-devel glib-devel gdk-pixbuf-devel SDL2_Pango-devel
# cargo build ....

**Comment by JimitSoni18** [comment]
Hello @mia0x75 @Lanpingner , thank you very much for helping, currently I was unable to build it after following those but I'll check with the void community as this seems to be a linking issue where the ld is not able to find the libraries even after setting the LD_LIBRARY_PATH, so I am closing the issue. again, thanks for helping.

**Comment by salva-ferrer** [comment]
Hello, I was experiencing the same case myself same distribution and libc. I was able to solve it myself with a simple env variable and brought to the attention of the void community, there are other solutions available, since this can plague other rust projects, i'd like to share for reference of other void users.

root cause 1.- void does not provide static versions of libraries for all their devel packages, in this case it affected ALL devel packages required.
root cause 2.- x_64-unknown-linux-musl target is staticaly by default linked when using standard rust from rustup.  

Solution 1.- use rustup but add the following RUSTFLAG='-C target-feature=-crt-static' before your cargo: RUSTFLAG='-C target-feature=-crt-static' cargo build....
Solution 2.- don't use rustup and use the rust version provided by void packages which already changes the default behavior.
