### ISSUE TITLE
[FEATURE] WGPU

### ISSUE THREAD

**Issue by tombombadilom** [elkowar/eww#967]
### Description of the requested feature

Sorry if this is a silly question, I'm not a rust developer...

I'm using eww with Hyprland for month now, using OpenGL, GLSL shaders on some place, on button hover effect, in backgrounds, to animate some windows.
It's nice and fun, works well, but there is a new techno that is way faster and use less GPU now: wgpu.

As I was watching WebGPU for browsers and 3D web motors, I noticed this lib, https://wgpu.rs/ for Rust, which is basically, if I understand well, an implementation of WebGPU for rust with optional libs to create gateway for other languages than rust.

As I don't know much Rust and use eww modifying CSS and .yuck to obtain already all that I was needed, I was wondering if it was thinkable to add it to eww and add GPU gain and speed on OpenGL render, or completely silly to think about it.

Code: https://github.com/gfx-rs/wgpu
Wiki: https://github.com/gfx-rs/wgpu/wiki

**Comment by elkowar** [comment]
Umm,... I think you where quite on-point with "completely silly to think about it", but more in the sense that I'm not sure I fully understand the question. How are you using OpenGL /GLSL Shaders in eww explicitly (or even implicitly)?
Eww uses GTK under the hood, so I have no direct access to the rendering engine used below.

**Comment by tombombadilom** [comment]
I have to look at, if it is in hyprland or directly in Eww, I don't remember, but I will check my .config, Maybe I mistook, sorry for that ...

**Comment by tombombadilom** [comment]
> I have to look at, if it is in hyprland or directly in Eww, I don't remember, but I will check my .config, Maybe I mistook, sorry for that ...

My shaders are in.config/hypr/. So it might be used in hyprland
```bash
[tom@tom-pc hypr]$ tree shaders/
shaders/
├── bluefilter.frag
├── crt.frag
├── drugs.frag
├── extradark.frag
├── hg.glsl
├── nothing.frag
└── solarized.frag
```
I'm a total idiot, sorry I should have checked first, sorry for wasting your time. 
But I love Eww :)
