### ISSUE TITLE
[FEATURE] Add screenshot/s to the README

### ISSUE THREAD

**Issue by Kellegram** [elkowar/eww#97]
## Description of the requested feature
Add screenshots showcasing some example widgets to the README. 

# Additional context
No screenshots for something visual is enough for a lot of people to not bother with your application at all. No one should have to install this just to see how it looks. It would only take a moment to add a screenshot or a gif showing them and would be very beneficial in gaining users.

**Comment by Swexti** [comment]
This ties in with #99, since we don't have any example (currently) we can't really show any screenshots.

**Comment by Kellegram** [comment]
> 
> 
> This ties in with #99, since we don't have any examples (currently) we can't really show any screenshots.

Cool, any example will be helfpul.

**Comment by elkowar** [comment]
Done in #99
