### ISSUE TITLE
[FEATURE] Shell autocompletion support

### ISSUE THREAD

**Issue by Readf0x** [elkowar/eww#978]
### Description of the requested feature

Please add support for bash (+ maybe other shells like fish & zsh?) autocomplete support. It would be incredibly useful, especially for people who use things like zsh-autocomplete, are used to using tab to complete commands, or are still learning how to use eww.

### Additional context

I _would've_ linked to the documentation for each shell and how they handle autocomplete scripts, but I couldn't find much documentation for bash and zsh regarding making completions for an app, though I know there are definitely resources _somewhere_. Fish, however is very well documented, and they have very good resources (while not for _specifically_ for devs) on making completions [here](https://fishshell.com/docs/current/completions). If nothing else you can learn by example since there are certainly a large amount of completion scripts already on your system provided by other applications.

**Comment by elkowar** [comment]
implemented in 3f478b6!
Eww now has `eww shell-completions --shell zsh` (and a lot of other shells), and will be able to generate completion scripts for those!
