### ISSUE TITLE
[FEATURE] Separate daemon client into an external library crate

### ISSUE THREAD

**Issue by devcexx** [elkowar/eww#980]
### Description of the requested feature

Hi, so I'm absolutely new to eww and I was playing around with it for a couple of days now (pretty nit, thanks for your work on the project).

I'm still not pretty familiar with the eww source code, but for what I've seen so far, most of the logic is stored into the eww executable crate. This is fine, but I was thinking as a personal project doing some sort of complex scripts in Rust, that end up calling eww, and I was thinking whether would be a good idea to move the daemon client to a separate crate, so it can be independently consumed by another applications, for keeping a warm connection with the daemon instead of need to spawn a new process every time you want to call eww.

Do you think it would be a good / feasible idea?

### Proposed configuration syntax

N/A

### Additional context

N/A

**Comment by elkowar** [comment]
I'm not quite sure how this would look -- would we have an eww-cli crate that basically just has the CLI logic, then have a eww-client crate that contains the daemon client logic? Not sure how that'd look

**Comment by devcexx** [comment]
I was thinking it could worth to think on keeping the eww crate as it is, but moving the daemon client interface to a separate eww-client. Right now I don't have too much time on working in some sort of prototype, so feel free to close this issue.
