### ISSUE TITLE
[WIDGET] Close button

### ISSUE THREAD

**Issue by max-ishere** [elkowar/eww#983]
### Description of the widget

Windows aren't renamed often, but would be nice if there was a way to close the window in which this widget is contained. However, I think it should behave like a box or have default, but changeable content. This should allow more flexibility for the end user, so they can style it to match the rest of the widget if they use a custom theme.

### Example usage

```lisp
(close-window-button)

(close-window-button
  (image "cross.png"))
```

**Comment by patri9ck** [comment]
Why can't you just create a button and run `eww close window`?

**Comment by newor0599** [comment]
`(button :onclick "eww close window_name" "x")`
It's that simple

**Comment by max-ishere** [comment]
The issue is that when the window is renamed that command doesn't work anymore.

**Comment by max-ishere** [comment]
Maybe a var with the window name would suffice
