### ISSUE TITLE
[BUG] The coordinates of the panel cannot exclude the location of bar in x11

### ISSUE THREAD

**Issue by DreamMaoMao** [elkowar/eww#995]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

But when I used waybar in hyprland, the y coordinate of the eww panel was relative to the y coordinate below the waybar, but in x11 it was relative to the entire monitor

### Reproducing the issue

my eww config:

![image](https://github.com/elkowar/eww/assets/30348075/5ebfb539-6f78-4824-98e7-240d514506ad)

eww  version:
eww 0.4.0 a9a35c1804d72ef92e04ee71555bd9e5a08fa17e

**Comment by DreamMaoMao** [comment]
dwm(x11):


https://github.com/elkowar/eww/assets/30348075/f557cdcf-1457-4be2-ae3d-ff4055ab758f

**Comment by max-ishere** [comment]
It could be because of the exclusive property in waybar.
